### ISSUE TITLE
Requires babel-register

### ISSUE THREAD

**Issue by djanowski** [postcss/autoprefixer#1000]
Babel-register is a highly invasive dependency. I assume Autoprefixer can be transpiled before publishing to npm.

**Comment by ai** [comment]
Build scripts reminder this dependency during publishing to npm.

https://github.com/postcss/autoprefixer/blob/master/gulpfile.js#L41

We need this dependency to use dev version of Autoprefixer directly from GitHub.

**Comment by djanowski** [comment]
🤔 That's quite misleading but fine. Is there a script to remove the require line from index.js?

**Comment by ai** [comment]
@djanowski `index.js` just will not be copied to npm package. And build script will change `main` field in `package.json` https://github.com/postcss/autoprefixer/blob/master/gulpfile.js#L38

**Comment by djanowski** [comment]
OK, thanks for clarifying that!
