### ISSUE TITLE
-webkit-print-color-adjust

### ISSUE THREAD

**Issue by Malvoz** [postcss/autoprefixer#1001]
Consider adding `-webkit-print-color-adjust` [(MDN Reference)](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-print-color-adjust) as prefix for `color-adjust` [(CSS Color Module Level 4 Draft)](https://drafts.csswg.org/css-color-4/#color-adjust)

Both properties keyword values are: `economy | exact`.

There is a [data support suggestion on caniuse](https://github.com/Fyrd/caniuse/issues/2634).

**Comment by ai** [comment]
@Malvoz good idea. Do you want to send PR?

**Comment by Malvoz** [comment]
@ai Although I've been around on Github for a while I'm still not sure how to go about PR's.. What are the implications of a PR?

**Comment by ai** [comment]
@Malvoz oops, sorry :).

PR = pull request.

1. Click Fork button in [Autoprefixer repository page](https://github.com/postcss/autoprefixer).
2. It will create your own Autoprefixer’s fork.
3. Clone it to your computer by git.
4. All `yarn install` or `npm install`.
5. Change `data/prefixes.js`.
6. Create git branch `git checkout -b print-color-adjust`
7. Make a commit to the branch.
8. Push to your fork in GitHub
9. Open your fork on GitHub, you will see button to send pull request.

**Comment by Malvoz** [comment]
@ai 
Thanks, I appreciate the instructions, I guess it's time to stop looking the other away and learn git.. I might find time for it tonight, if this PR can wait? 😆

**Comment by ai** [comment]
Sure. Anyways I will have time for it only in Friday.

**Comment by Malvoz** [comment]
@ai 

I've been busy and I wont be able to priorities learning git within the next couple of days. 

I understand this probably shouldn't wait for too long (although probably not a wide usage of this property yet) and because I cannot give you a reliable time frame - if you or anyone else want to PR this then by all means go ahead. 

I'll make sure to get on with git until the next contribution I make!

**Comment by ai** [comment]
@Malvoz don’t worry, I will send developer from Cult of Martians. I plan they will close this issue in this week.

**Comment by soul-wish** [comment]
@Malvoz @ai don't you mind if I'll try to work on this issue?

**Comment by ai** [comment]
@soul-wish sure!

**Comment by soul-wish** [comment]
@ai great! Currently working on a PR to caniuse database.

**Comment by YozhikM** [comment]
Ready hack and tests, we are waiting for the approval of the PR

**Comment by ai** [comment]
@YozhikM since @soul-wish made so great Can I Use PR he will have priority. But I will try to merge both PR to keep 2 names in GitHub history.

Just send PRs (fallen tests is OK).

**Comment by YozhikM** [comment]
@ai did it

**Comment by yuriyalekseyev** [comment]
Hi! 
I found some minor problems in @soul-wish PR to Can I Use and fixed them.

Should I continue to work on this issue and create a PR to Autoprefixer or is it too late?

**Comment by ai** [comment]
@yuriyalekseyev addition PR is good

**Comment by soul-wish** [comment]
@yuriyalekseyev @ai unfortunately it is not additional PR, it is completely separate PR. So now we have two separate PR's to caniuse db for adding the same feature. Not sure if it is the correct way to do OS. Lets wait for caniuse author reply.

**Comment by ai** [comment]
@yuriyalekseyev @soul-wish :(

**Comment by soul-wish** [comment]
Don't get me wrong, guys. But instead of trying to do the best possible thing together I see some type of race here. This is not very motivational for any person, especially for OS newcomers. Also, there is a real issue for repo maintainers, because they should check all those issues and PR's, waste much more time and made a decisions at the end of the day.

**Comment by yuriyalekseyev** [comment]
@soul-wish @ai sorry about that! I'm kinda junior, so mistakes is my friends :)
Is there a way to reconfigure it to be an addition PR, or leave it untouched and let caniuse maintainer manage it?

**Comment by soul-wish** [comment]
@yuriyalekseyev ok, got it :). For future reference, there are a few options, I think:

- you can leave some comments on any public PR on GitHub (you can suggest changes to a specific lines/files etc.)
- you can create a new additional PR from the version in original PR (you can checkout from the same branch as original PR, made necessary modifications and submit additional PR with some explanations for maintainer)

In our case, I think the best options would be to delete my PR completely from Can I Use repo. I don't want to waste Can I Use db maintainer's time really. @ai what do you think? Is it the best option?

**Comment by YozhikM** [comment]
@soul-wish  I can cancel my PR here if it's necessary

**Comment by soul-wish** [comment]
@YozhikM it is not necessary. I hope @ai will be able to merge them somehow :)
One more time: I'm not offended, or something ;). Just want to point all of us to some issues in OS processes. GitHub made so much convenient features, hints and notifications inside issues and PR's and here we are, having two PR's with the same feature into one repo and two PR's with the same feature into another :)

**Comment by yuriyalekseyev** [comment]
@soul-wish so to create an additional PR, my steps are:
- fork/clone repo from original PR
- checkout to original PR branch
- submit PR to original PR
Did I get all correct?

**Comment by soul-wish** [comment]
@yuriyalekseyev I hope so, yeah. After that there should be only original PR with two commits (from me and from you). Do you have some time to try that right now?

**Comment by yuriyalekseyev** [comment]
@soul-wish yup, ofc. I'm here not for a race or competition, but for learning and getting experience. I'll close my PR here and on Can I Use and create additional PRs in ~15 mins.

**Comment by soul-wish** [comment]
@yuriyalekseyev 👍

**Comment by soul-wish** [comment]
Great work, @yuriyalekseyev! Our PR to Can I Use repo was updated. Looking forward to maintainer's answer ;)

**Comment by soul-wish** [comment]
@yuriyalekseyev our PR to Can I Use repo was merged 🎉

**Comment by yuriyalekseyev** [comment]
@soul-wish great! 🎉

**Comment by ai** [comment]
OK, now it is hard time for me to merge PRs :sweat_smile:

**Comment by ai** [comment]
Both PRs from @YozhikM and @soul-wish were merged to Autoprefixer. @YozhikM, @soul-wish, and @yuriyalekseyev will be mentioned in ChangeLog. @soul-wish will be the winner of Cult of Martian task.

Is it fare for everyone?

**Comment by yuriyalekseyev** [comment]
@ai sadly, that my commits to @soul-wish PR not shown in repo, but mention in ChangeLog also makes me happy. Thanks!

**Comment by ai** [comment]
@yuriyalekseyev oops. It was the side effect of “squash and merge” :(. Since you did really good fixes in @soul-wish PR I added extra commit with your name. Not your name is in Autoprefixer history too.

**Comment by yuriyalekseyev** [comment]
@ai wow, that is really cool. Thank you guys for a warm welcome 👍

**Comment by soul-wish** [comment]
Thanks, guys! Thanks @ai for all your help and patience. And big thanks to @yuriyalekseyev for his fixes and corrections to my original PR's! Great work, everyone. 👍😎

**Comment by ai** [comment]
Released in 8.2
