### ISSUE TITLE
mask-image and gradients

### ISSUE THREAD

**Issue by BaliBalo** [postcss/autoprefixer#1002]
```
mask-image: radial-gradient(circle closest-corner at 100% 50%, #000, transparent);
```

outputs the following

```
-webkit-mask-image: -webkit-radial-gradient(circle closest-corner at 100% 50%, #000, transparent);
mask-image: radial-gradient(circle closest-corner at 100% 50%, #000, transparent);
```

This is wrong because:
- The prefixed version of `radial-gradient` uses an old syntax (`-webkit-radial-gradient(100% 50%, circle closest-corner, ...)`), the standard `at 100% 50%` is not recognized, so the first line doesn't work.
- Webkit doesn't support the unprefixed `mask-image`, so the second line doesn't work.

One thing that would work would be the prefixed version of mask-image with the unprefixed version of radial-gradient: `-webkit-mask-image: radial-gradient(circle closest-corner at 100% 50%, #000, transparent);`

(I am testing in Chrome, not sure if this applies in Safari)

**Comment by ai** [comment]
Thanks or report. I will look at it on Friday. Seems like gradient direction syntax replacer has some problem with this direction.

**Comment by ai** [comment]
@BaliBalo Oops. I forget, sorry. Maybe you want to send PR?

**Comment by ai** [comment]
Done 847bfd5

**Comment by ai** [comment]
Released in 8.5

**Comment by BaliBalo** [comment]
Thanks a lot! Haven't had time to make a PR sorry.

**Comment by Finesse** [comment]
It introduces a bug in Chrome:

![image](https://user-images.githubusercontent.com/9006227/74095916-5f2e8e00-4b43-11ea-8f1f-da621d6ad009.png)
