### ISSUE TITLE
suggestion: ability to toggle off autoprefixer on folder regex match.

### ISSUE THREAD

**Issue by rokyed** [postcss/autoprefixer#1008]
I have a pretty specific case, where we have some very old CSS and autoprefixer, removes some of the properties and that breaks that CSS.

exclude some paths from autoprefixing by using regex in the config

if there is a solution please let me know, thanks.

**Comment by ai** [comment]
You can add `remove: false` option and Autoprefixer will not remove anything.

But it is strange that something is broken. Can you show me some examples of broken removes?

**Comment by rokyed** [comment]
wow, so fast

we do use ```remove: false``` for now. 

the kind of stuff that gets removed are: -webkit-box-pack, -webkit-box-orient which i know they are non standard now, but they still work in some browsers.

i guess ```remove: false``` it's the best option for this. 
also the autoprefixer works flawlessly.

**Comment by ai** [comment]
If your users still use browsers with `-webkit-box-pack`, you need to create `.browserslistrc` file and add your browsers to config by Browserslist queries https://github.com/ai/browserslist#queries

**Comment by rokyed** [comment]
I will come back at you with more data, because we are 2 working on this issue 😄and I've spoken with my coleague and we suspect maybe the issue it's not autoprefixer, i will dig further and will keep u updated 😄 thanks anyway
