### ISSUE TITLE
Grid Configuration For Django Project

### ISSUE THREAD

**Issue by ojtayo** [postcss/autoprefixer#1011]
I have set the environment variable in my django project as os.environ['BROWSERSLIST'] = 'last 3 versions'

How would I also include the config to specify grid is true?

**Comment by evgeny-petukhov** [comment]
How do you use autoprefixer?

**Comment by ojtayo** [comment]
I use it through COMPRESS_CSS_FILTERS and COMPRESS_POSTCSS_PLUGINS

I followed the instructions here..https://github.com/Pithikos/django-compressor-postcss which worked fine but was unable to figure out how to set the grid to be true as I haven't got a package.json in my solution.

**Comment by evgeny-petukhov** [comment]
This django module uses `postcss-cli` ana it uses shareable postcss config. Try to use `postcss.config.js` https://github.com/postcss/postcss-cli#config

**Comment by ojtayo** [comment]
Lovely, thank you

**Comment by evgeny-petukhov** [comment]
Also you can use `.browserslistrc`
