### ISSUE TITLE
-webkit-box-flex missing

### ISSUE THREAD

**Issue by oufresh** [postcss/autoprefixer#1012]
Hello,
I'm using autoprefixer within create-react-app. I tried to configure the browserlist in node_modules\react-scripts\config\webpackconfig.dev.js (or PROD).
The code is:

plugins: () => [
                    require('postcss-flexbugs-fixes'),
                    autoprefixer({
                      browsers: [
                        '>1%',
                        'last 4 versions',
                        'Firefox ESR',
                        'not ie < 9', // React doesn't support IE8 anyway
			'chrome 17'  // for SOE
                      ]/*,
                      flexbox: 'no-2009',*/
                    }),
                  ],

I addedd 'chrome 17' and removed flexbox: 'no-2009',.
I expect to find on a div flex element with "flex: 1" -> -webkit-box-flex: 1; but I don't see it in the browser elements debugging tool.
Is this translation supported?

May Thanks

**Comment by ai** [comment]
You should ask create-react-app.

We already sent them PR work correct Browserslist support (using `browsers` option is a wrong way), but they decide to delay it until next major update.
