### ISSUE TITLE
can work with caniuse-db-1.0.30000821

### ISSUE THREAD

**Issue by transtone** [postcss/autoprefixer#1013]
I use a [vue-cli](https://github.com/vuejs/vue-cli) repo, it use postcss-loader and autoprefixer to auto add prefixers to css file.
but it won't work when caniuse-db update from `1.0.30000789` to  `1.0.30000821`

repo for test: https://github.com/transtone/cli-server-test/tree/master

bug related:
https://github.com/vuejs/vue-cli/issues/1042

**Comment by ai** [comment]
What "won't work" means?

When you create a issue try to always ignore "won't work". It's bad practice. Describe what you do (input CSS), what is the result (output CSS), what you expected (expected output).

**Comment by transtone** [comment]
not a bug, sorry. It's browserlist settings that doc not mention.
