### ISSUE TITLE
broccoliBuilderErrorStack: TypeError: Cannot read property 'indexOf' of undefined     at OldSelector.check (./ui/node_modules/autoprefixer/lib/old-selector.js:79:27

### ISSUE THREAD

**Issue by mileslane** [postcss/autoprefixer#1019]
Is this the right project to report this error on?  Not sure what is going wrong here.  Thanks!
 
 - node: 8.10.0
  - v8: 6.2.414.50

ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: Cannot read property 'indexOf' of undefined
    at OldSelector.check (/Users/mileslane/Projects/cds-tools/ui/node_modules/autoprefixer/lib/old-selector.js:79:27)
    at /Users/mileslane/Projects/cds-tools/ui/node_modules/autoprefixer/lib/processor.js:189:29
    at /Users/mileslane/Projects/cds-tools/ui/node_modules/broccoli-postcss-single/node_modules/postcss/lib/container.js:237:28
    at /Users/mileslane/Projects/cds-tools/ui/node_modules/broccoli-postcss-single/node_modules/postcss/lib/container.js:144:26
    at Root.each (/Users/mileslane/Projects/cds-tools/ui/node_modules/broccoli-postcss-single/node_modules/postcss/lib/container.js:110:22)
    at Root.walk (/Users/mileslane/Projects/cds-tools/ui/node_modules/broccoli-postcss-single/node_modules/postcss/lib/container.js:143:21)
    at Root.walkRules (/Users/mileslane/Projects/cds-tools/ui/node_modules/broccoli-postcss-single/node_modules/postcss/lib/container.js:235:25)
    at _loop (/Users/mileslane/Projects/cds-tools/ui/node_modules/autoprefixer/lib/processor.js:188:17)
    at Processor.remove (/Users/mileslane/Projects/cds-tools/ui/node_modules/autoprefixer/lib/processor.js:211:13)
    at plugin (/Users/mileslane/Projects/cds-tools/ui/node_modules/autoprefixer/lib/autoprefixer.js:87:32)
  - codeFrame: Cannot read property 'indexOf' of undefined
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `PostcssCompiler` plugin. 💥
Cannot read property 'indexOf' of undefined
  - errorType: Build Error

**Comment by mileslane** [comment]
"assemble-base": "1.0.14",
    "assemble-buttons": "1.1.0",
    "assemble-forms": "1.1.1",
    "assemble-tables": "1.1.4",
    "autoprefixer": "7.2.5",
    "babel-eslint": "8.2.2",
    "bower": "1.8.4",
    "broccoli-asset-rev": "^2.4.5",
    "broccoli-builder": "0.18.11",
    "broccoli-postcss-single": "1.6.0",
    "broccoli-static-compiler": "0.2.2",
    "caniuse-lite": "^1.0.30000697",
    "css-mqpacker": "6.0.2",
    "cssnano": "3.10.0",
    "ember-ajax": "^3.0.0",
    "ember-cli": "~3.1.1",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.6.0",
    "ember-cli-dependency-checker": "^2.0.0",
    "ember-cli-eslint": "^4.2.1",
    "ember-cli-htmlbars": "^2.0.1",
    "ember-cli-htmlbars-inline-precompile": "^1.0.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-qunit": "^4.1.1",
    "ember-cli-shims": "^1.2.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^2.0.0",
    "ember-data": "~3.1.0",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.0.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-resolver": "^4.0.0",
    "ember-source": "~3.1.0",
    "ember-welcome-page": "^3.0.0",
    "eslint": "^4.0.0",
    "eslint-plugin-ember": "^5.0.0",
    "eslint-plugin-import": "2.11.0",
    "fs-extra": "^3.0",
    "loader.js": "^4.2.3",
    "postcss-animation": "0.0.12",
    "postcss-at-rules-variables": "0.1.5",
    "postcss-bem": "0.4.1",
    "postcss-bem-linter": "3.1.0",
    "postcss-color-function": "4.0.1",
    "postcss-cssnext": "3.1.0",
    "postcss-font-magician": "2.1.1",
    "postcss-for": "2.1.1",
    "postcss-import": "11.1.0",
    "postcss-map": "0.9.0",
    "postcss-media-minmax": "3.0.0",
    "postcss-mixins": "6.2.0",
    "postcss-neat": "2.5.3",
    "postcss-nested": "3.0.0",
    "postcss-use": "3.0.0",
    "stylelint": "7.13.0",
    "stylelint-config-standard": "15.0.1",
    "stylelint-selector-bem-pattern": "2.0.0"

**Comment by ai** [comment]
Hi. Thanks for a lot of info. But I need few other data:

1. Input CSS.
2. Browserslist config,

**Comment by mileslane** [comment]
Running `ember build` fails.  The error seems to occur before any CSS is getting processed.

testem.js contains:

/* eslint-env node */
module.exports = {
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launch_in_ci": [
    "PhantomJS"
  ],
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ]
};

Also, we are using bower components:

bower iCheck#1.0.2              cached https://github.com/fronteed/iCheck.git#1.0.2
bower iCheck#1.0.2            validate 1.0.2 against https://github.com/fronteed/iCheck.git#1.0.2
bower airbrake-js-client#0.5.9  cached https://github.com/airbrake/airbrake-js.git#0.5.9
bower airbrake-js-client#0.5.9         validate 0.5.9 against https://github.com/airbrake/airbrake-js.git#0.5.9
bower font-awesome#4.7.0                 cached https://github.com/FortAwesome/Font-Awesome.git#4.7.0
bower font-awesome#4.7.0               validate 4.7.0 against https://github.com/FortAwesome/Font-Awesome.git#4.7.0
bower node-uuid#1.4.7                    cached https://github.com/broofa/node-uuid.git#1.4.7
bower node-uuid#1.4.7                  validate 1.4.7 against https://github.com/broofa/node-uuid.git#1.4.7
bower jquery#>=1.7                       cached https://github.com/jquery/jquery-dist.git#3.3.1
bower jquery#>=1.7                     validate 3.3.1 against https://github.com/jquery/jquery-dist.git#>=1.7
bower iCheck#1.0.2                      install iCheck#1.0.2
bower airbrake-js-client#0.5.9          install airbrake-js-client#0.5.9
bower node-uuid#1.4.7                   install node-uuid#1.4.7
bower jquery#>=1.7                      install jquery#3.3.1
bower font-awesome#4.7.0                install font-awesome#4.7.0

**Comment by ai** [comment]
Hm. Can you put a `console.log` before this line in Autoprefixer. Don't worry any PostCSS is a simple JS functions. I need some input to fix the issue.

Also could you update Autoprefixer. Current version is 8.2.0. Even if I found a error the fix will be in 8.x release.

**Comment by mileslane** [comment]
I think maybe the problem isn't in this package. 
I put "output.log" here:

 77     OldSelector.prototype.check = function check(rule) {
 78         if (rule.selector.indexOf(this.prefixed) === -1) {
 79             console.log("Test");
 80             return false;
 81         }
 82         if (!rule.selector.match(this.regexp)) {
 83             return false;
 84         }
 85         if (this.isHack(rule)) {
 86             return false;
 87         }
 88         return true;
 89     };
 90
 91     return OldSelector;

 When I run `ember build`:

⠋ Building
The plugin argument has been deprecated, please set your plugins as a property on the options object.
Node#moveTo was deprecated. Use Container#append.
Node#before is deprecated. Use Node#raws.before
Node#moveAfter was deprecated. Use Node#after.
Node#moveTo was deprecated. Use Container#append.
Node#before is deprecated. Use Node#raws.before
cleaning up...
Test
Test
Test **(and lots more of these)**
Build failed.
Build Error (PostcssCompiler)
Cannot read property 'indexOf' of undefined

**Comment by ai** [comment]
Yeap. At first step please update PostCSS and Autoprefixer. Maybe I already fixed this error.

**Comment by mileslane** [comment]
`more node_modules/postcss/package.json` outputs:
  "name": "postcss",
  "version": "5.2.18",

I don't know how yarn manages dependencies when there are several conflicting requirements for the same package, but running `yarn install` reports no errors.

**Comment by ai** [comment]
Looks who include `postcss@^5.0.20` in `yarn list`.

**Comment by ai** [comment]
Do you have the same error in 8.3?

What is input CSS?
