### ISSUE TITLE
Convert place-items and place-content into their long formats

### ISSUE THREAD

**Issue by Dan503** [postcss/autoprefixer#1022]
````css
place-items: center;
````
=
````css
align-items: center;
justify-items: center;
````

**Comment by ai** [comment]
Good idea. But it is not vendor prefix, so it is not a feature for Autoprefixer.

What about creating custom PostCSS plugin (Autoprefixer is PostCSS plugin too). https://github.com/postcss/postcss/blob/master/docs/writing-a-plugin.md

**Comment by evgeny-petukhov** [comment]
@Dan503 I think it's also a good proposal to `postcss-preset-env`
