### ISSUE TITLE
[Feature Request] Control Comments PerLine

### ISSUE THREAD

**Issue by levin-du** [postcss/autoprefixer#1024]
Control Comments per line or multi-lines is very useful just like eslint does.  Thanks.

**Comment by ai** [comment]
Yeap. Good idea.

**Comment by ai** [comment]
Do you want to send PR?

I will have to implement it only in June.

**Comment by levin-du** [comment]
Interested in this question. Would you like to give me some hits on how to implement? It seems have some test case already.

**Comment by ai** [comment]
I think you should add some code here https://github.com/postcss/autoprefixer/blob/master/lib/processor.js#L340

**Comment by LonelyGriffin** [comment]
I have question. How do the 'ignore next' comment should  interact with nested the 'on' comment? Do it should ignore whole rule in spite off the 'on' comment or conversely.

**Comment by ai** [comment]
@LonelyGriffin I think ignore should disable adding a prefix to a selector or to at-rule, but ignore will not preventing adding prefixes to children. So no problems with nested `on` :D

**Comment by ai** [comment]
Done https://github.com/postcss/autoprefixer/pull/1027

**Comment by ai** [comment]
Released in 8.4

**Comment by ai** [comment]
@simevidas I agree with you. We even have this text in the docs.

But since they anyway need to find a docs to find this feature, it is OK to have it. We had a disabling comments. And a lot of users understand it wrong. So now we just fixed old control comments. Not add them.

**Comment by simevidas** [comment]
@ai By docs, do you mean the section on control comments in the README [1]? That section does not provide usage guidelines; the provided example is `transition: 1s;`. Meanwhile, the 8.4 release notes [2] provide the examples `user-select: none;` and `::placholder`.  

Is there a legitimate reason to disable prefixing for any of these three examples? If not, doesn’t this mean that these are bad examples?

However, if there *are* good reasons to disable Autoprefixer in these cases, I would recommend that these reasons are explained via a note. Some explicit guidelines are definitely needed (or even a warning).

[1]: https://github.com/postcss/autoprefixer#control-comments
[2]: https://github.com/postcss/autoprefixer/releases/tag/8.4.0

**Comment by ai** [comment]
@simevidas PR is welcome
