### ISSUE TITLE
grid-row: 1 / 3

### ISSUE THREAD

**Issue by ai** [postcss/autoprefixer#1031]
@evgeny-petukhov right we support `grid-row: 1 / span 3`. But can we support `grid-row: 1 / 3`?

Here is a origin Twitter thread from @bootsified and @adrifolio https://twitter.com/bootsified/status/991437060186652672

**Comment by bootsified** [comment]
Well, crap...  This may have been a false alarm after all.  Looks like my packages weren't up to date.  `npm update` isn't installing the latest versions for some reason.  I'll update in the morning - I have some dependencies issues to sort out - and I'll let you know if I still have trouble.  Sorry about that.  😕

**Comment by evgeny-petukhov** [comment]
`grid-column` and `grid-row` work the same now. But we really missed test case with `grid-row`, I'll add it this week.

**Comment by evgeny-petukhov** [comment]
It's very good.

Note:
@Dan503 Be careful with https://autoprefixer.github.com. It's is not official and don't have auto-updates of autoprefixer and postcss versions. For example, you tested the example in version 9.0.0, but actual version is 9.4.1
<img width="264" alt="image" src="https://user-images.githubusercontent.com/11796206/39568320-7e67364a-4eca-11e8-9b2f-26738b20d225.png">

It's better to use smth that works in runtime (e.g. runkit.com). See: https://runkit.com/alanev/5aead1d913bf340012f05d55
