### ISSUE TITLE
Don't prefix SCSS only CSS

### ISSUE THREAD

**Issue by KeviinCosmos** [postcss/autoprefixer#1034]
I use your awesome tool with visual code. I want not i autoprefix my scss files, but only my miified css file.. Is there a way?
I'm not using gulp or grunt, just the extension in VC.

Thanks, Keviin :)

**Comment by ai** [comment]
Hi. You should ask question to VC plugin author.

Autoprefixer is a plugin for PostCSS. PostCSS has a SCSS syntax support and can change SCSS sources. So You can run Autoprefixer on SCSS sources.

But I think VC plugin just has a code to block running Autopefixer on SCSS code. So you should ask plugin author to remove this code.

**Comment by ai** [comment]
Also, I highly recommend starting to use `postcss-cli` instead of VC plugin. It is a more flexible solution.

**Comment by KeviinCosmos** [comment]
Waw.. Fast reply! I'll check it out.. Thank you guys :)
