### ISSUE TITLE
[css-grid] The `grid-` prefix has been dropped from the `*‑gap` properties

### ISSUE THREAD

**Issue by ExE-Boss** [postcss/autoprefixer#1036]
The [`grid‑*‑gap` properties](https://drafts.csswg.org/css-align-3/#gap-legacy) were recently unprefixed into [`*‑gap` properties](https://drafts.csswg.org/css-align-3/#column-row-gap) [by the relevant](https://drafts.csswg.org/css-align-3/#gap-shorthand) [specifications](https://drafts.csswg.org/css-grid-1/#gutters).

## See also:
- [`column-gap` - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/column-gap)
- [`grid-row-gap` - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row-gap)
- [`grid-column-gap` - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column-gap)
- [`grid-gap` - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-gap)
- mdn/browser-compat-data#1990
- Fyrd/caniuse#3989

**Comment by evgeny-petukhov** [comment]
#1021

**Comment by ExE-Boss** [comment]
Done as [`postcss-gap-properties`](https://github.com/jonathantneal/postcss-gap-properties).
