### ISSUE TITLE
it doesn't work in webpack4.x vue-loader15.x

### ISSUE THREAD

**Issue by Qymh** [postcss/autoprefixer#1037]
i use webpack 4.6 vue-style-loader 4.1.0 but it doesn't work 
**this is the code Snippet**
![image](https://user-images.githubusercontent.com/29172211/39849468-162871fa-543f-11e8-90ca-c88ca3006bae.png)
**and this is postcss.config.js**
![image](https://user-images.githubusercontent.com/29172211/39849487-27ed2c46-543f-11e8-842f-0d2c3bff1e4d.png)
**this is my package.json**
![image](https://user-images.githubusercontent.com/29172211/39849489-311eb1d6-543f-11e8-996f-aa8ad5961d70.png)
**this is the reuslt**
![image](https://user-images.githubusercontent.com/29172211/39849517-5a6240c6-543f-11e8-9298-c46d085ab879.png)

**if you want to kown more you can see code there**
https://github.com/Qymh/webpackDemos/tree/master/vueTemplate/webpack

**Comment by ai** [comment]
You do not need any vendor prefixes for any your properties in CSS input.

Flexbox doesn’t need a prefix right now https://caniuse.com/flexbox

Try `::placeholder {}`

**Comment by Qymh** [comment]
@ai  thanks for your answer
lately , i used postcss-loader it would influence display:flex. now i try `animation`  `transition`  and it can work 
![image](https://user-images.githubusercontent.com/29172211/39853934-be2cbb78-5457-11e8-90a9-13988068f5c0.png)

**Comment by ai** [comment]
Yep, because we still need a prefix for `animation` and don’t need a prefix for flexbox.
