### ISSUE TITLE
IE 11 input placeholder styling problem

### ISSUE THREAD

**Issue by lohmatyi** [postcss/autoprefixer#1043]
According to [this stackoverflow issue](https://stackoverflow.com/questions/22199047/placeholder-css-not-being-applied-in-ie-11) IE 11 needs '!important' flag for rules inside his ':-ms-input-placeholder' pseudo-selector.
For me the problem was only visible on the development server but not on the production one.

**Comment by ai** [comment]
> For me the problem was only visible on the development server but not on the production one.

Very strange. Are we sure that it is the only and the best way?

Maybe we need some extra research here?

**Comment by Dan503** [comment]
I took a look at some of the comments and someone found the real fix. The html metadata was wrong

> Oh - it has something to do with the document mode.  If I change the document mode to 10 and back to edge, then it works. I hate document mode.

> Then remember to add `<meta http-equiv="X-UA-Compatible" content="IE=edge" />` to `<head>`. Also, use the HTML 5 doctype, i.e. `<!DOCTYPE html>`.

> Perfect!  That makes it work!  Thanks for that.
