### ISSUE TITLE
Config options for browserslist not supported

### ISSUE THREAD

**Issue by GodOfGrandeur** [postcss/autoprefixer#1053]
I've got a project setup with autoprexfixer and browserlist using the extends functionality provided by browserslist. When running I am getting the error:

> BrowserslistError: Unknown version 62 of android

To fix this i've added the **ignoreUnknownVersions** flag made available in the browserslist config. After some investigation i've noticed this flag isn't getting passed through to browserslist from the setup in the browsers.js file. Looks like the options it passes through are hardcoded on line 62-64 (if i manually set this option the error goes away). This in itself is a issue as there are more options supported by browserslist but these are never passed in.

We should fix this so that we send through all the options passed from a browserslist config when initialising the module in the browsers.js file and not hardcode this in order to support future changes.

**Comment by ai** [comment]
Yeap, there is no way to set option for Browserslist. 

The main problem is that not only Autoprefixer use Browserslist. For instance, what will be with Babel on same version.

What do you think about adding environment variable for it?

**Comment by GodOfGrandeur** [comment]
Not sure why we can't load this from the browserslist config like we do for the **browsers** config options.

**Comment by GodOfGrandeur** [comment]
Indeed so when this isn't set we read the config for this setting. I was just wondering why we can't do the same for the **ignoreUnknownVersions**, we wouldn't have to expose it as you could configure it from your browserslist config. I'm also leaning towards just setting this to true all the time as I can't forsee any side effects of this...

**Comment by ai** [comment]
Sure. I will think it on next week, OK? Sorry, I am in the middle of talk on HelsinkiJS.

Quick fix is `browsers: browserslist(browsers, opts)`

**Comment by ai** [comment]
Can you tell me more about your case? Why do you not use Browserslist config? Why do you need to specify Chrome by exact versions? 

We can add option, but I need more info — maybe there is much better API.

**Comment by GodOfGrandeur** [comment]
So I have a custom module which I import into my browserslist config in my app using browserslist extends functionality. The reason behind the custom module is that I export our GA stats from our account so we check against browsers our users use.

Now exporting this stats has caused an issue that one of the browsers is not supported by browserslist. Which is reporting the error:

BrowserslistError: Unknown version 62 of android

To get around this I've used the ignoreUnknownVersions:true option in my custom module which gets imported into my app. This means I have a single place for my config across all my apps. Now the autoprefixer works in that it is reading the stats from my custom module but is not passing through the ignoreUnknownVersions config option causing autoprefixer to throw the unknown version error.

**Comment by ai** [comment]
Hm. I am worried that adding `ignoreUnknownVersions` is a hack. We solve symptoms, but not the source of the problem.

What you will do when you will use this config in Babel 7, which doesn’t have `ignoreUnknownVersions`.

You are not the first who use Browserslist shared config to share GA stats. Maybe the real solution is to add GA stats to shared configs.

> So I have a custom module which I import into my browserslist config in my app using browserslist extends functionality. The reason behind the custom module is that I export our GA stats from our account so we check against browsers our users use.

Can you tell me more about this module?

**Comment by GodOfGrandeur** [comment]
The `ignoreUnknownVersions`option is a config option provided by browserslist https://github.com/browserslist/browserslist#js-api

It makes sense because GA won't valid the browser it receives is a real browser is just takes all data and stores it so when we export the data we end up with incorrect browsers (people may have a unsupported browser or a agent spoofing). This option was added for that. I've not checked if Babel 7 respects this config option from browserslist. I'm trying to produce a test to show the use case but will be going to USA this weekend so no guarantee I will get it over in time.

**Comment by ai** [comment]
Can you tell me more about “custom module which I import into my browserslist config”?

**Comment by ai** [comment]
I added the option 01b2d24

But I am still thinking that it is fixing symptoms instead of the real problem. So I am waiting for more info from you about how do you work with GA stats.

**Comment by GodOfGrandeur** [comment]
I was reading the README and saw the option and thought I was going crazy because I'd missed it, lol. 

Basically I run `npx browserslist-ga` and generate my custom stats, this however generates some stats which throw the error because the browser is invalid (this is as it is in GA). I can modify this file and remove the invalid browsers but we don't want to be doing this every month when I generate a new file. So I would prefer to use the `ignoreUnknownVersions` to solve this problem for me. 

My custom module looks like this:

`
const config = browserslist([], {
  stats: statsFile,
  ignoreUnknownVersions: true,
});

module.exports = config;
`
Then in my package.json I have:
`
"browserslist": [
    "extends browserslist-config-custom"
]
`
Your solution solves the issue however I would have been nice to have this inherit from the browserslist config so we don't have to define it in multiple places. Either way thanks for your help.

**Comment by ai** [comment]
OK, tomorrow we will have `ignoreUnknownVersions` as a temporary solution.

ANd in next month I will think about a better way to share custom statistics https://github.com/browserslist/browserslist/issues/258
