### ISSUE TITLE
classnames and id names become random strings?

### ISSUE THREAD

**Issue by slmjkdbtl** [postcss/autoprefixer#1060]
## setup
i'm using `parcel-bundler 1.8.1`, `postcss-modules 1.1.0` and `autoprefixer 8.6.2`

```json
// .postcssrc
{
	"modules": true,
	"plugins": {
		"autoprefixer": {
 			"grid": true
		}
	}
}

```
## problem
origin scss
```scss
#game {
    // ...
}
```

result css
```css
#_game_1pyaf_1 {
    /* ... */
}
```

don't have this problem if not using postcss autoprefixer

**Comment by slmjkdbtl** [comment]
i turned off module option and it's normal

**Comment by ai** [comment]
You have random class named because of `postcss-modules`. It is main purpose of `postcss-modules`. Just remove `postcss-modules` if you doesn't need selector isolation.
