### ISSUE TITLE
[css-grid] -ms-grid-columns -- wrong auto-fill value

### ISSUE THREAD

**Issue by dkrnl** [postcss/autoprefixer#1062]
input:
```css
grid-template-columns:repeat(auto-fill,minmax(400px,1fr));
```

output:
```css
-ms-grid-columns:(minmax(400px,1fr))[auto-fill];
grid-template-columns:repeat(auto-fill,minmax(400px,1fr));
```

browsers: last 4 version

**Comment by YozhikM** [comment]
@dkrnl Hey. And what kind of behavior is expected?

**Comment by yepninja** [comment]
IE doesn't support `auto-fill` and `auto-fit`. Let's don't add a prefixed prop and create warnings for these values.

**Comment by ai** [comment]
@yepninja good plan. Do you want to do it this weekend?

**Comment by yepninja** [comment]
Yes, I'll do it. Let's dedicate this weekend to "warnings" :)

**Comment by ai** [comment]
Done 30f3812

**Comment by tfalvo** [comment]
Hi. 
I completely understand the coherence of your change. 
However, since this update, I have a lot of warnings because IE is not supporting auto-fit. Could you bring me some help by giving an example on how to solve warning and to remove IE ?
I'm using Angular 6, and even if I remove IE from browsers list, warning remains.

package.json : 
`...
"browserslist": [
    "last 2 versions",
    "not ie <= 12",
    "not ie_mob <= 12"
  ],
...
`

output : 
`
WARNING in ./src/app/asset/components/.../my-component.scss
(Emitted value instead of an instance of Error) autoprefixer: /Users/xxx/yyy/src/app/asset/components/my-component.scss:23:27: auto-fit value is not supported by IE
...
`

Thanks a lot for your help !
Have a nice day.

**Comment by ai** [comment]
@tfalvo do you enabled Grid layout by `grid: true` option?

**Comment by tfalvo** [comment]
Hi. No I didn't change anything. In fact Autoprefixer is called directly by Angular CLI. 
I force downgrade to previous version of Autoprefixer, and it works fine. No more warning. 
For me it's ok now, but maybe you will receive soon new requests, if Angular changes its package dependencies...

**Comment by ai** [comment]
Strange. Maybe Angular team enabled Grid?

**Comment by koop4** [comment]
same problem here.
Just upgraded from Angular 5 to 6 and i got errors like these:

> 
> WARNING in ./somepath/some.component.scss
> (Emitted value instead of an instance of Error) autoprefixer: 
> .../somepath/some.component.scss:190:33: auto-fill value is not supported by IE

> WARNING in ./someotherpath/someother.component.scss
> (Emitted value instead of an instance of Error) autoprefixer: 
> .../someotherpath/someother.component.scss:18:29: auto-fill value is not supported by IE
> 

i'll be happy to provide anything you need to find a way to remove these warnings which are pretty annoying

**Comment by ai** [comment]
@koop4 try to investigate. Did they enable `grid` by default in Angular?

**Comment by nazarkryp** [comment]
I also get that annoying warning. (Emitted value instead of an instance of Error) autoprefixer ...auto-fill value is not supported by IE;
does anyone know how to disable those warnings, I don't give * about IE

**Comment by ai** [comment]
@nazarkryp just remove `grid: true` option from your Autoprefixer

**Comment by nazarkryp** [comment]
@ai i don't have specified 'grid: true' anywhere. i use default angular project generated by angular-cli

**Comment by ai** [comment]
@nazarkryp I sent a PR to Angular CLI https://github.com/angular/angular-cli/pull/11453

**Comment by tfalvo** [comment]
Sorry but I don't understand, why we should disable completely grid feature in autoprefixer. 
For example, in my case, I use grid layout and it was working perfectly with Angular. 
But what about update you made in project mentioned at the beginning of this discussion. 
Please @yepninja could you explain what is this change "IE doesn't support auto-fill and auto-fit. Let's don't add a prefixed prop and create warnings for these values.". And so why theses warnings appear even if you add browser rules omission on autoprefixer. 

Is it possible to "unscope" IE but not all the grid feature ?

Sorry in advance if my comprehension is not good. but i'm a little afraid we'll shut down the tree while we can probably just cut a branch... ;-)

**Comment by ai** [comment]
@tfalvo we don't need to disable it completely. Current idea is to disable it by default and enable only if you understand it's limits

**Comment by tfalvo** [comment]
why not suppress warning recently added if IE is not in browser list ? It could in this way respect autoprefixer's coherence and rules. What do you think ?

**Comment by ai** [comment]
@tfalvo I think we don't see a warning if there is no IE 10-11 in Browserslist config. The problem is that some of users uses different techniques to run Grid in IE and they don't need prefixes

**Comment by tfalvo** [comment]
@ai it was my issue. I tried to exclude IE with a lot of different ways. But no change, warnings remain. So if we find the correct way to exclude IE I think it will be ok for every body. As Angular dev, we will add an exclude rule on project config. It could be a proper way to solve issue.

**Comment by ai** [comment]
I fix the warning. Not it will not be printed if you didn’t select IE 11 in [Browserslist](https://github.com/browserslist/browserslist) config
