### ISSUE TITLE
doesn't output ms- prefix for relevant IE 9 styles

### ISSUE THREAD

**Issue by steveblue** [postcss/autoprefixer#1066]
With 8.6.3 I can't get autoprefixer to output the ms prefix or 2D transforms.

```
transform:translateX(-50%) translateY(35px);
```
becomes
```
  -webkit-transform:translateX(-50%) translateY(35px);
          transform:translateX(-50%) translateY(35px);
```

when I need

```
  -ms-transform:translateX(-50%) translateY(35px);
  -webkit-transform:translateX(-50%) translateY(35px);
                transform:translateX(-50%) translateY(35px);
```

using this Browserslist config

```
last 5 versions
Firefox ESR
not dead
IE 9-11
```

and have this option set, per the documentation.

```
'autoprefixer': {
        remove: false
    }
```

**Comment by ai** [comment]
Try to remove `non dead` query (IE <= 10 is dead browsers).

If it will not help: Where do you put Browserslist config. How do you run Autoprefixer?

**Comment by steveblue** [comment]
In package.json
```
  "browserslist": [
    "last 5 versions",
    "Firefox ESR",
    "IE 9-11"
  ],
```
and I tried `browserslist` file

I am using the postcss-cli
```
postcss src/components/card/card.component.css  --output card.component.css --config postcss.config.js --use autoprefixer --no-map --verbose
```

**Comment by steveblue** [comment]
Ok this seems to be a postcss-cli issue. It took me awhile to track down but using the pipe works, but the traditional command does not. `cat src/components/card/card.component.css | postcss -u autoprefixer > card.component.css`
