### ISSUE TITLE
adding `don't auto prefix ******`

### ISSUE THREAD

**Issue by oriSomething** [postcss/autoprefixer#107]
it might exists but i didn't found it...
the problem is that sometime there is a style like `flexbox` that you don't want to be `auto prefix` when you create something that is compatible with browser that has old implementation.
because poor implementation of `flexbox` for example, there are rules that cannot be implemented in some browser like `IE 10` which can result a poor layout, and _not_ supporting `IE 10` is usually not an option if not earlier versions. specific right now i use `Modernizr` for `flexboxlegacy`, but it wasn't always work as you expected.

so is there a way to do something like:
`autoprefixer("last 2 version", "ignore flexbox").compile(css);`

by the way, <strong>big thanks</strong>. this project saves me time after time.

**Comment by yairEO** [comment]
is there a way to do this already? 
Thought it would be easy to ignore a section which is wrapped between comments, but it seems to be taking years :/

**Comment by philwareham** [comment]
How would this work on `@supports` rules?

**Comment by ai** [comment]
@philwareham this tread is too big for “this” :). Can yoou explain?

**Comment by philwareham** [comment]
Sorry, but this code example seems to totally turn off autoprefixing for my whole stylesheet - I just want to disable autoprefixing of the `@supports` rule only:

    /* autoprefixer: off */
    @supports (transition: all) {
        /* autoprefixer: on */
        a {
            /* autoprefixer: off */
        }
    }

By the way, there is a type in your README example, should be `@supports` not `@support`.

**Comment by ai** [comment]
@philwareham thanks, fixed

**Comment by ai** [comment]
@philwareham `/* autoprefixer: off */`  disable Autoprefixer in current body. So if you put it to root it will disable Autoprefixer in all document.

BTW, why you need to disable Autoprefixer for `@support`?

**Comment by philwareham** [comment]
Basically I need this rule to stay exactly as-is:

    @supports (display: flex) { .. }

Because autoprefixer makes it this:

    @supports ((display: -webkit-flex) or (display: -ms-flexbox) or (display: flex)) { ... }

Which is incorrect, because Safari 8 (which used `-webkit-flex`) and IE (which used `-ms-flexbox`) don't use `@supports` anyway.

**Comment by ai** [comment]
@philwareham if you problem is only with this, custom PostCSS plugin can solve it:

```js
var postcss = require('postcss');

module.exports = postcss.plugin('flexbox-cleaner', function () {
    return function (css) {
        css.walkAtRule('supports', function (rule) {
            rule.params = rule.params.replace('((display: -webkit-flex) or (display: -ms-flexbox) or (display: flex))', '(display: flex)');
        });
    };
}
```

**Comment by ai** [comment]
@philwareham other solution is to put `@supports` into some other body, like `@media {}`. But it will produce extra CSS, which you want to avoid.

**Comment by dantman** [comment]
That problem may be worthy of splitting into a separate bug. If certain prefixed properties just don't exist in any browser that supports `@supports`, then autoprefixer should understand that and omit those properties in the `@supports` line. Ideally that would cascade and restrict browsers that affect the nested properties but that might be a bit harder.

**Comment by ai** [comment]
@dantman yeap, you can open a bug. But I will not have time on it in near future.

**Comment by philwareham** [comment]
@ai OK thanks, erm... how do I add that custom PostCSS plugin to my Grunt task?...

    postcss: {
        options: {
            processors: [
                require('autoprefixer')({
                    browsers: ['last 2 versions']
                })
            ]
        },
        ...
    },

Thanks for any help.

**Comment by ai** [comment]
```js
postcss: {
    options: {
        processors: [
            require('autoprefixer')({
                browsers: ['last 2 versions']
            }),
            require('./my-postcss-plugin')
        ]
    },
    ...
},
```

**Comment by ai** [comment]
@philwareham BTW, I think I fix this issue and next Autoprefixer 6.2 will not add prefxes for non-`@supports` browsers

**Comment by ai** [comment]
@philwareham @dantman Done. Not Autoprefixer uses only browsers with `@supports` support in `@supports` params prefixing. But `@supports` content will be prefixed in old way.

Sorry, adding fix for `@supports` content can make a mess from Autoprefixer sources. And it is a bad price for that 0,01% `app.css.gz` size.

**Comment by philwareham** [comment]
Brilliant, thanks! Will await 6.2 and will use your custom postCSS plugin workaround for now.

**Comment by foreverling** [comment]
I met the same problems as you. Finally, I found that the options of postcss  need to be configured to limit the range of vendor prefixes. For example, like this:
`options: {
        processors: [
          require('autoprefixer-core')({browsers: ['> 1%','last 1 version', 'Firefox ESR', 'Opera 12.1']})
        ]
      }`

**Comment by foreverling** [comment]
I met the same problems as you. Finally, I found that the options of postcss need to be configured to limit the range of vendor prefixes. For example, like this:
```javascript
options: {
        processors: [
          require('autoprefixer')({browsers: ['> 1%','last 1 version', 'Firefox ESR', 'Opera 12.1']})
        ]
      }
```
