### ISSUE TITLE
Different autoprefixing than in https://autoprefixer.github.io/

### ISSUE THREAD

**Issue by ifisidro** [postcss/autoprefixer#1070]
Hey there!

I'm opening this issue cause I'm blocked figuring out why my CSS isn't autoprefixed / compiled into the same result using postcss + autoprefixer in Node.JS as in https://autoprefixer.github.io/.

In https://autoprefixer.github.io/, with
`broswers = "> 0.3%, last 6 iOS versions, last 2 versions, not dead"`

A `display: grid;` is compiled into:

`display: -ms-grid;
 display: grid;`

But in my Node.js code I'm not getting the same result, `display: grid` is left as `display: grid`.
My code is the following:

`
const autoprefixerLib = require('autoprefixer');
const postcss = require('postcss');`

**npm-shrinkwrap.json:**
` ...
"postcss": {
      "version": "6.0.19", 
...`
and 
`...
    "autoprefixer": {
      "version": "8.0.0",
...`

So you may notice that I'm using the same version as https://autoprefixer.github.io/ currently displays. the above.

Then I use it here:
`
postcss([ autoprefixerLib({ browsers }) ]).process(readFile, { from: filename }).then(function(result) {
`

Where:
* `browsers` is ` ["> 0.3%", "last 6 iOS versions",  "last 2 versions", "not dead"]`
* `readFile` is the CSS file (read from the filesystem) to compile/to be autoprefixed

¿Someone may help me to figure out what I'm doing wrong? I really would appreciate your help.

**Comment by ai** [comment]
Current version is 8.6.3

**Comment by ifisidro** [comment]
Okay, sorry, I'll open the issue there! 

Thanks for the quick response
