### ISSUE TITLE
[css-grid] Grid fallback for IE should require implicit grid item assignment

### ISSUE THREAD

**Issue by CyberAP** [postcss/autoprefixer#1074]
IE does not have implicit grids and they can not be safely emulated without knowing markup (assuming markup is always static). That means if there is a `display: -ms-grid;` value without explicit grid areas the grid would fail to display correctly.

Example:

```html
<div class="grid">
   <div>First cell</div>
   <div>Second cell</div>
</div>
```
```css
.grid
{
   display: -ms-grid;
   display: grid;
}
```
The code above would render elements on top of each other in IE, which is not expected.

![Grid fail](https://i.imgur.com/eWbpBvu.png)

**Comment by ai** [comment]
How will modern browsers show this settings-less grid?

**Comment by ai** [comment]
Let’s think for conditions to show a warning.

**Comment by CyberAP** [comment]
That's how it should be and how modern browsers render it:
![Correct behaviour](https://i.imgur.com/1kdPIpM.png)

The problem with this is that it is not fixable at all. Grid items in IE require explicit grid cell assignment.
We can not determine the connected grid items for the particular container. That means that the info message should be shown every time grid fallback is used. 

> Info: grid items must be implicitly assigned to grid cells for IE support

**Comment by ai** [comment]
@CyberAP the core idea of using Autoprefixer is to always use it with `grid-template-areas`

**Comment by CyberAP** [comment]
Setting `grid-template-areas` or `grid-template-columns\rows` won't fix this, unfortunately. Grid items still have to be manually assigned to proper cells and rows. Autoprefixer doesn't inform you about that right now and I think it should (once per process would be fine I guess).

**Comment by ai** [comment]
Autoprefixer will inform you if you explicit ask for auto placement.

If we will have clear conditions, we can inform about other cases as well.

**Comment by ai** [comment]
Of course, we don't tell that any Grid can be converted. This is why Grid feature is behind the flag.
