### ISSUE TITLE
NOT ABLE TO INSTALL ng new my-app

### ISSUE THREAD

**Issue by srjkrl20011991** [postcss/autoprefixer#1076]
I am new in angular ... getting error
CREATE UserApp/e2e/tsconfig.e2e.json (213 bytes)
npm ERR! code E500
npm ERR! 500 Internal Server Error: autoprefixer@^8.4.1

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\suraj.karale\AppData\Roaming\npm-cache_logs\2018-07-03T06_16_43_259Z-debug.log
Package install failed, see above.

Version Details -

Angular CLI: 6.0.8
Node: 8.11.1
OS: win32 x64
Angular:
...

Package Version

@angular-devkit/architect 0.6.8
@angular-devkit/core 0.6.8
@angular-devkit/schematics 0.6.8
@schematics/angular 0.6.8
@schematics/update 0.6.8
rxjs 6.2.0
typescript 2.7.2

**Comment by ai** [comment]
It is just npm server error. Doesn’t related with Autoprefixer. It was just a random package during installation.

But anyway thank for the report. It is better to have few false alarms, rather than lost really important issue.
