### ISSUE TITLE
Possibly misleading documentation about postcss-preset-env

### ISSUE THREAD

**Issue by halfzebra** [postcss/autoprefixer#1088]
Hello, thanks for the autoprefixer! 👍 

During the migration of my build setup to [postcss-preset-env](https://github.com/csstools/postcss-preset-env), I've stumbled upon the [mention of the preset](https://github.com/postcss/autoprefixer#does-it-add-polyfills) in Autoprefixer docs.

Since the preset includes Autoprefixer, I'm assuming it's worth mentioning that in the docs.

I'll send a PR if this makes sense and please feel free to close this issue if not.

**Comment by ai** [comment]
Sure. This plugin is our friend and we always want to promote it. Feel free to send PR.
