### ISSUE TITLE
 npm install autoprefixer >> Unexpected token } in JSON at position 1371

### ISSUE THREAD

**Issue by jcraigtt** [postcss/autoprefixer#1100]
Hi there, 

Just an FYI.   While using npm via meteor the basic no-options install of autoprefixer failed today.   I re-ran it 4-5 with same exact result each time.   

Hoping to try it soon...  

Have a great day.

C:\lrproj\project01\t>meteor npm install autoprefixer
npm ERR! file C:\lrproj\meteor1\t\package.json
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! Unexpected token } in JSON at position 1371 while parsing near '...-vars": "^3.0.0",
npm ERR!   },
npm ERR!   "dependencies":...'
npm ERR! File: C:\lrproj\meteor1\t\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by ai** [comment]
It is npm servers problem. Sorry, I don’t have any way to fix it.

**Comment by jcraigtt** [comment]
No problem at all.   Thanks to you and this team for making a FOSS contribution!
