### ISSUE TITLE
Autoprefixer setting -ms-grid row and column to opposite actual values

### ISSUE THREAD

**Issue by Dawdre** [postcss/autoprefixer#1122]
https://stackoverflow.com/questions/52425765/css-grid-ms-grid-row-and-column-being-set-opposite-to-actual-value

I posted a question regarding this here. With a little more investigation I think this may be a autoprefixer issue. As when I manually add the -ms- syntax (I am compiling from Sass) into the compiled CSS file. It works correctly.

**Comment by Dan503** [comment]
That's odd :/
Are you using the latest version?

Try pasting your input code into this:

http://autoprefixer.github.io/

Does it still cause the issue?

**Comment by ai** [comment]
Hi. I am on conference today. I will try to look at weekend.

Maybe @Dan503 can help you?

**Comment by Dawdre** [comment]
Thanks for the quick replies.

Yes here is my Sass code:

```
#wrapper {
	//wrapper grid template
	display: grid;
	grid-template-rows: 45px 100px 1fr;
	grid-template-columns: 1fr;
	grid-template-areas: "menu"
						 "context-header"
						 "main";
}

#main {
	height: $viewport-height;
	//grid child of wrapper
	grid-area: main;
	//main grid template
	display: grid;
	grid-template-rows: 1fr;
	grid-template-columns: 15em 1fr;
	grid-template-areas: "sidebar" "content";

	#sidebar {
		//grid child of main
		grid-area: sidebar;	
		grid-column: 1;
		grid-row: 1;
		//styles
		background: #f4f4f4;
		padding: 1em;
	}

	#content {
		//grid child of main
		grid-area: content;
		grid-row: 1 / 2;		
		grid-column: 2 / 3;

		//styles
		padding: 1em;

		//content grid template
		display: grid;
		//grid-template-areas: "content-actions" "panel-actions" "content-all" "content-actions" "panel-actions";
		grid-template-rows: repeat(2, minmax(min-content, max-content)) 1fr repeat(2, minmax(min-content, max-content));
		grid-template-columns: 2fr 1fr;
	}
}
```

**Comment by ai** [comment]
Check the version of Autoprefixer by `npm ls | grep autoprefixer`

**Comment by Dan503** [comment]
You can use this to convert your SCSS to CSS 

https://www.sassmeister.com/

**Comment by Dawdre** [comment]
It does work in http://autoprefixer.github.io/.

gulp-autoprefixer@5.0.0
autoprefixer@8.6.5

**Comment by ai** [comment]
Try to update Autoprefixer first

**Comment by Dan503** [comment]
Ok well try upgrading you're version of Autoprefixer then.

You may need to upgrade gulp-postcss as well.

**Comment by Dawdre** [comment]
Does this need remedying?

```
+-- autoprefixer@9.1.5
| +-- browserslist@4.1.1
| | +-- electron-to-chromium@1.3.70
| | `-- node-releases@1.0.0-alpha.11
| |   `-- semver@5.5.1
| +-- caniuse-lite@1.0.30000885
| `-- postcss@7.0.2
|   +-- chalk@2.4.1
|   | `-- ansi-styles@3.2.1
|   +-- source-map@0.6.1
|   `-- supports-color@5.5.0
`-- gulp-autoprefixer@5.0.0
  `-- autoprefixer@8.6.5
    `-- browserslist@3.2.8

PS C:\Users\escull\Documents\GitHub\Grid-Layout> npm ls | grep autoprefixer
npm ERR! extraneous: autoprefixer@9.1.5 C:\Users\escull\Documents\GitHub\Grid-Layout\node_modules\autoprefixer
+-- autoprefixer@9.1.5 extraneous
+-- gulp-autoprefixer@5.0.0
| +-- autoprefixer@8.6.5
```

**Comment by Dan503** [comment]
`gulp-autoprefixer` is your issue.

Use `gulp-postcss` instead and then import Autoprefixer as a post-css plugin. 

https://www.npmjs.com/package/gulp-postcss

**Comment by Dan503** [comment]
You will need to uninstall `gulp-autoprefixer` for it to work.

**Comment by Dawdre** [comment]
```
var gulp = require('gulp');
var postcss = require('gulp-postcss');
var sass = require('gulp-sass');
var autoprefixer = require('autoprefixer');

var sassOptions = {
	outputStyle: 'expanded'
};

var autoprefixerOptions = {
	browsers: ['last 3 versions', '> 0.1%', 'Firefox ESR'],
	grid: true
};

gulp.task('sass', function() {
	return gulp.src('scss/**/*.scss')
	.pipe(sass(sassOptions))
	.pipe(autoprefixer(autoprefixerOptions))
	.pipe(gulp.dest('css'))
});

gulp.task('watch', function(callback) {
	gulp.watch('scss/**/*.scss', ['sass']);
});
```
I have modified my `gulpfile.js` to this. Will this work?
Also what is the best way to uninstall that package? Can I just delete it from the directory?

**Comment by bogdan0083** [comment]
You can read about uninstalling npm packages [here](https://docs.npmjs.com/cli/uninstall)

In your `gulpfile.js` you don't use `postcss` plugin. You can read about usage examples [here](https://www.npmjs.com/package/gulp-postcss) (this link has an example with autoprefixer):

**Comment by Dan503** [comment]
The critical bit you left out was this bit

```js
    var plugins = [
        autoprefixer({browsers: ['<0.5%']})
    ];
```

**Comment by ai** [comment]
Also, Autoprefixer best practices is to use `.browserslistrc` file in project root with

```
> 0.5%
```

Instead of `browsers` option.

**Comment by Dawdre** [comment]
I very much appreciate everyone's help. But I just retested it. I now have latest versions of autoprefixer and gulp-postcss (The same versions as http://autoprefixer.github.io). And I am still getting my original problem 😭. -ms-grid-row and column are compiling to the exact opposite values stated in my sass file. This is very odd as no other div in my layout displays this behaviour.

Again I appreciate everyone's time.

**Comment by Dan503** [comment]
Can you post input, output, and expected output code samples?

Post reduced test cases that only have the problematic grid styles. Don't post your entire CSS file.

**Comment by Dawdre** [comment]
**Input:**
```
#content {
 //grid child of main
 grid-area: content;
 grid-row: 1;		
 grid-column: 2;
}
```
**Output:**
```
#content {
  -ms-grid-row: 2;
  -ms-grid-column: 1;
  grid-area: content;
  grid-row: 1;
  grid-column: 2;
}
```

**Exact same use case:**
This `#sidebar` is the direct sibling of the `#content` div and both are the only children of the parent grid.
**Input**
```
#sidebar {
//grid child of main
grid-area: sidebar;	
grid-column: 1;
grid-row: 1;
}
```
**Output:**
```
#sidebar {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: sidebar;
  grid-column: 1;
  grid-row: 1;
}
```
Again if I manually add the correct values in the output css it works as intended in IE10 and 11.

**Comment by Dan503** [comment]
Why are you using both grid area and grid column/row settings in the same rule?

**Comment by Dan503** [comment]
Either use grid area or use grid column/row. Don't use both at the same time. That is why Autoprefixer is freaking out.

**Comment by ai** [comment]
Should we show warning?

**Comment by Dawdre** [comment]
Ah I see. Ok I was getting very confused because the sidebar was behaving as normal. I didn't see to try this. It does work now. Would you never use them together?

**Comment by Dan503** [comment]
Yeah we probably should to stop people from doing silly things like this.

**Comment by ai** [comment]
Let's not call it silly, because I do the same mistake many times 😅

**Comment by Dan503** [comment]
> Would you never use them together?

They are never to be used together because they are two different ways of telling the grid cell where it belongs in the grid.

What were you even trying to achieve by setting both grid area and column/row in the same rule?

**Comment by Dawdre** [comment]
Well I apologise for being silly. https://css-tricks.com/css-grid-in-ie-css-grid-and-the-new-autoprefixer/ does give the impression you can use `area` properties together. 
Honestly putting them together intentionally was not my intention. I set the areas before I started to make it IE compatible. But I can imagine this be quite a common occurrence?
 
I thank you all for your time and enjoy your weekends.
