### ISSUE TITLE
Not expanding CSS 

### ISSUE THREAD

**Issue by Abd-Ur-Rehman** [postcss/autoprefixer#1136]
I have installed it and even though I have `v8.12.0` Why it's not working for me? Could be the $PATH is wrong? I don't find info to change that. Can you let me know know?

**Comment by ai** [comment]
@Abd-Ur-Rehman what is input CSS and output CSS? How do you run Atuoprefixer?

(Always try to add this information to any issue in open source projects)

**Comment by Abd-Ur-Rehman** [comment]
Sorry about that, I just made a video, I'm checking this for `box-shadow` have a look at this video.https://youtu.be/-hQnAQ9qUbM

**Comment by ai** [comment]
`box-shadow` doesn't need prefixes.

If you want to test Autoprefixer try `::placeholder {}`

**Comment by Abd-Ur-Rehman** [comment]
Ah! sorry, got this working. Didn't know that doesn't need anymore. Thanks for your time. 👍

**Comment by ai** [comment]
Yeap, it is amazing how many prefixes was removed 😍

**Comment by Abd-Ur-Rehman** [comment]
I tested this with `  background: linear-gradient(top, blue, white);` and it doesn't add the webkit prfix If I use it through this http://expressprefixr.herokuapp.com/ it does add the prefix and add the correct CSS `  background: -webkit-linear-gradient(top, blue, white);` Can you test this on your end?

**Comment by ai** [comment]
Gradients doesn’t need prefixes too https://caniuse.com/#feat=css-gradients

**Comment by Abd-Ur-Rehman** [comment]
I'm using `Version 69.0.3497.100 (Official Build) (64-bit)` and when I don't add -webkit- it doesn't work. Would you mind trying this on your end?

**Comment by ai** [comment]
Because you use old gradient syntax.

Autoprefixer even writes it to the warning, but your text editor plugin doesn’t show these warnings. This is why I suggest using `gulp-postcss` or `postcss-loader` to use Autoprefixer.

`top` → `to bottom`

**Comment by Abd-Ur-Rehman** [comment]
Is the postcss-loader available in package control?
I'm getting these results when searched. 
![image](https://user-images.githubusercontent.com/7280837/46583631-3d5a5e00-ca5a-11e8-9288-1085fa87a01e.png)

**Comment by ai** [comment]
`postcss-loader` is a plugin for webpack. Stand-alone build tool. Out of text editor.

**Comment by ai** [comment]
What Atom plugin do you use for Autoprefixer? Maybe we can create an issue there to show warnings?

**Comment by Abd-Ur-Rehman** [comment]
I'm using Sublime Text 3

**Comment by ai** [comment]
What plugin for Sublime Text 3 to do you use for Autoprefixer?

**Comment by Abd-Ur-Rehman** [comment]
I'm using this one https://github.com/postcss/autoprefixer

**Comment by ai** [comment]
@Abd-Ur-Rehman this is a core. It is just JS library, which has no UI.

So, if you run it in a text editor you use some wrapper around this JS library and PostCSS.

**Comment by Abd-Ur-Rehman** [comment]
Well, I was adding prefixes via web just started using this. I got this recommended from one post, don't seem to get how does it work. 😕 

Do I need an extra plugin to work with this?

**Comment by ai** [comment]
Did you use autoprefixer.github.io

I need to know where do you put your CSS. We need to ask creator of this wrapper add code to show warnings

**Comment by Abd-Ur-Rehman** [comment]
>Did you use autoprefixer.github.io

No, I didn't use this. 

About what I use, I'd posted that link above, which is http://expressprefixr.herokuapp.com/ If you use this CSS:
`.box {
    width: 500px;
    height: 500px;
    text-align: center;
    margin: 0 auto;
    background: linear-gradient(top, red 50%, blue 25%, green);
}
`

You'll get:

`.box {
  width: 500px;
  height: 500px;
  text-align: center;
  margin: 0 auto;
  background: -webkit-linear-gradient(top, red 50%, blue 25%, green);
  background: -moz-linear-gradient(top, red 50%, blue 25%, green);
  background: -ms-linear-gradient(top, red 50%, blue 25%, green);
  background: -o-linear-gradient(top, red 50%, blue 25%, green);
  background: linear-gradient(top, red 50%, blue 25%, green);
}`

Can you share post or tutorial how can I setup this properly to work within the text editor?

**Comment by Abd-Ur-Rehman** [comment]
>So, how do you added prefixes with Autoprefixer? Where do you post your CSS to get prefixes?

I'm a newbie, just starting to use it in Sublime Text 3. Before I was adding the prefixes via webs e.g. the link I'd shared above. 

About to use the `top` just adding the webkit prefix it works.

**Comment by ai** [comment]
> About to use the top just adding the webkit prefix it works.

It works now, but will not work in the future. Check MDN docs: https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient They say that current correct syntax is only `to bottom`, not `top`. `top` was a old syntax, some browsers support it for a while, but there is no guarantee that they will support it in future.

**Comment by Abd-Ur-Rehman** [comment]
Ok. Thanks for sharing that. Won't use it anymore. 

In Sublime, I'm trying to install this https://github.com/sindresorhus/sublime-autoprefixer but I think I have it already: 
![image](https://user-images.githubusercontent.com/7280837/46584149-071fdd00-ca60-11e8-967b-5aca6fdf1bdc.png)
Right? If so then it won't show up any warnings.

**Comment by ai** [comment]
@Abd-Ur-Rehman yeap, Autoprefixer plugin for Sublime doesn’t support warnings. And also there is no way to open an issue there :(.

**Comment by Abd-Ur-Rehman** [comment]
Ok. thank you for your time. :)

Will find something else...
