### ISSUE TITLE
Warnings for IE although IE is excluded through browserlist

### ISSUE THREAD

**Issue by DaSchTour** [postcss/autoprefixer#1137]
I'm getting a lot of warning ins my project about `grid-auto-flow` not beeing supported in IE. As the application I'm build will not run in IE at all and we display another page that tells the user to use another browser and we have excluded IE prefixes through browserlist this warnings don't make much sense, as many other things also would not work because of missing IE prefixes.

And from reading https://nealbuerger.com/2018/01/the-end-of-life-of-internet-explorer-11/ recently I think we should discourage developing for IE 11 to speed up retirement of IE 11.

**Comment by Dan503** [comment]
You probably have the `grid` setting enabled  then.

Though it's odd that you are receiving warnings if you have explicitly stated that you are not supporting IE in your browser list settings 😕

**Comment by ai** [comment]
1. The best way to solve it is to disable `grid` option.
2. Quick version to fix it is to add PostCSS plugin after Autoprefixer which will clean `result.warnings`.
3. The optimal way is to wait for 9.2 release. We will implement `/* autoprefixer grid: off */` control comment. The code is ready.

**Comment by Dan503** [comment]
Ooooh I didn't know about the `/* autoprefixer grid: off */` control comment. That's a great idea! 😁

**Comment by Dan503** [comment]
@ai I think there might still be an issue here. If the user has explicitly set in their browser settings to not support IE or the older versions of Edge but for whatever reason the grid setting is enabled, we should not be outputting grid translations or warnings.

**Comment by ai** [comment]
@DaSchTour can you show Autoprefixer version from `npm ls` and your Browserslist config?

**Comment by ai** [comment]
@DaSchTour Add `not ie_mob <= 11` to hide warnings

@Dan503 thanks to note it

**Comment by DaSchTour** [comment]
So it looks like this now
```
"browserslist": [
    "> 1%",
    "last 3 versions",
    "not dead",
    "not ie <= 11",
    "not ie_mob <= 11"
  ],
```

But that didn't help. But I suspect that's because of the old version.

**Comment by ai** [comment]
Ping me in issue, when you ask `angular-cli` team to update Autoprefixer

**Comment by Dan503** [comment]
@ai have you tested that the current build does not output warnings when grid is set to true but IE support is set to false in the browser list?

**Comment by ai** [comment]
Yeap, we fixed this issue
