### ISSUE TITLE
[css-grid] Syntax error for grid-template-columns

### ISSUE THREAD

**Issue by Genenenenaam** [postcss/autoprefixer#1150]
When compiling scss with autoprefixer i get css syntax error, because of added [#] to -ms-grid-columns.

Input:
`grid-template-columns: repeat(2, 1fr);`

Output:
`
-ms-grid-columns: (1fr)[2];
grid-template-columns: repeat(2, 1fr);
`

Autoprefixer config:
`
{
    cascade: false,
    browsers: [
      "ie >= 11",
      "last 1 Firefox version",
      "last 1 Chrome version",
      "last 1 Opera version"
    ],
    grid: true
}
`

**Comment by Dan503** [comment]
Did you test it in IE before posting?

`-ms-grid-columns: (1fr)[2];` is the old IE way of writing `grid-template-columns: repeat(2, 1fr);`

See this for more details:

https://css-tricks.com/css-grid-in-ie-debunking-common-ie-grid-misconceptions/#article-header-id-2

**Comment by Genenenenaam** [comment]
Tnx, didn't know that.

**Comment by Dan503** [comment]
FYI, you should read the full CSS Grid in IE series before attempting to use the IE CSS Grid translations that Autoprefixer outputs. There are many Caveats that you need to be aware of.

https://css-tricks.com/css-grid-in-ie-debunking-common-ie-grid-misconceptions/
