### ISSUE TITLE
Remove unneeded nested calc()

### ISSUE THREAD

**Issue by tkrotoff** [postcss/autoprefixer#1153]
(Might be out of scope)
autoprefixer should remove unneeded nested calc():

```CSS
margin-top: calc(calc(2.25rem + 2px + 20px) / -2);
```

should be:
```CSS
margin-top: calc((2.25rem + 2px + 20px) / -2);
```

IE fails with `calc(calc(...) ...)` but works with `calc((...) ...)`, see https://github.com/sylvainpolletvillard/postcss-grid-kiss/issues/8#issuecomment-293746195

I believe this rule (remove "calc" string if parent is a calc expression) should always be applied: no harm + the syntax is shorter and more natural.

FYI My use case:
[Bootstrap 4 defines a variable](https://github.com/twbs/bootstrap/blob/v4.1.3/scss/_variables.scss#L446):
```SASS
$input-height: calc(#{$input-height-inner} + #{$input-height-border});
```

I want to re-use `$input-height`:
```SASS
margin-top: calc((#{$input-height} + 20px) / -2);
```

To bypass the issue I do:
```SASS
$input-height-without-calc-for-ie: str-replace($input-height, 'calc');
margin-top: calc((#{$input-height-without-calc-for-ie} + #{$spinner-size}) / -2);
```

**Comment by Dan503** [comment]
Definitly out of scope. It has nothing to do with prefixes.

**Comment by tkrotoff** [comment]
I guess postcss-preset-env is better suited for these kinds of "hacks"

**Comment by Dan503** [comment]
I think it is more something that would need to have it's own PostCSS plugin built for it.
