### ISSUE TITLE
VS Code autoprefix extension - unknown browser query

### ISSUE THREAD

**Issue by alljamin** [postcss/autoprefixer#1154]
When specifying in VS Code User Settings 

```
{
"autoprefixer.browsers": [
        "cover 99.5%"
    ]
}
```

Returns

```
[Autoprefixer]

BrowserslistError: Unknown browser query `cover 99.5%`
```

Borwserslist docs say that `cover 99.5% ` is a [valid command](https://github.com/browserslist/browserslist#full-list). 

What should I change to fix this issue?

macOS 10.13.6, VS Code 1.28.2

**Comment by alljamin** [comment]
I have tried `>=0.5%` and for example, it does not prefix `transition: background .5s ease;`. Testing in https://autoprefixer.github.io/ `>=0.5%` does not add prefixes when `cover 99.5%` adds webkit, opera and mozilla prefixes. 
Is this an expected behaviour?

**Comment by ai** [comment]
@alljamin the problem is that VS Code uses very old Autoprefixer. You need to open an issue there and ask them to update Autoprefixer.

It is one of the reasons why we do not recommend to use text editor plugin. They mostly contain old prefixes and browsers databases.
