### ISSUE TITLE
Is there a functionality to convert css json object to string

### ISSUE THREAD

**Issue by Stifutina** [postcss/autoprefixer#1160]
I need to convert css properties json object to valid crossbrowser css code and make json object back;
I'm using autoprefixer on browser side

Example:

`const cssJSON = {`
`    color: '#000000',`
`    fontSize: '34px',`
`    width: 'calc(25% - 20px)',`
`    borderRadius: '10px',`
`    display: 'inline-flex',`
`    flexDirection: 'column',`
`    flexWrap: 'nowrap',`
`};`

`const cssCode = window.autoprefixer.process(cssJSON, postCSSPlugin.options, postCSSPlugin.browsers).css;`

Is there a way to do these manipulations using the Autoprefixer?

**Comment by ai** [comment]
Of course, there is JS syntax for PostCSS: https://github.com/postcss/postcss-js

```js
postcss([autoprefixer]).process(cssJSON, { parser: postcssJs })
```

But I do not recommend to load PostCSS and Autoprefixer to client. Autoprefixer contains huge Can I Use DB (about 600 KB of JS). It will be extremely bad for perfomance. If you want to use Autoprefixer for CSS-in-JS, I recommend to use zero-runtime CSS-in-JS solutions like [astroturf](https://github.com/4Catalyzer/astroturf)
