### ISSUE TITLE
::-webkit-input-placeholder Removed

### ISSUE THREAD

**Issue by hawckins** [postcss/autoprefixer#1161]
::-webkit-input-placeholder removed from our css, I understand because of upgraded caniuse-lite. 

But which version of caniuse-lite, should I use to lock down and get it back? We need to lock down caniuse to avoid conflicts in targeted releases?

Also please let me know how to lockdown caniuse in npm?

**Comment by ai** [comment]
With locked `caniuse-lite` Autoprefixer will not work correctly (Browserslist queries like `last 2 versions` will not use latest browser versions).

There is a much better way. Change your target browsers by Browserslist config to have any browser, which requires `::-webkit-input-placeholder`.
