### ISSUE TITLE
Autoplacement warning appearing even when autoplacement is disabled

### ISSUE THREAD

**Issue by Aljullu** [postcss/autoprefixer#1164]
After updating to 9.4.0 (and 9.4.1), I see several warnings with this message:
```
Autoplacement does not work without grid-template-rows property
```
I have `grid` enabled but autoplacement disabled, my settings look as follows: `{ grid: true }`.

I noticed this warning was implemented in #1151, but after reading the discussion there, I can't see the reasoning of displaying them when autoplacement is disabled.

**Comment by Dan503** [comment]
Yeah those warnings are not meant to be getting output when autoplacement is disabled. 😕

**Comment by ai** [comment]
Fixed a8cc4e3

**Comment by ai** [comment]
Released in 9.4.2

**Comment by Aljullu** [comment]
Thank you, that was fast!

**Comment by ai** [comment]
@Dan503 yeap, please send PR with tests.
