### ISSUE TITLE
Option to Treat Warnings as Errors

### ISSUE THREAD

**Issue by fabb** [postcss/autoprefixer#1165]
It would be nice if warnings could fail the prefixing, so it breaks my automatic gulp build.
I.e. I get the warning `IE does not support align-items on grid containers.` when running it manually, but most of the time the build happens on the CI server, and noone looks through the console output unless the build breaks. So it would be helpful if there was an option to make the build break on these warnings.

**Comment by ai** [comment]
You can do it by adding additional PostCSS plugins:

```js
postcss.plugin("postcss-fail-on-warn", () => {
  return (root, result) => {
    if (result.warnings().length > 0) {
      throw new Error(result.warnings()[0])
    }
  }
})
```

**Comment by fabb** [comment]
Nice, thanks! Maybe would be worth mentioning in the readme?

**Comment by ai** [comment]
@fabb sure, please send PR :)

**Comment by fabb** [comment]
Here you go: https://github.com/postcss/postcss/pull/1209
I guess it's enough to mention it in the PostCSS repo, and not in plugin repos like Autoprefixer, what do you think?
