### ISSUE TITLE
Transition loop problem in Safari when duplicate properties

### ISSUE THREAD

**Issue by ginovski** [postcss/autoprefixer#1169]
Hi there,

I'm using autoprefixer@9.4.2 with React, and there is an issue on Safari. One border-radius transition gets in an infinite loop. I guess it's because of the duplicate properties that autoprefixer generates for future compatibility because when I remove the duplicate property it ends the loop.

Here is the compiled CSS:
<img width="297" alt="screenshot 2018-12-10 at 17 43 37" src="https://user-images.githubusercontent.com/6017552/49743638-e06e6480-fca3-11e8-96ea-cbda2f4c55f7.png">

When I remove the duplicated definition and leave only **transition: border-radius 0.5s** it stops.

Here is a video of the bug:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6017552/49743847-4fe45400-fca4-11e8-89a1-7e39818a99e1.gif)

**Comment by ai** [comment]
1. Make a very small example to reproduce the error.
2. Report it to Safari.

Sorry, I can’t change output, since it will break other browsers.
