### ISSUE TITLE
[wishlist] support building standalone with webpack

### ISSUE THREAD

**Issue by pravi** [postcss/autoprefixer#1174]
I'd like to generate standalone autoprefixer.js (to be used with autoprefixer-rails) with webpack instead of browserify. Would it be possible to add a webpack.config.js as an option?

```
$ webpack lib/autoprefixer.js autoprefixer.js
Hash: 31b56e71aa570d05eaee
Version: webpack 3.5.6
Time: 50ms
          Asset    Size  Chunks             Chunk Names
autoprefixer.js  3.6 kB       0  [emitted]  main
   [0] ./lib/autoprefixer.js 1.13 kB {0} [built] [failed] [1 error]

ERROR in ./lib/autoprefixer.js
Module parse failed: /home/pravi/forge/debian/git/js-team/node-autoprefixer/lib/autoprefixer.js this.curPosition is not a function
You may need an appropriate loader to handle this file type.
TypeError: this.curPosition is not a function
    at new Parser (/usr/lib/nodejs/acorn/src/state.js:60:40)
    at Object.parse (/usr/lib/nodejs/acorn/src/index.js:58:10)
    at Parser.parse (/usr/lib/nodejs/webpack/lib/Parser.js:1328:16)
    at doBuild (/usr/lib/nodejs/webpack/lib/NormalModule.js:295:17)
    at runLoaders (/usr/lib/nodejs/webpack/lib/NormalModule.js:209:11)
    at /usr/lib/nodejs/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/usr/lib/nodejs/loader-runner/lib/LoaderRunner.js:211:10)
    at Array.<anonymous> (/usr/lib/nodejs/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/usr/lib/nodejs/enhanced-resolve/lib/CachedInputFileSystem.js:40:15)
    at /usr/lib/nodejs/enhanced-resolve/lib/CachedInputFileSystem.js:77:9
    at /usr/lib/nodejs/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

```

**Comment by ai** [comment]
Autoprefixer is build-able. We [use](https://github.com/postcss/autoprefixer/blob/master/package.json#L14) [Size Limit](https://github.com/ai/size-limit) to calculate Autoprefixer’s bundle cost and Size Limit pack Autoprefixer with Webpack to calculate bundle size.

How you can deal with it:

1. First, you can take Autoprefixer Rails [bundle](https://github.com/ai/autoprefixer-rails/blob/master/vendor/autoprefixer.js).
2. Second, try to bundle `require('autoprefixer.js')` file. Webpack may miss our `package.json#browser` hacks when you call it directly on `webpack lib/autoprefixer.js`.

**Comment by pravi** [comment]
Option 1 is not possible as we want to build it from source ourselves. I tried with entry.js which has this line `require('./lib/autoprefixer');` but it still fails with same error.

**Comment by ai** [comment]
You need `require("autoprefixer")` to load it from `node_modules`, instead of relative path.

**Comment by ai** [comment]
1. Create a new npm project
2. Add `autoprefixer` to it's `dependencies`
3. Create `index.js` with `module.exports = require("autoprefixer")`
4. Run webpack on this `index.js`

**Comment by pravi** [comment]
Thanks for the help, this was some issue with my local system (I had a broken acorn/webpack), worked on a clean install.
