### ISSUE TITLE
Support for `text-decoration-skip-ink: auto;`

### ISSUE THREAD

**Issue by lukasziegler** [postcss/autoprefixer#1179]
Based on MDN the `text-decoration-skip: ink;` property is now outdated and was moved to `text-decoration-skip-ink: auto;`. Can you include this rewrite in autoprefixer?

I am not well versed in the details of autoprefixer, but what I'd imagine is that it's enough for me to specify `text-decoration-skip-ink: auto;` and autoprefixer will decide whether to show `-webkit-text-decoration-skip: ink;` or not.

Interested in your thoughts!

**Browser support**
- Chrome 57 - 64 use `-webkit-text-decoration-skip: ink;`
- Chrome >= 64: text-decoration-skip-ink: auto; (now available as [default behavior](https://www.chromestatus.com/feature/5631679087509504), thus not explicitly needed)
- Opera >= 50: text-decoration-skip-ink: auto;
- Safari >= 8: -webkit-text-decoration-skip: ink;

**Resources**

MDN specs
https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip
https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink

Chrome default behavior
https://www.chromestatus.com/feature/5631679087509504

**Comment by ai** [comment]
Autoprefixer will support both old and new syntax, but it will show warning for old syntax to force users to migrate

**Comment by ai** [comment]
I will try to fix it today

**Comment by ai** [comment]
Done 3d093f7

**Comment by ai** [comment]
Released 7.4.5

**Comment by lukasziegler** [comment]
Thanks for the quick fix @ai 🙌
