### ISSUE TITLE
Generates warning You did not set any plugins, parser, or stringifier. ...

### ISSUE THREAD

**Issue by umakantp** [postcss/autoprefixer#1180]
I keep getting warning while running the build as follows:-

"You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js."

My configuration is as follows:-

**autoprefix version**:- 9.4.5 (I have warning in older version too)

**postcss.config.js**
```module.exports = {
  plugins: [
    require('autoprefixer')
  ]
}
```

**webpack.config.js** (Shorter version)
```
module.exports = {
  module: {
    rules: [
       {
           test: /\.scss$/,
           use: [
                {
                   loader: MiniCssExtractPlugin.loader
                },{
                   loader: 'css-loader',
                   options: {
                     sourceMap: true
                   }
               }, {
                   loader: 'postcss-loader',
                   options: {
                     sourceMap: true,
                     sourceMapContents: true
                  }
               }, {
                   loader: 'sass-loader',
                   options: {
                     sourceMap: true,
                     sourceMapContents: true,
                     includePaths: [resolve(__dirname, 'src')]
                   }
               }
           ]
       }
    ]
  }
}
```

What could be the issue?

**Comment by ai** [comment]
It's mean that for some reason, PostCSS config was not loaded and Autoprefixer was not applied.

I’m closing this issue, because it is not related with Autoprefixer.

**Comment by ai** [comment]
In your config example there is no `module.exports = {" on this first line. Maybe it is a reason.

**Comment by umakantp** [comment]
"module.exports = {" is present in my file. It was just copy-paste error.

@ai Please give some time for responding before you close issue?!

**Comment by umakantp** [comment]
Ah, well, "module.exports = {" is present in the post. I can see it while editing. Markdown is not displaying it.

**Comment by ai** [comment]
> Please give some time for responding before you close issue?!

Sorry. I use Issues as my ToDo manager. When I think that I should not think about the error, I am closing issue.

I understand that you still need somehow to check your configs and system to find a reason why config was not loaded. Unfortunately, Autoprefixer’s issues is a wrong place to ask “why postcss-loader doesn’t see my PostCSS config”. I can’t help you with environmental problems. You can ask on StackOverflow.
