### ISSUE TITLE
-ms-flex shorthand unitless IE11

### ISSUE THREAD

**Issue by rpellerin** [postcss/autoprefixer#1185]
I have declared `flex: 1 1 0` in my code.

When my `.browserslistrc` contains both IE 10 and IE 11, I get `-ms-flex: 1 1 0px` as expected. However, when I take IE 10 out and only keep IE 11, I don't get `-ms-flex: 1 1 0px`, not even `flex: 1 1 0px`.

How come? Is this a bug?
Thanks

**Comment by ai** [comment]
@rpellerin show you CSS input and output

**Comment by rpellerin** [comment]
This is the output CSS I get with `IE 10` in `.browserslistrc`:

![image](https://user-images.githubusercontent.com/5323445/51606096-3bd17a80-1f11-11e9-8be7-1aa308101791.png)

Input CSS:
![image](https://user-images.githubusercontent.com/5323445/51606115-4a1f9680-1f11-11e9-83c4-99b9651a6785.png)

**Comment by ai** [comment]
I need output without IE 10 :)

**Comment by rpellerin** [comment]
Without IE 10:
![image](https://user-images.githubusercontent.com/5323445/51606776-21989c00-1f13-11e9-827d-a33ede4d7684.png)

**Comment by ai** [comment]
You do not need `-ms-` prefix for IE 11
https://caniuse.com/#feat=flexbox

Your CSS doesn’t work without maybe because of IE 11 issue. Here is another PostCSS plugin to fix this issue automatically:
https://github.com/luisrudge/postcss-flexbugs-fixes

**Comment by rpellerin** [comment]
I do not need `-ms-` but I need the hack for the unitless third argument, i.e I need `flex: 1 1 0` to become `flex: 1 1 0px`

**Comment by ai** [comment]
> I need flex: 1 1 0 to become flex: 1 1 0px

Yeap, `postcss-flexbugs-fixes` does it.

Autoprefixer doesn’t do it since it is not a polyfill or spec compatibility fixer (we need completely different API for these cases).

Autoprefixer is PostCSS plugin as well. You should not afraid to add one additional PostCSS plugin.

**Comment by rpellerin** [comment]
My only concern is that `postcss-flexbugs-fixes` turns `flex: 1 1 0` into `flex: 1 1`, which is not what I want.

**Comment by ai** [comment]
Good idea to suggest it to `postcss-flexbugs-fixes` author.

Sorry, I can’t add any prefix-less fixes to Autoprefixer
https://github.com/postcss/autoprefixer#does-it-add-polyfills

**Comment by rpellerin** [comment]
Ok, thanks a lot for your help.
