### ISSUE TITLE
flexbox: "no-2009" can not work in IE9

### ISSUE THREAD

**Issue by kwzm** [postcss/autoprefixer#1193]
I read this in doc, so I think autoprefixer can support flex in IE9 with flexbox option, but it doesn't, I don't know whether I have a problem with the usage or my understanding of the passage.

> flexbox (boolean|string): should Autoprefixer add prefixes for flexbox properties. With "no-2009" value Autoprefixer will add prefixes only for final and IE versions of specification. Default is true.

This is my config:

![default](https://user-images.githubusercontent.com/16114101/53537182-11905f80-3b44-11e9-87fb-9f63eb1e6a1c.PNG)

**Comment by ai** [comment]
@kwzm you need to create `.browserslistrc` file with:

```
default
ie 9
```

Read more about specific target browsers for Autoprefixer, `postcss-preset-env` and Babel https://github.com/browserslist/browserslist

**Comment by kwzm** [comment]
@ai I have set the browserslist in package.json:
![default](https://user-images.githubusercontent.com/16114101/53537532-4224c900-3b45-11e9-8052-61ee24a827e1.PNG)
And I use npx browserslist to test, the IE9 is in the list.

**Comment by ai** [comment]
I just remembered that IE 9 doesn't support flexbox. Do you want to make it clear in the docs?

**Comment by kwzm** [comment]
@ai Ok, thanks, it will be helpful to add a explain in the docs.

**Comment by Dan503** [comment]
@kwzm it isn't Autoprefixer's job to say what browsers support what features.

That is what caniuse.com is for.

https://caniuse.com/#feat=flexbox

**Comment by ai** [comment]
@Dan503 we should prevent this error in the future, not teaching this exact user. Doc says “IE”. If we will replace it to “IE 10-11” it will help other users in the future.

**Comment by ai** [comment]
Done 5958963
