### ISSUE TITLE
Add support for `steps(n, jump-none)`

### ISSUE THREAD

**Issue by iamvdo** [postcss/autoprefixer#1200]
Reading this article this morning and wondering if this could be added to Autoprefixer

https://danielcwilson.com/blog/2019/02/step-and-jump/

Chrome supports `frames(n)`, a deprecated name for `steps(n, jump-none)`

So, as far as I can tell:

```css
animation-timing-function: steps(5, jump-none)
```
could be
```css
animation-timing-function: frames(5);
animation-timing-function: steps(5, jump-none)
```

**Comment by ai** [comment]
Sorry, Autoprefixer works only for prefixes (because of internal limits). Ask [postcss-preset-env](https://github.com/csstools/postcss-preset-env).
