### ISSUE TITLE
`-webkit-appearance` being ignored

### ISSUE THREAD

**Issue by comatory** [postcss/autoprefixer#1201]
OK this might be some kind of config mismatch in the project I'm working on but I thought I'd ask here anyway.

I'm using `postcss-loader`, and in the config I have `autoprefixer`:

```
module.exports = {
  plugins: [
    require('autoprefixer')
  ]
}
```

And I use `browserslist` in my `package.json`:

```
"browserslist": [
    "Chrome >= 69",
    "Firefox >= 63",
    "Safari >= 11"
  ]
```

I have a CSS code (well actually `less`) that uses mixin for certain CSS class:

```
.appearance (@appearance, @firefox: @appearance) {
  -webkit-appearance: @appearance;
  -moz-appearance: @firefox;
  appearance: @appearance;
}
```

I know that with `autoprefixer` I shouldn't need to specify prefixes manually but it's a legacy codebase. Now for the strange behaviour: If I change chrome in my `browserslist` to `"Chrome >= 60"` then I have `-webkit-appearance` prefixes present.

If I bump to any version higher than that the `-webkit-appearance` and `-moz-appearance` prefix is removed, only the property `appearance` stays. Also If I remove the prefixes from the `.appearance` mixin it does not help, the prefix is never added. Last time I checked, `appearance` is not supported in Chrome so I don't understand why it's not being included.

My webpack config uses `style-loader` (`"^0.13.0"`), `css-loader` (`"^0.28.11"`), `postcss-loader` (`"^2.0.6"`) and `less-loader` (`"^4.1.0"`) to deal with CSS files. I have tried updating all these dependencies to latest versions but it does not fix the issue for me.

**Comment by ai** [comment]
I checked

```css
.example {
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
}
```

in http://autoprefixer.github.io/ru/ and everything works. I think you have a too complicated case here and it causes the error.

1. Do not use Autoprefixer on LESS sources. Compile them to CSS and them apply Autoprefixer.
2. Try to update `autoprefixer`

I am closing this issue since it is environment specific.

**Comment by comatory** [comment]
@ai thank you for your insights.

I managed to find the cause finally. It was very obvious but I haven't tried updating `autoprefixer` and that did the trick. So now it works.
