### ISSUE TITLE
Test fail in OS Windows

### ISSUE THREAD

**Issue by Gibr** [postcss/autoprefixer#1203]
When test run in OS Windows it causes fail:
![](http://dl4.joxi.net/drive/2019/03/14/0021/0002/1396738/38/b80a04cdc4.jpg)
Test indicates problem with '}' and as i understand it occurs by difference with chars 13 + 10 (carriage return + line feed) in `output` and just char 10 in `result.css`.
This problem shows only for next tests:
- `prefixes @viewport`
- `has actual example in docs`
- `prevents doubling prefixes`
- `hacks › supports all fullscreens`

**Comment by ai** [comment]
Feel free to send PR
