### ISSUE TITLE
Gulpfile not working 

### ISSUE THREAD

**Issue by Mikeskay** [postcss/autoprefixer#1206]
Hi Guys, previous issue: #1205 @ai   @Dan503 

I've been stuck on a problem for a couple of days as i've been following a git web developer video course and I'm having trouble with the gulp watch bit of the video. As the video is few years old, it seems the code in the video is out of date so I had to modify the code a little. I have gotten to this part but when I write my code in the gulpfile I get the error below in my command line.

I tried both your solutions and it doesn't seem to work.

 **@Dan503 solution :**

gulp.task('styles', function () {
  var gulp = require('gulp');
  var watch = require('gulp-watch');
  var postcss = require('gulp-postcss');
  var autoprefixer = require('autoprefixer');
  var cssvars = require('postcss-simple-vars');
  var nested = require('postcss-nested');
  var cssImport = require('postcss-import');
 
   return gulp.src('./app/assets/styles/styles.css')
   .pipe(cssImport())
   .pipe(postcss())
   .pipe(cssvars())
   .pipe(nested())
   .pipe(autoprefixer())
   .pipe(gulp.dest('./app/temp/styles'));
   
  });

 gulp.task('watch', function() {

  gulp.watch('./app/assets/styles/**/*.css', gulp.series('styles'));

});

**and @ai solution of using gulp-postcss in gulp.task('styles'.:**
var gulp = require('gulp'),
watch = require('gulp-watch'),
postcss = require('gulp-postcss'),
autoprefixer = require('autoprefixer'),
cssvars = require('postcss-simple-vars'),
nested = require('postcss-nested'),
cssImport = require('postcss-import');

gulp.task('styles', function(){
gulp.src('./app/assets/styles/styles.css')
.pipe(cssImport())
.pipe(postcss())
.pipe(cssvars())
.pipe(nested())
.pipe(autoprefixer())
.pipe(gulp.dest('./app/temp/styles'));
});

gulp.task('watch', function() {

gulp.watch('./app/assets/styles/**/*.css', gulp.series('styles'));

});

Can someone please help me out, I just would like to automate some inputs when I save my css file.

Thank you guys

**Comment by Dan503** [comment]
You need to pay closer attention to documentation code samples.

The post css plugins need to go inside gulp-postcss. They are not gulp plugins.

This is what you are doing:

```js
.pipe(cssImport())
.pipe(postcss())
.pipe(cssvars())
.pipe(nested())
.pipe(autoprefixer())
```
This is what you are supposed to do:

```
.pipe(postcss([
  autoprefixer(),
  cssImport(),
  cssvars(),
  nested(),
  autoprefixer()
]))
```

By the way, when posting code in GitHub, use 6 back ticks like so to create code blocks. (I've added a space to the start to stop GitHub from thinking it is opening/closing the code block)

```
 ```js
 // code goes here
 ```
```

**Comment by Mikeskay** [comment]
Thank so much for both your helps, it works now. Much appreciated  

@Dan503 @ai
