### ISSUE TITLE
Error installing autoprefixer in SublimeText 3 for me

### ISSUE THREAD

**Issue by HakaCode** [postcss/autoprefixer#1212]
![image](https://user-images.githubusercontent.com/33907565/57183266-ab47f600-6e80-11e9-9731-3b54f00854a3.png)

**Comment by ai** [comment]
We do not recommend to use `Autoprefixer for Sublime Text` or any other text editor plugins.

https://github.com/postcss/autoprefixer#text-editors-and-ide

Use Parcel. It is better to update prefixes during the build.

If you still want to Autoprefixer for Sublime Text, report the issue
https://github.com/sindresorhus/sublime-autoprefixer
