### ISSUE TITLE
background-color transparent changes to initial

### ISSUE THREAD

**Issue by taskinkemal** [postcss/autoprefixer#1213]
The background-color:transparent style changes to initial. This is not supported in some instances of IE11.
Please consider not doing this replacement. In my current project it causes multiple issues - basically wherever I use this style.

**Comment by ai** [comment]
Can you show input, ouput and expected ouput CSS?

**Comment by taskinkemal** [comment]
Yes, sure.

The input:
`.myClass {
  background-color: transparent;
}`

Actual output:
`.myClass {background-color:initial}`

Expected output:
`.myClass {background-color:transparent}`

Workaround:
This doesn't work: /* autoprefixer: ignore next */
Changing from transparent to #00000000 worked. (and the autofixer converts to "transparent" by the way).

**Comment by ai** [comment]
Very strange. Autoprefixer should now change this property.

Can you disable all other tool?

**Comment by taskinkemal** [comment]
I'm sorry, I couldn't understand which tools you are talking about.
And just a clarification: Autoprefixer does do the change, and that is the problem. It shouldn't change it in my opinion.
Thanks.

**Comment by ai** [comment]
I tested `.myClass { background-color: transparent; }` on http://autoprefixer.github.io/ru/ and didn’t get `.myClass {background-color:initial}`

Autoprefixer’s code doesn’t do anything with `background-color`.

This is why I think some another tool replace `transparent` to `initial`.

**Comment by taskinkemal** [comment]
Ok, thank you.

**Comment by romanlex** [comment]
@taskinkemal have you solved this problem?

**Comment by romanlex** [comment]
found bug in cssnano https://github.com/cssnano/cssnano/issues/721
