### ISSUE TITLE
Autoprefixer placeholder doesn't work on IE

### ISSUE THREAD

**Issue by RuelleAnthony** [postcss/autoprefixer#1214]
Hi, 

Since autoprefixer version 7.1.5, the ::placeholder pseudo element to no longer work on IE (11).

Before this version, i have never had a problem...

`input {
    &::placeholder {
      color: grey;
    }
}`

Thx

**Comment by ai** [comment]
What is your Autoprefixer output? Maybe you removed IE from Browserslist?

**Comment by DorotkaMakotka** [comment]
I have the same issue. Output contains 
`::-webkit-input-placeholder` and `::-ms-input-placeholder`,
but no `:ms-input-placeholder`.

ie 11 is on my browserslist

Thx

**Comment by ai** [comment]
`:ms-input-placeholder` works in Autoprefixer’s [tests](https://github.com/postcss/autoprefixer/blob/master/test/cases/placeholder.out.css) and [online demo](https://autoprefixer.github.io/).

Seems like you have some environment problem. Try to disable CSS tools one by one until you will frind who cut the prefix after Autoprefixer.
