### ISSUE TITLE
Pixel ratio media queries aren't being autoprefixed

### ISSUE THREAD

**Issue by borodean** [postcss/autoprefixer#122]
There are no option to write such things with no prefixes to be completed with Autoprefixer: 

```css
@media
  only screen and (-webkit-min-device-pixel-ratio: 1.3),
  only screen and (-o-min-device-pixel-ratio: 13/10),
  only screen and (min-resolution: 120dpi) {}
```
Source of the snippet: https://gist.github.com/marcedwards/3446599
More prefixes hell: http://css-tricks.com/snippets/css/retina-display-media-query/

**Comment by andreicojea** [comment]
:+1:  I need this too

**Comment by pepelsbey** [comment]
@ai you’re rescheduling this for the 4th time already :(

**Comment by ai** [comment]
@pepelsbey because PostCSS and Browserslist also need my support :).

**Comment by pepelsbey** [comment]
@ai, since Autoprefixer is the most useful & popular application for PostCSS and Browserslist there should be a balance ;)

**Comment by andreicojea** [comment]
Maybe an option to skip certain properties? I'm using `@media screen and (-webkit-min-device-pixel-ratio: 0)` to write webkit only styles, but this breaks autoprefixer... :-(

**Comment by ai** [comment]
@pepelsbey don’t forgeet that Autoprefixer is open source ;). `media.coffee` will be like [supports.coffee](https://github.com/postcss/autoprefixer-core/blob/master/lib/supports.coffee) and CoffeeScript is very familiar to JS codes ([coffeescript.org](http://coffeescript.org/)’s examples should be enough to write Coffee code in same day).

**Comment by pepelsbey** [comment]
@ai, I’m allergic to coffee :P

**Comment by ai** [comment]
@Grawl can you fix your Can I Use feature JSON and add `-o-` for old Opera?

**Comment by ai** [comment]
Autoprefixer Core master now can add prefixes for `min-resolution` and `max-resolution`.

Next I add code to remove old resolution prefixes and task will be finished.

**Comment by ai** [comment]
Important notice. Autoprefixer will not convert `dppx` to `dpi` for IE. It will only add `-webkit-min-device-pixel-ratio` and convert `dpi` or `dppx` to old value.

Don’t forget, that Autoprefixer is about  prefixes, not polyfills.

If you want to conver `dppx` to `dpi` you should ask @yisibl to add this feature to his awesome polyfills packe [CSS Grace](https://github.com/cssdream/cssgrace).

**Comment by ai** [comment]
Now Autoprefixer can clean resolution queries from old prefixes too https://github.com/postcss/autoprefixer-core/commit/1bfefcc4869ecff30fad4d46763013aeb88768f4

**Comment by ai** [comment]
@Grawl I fix Can I Use data https://github.com/Fyrd/caniuse/pull/863

**Comment by Grawl** [comment]
@ai good

**Comment by yisibl** [comment]
[Fix]Support decimal value https://github.com/postcss/autoprefixer-core/commit/5b5d211721931ce2eb4851a3077d84d8ea03281b

input:
```css
@media (min-resolution: 2.5dppx) { }

@media (min-resolution: 144dpi) { }
```

output:
```css
@media (-webkit-min-device-pixel-ratio: 2.5), (min-resolution: 2.5dppx) { }

@media (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi) { }
```

@ai 
Do you intend to let it support word wrap?

Like this:

```css
@media
screen and (-webkit-min-device-pixel-ratio: 1.5), 
screen and (min-resolution: 144dpi) {
    display: block;
}
```

`dppx` , `dpi`, `dpcm` are both standard value, why not support their mutual conversion?

**Comment by ai** [comment]
@yisibl yeap, `screen and` is no a problem for Autoprefixer :).

**Comment by ai** [comment]
@yisibl unfortunately, Autoprefixer can’t insert fallbacks without prefixes. We need other tool for IE fallbacks. This is a same logic as with `opacity` for IE. I really think that CSS Grace can do it better.

**Comment by yisibl** [comment]
@ai Well, CSS Grace deals with the problem of fallback.
However, has already supported the -webkit-min-device-pixel-ratio property, why not support other prefix?

**Comment by yisibl** [comment]
@ai 

Do you intend to let it support word wrap?

output: 

```css
@media
(-webkit-min-device-pixel-ratio: 1.5), 
(min-resolution: 144dpi) {
    display: block;
}

**Comment by ai** [comment]
@yisibl support is in Autoprefixer, but I wait for Can I Use update.

**Comment by yisibl** [comment]
Okey, Thanks!

**Comment by ai** [comment]
@yisibl now Autoprefixer 5.1 has support for `-moz-` and `-o-` resolutions https://github.com/postcss/autoprefixer-core/commit/30db19e85cf8076cf078edde7a17f651f4e11072

**Comment by yisibl** [comment]
@ai 
https://github.com/postcss/autoprefixer-core/commit/30db19e85cf8076cf078edde7a17f651f4e11072#diff-780050d78c22949ea582bf8b8c58713cR1

I created a simple module, converting Number to Fraction, you can use it :ghost: .

https://github.com/yisibl/num2fraction

```js
var n2f = require('num2fraction')

console.log(n2f(0))            // => 0
console.log(n2f(1.3))          // => 13/10
console.log(n2f(1.4))          // => 7/5
```

**Comment by ai** [comment]
@yisibl thanks :) https://github.com/postcss/autoprefixer-core/commit/7e8c099501dff068f0245e82332706f8a7b00319

**Comment by yisibl** [comment]
Too great. :ghost:

**Comment by akashivskyy** [comment]
:tada:

**Comment by yisibl** [comment]
@ai 

input:
```css
@media (min-resolution: 96dpi) {}
```

output:

```css
@media (-webkit-min-device-pixel-ratio: 1), (-o-min-device-pixel-ratio: 1/1), (min-resolution: 96dpi) {}
```

Missing `-moz`

In addition, we need to consider a nested case.

```css
@viewport{
  @media (min-resolution: 96dpi) {}
}
```

output:

```css
@-ms-viewport{
  @media (min-resolution: 96dpi) {}
}
@-o-viewport{
  @media (min-resolution: 96dpi) {}
}
@viewport{
  @media (-webkit-min-device-pixel-ratio: 1), (-o-min-device-pixel-ratio: 1/1), (min-resolution: 96dpi) {}
}
```

**Comment by ai** [comment]
@yisibl because Firefox supports `min-resolution: 96dpi`, so I add `min--moz-device-pixel-ratio` only if you use `dppx`.

**Comment by yisibl** [comment]
Ok!

**Comment by ai** [comment]
Released today in 5.1

**Comment by andreicojea** [comment]
:+1: great, thanks!

**Comment by rguanghui** [comment]
:tada:
