### ISSUE TITLE
Do Not Remove Browsers Option

### ISSUE THREAD

**Issue by bdkjones** [postcss/autoprefixer#1226]
I read the release notes for version 9.6 and saw that you have deprecated the `browsers` option and, in the next release, are going to force people to provide browsers either in `package.json` or `.browsersrc` files.

This is a big deal for me because I integrate AutoPrefixer into my app (CodeKit) and MANY of my customers are very simple: they have one or two CSS files that they want to process. They do not use Babel, they don't have any npm packages installed, etc.

These customers would be very irritated if I started polluting their projects with needless `package.json` or `.browsersrc` files. So much so that I would be forced to fork AutoPrefixer to maintain a way to pass necessary configuration to the tool without resorting to a file on disk.

### Why?

The release notes say their are certain issues with the `browsers` option, but they do not describe them. Why has this decision been made? Why MUST the browsers configuration be read off a file on disk instead of passed programmatically to AutoPrefixer?

Removing that feature virtually eliminates my ability to cleanly integrate AutoPrefixer into my app so that my users can adjust their selected browsers in a nice UI instead of manually editing some JS config file on disk.

### Please Reconsider

I depend on this feature a lot and would prefer not to maintain a separate fork of AutoPrefixer. Please keep the feature for those edge cases where it is required.

**Comment by bdkjones** [comment]
Note: I do see this line in `changelog`:

    Add warning-less overrideBrowserslist option.

But the release notes and documentation don't make it clear if this is a new API that can be relied upon as an alternative to the `browsers` option, or if this is just temporary and will be going away when that option does. I'm confused about what `overrideBrowserslist` actually does.

**Comment by ai** [comment]
We deprecated `browsers` option since it force developers to use wrong practice with target browsers.

I agree, that forcing users to create Browserslist config is not good. What do you think about this behavior:

1. By default you use default target browsers in Autoprefixer (so you will not need to pass `browsers` option).
2. If users will need to set browsers (it should be rare) they can do it in CodeKit GUI, but then CodeKit will creates `.browserslist` file near input CSS file.

This solution will work better than current one in big teams:

1. New developers will know where to find target browsers without asking question in group chat.
2. Target browsers will be saved in project Git (or just in directory).
3. Developers will share the same target browsers

If you need some backward compatible you can add “save to Browserslist” checkbox near target browsers field in GUI. Developer will be able to uncheck this checkbox and you will use `overrideBrowserslist` option.

**Comment by bdkjones** [comment]
This is not ideal because CodeKit provides a different set of default browsers and from my users’ perspective, they will still see that extra .browsersrc file as junk.

I do understand that you want AutoPrefixer to integrate well into big projects that use lots of tools together. Could you keep the browsers option in place and simply remove all the documentation about it? This would ensure that folks using AutoPrefixer directly configure it with files but still allow integrators like CodeKit to programmatically configure AutoPrefixer.

The whole point of CodeKit is that it removes the need to write config files.

**Comment by bdkjones** [comment]
Also: CodeKit does store browsers in a config file, it’s just not a “package.json” or “.browsersrc” file. It’s a custom config file for CodeKit named “codekit.config”. This means the setting gets committed to git, etc. The user just gets to edit settings in a GUI instead of directly in a file. If keeping the browsers option is not possible, could AutoPrefixer look for a “codekit.config” file if the other two files don’t exist? If that’s an option, I can verify the exact format of the config file and where the Browsers array is stored in it.

**Comment by bdkjones** [comment]
The “codekit.config” file is just normal JSON, so it would be easy to parse. I know you probably don’t want to add extra stuff to support one tool, so keeping the “browsers” option for its flexibility would still be the easiest route—especially because it’s already done and implemented.

**Comment by ai** [comment]
You can always use `overrideBrowserslist`. It works the same as old option.

What is default target browsers in CodeKit? Maybe we should change default Browserslist if it's defaults doesn't work for you.

**Comment by bdkjones** [comment]
Is “overrideBrowsersList” going to be supported in the future? Does it work exactly like the old “browsers” option? I couldn’t find any documentation about it. If you’re going to keep that option, I can definitely move to using it instead.

**Comment by ai** [comment]
> Is “overrideBrowsersList” going to be supported in the future? 

Of course

> Does it work exactly like the old “browsers” option? 

Yeap

> I couldn’t find any documentation about it.

We do it for a purpose to force Browserslist config

**Comment by bdkjones** [comment]
Oh, perfect! I'm all set then. Thanks!
