### ISSUE TITLE
Expose and/or document an API for using the "should I prefix" logic in other applications

### ISSUE THREAD

**Issue by MrJohz** [postcss/autoprefixer#1228]
Hi,

I've got a use-case where I'm using a CSS-in-JS tool to handle my CSS, and I want to write a ESLint that can check all uses of this tool to figure out if I've left out some prefixes, or added prefixes that I shouldn't have done.

I would like to be able to use autoprefixer to help me do this, so as to avoid code duplication, make fewer mistakes, etc etc.  Looking through [this](https://github.com/stylelint/stylelint/tree/master/lib/rules/property-no-vendor-prefix) stylelint rule, I tried to use some of the internal autoprefixer APIs to create something workable, but my use-case is fairly different to that rule, and, while I'm mostly able to create something that seems to work, I'm not so confident that I've used these internal APIs correctly.  And obviously if you guys want to change that internal stuff, I'll need to hang back on an older version, or spend time updating.

I would be surprised if I'm the only person who's wanted to do something like this.  (Well, no, I'm definitely not - the stylelint team also needed something like this!)  As such, I wonder if it might be possible to expose some sort of API for handling prefixed properties.

I can imagine an API that looks something like this (in a pseudo-TypeScript thing that I've made up just now...):

```typescript
function check(propertyName: string):
    // for a prefixed property, provide the un-prefixed version, and whether or not it's needed for the supported browser list
    | { kind: 'PREFIXED', unprefixedProperty: string, action: 'REMOVE' | 'KEEP' }
    // for an un-prefixed property, provide all of the prefixes that would be added by autoprefixer (could be empty)
    | { kind: 'UNPREFIXED', additionalPrefixes: string[] }
    // for a property that isn't recognised for whatever reason
    | { kind: 'UNRECOGNISED' }
```

I recognise this just deals with properties, and, as I understand it, autoprefixer also handles some values, @-rules, etc, so I imagine there would need to be a `check` function like this for each of those types of element.  Or they could be combined into a single API, but I'm not so sure what the best way of doing that is.

I recognise this would add a maintenance burden to you guys, but I believe all this information is currently available, so it should hopefully just be a case of retrieving it.  It would also help maintainers of other adjacent tools to rely on the significant knowledge of autoprefixer, and reduce duplication in the ecosystem.

**Comment by ai** [comment]
> { kind: 'PREFIXED', unprefixedProperty: string, action: 'REMOVE' | 'KEEP' }

Sorry, it will require a full rewrite. Also, the current architecture just can add a list of commands, since the next step needs to look at AST changes from previous.

I think there is a better way. You can use the flexibility of PostCSS to archive the same result:

1. [postcss-js](https://github.com/postcss/postcss-js) can be used to convert JS data structure to PostCSS AST
2. Then you call Autoprefixer on this AST
3. Then you will have an origin and changed ASTs. You can compare them and find what changes do you need to show to the user.

What do you think about this way?

**Comment by MrJohz** [comment]
I can give that a go and see how well it works.

**Comment by ai** [comment]
Open new issue if you will have questions
