### ISSUE TITLE
browserList ignore?

### ISSUE THREAD

**Issue by maniac0s** [postcss/autoprefixer#1229]
I am not using browserlist nor do I intend to. How can I stop getting that warning?

    Replace Autoprefixer browsers option to Browserslist config.
    Use browserslist key in package.json or .browserslistrc file.

    Using browsers option cause some error. Browserslist config 
    can be used for Babel, Autoprefixer, postcss-normalize and other tools.

    If you really need to use option, rename it to overrideBrowserslist.

    Learn more at:
    https://github.com/browserslist/browserslist#readme
    https://twitter.com/browserslist

**Comment by ai** [comment]
What exactly warning do you have?

**Comment by maniac0s** [comment]
Edited the post

**Comment by ai** [comment]
Check out `npm ls` output for tools using `autoprefixer`. Then create an issue in that tools to avoid `browsers` option and use Browserslist.
