### ISSUE TITLE
Why is my configuration invalid in webstrom

### ISSUE THREAD

**Issue by awnawnawn** [postcss/autoprefixer#1230]
How do I configure it
![@QEMJK{8KNRA0()8LX5_9_U](https://user-images.githubusercontent.com/47672657/60949099-0dacef00-a327-11e9-8bec-e8db139e9096.png)
![%}WWEP0WJ_7P@MJ} EKX%$T](https://user-images.githubusercontent.com/47672657/60949102-0f76b280-a327-11e9-8ae3-ccde1612f7d0.png)

**Comment by ai** [comment]
Sorry, I do not use JetBrains products and not able to help you.

You should ask JetBrains. It is commercial products and they own you support.

I recommend to use Parcel builder instead of IDE plugins because this plugins reduce readability.
