### ISSUE TITLE
::moz-selection selector was created with last 2 versions

### ISSUE THREAD

**Issue by marutpun** [postcss/autoprefixer#1233]
TL;DR. Autoprefixer add `-moz-` prefix with last 2 versions browserslist.

I search [Can I Use](https://caniuse.com/#search=%3A%3Aselection) for `::selection` and understand that it is no longer required `-moz-` after Firefox v62

The point is with [last 2 versions in browserslist](https://browserl.ist/?q=last+2+versions) which show Firefox v67, v68. So I wonder why `-moz-` was added to my CSS.

_autoprefixer v9.6.1 + gulp-postcss_

**Comment by ai** [comment]
I check it locally and could not reproduce the bug. It could be an environmental issue.

1. Check `npm ls | grep caniuse-lite` output. Run `npm update` if you will see old Can I Use data.
2. Run `npx autoprefixer --info` to check what browsers are used in FF. If Browserslist config doesn’t work correctly, write where did you put it.

**Comment by marutpun** [comment]
Thanks. After run `npm ls | grep caniuse-lite` and `autoprefixer --info` I found
```
$ npm ls | grep caniuse-lite
| | +-- caniuse-lite@1.0.30000988 deduped
| +-- caniuse-lite@1.0.30000988
```
```
Browsers:
...
Firefox: 68, 67
...
Selectors:
...
 ::selection: moz
...

```

Is this the cause of my problem ?

**Comment by ai** [comment]
How do you specify target browsers? `.browserslistrc` Can you show me it’s code?

**Comment by marutpun** [comment]
Here is my `.browserslistrc`
```
last 2 versions
ie >= 9
ios >= 7
android >= 4.4
```

**Comment by ai** [comment]
Now it is very strange.

Can you replace this block https://github.com/postcss/autoprefixer/blob/master/data/prefixes.js#L348-L354 to

```js
f(require('caniuse-lite/data/features/css-selection'), browsers => {
  console.log(browsers)
  return prefix(['::selection'], {
    selector: true,
    feature: 'css-selection',
    browsers
  })
})
```

**Comment by marutpun** [comment]
Here is the console.log. I try copying prefixes.js from repository to my node_modules folder. But still the same
```
$ gulp build
[ 'firefox 2',
  'firefox 3',
  'firefox 3.5',
  'firefox 3.6',
  'firefox 4',
  'firefox 5',
  'firefox 6',
  'firefox 7',
  'firefox 8',
  'firefox 9',
  'firefox 10',
  'firefox 11',
  'firefox 12',
  'firefox 13',
  'firefox 14',
  'firefox 15',
  'firefox 16',
  'firefox 17',
  'firefox 18',
  'firefox 19',
  'firefox 20',
  'firefox 21',
  'firefox 22',
  'firefox 23',
  'firefox 24',
  'firefox 25',
  'firefox 26',
  'firefox 27',
  'firefox 28',
  'firefox 29',
  'firefox 30',
  'firefox 31',
  'firefox 32',
  'firefox 33',
  'firefox 34',
  'firefox 35',
  'firefox 36',
  'firefox 37',
  'firefox 38',
  'firefox 39',
  'firefox 40',
  'firefox 41',
  'firefox 42',
  'firefox 43',
  'firefox 44',
  'firefox 45',
  'firefox 46',
  'firefox 47',
  'firefox 48',
  'firefox 49',
  'firefox 50',
  'firefox 51',
  'firefox 52',
  'firefox 53',
  'firefox 54',
  'firefox 55',
  'firefox 56',
  'firefox 57',
  'firefox 58',
  'firefox 59',
  'firefox 60',
  'firefox 61',
  'kaios 2.5' ]
[06:26:50] Using gulpfile ~\Desktop\usfrmw\gulpfile.js
[06:26:50] Starting 'build'...
[06:26:50] Starting 'build'...
[06:26:50] Finished 'build' after 277 ms
[06:26:50] Finished 'build' after 280 ms
Done in 3.10s.
```

**Comment by ai** [comment]
Now we found the reason. `kaios 2.5` adds `-moz-` prefix.
