### ISSUE TITLE
Converting to boolean

### ISSUE THREAD

**Issue by RinatValiullov** [postcss/autoprefixer#1235]
It's not an issue maybe, but I didn't find where to write.

I noticed that you use double logical operator - `!!` instead of `Boolean()` constructor in `return` statement. Wouldn't it be more explicit to use a constructor instead of a logical operator - `NOT`?

P.S. Or just use regexp `test()` method returning boolean value (that you need in `check` method):

```
check (rule) {
    if (rule.selector.indexOf(this.name) !== -1) {
        return this.regexp(rule.selector)
    }

    return false
}
```

https://github.com/postcss/autoprefixer/blob/04bd4860f73827a952f8dadfcfd0b0ca8b796ed3/lib/selector.js#L17

**Comment by ai** [comment]
> Wouldn't it be more explicit to use a constructor instead of a logical operator

Yeap, it will be more explicit. However, I think that it is not a big deal and we can keep the old code. Anyway only I work with Autoprefixer code.
