### ISSUE TITLE
Autoprefixer ignores browserlist

### ISSUE THREAD

**Issue by VadymBoguslavsky** [postcss/autoprefixer#1236]
Hi there. We started using Next.js and after update to it our autoprefixer stopped working.
We created postcss.config.js and in it declared 
`const autoprefixer = require('autoprefixer');

module.exports = {
  plugins: [autoprefixer({})]
};
`
Also we have .browserslistrc

When we pass our browsers to autoprefixer like 
`module.exports = {
  plugins: [autoprefixer({
    "overrideBrowserslist": [
      "last 3 version",
      "> 0.5%"
    ]
})]
};`

its working. 
Is it a problem with autoprefixer or with a  browserslist?

**Comment by ai** [comment]
1. Show me your `broswerslistrc` and the path to the file.
2. How do you test that Autoprefixer is not working?

**Comment by VadymBoguslavsky** [comment]
1. this is ` .broswerslistrc` .  But its just a file, we do not indicate the path somewhere
```
last 3 version
> 0.5%
not dead
```

2. We dont have vendor prefixes

**Comment by ai** [comment]
What input CSS do you use to test prefixes? What CSS do you expect to have on output?

**Comment by VadymBoguslavsky** [comment]
this is our css, 
`    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 13px 10px;
    box-sizing: border-box;
    background-color: #fff;
    margin: 0 -10px 10px;
    text-transform: initial;`

When we uses browsers in autoprefixer as `overrideBrowserslist` or just `browsers`, css will become like this

```
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    -webkit-box-pack: justify;
    -ms-flex-pack: justify;
    justify-content: space-between;
    padding: 13px 10px;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    background-color: #fff;
```

**Comment by ai** [comment]
You do not need these prefixes because `non dead` query remove all old browsers without security updates, which requires these prefixes.

Call `npx autoprefixer --info` with `not dead` and without it in config.
