### ISSUE TITLE
IE11 GridCSS issue - display: none

### ISSUE THREAD

**Issue by evandiamond** [postcss/autoprefixer#1237]
I ran into this issue earlier today and a colleague of mine ran into it a couple weeks ago as well.

While using `display: grid;` if there is an element in your grid that has a `display: none;` property, modern browsers will appropriately disregard this element when Autoprefixer builds the grid elements out. In IE11, Autoprefixer counts a `display: none;` element as part of the grid items and everything gets shifted out of place.

*Example 1:*
```
<div class="grid">
    <style type="text/css">.css{}</style>
    <div class="grid-item"></div>
    <div class="grid-item"></div>
    <div class="grid-item"></div>
</div>
```

*Example 2:*
```
<div class="grid">
    <div class="grid-item" style="display: none;"></div>
    <div class="grid-item"></div>
    <div class="grid-item"></div>
    <div class="grid-item"></div>
</div>
```

Chrome recognizes the `<style>`  tag with a `display: none;` and doesn't assign it any grid properties. IE11 fails.

_Sidenote:_ In Example 1, I realize how silly it is to have a `<style>` tag within a `<div>`, but this is being brought in automatically from a third-party plugin.

**Comment by Dan503** [comment]
There isn't anything we can do about this.

Autoprefixer has no access to DOM information and so it has no way of knowing if an element in the grid is set to `display: none`.

You will need to work around the issue yourself.

It sounds like you are taking advantage of Autoprefixer's autoplacement functionality. The autoplacement functionality is extremely limited and can only handle the most basic of grids.

I would recommend using grid areas to work around the issue instead. I'm going to use scss in this example for brevity.

```scss
.grid {
  display: grid;
  grid-template:
    "a    b   c" /
     1fr 1fr 1fr;
}
.grid-item {
  &:nth-child(2) { grid-area: "a"; }
  &:nth-child(3) { grid-area: "b"; }
  &:nth-child(4) { grid-area: "c"; }
}
```

**Comment by evandiamond** [comment]
@Dan503 Appreciate the quick reply. I was afraid of that :(
I chose not to go ahead with grid areas, since there are multiple forms and the client has the ability to add fields at will, which would indeed get wonky at some point or another.

**Comment by Dan503** [comment]
Yeah sorry.

I would recommend using a flexbox based solution then if that's an option.

I explain my preferred method in this article:
https://css-tricks.com/css-grid-in-ie-faking-an-auto-placement-grid-with-gaps/

**Comment by evandiamond** [comment]
@Dan503 No worries. The problem with faking it like you link mentions is we have no control over the form elements. Your examples show a lot of uniform boxes, but the design we have calls for inputs of varying lengths, which would work, assuming there were differentiating classes, but I'm not sure this is possible with this third-party form. Something I need to investigate.

Thanks again for your help.

**Comment by Dan503** [comment]
If it is a case of certain columns being wider than others, you can probably do some fancy nth-child math to get the desired result.

For example, if you have 3 columns and the 2nd column needs to be twice the width of the other 2 columns, you could do this:

```scss
.grid-item {
  width: 25%;

  &nth-child(3n+2) {
    width: 50%;
  }
}
```

**Comment by evandiamond** [comment]
Right, the problem is the rows/input are randomly 50% and 100%
Can't win em all :)

I'll see if I can tack on some classes to the rows if we can get access to the admin.
Cheers!

**Comment by ai** [comment]
I am closing this issue, because as I understood we can’t do anything about this issue (correct me if I am wrong, I will reopen issue)
