### ISSUE TITLE
Autoprefixer and postcss-cli not working 

### ISSUE THREAD

**Issue by harshit2608** [postcss/autoprefixer#1239]
Having problem getting my css code some prefixes , always gives me the same error 
below are the images of error and scripts
![Screenshot (85)](https://user-images.githubusercontent.com/42277796/63551166-0433bb00-c552-11e9-950d-b77c318d1b4c.png)
![Screenshot (84)](https://user-images.githubusercontent.com/42277796/63551172-08f86f00-c552-11e9-88b8-0362626b02c0.png)

**Comment by ai** [comment]
1. Remove `-b` argument and use Browserslist config
2. If you will have error, report to `postcss-cli`
