### ISSUE TITLE
Autoprefixer computes grid and row numbers incorrectly for ie (specific example given)

### ISSUE THREAD

**Issue by sallysupercool** [postcss/autoprefixer#1241]
Possibly the same as #1181 

Given a grid of named areas
And a grid gap 
When Autoprefixer creates output
Then it first assigns col and row numbers
Then it computes grid with extra rows and  columns, so the items are added to the grid gaps
 
### INPUT 
```
  .header { 
    display: grid;
    grid-gap: 20px 0;
    grid-template-areas: 
    "backlink ."
    "title ."
    "date .";
} 
```

(and then assign each element: .backlink {grid-area: backlink } etc, you get it!)

### OUTPUT Autoprefixer outputs
```
   .header {
    display: -ms-grid;
    display: grid;
    gap: 15px 20px;
    -ms-grid-columns: 8fr 20px 4fr;
    grid-template-columns: 8fr 4fr;
    -ms-grid-rows: auto 15px auto 15px auto;
    grid-template-areas: "backlink .""title     .""date  .";
  }
    .header__title {
        -ms-grid-row: 2; // should be 3 => applied to 15px gap
        -ms-grid-column: 1;
        -ms-grid-column-span: 1
    }

    .header__backlink {
        -ms-grid-row: 1;
        -ms-grid-column: 1
    }

    .header__date {
        -ms-grid-row: 3; //should be 5 => applied to title row
        -ms-grid-column: 1;
        -ms-grid-column-span: 2
    }
```

#### Browserlist:
and_chr 73
android 67
chrome 75
chrome 74
chrome 73
edge 17
firefox 67
firefox 66
ie 11
ios_saf 12.2
ios_saf 12.0-12.1
ios_saf 11.3-11.4
safari 12.1
safari 12

**Comment by Dan503** [comment]
Can you clean up your code samples?

Use the back tick ( ` ) 3 times and then [enter] to go to a new line to create a code block.

Close the code block by using another 3 back ticks

**Comment by sallysupercool** [comment]
Sure, there you go.

**Comment by Dan503** [comment]
Thanks.

When I use this input:

```
.header { 
    display: grid;
    grid-gap: 20px 0;
    grid-template-areas: 
    "backlink ."
    "title    ."
    "date     .";
} 


.header__title {
    grid-area: title;
}

.header__backlink {
    grid-area: backlink;
}

.header__date {
    grid-area: date;
}
```

On here https://autoprefixer.github.io/ it outputs correctly.

Are you using the latest version? Or is this a regression :/

**Comment by sallysupercool** [comment]
I'm looking on the site I was fixing (sorry, we have a bazillion)...

It's running autoprefixer 9.4.7... Holy gosh you move fast! *blush* I was so pleased to figure out why this generation of sites was broken I rushed to tell you guys. But you are way ahead. I'll update it and most likely that will all be fixed. Thanks!
