### ISSUE TITLE
Please add support mask-position-x

### ISSUE THREAD

**Issue by NikolayMakhonin** [postcss/autoprefixer#1245]
It seems that `mask-position` supported but `mask-position-x` aren't

I think it will be better to add all the properties that Chrome DevTools shows:
```
-webkit-mask-box-image-outset
-webkit-mask-box-image-repeat
-webkit-mask-box-image-slice
-webkit-mask-box-image-source
-webkit-mask-box-image-width
-webkit-mask-clip
-webkit-mask-composite
-webkit-mask-image
-webkit-mask-origin
-webkit-mask-position-x
-webkit-mask-position-y
-webkit-mask-repeat-x
-webkit-mask-repeat-y
-webkit-mask-size
```

**Comment by ai** [comment]
Sure. Do you want to send PR? (Just fix [this list](https://github.com/postcss/autoprefixer/blob/master/data/prefixes.js#L511-L513) if you do not need to change syntax)

**Comment by ai** [comment]
Are you sure that spec contains `mask-position-x`? MDN says that this is non-standard property https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask-position-x

**Comment by ai** [comment]
Closing since there is no spec
