### ISSUE TITLE
flex-wrap: nowrap does not works with chrome 21 to 24

### ISSUE THREAD

**Issue by SuperPat45** [postcss/autoprefixer#1246]
I tested my site with the old chromium portable versions 21 and 24 and I found that the property:
`flex-wrap: nowrap;`
who was prefixed with:
`-webkit-flex-wrap: nowrap;`
does not work with these browsers, nowrap is not a valid value, however, it works fine if I add property:
`-webkit-flex-wrap: none;`
Starting from chrome 25, nowrap is recognized

**Comment by ai** [comment]
Does `nowrap` is 100% equal to `none`?

Why Chrome 21-24 is still important for us?

**Comment by ai** [comment]
I closed it because there was no answers
