### ISSUE TITLE
Autoprefixer is not prefixing style with JavaScript  

### ISSUE THREAD

**Issue by midnightgamer** [postcss/autoprefixer#1247]
I am trying to add autoprefixer in my project but it ain't working , i just copy pasted whole code from documentation yet not working.

**Comment by ai** [comment]
What tool do you use (out plan to use) to process CSS? Webpack, Gulp, Grunt? Maybe you want to work with plain files.

**Comment by midnightgamer** [comment]
I am using npm.

**Comment by ai** [comment]
Show me your `package.json`

**Comment by midnightgamer** [comment]
```
postcss([autoprefixer])
            .process(results)
            .then(result => {
              result.warnings().forEach(warn => {
                console.warn(warn.toString());
              });
              console.log(result);
             });
```

result is string passed other function as a result.

**Comment by ai** [comment]
Show me what CSS do you use as input

**Comment by midnightgamer** [comment]
I have lot of lines of code so i am just giving chunk of that code.

`
.team-card .card .card-text {
    font-size: 18px;
    font-weight: 300;
}


.teamstory-img {
    width: 100%;
    height: 92vh;
    object-fit: cover;
}




.hw-box::-webkit-scrollbar { width: 0 !important }

.hw-box { overflow: -moz-scrollbars-none; }


.hw-box { -ms-overflow-style: none; }


.card-image-team {
  --size: 400px;
    width: var(--size);
    height: var(--size);
    display: flex;
    background: #000;
    align-items: flex-end;
    justify-content: flex-end;
    transition: all .2s;

}

`

**Comment by midnightgamer** [comment]
> Show me your `package.json`

{
  "name": "minify-project",
  "version": "1.0.4",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "jest"
  },
  "keywords": [
   
  ],
  "author": "midnightgamer",
  "license": "ISC",
  "dependencies": {
    "autoprefixer": "^9.6.1",
    "clean-css": "^4.2.1",
    "concat": "^1.0.3",
    "fs-extra": "^8.1.0",
    "globby": "^10.0.1",
    "jest": "^24.9.0",
    "postcss": "^7.0.18",
    "uglify-es": "^3.3.9"
  },
  "devDependencies": {}
}

**Comment by ai** [comment]
Try this input `body { user-select: none }`, what output you will have?

**Comment by midnightgamer** [comment]
> Try this input `body { user-select: none }`, what output you will have?

This worked , but not why other css property ?

**Comment by ai** [comment]
Because modern browsers don’t need prefixes for properties from your CSS

**Comment by ai** [comment]
You can call `npx autoprefixer --info` to find what prefixes are necessary for modern browsers (according target browsers from your Browserslist)
