### ISSUE TITLE
gulp-postcss is not working like the Interactive demo

### ISSUE THREAD

**Issue by 93lucasp** [postcss/autoprefixer#1248]
If I write this like the interactive demo:
```
.example {
    display: grid;
    transition: all .5s;
    user-select: none;
    background: linear-gradient(to bottom, white, black);
}
```

My output will be:
```
.example {
  display: grid;
    transition: all .5s;
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;
    background: linear-gradient(to bottom, white, black);
}
```

But it should be:
```
.example {
    display: -ms-grid;
    display: grid;
    -webkit-transition: all .5s;
    -o-transition: all .5s;
    transition: all .5s;
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;
    background: -webkit-gradient(linear, left top, left bottom, from(white), to(black));
    background: -o-linear-gradient(top, white, black);
    background: linear-gradient(to bottom, white, black);
}
```

So I think there is something wrong.

In my gulp I have this:
```
function css() {
    return gulp.src('./src/assets/css/main.css')
        .pipe(postcss([ autoprefixer() ]))
        .pipe(gulp.dest('./public/assets/css/'));
}
```

I do something wrong or it is not working correctly?

**Comment by ai** [comment]
Autoprefixer adds actual prefixes. You do not need anymore prefixes for gradients and transition (check Can I Use).

Interactive demo is not official and could use different target browsers.

If you need to support some browsers, which need these prefixes, add browsers by Browserslist config.

**Comment by 93lucasp** [comment]
If I add: `display: contents` that is not supported in all browsers how you can see here https://caniuse.com/#search=display it will do the same why?

**Comment by ai** [comment]
`display: contents` has no prefixes

**Comment by Dan503** [comment]
```
.example {
    display: -ms-grid; // you need to enable CSS grid
    display: grid;
    -webkit-transition: all .5s; // not needed any more
    -o-transition: all .5s; // not needed anymore
    transition: all .5s;
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;
    background: -webkit-gradient(linear, left top, left bottom, from(white), to(black)); // not needed anymore
    background: -o-linear-gradient(top, white, black); // not needed anymore
    background: linear-gradient(to bottom, white, black);
}
```

To enable CSS grid:

```js
.pipe(postcss([ autoprefixer({ grid: 'autoplace'} ) ])
```

Make sure you read all of this series:

https://css-tricks.com/css-grid-in-ie-debunking-common-ie-grid-misconceptions/

And all of this section of the documentation:

https://github.com/postcss/autoprefixer/blob/master/README.md#grid-autoplacement-support-in-ie

Before attempting to use CSS Grid. 

Autoprefixer's CSS grid translation feature is powerful but still limited. This is why it is not enabled by default. Authors must understand the limitations before using it.

**Comment by 93lucasp** [comment]
So I wonder why if I use it with webpack it is adding different prefix🤔
I get the following with webpack
```
    display: grid;
    -webkit-transition: all .5s;
    transition: all .5s;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background: -webkit-gradient(linear,left top,left bottom,from(#fff),to(#000));
    background: linear-gradient(180deg,#fff,#000);
```

**Comment by 93lucasp** [comment]
So in gulp I get this:
```
.example {
  display: grid;
    transition: all .5s;
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;
    background: linear-gradient(to bottom, white, black);
}
```
with webpack this:
```
.example{
   display: grid;
    -webkit-transition: all .5s;
    transition: all .5s;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background: -webkit-gradient(linear,left top,left bottom,from(#fff),to(#000));
    background: linear-gradient(180deg,#fff,#000);
}
```

**Comment by Dan503** [comment]
> So I wonder why if I use it with webpack it is adding different prefix🤔

This is dependent on your browsersList settings

**Comment by 93lucasp** [comment]
@Dan503 Could you explain better? Ehat does it mean? I'm using the docs for gulp and webpack i didn't set any browsersList settings. As I understood from what Ai said it is based on "Can I use" so I don't understand why is getting different prefix. which one is correct? If with gulp i get less because the browsers don't need them. Why with Webpack I have?

**Comment by ai** [comment]
@93lucasp Autoprefixer adds actual prefixes for your target browsers (what browsers do you support). You specify target browsers in [Browserslist config](https://github.com/browserslist/browserslist). Different projects may have different target browsers. As result, Autoprefixer will insert different prefixes.

**Comment by Dan503** [comment]
Read the documentation for Browsers List found here:
https://github.com/browserslist/browserslist
