### ISSUE TITLE
Any news on this? The repetivtive calls to `postcss.config.js` is causing 3+ minute build times for us and without it only 30 seconds or so. Is there any quick workaround we can do to memorize the information/restrict the number of repetitive calls to our config? It doesn't change at all so we don't need dynamic nature

### ISSUE THREAD

**Issue by amin137954** [postcss/autoprefixer#1255]
Any news on this? The repetivtive calls to `postcss.config.js` is causing 3+ minute build times for us and without it only 30 seconds or so. Is there any quick workaround we can do to memorize the information/restrict the number of repetitive calls to our config? It doesn't change at all so we don't need dynamic nature

_Originally posted by @garygreen in https://github.com/postcss/postcss/issues/1147#issuecomment-514021142_

**Comment by ai** [comment]
Did you open issue in postcss-load-config?

Autoprefixer doesn't load config.
