### ISSUE TITLE
`caniuse-lite` acknowledgement notice while running `npx tldrlegal` 

### ISSUE THREAD

**Issue by ankurkaushal360** [postcss/autoprefixer#1267]
Since my company has to comply with SOC [compliance](https://www.imperva.com/learn/data-security/soc-2-compliance/), we ran `npx tldrlegal` on our project & it brought this to our attention:

![Screen Shot 2019-11-26 at 11 11 22 AM](https://user-images.githubusercontent.com/31927177/69651339-eccb0900-103d-11ea-8e2e-0ebf6668581a.png)

We don't use `caniuse-lite` directly but `babel` & other packages in our project does:

![image](https://user-images.githubusercontent.com/31927177/69651399-066c5080-103e-11ea-9563-9279af6c7443.png)

I would love to discuss how I help in fixing this & is it something that maintainers / contributors can fix themselves?

**Comment by ai** [comment]
I am a maintainer of Browserslist too. I got your issue there.

**Comment by ankurkaushal360** [comment]
@ai Apologies & thank you :)
