### ISSUE TITLE
Autoprefixer not detecting changes

### ISSUE THREAD

**Issue by GuerrillaCoder** [postcss/autoprefixer#1270]
I have this NPM script:

```
"scripts": {
    "autoprefixer-watch": "postcss build/*.css --use autoprefixer -d css/ -w"
}
```

It compiles the file first time it is run but it does not re-compile when a change is made.

My versions:

```
	"devDependencies": {
		"autoprefixer": "^9.7.3",
		"postcss": "^7.0.23",
		"postcss-cli": "^6.1.3"
	},
```

I am using windows 10 x64.

I tried modifying files in a different editor (notepadd++, vscode and PHPStorm) and none of them detects changes as I did have similar issue once that was due to IDE locking the files.

Am I doing something wrong or is this a bug?

**Comment by ai** [comment]
You need to report this bug to `postcss-cli`. Autoprefixer doesn't have watch logic. In your command you ask `postcss-cli` to watch for changes and recall Autoprefixer on changes.
