### ISSUE TITLE
-webkit-box-orient property gets removed

### ISSUE THREAD

**Issue by TimWensink** [postcss/autoprefixer#1279]
For a project I am using the [line-clamp](https://caniuse.com/#search=line-clamp) property to show 3 lines per comment max. This property, for all browsers, needs the prefix -webkit-. 

My css is:

```
.class {
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
```

However in the compiled CSS the -webkit-box-orient property is missing. The -webkit-line-clamp property is being compiled fine.

```
.compiledresult {
  display: -webkit-box;
  -webkit-line-clamp: 3;
  overflow: hidden;
}
```

I have also tried the properties without the -webkit- prefix but then they will not be autoprefixed at all. 

Is this a bug, or is there a setting I can switch to enable this property?
I have now made it work using the /* autoprefixer: ignore next */ above the rule, but I think it should be allowed by default.

Thanks in advance.

**Comment by ai** [comment]
We fixed this issue. Seems like you use old Autoprefixer (maybe as a dependency as in another tool).

Check `npm ls | grep autoprefixer`

**Comment by dongjoon-li** [comment]
may i get this version?

**Comment by ai** [comment]
https://github.com/postcss/autoprefixer/blob/master/CHANGELOG.md#961
