### ISSUE TITLE
Parcel & Svelte support ?

### ISSUE THREAD

**Issue by vexkiddy** [postcss/autoprefixer#1282]
Trying to get Autoprefixer working with Svelte & Parcel using `svelte-preprocess`. However I can't seem to get any browser prefixes on compile. I can supply a repro if you think you might be able to help? :D

**Comment by ai** [comment]
Let’s start with basic steps.

1. What CSS do you use for a test? I recommend to use `a { user-select: none }` since `user-select` still requires prefixes for all browsers.
2. What did you already try?
3. what was the exact result?

**Comment by vexkiddy** [comment]
Interesting! So I just made a simple Svelte & Parcel project to test Autoprexifer and PostCSS. So in `svelte-preprocess` I have the following:

```
const sveltePreprocess = require('svelte-preprocess');
 
module.exports = {
  preprocess: sveltePreprocess({
    postcss: {
      plugins: [require('autoprefixer')({ browsers: 'last 2 versions' })],
    },
  }
  )
};
```
This now works, however **Autoprefixer** throws an error in the console saying to use a .browserlistrc file to pick the browser compatibility. If you then remove the browser list from the `svelte-preprocess` file and try and rely solely on `package.json` or a `.browserlistrc` file then **Autoprefixer** doesn't work. There is a known issue with Parcel & Svelte where you have to have the following in your package JSON for Svelte to compile correctly using Parcel. 
```
 "browserslist": [
    "last 1 chrome versions"
  ],
```
It's mentioned here https://github.com/sveltejs/svelte/issues/3873. I'm not sure if this has something to do with the issue? Either way, it would be great to not have this **Autoprefixer** error every time you compile 👍 

I've uploaded a repro that you can see here: 
https://github.com/vexkiddy/parcel-svelte-sass-autoprefixer

**Comment by ai** [comment]
> then Autoprefixer doesn't work

What does it mean? What CSS do you use to test Autoprefixer? What is expected and real output?

**Comment by vexkiddy** [comment]
I'm using the below css to test Autoprefixer:

```
.container {
      user-select: none;
      display: flex;
      background: linear-gradient($main-background, #f5aa2f); 
  }
```

If you check the repro I added above with the browserlist config in the svelte.preprocess file, Autoprefixer works fine, however it throws a warning in the console when you compile. I just wanted to find out why this was happening and why it seems that relying solely on a .browserlistrc file or the package.json doesn't seem to work with Svelte & Parcel at the moment.

**Comment by ai** [comment]
@vexkiddy sorry, I have too many open-source projects today to work deeply with your project. Can you help me with tests? Can you:

1. replace `last 1 chrome versions` in `package.json` to `defaults`. Using last Chrome versions is not the best way to test Autoprefixer since it could not need prefixes for any of the properties in your example.
2. Replace `plugins: [require('autoprefixer')({ browsers: 'last 2 versions' })]` to `plugins: [require('autoprefixer')()]` in `svelte.config.js`
3. Remove `.cache`
4. Rebuild project

**Comment by vexkiddy** [comment]
@ai yep no problem. I've actually already tried this :D  

1. replacing `last 1 chrome versions` with `defaults` stops svelte and parcel from compiling as mentioned here: https://github.com/sveltejs/svelte/issues/3873. having both also doesn't work
2. just using `plugins: [require('autoprefixer')()]`means that the above needs to happen in package.json or in .browserlistrc file leading to the same issue mentioned in point 1.
3. the only way I have `autoprefixer` working is with the `plugins: [require('autoprefixer')({ browsers: 'last 2 versions' })]` but I then get the autoprefixer warning in the console  :(

**Comment by ai** [comment]
OK, let’s have `plugins: [require('autoprefixer')()]` and `"browserslist": "last 2 versions"`.

Do you have any error in this case? What is the input and output CSS?

**Comment by vexkiddy** [comment]
I don't get an error in this case, autoprefixer works and adds prefixes etc however i get the following in the console with compiling. so, shall I just use `overrideBrowserslist` then ? This removes this warning from the console and autoprefixer works as normal, i'm just wanting to follow the correct way of implementing autoprefixer :D

  ```
Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option can cause errors. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist
```

**Comment by ai** [comment]
> shall I just use overrideBrowserslist then

Nope. Having two different places with target browsers will lead you to errors. For instance, you could update `browserslist` for Babel in `package.json`, but will forget to update `overrideBrowserslist` in Autoprefixer.

> however i get the following in the console with compiling

Are you getting this warning with `plugins: [require('autoprefixer')()]`?

**Comment by vexkiddy** [comment]
I get **no** warning when just using `plugins: [require('autoprefixer')()]`, however as mentioned above when using package.json or .browserlistrc entries svelte & parcel either will not compile or autoprefixer will not add prefixes

**Comment by ai** [comment]
> I get no warning when just using plugins: [require('autoprefixer')()], however as mentioned above when using package.json or .browserlistrc entries svelte & parcel either will not compile or autoprefixer will not add prefixes

You mean that you have error:

```
css-loader.js:30 Uncaught TypeError: Class constructor SvelteComponentDev cannot be invoked without 'new'
```

Do you have any stack trace for this error?

**Comment by vexkiddy** [comment]
Exactly, this is the error that gets thrown in the console from Svelte / Parcel. I don't have a stack trace for it I'm afraid :(

**Comment by ai** [comment]
Seems like it is not a Autoprefixer issue, but Babel.

If you set everything properly it causes an wrong JS build. By setting `last 1 chrome version` you avoid this Babel issue, but Autoprefixer doesn't see any properties in your CSS which needs prefixes.

What browsers do you really need to support?

**Comment by vexkiddy** [comment]
it's ok. it's working for me with the `overridebrowserlist` so i'll just continue with that until the babel issue is somehow resolved. many thanks for your help!
