### ISSUE TITLE
-ms extensions removed when autoprefixer applied

### ISSUE THREAD

**Issue by sashkanz** [postcss/autoprefixer#1283]
![image](https://user-images.githubusercontent.com/2167760/74394394-69b59400-4e71-11ea-9e23-aaea51ddeb2c.png)

Is it a bug?

**Comment by ai** [comment]
It’s a feature. Autoprefixer removes outdated prefixes, which is not required for your target browsers.

**Comment by sashkanz** [comment]
How can I add it back please?

**Comment by ai** [comment]
Add IE to your target browser.

<hr>

If you need better support with deep review of your case and project, we have [OpenCollective donation with support](https://opencollective.com/postcss/).
