### ISSUE TITLE
no such file to load -- autoprefixer-rails

### ISSUE THREAD

**Issue by matthewcarleton** [postcss/autoprefixer#129]
I've followed the instructions and installed everything. This is what I get when I tell compass to watch the directory.

no such file to load -- autoprefixer-rails
org/jruby/RubyKernel.java:1062:in `require'
file:/Applications/compass.app/Contents/Resources/Java/compass-app.jar!/require_patch.rb:6:in`require'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_0.12/compass-0.12.2/lib/compass/configuration/data.rb:161:in `require'
/Users/matthewcarleton/Desktop/prefix_test/config.rb:1:in`parse_string'
org/jruby/RubyKernel.java:1112:in `eval'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_0.12/compass-0.12.2/lib/compass/configuration/serialization.rb:24:in`parse_string'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_0.12/compass-0.12.2/lib/compass/configuration/serialization.rb:15:in `_parse'
org/jruby/RubyIO.java:1139:in`open'
org/jruby/RubyKernel.java:296:in `open'
file:/Applications/compass.app/Contents/Resources/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/1.8/open-uri.rb:32:in`open'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_0.12/compass-0.12.2/lib/compass/configuration/serialization.rb:14:in `_parse'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_0.12/compass-0.12.2/lib/compass/configuration/file_data.rb:7:in`new_from_file'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_0.12/compass-0.12.2/lib/compass/configuration/inheritance.rb:204:in `with_defaults'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_0.12/compass-0.12.2/lib/compass/configuration/file_data.rb:6:in`new_from_file'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_0.12/compass-0.12.2/lib/compass/configuration/helpers.rb:42:in `configuration_for'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_0.12/compass-0.12.2/lib/compass/configuration/helpers.rb:97:in`add_project_configuration'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_0.12/compass-0.12.2/lib/compass/commands/project_base.rb:31:in `add_project_configuration'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_0.12/compass-0.12.2/lib/compass/commands/project_base.rb:25:in`configure!'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_0.12/compass-0.12.2/lib/compass/commands/project_base.rb:15:in `initialize'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_0.12/compass-0.12.2/lib/compass/commands/update_project.rb:37:in`initialize'
file:/Applications/compass.app/Contents/Resources/Java/compass-app.jar!/ui/tray.rb:430:in `watch'
file:/Applications/compass.app/Contents/Resources/Java/compass-app.jar!/app.rb:207:in`try'
file:/Applications/compass.app/Contents/Resources/Java/compass-app.jar!/ui/tray.rb:425:in `watch'
file:/Applications/compass.app/Contents/Resources/Java/compass-app.jar!/ui/tray.rb:142:in`compass_switch_handler'
file:/Applications/compass.app/Contents/Resources/Java/compass-app.jar!/ui/tray.rb:71:in `run'
file:/Applications/compass.app/Contents/Resources/Java/compass-app.jar!/main.rb:116:in`run_tray'
file:/Applications/compass.app/Contents/Resources/Java/compass-app.jar!/main.rb:132:in `(root)'
org/jruby/RubyKernel.java:1062:in`require'
file:/Applications/compass.app/Contents/Resources/Java/compass-app.jar!/main.rb:1:in `(root)'

**Comment by theodorosploumis** [comment]
You must add the gem in your **Gemfile**. And then run `bundle exec compass compile` again to compile the new gem.

``` ruby
source "https://rubygems.org"

gem "sass", "~>3.3"
gem "compass", "~>1.0"
gem "breakpoint", "~>2.5.0"
gem "singularitygs", "~>1.4"
gem "autoprefixer-rails", "~>5.1.0"
```

**Comment by savelyenne** [comment]
@theodorosploumis, thank you very much! Your answer was of great help for me :)
