### ISSUE TITLE
Browserslist: caniuse-lite is outdated. Please run next command `npm update`

### ISSUE THREAD

**Issue by oguilleux** [postcss/autoprefixer#1293]
Hi there,

I'm having this error in my console when I create my build with autoprefixer :

"Browserslist: caniuse-lite is outdated. Please run next command `npm update`"

I tried :
`sudo npm i -g browserslist caniuse-lite`
and
`sudo npm i -g autoprefixer caniuse-lite`

but nothing worked, I still have the warning.

Thanks for your help

**Comment by Dan503** [comment]
The `-g` installs globally. You want to install it locally.

Try `npm i caniuse-lite@latest`

**Comment by oguilleux** [comment]
Ok but I don't have `caniuse-lite` in my package.json file. It's a dependency of the dependency autoprefixer.

**Comment by ai** [comment]
We do not recommend to install Autoprefixer globally.

Install it locally by removing `-g`

**Comment by ai** [comment]
We have stool to update `caniuse-lite` but it will work only with locally installed Autoprefixer.

1. Update or install latest `browserslist`
2 Call `npx browserslist --update-db`

**Comment by oguilleux** [comment]
It's not installed globally

I have autoprefixer installed locally with my project's package.json. It's used in my gulp workflow as a plugin for postcss. I don't have browserslist installed as a dev dependency, it's a dependency of autoprefixer.

here is my package.json devDependencies : 

```
"devDependencies": {
    "ansi-colors": "4.1.1",
    "autoprefixer": "9.7.4",
    "babel-core": "6.26.3",
    "babel-eslint": "10.1.0",
    "babel-loader": "7.1.5",
    "babel-plugin-transform-runtime": "6.23.0",
    "babel-preset-env": "1.7.0",
    "browser-sync": "2.26.7",
    "cssnano": "4.1.10",
    "del": "5.1.0",
    "eslint": "5.16.0",
    "eslint-config-airbnb": "17.1.1",
    "eslint-loader": "3.0.3",
    "eslint-plugin-babel": "5.3.0",
    "eslint-plugin-import": "2.20.1",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-react": "7.19.0",
    "fancy-log": "1.3.3",
    "gulp": "4.0.2",
    "gulp-add": "0.1.0",
    "gulp-filter": "6.0.0",
    "gulp-imagemin": "7.1.0",
    "gulp-insert": "0.5.0",
    "gulp-notify": "3.2.0",
    "gulp-plumber": "1.2.1",
    "gulp-postcss": "8.0.0",
    "gulp-sass": "4.0.2",
    "gulp-sourcemaps": "2.6.5",
    "gulp-svg-sprite": "1.5.0",
    "gulp-svgmin": "2.2.0",
    "lodash": "4.17.15",
    "map-stream": "0.0.7",
    "merge-stream": "2.0.0",
    "node-notifier": "6.0.0",
    "supports-color": "7.1.0",
    "terser-webpack-plugin": "2.3.5",
    "vinyl-named": "1.1.0",
    "webpack": "4.42.0",
    "webpack-stream": "5.2.1"
  }
```

How can I updated autoprefixer's browserslist dependency ?

Thanks a lot

**Comment by ai** [comment]
Try `npx browserslist@4.10.0 --update-db `

**Comment by oguilleux** [comment]
That worked thank you.
