### ISSUE TITLE
Browserslist: caniuse-lite is outdated. Please run next command `npm update`

### ISSUE THREAD

**Issue by CodeBradley** [postcss/autoprefixer#1295]
I've been using this NPM script for a while now and today we started getting this error when running `node render.js` or `npm start`. I tried deleting my package-lock.json file and regenerating it and I get the same error. Below are the contents of my package.json

```
λ npm start

> ers-bootstrap@1.3.0 start C:\Users\*\*\er-bootstrap
> node render.js

*Browserslist: caniuse-lite is outdated. Please run next command `npm update`*

λ npm update

λ npm start

> ers-bootstrap@1.3.0 start C:\Users\*\*\er-bootstrap
> node render.js

*Browserslist: caniuse-lite is outdated. Please run next command `npm update`*

λ cat package-lock.json | grep caniuse
            "caniuse-lite": "^1.0.30001035",
        "caniuse-lite": {
          "resolved": "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001036.tgz",
            "caniuse-lite": "^1.0.30001035",
        "caniuse-lite": {
          "resolved": "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001036.tgz",
            "caniuse-lite": "^1.0.30001035",
        "caniuse-lite": {
          "resolved": "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001036.tgz",
        "caniuse-lite": "^1.0.30000998",
        "caniuse-lite": "^1.0.30000989",
    "caniuse-lite": {
      "resolved": "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30000999.tgz",
            "caniuse-lite": "^1.0.30001035",
        "caniuse-lite": {
          "resolved": "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001036.tgz",
        "caniuse-lite": "^1.0.30000981",
```

Package.json
```
{
...
  "main": "render.js",
  "scripts": {
    "start": "node render.js"
  },
...
  "homepage": "git+https://lawsudo@bitbucket.org/lawsudo/",
  "dependencies": {
    "animatewithsass": "^3.2.1",
    "dotenv": "^8.2.0",
    "jquery": "^3.4.1",
    "jquery-ui": "^1.12.1"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/preset-env": "^7.9.0",
    "eslint": "^6.8.0",
    "extend-shallow": "^3.0.2",
    "javascript-obfuscator": "^0.18.8",
    "node-dir": "^0.1.17",
    "node-sass": "^4.13.1",
    "postcss-preset-env": "^6.7.0",
    "pug": "^2.0.4",
    "pug-bootstrap": "0.0.15",
    "pug-cli": "^1.0.0-alpha6",
    "pug-loader": "^2.4.0",
    "stylelint": "^9.10.1",
    "stylelint-config-recommended-scss": "^3.3.0",
    "stylelint-config-standard": "^18.3.0",
    "stylelint-order": "^1.0.0",
    "stylelint-scss": "^3.16.0"
  }
}

```

**Comment by ai** [comment]
You need to call:

```sh
npx browserslist@4.10 --update-db
```

It will update `caniuse-lite` in nested dependencies too.

**Comment by Dan503** [comment]
@ai there needs to be clearer guidance around this.

From the warning that you get there is no way for the user to know that the command you are supposed to run is
`npx browserslist@latest --update-db`.

I say `@latest` because it's the more reliable command that is more generic.

Is there any way to detect this warning and give the correct guidance?

If not, maybe we can ask caniuse-light to update their warning to this:
`caniuse-lite is outdated. Please run next command npm update or npx browserslist@latest --update-db if using browsers list`

**Comment by ai** [comment]
@Dan503 

> there needs to be clearer guidance around this.
> From the warning that you get there is no way for the user to know that the command you are supposed to run is

Of course! New Browserslist 4.10 print different warning:

```
Browserslist: caniuse-lite is outdated. Please run next command `npx browserslist --update-db`
```

The problem is that @CodeBradley also has old Browserslist.

> I say @latest because it's the more reliable command that is more generic.

Yeap, it is a great idea. I updated warning https://github.com/browserslist/browserslist/commit/2c03f11d92e601ba0d57225676d3a7728515f065

**Comment by Dan503** [comment]
There is one possible conscern with using `@latest` it downloads through breaking changes by downloading the latest version no matter what you're current version is. Is that a conscern?

**Comment by ai** [comment]
> Is that a conscern?

I think it is OK for now and next few years.

In some moments I will publish 5.x without old Node.js 8 support but without API changes (at least `--update-db` will work the same). It will be better if users will use 5.x in this case.

**Comment by CodeBradley** [comment]
Thanks guys, worked great. I tried running this previously but the command I copied from another issue didn't have browserslist version appended to it. Do I need to update Babel version or anything too?

**Comment by ai** [comment]
@CodeBradley you do not need to update Babel, but for me it is always a good idea to update minor and patch version of Babel

**Comment by KevinFerreira** [comment]
Hey guys, I still seem to get the error:
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

despite trying the scripts above. any more thoughts on this?

**Comment by khatekar** [comment]
Hello all,

Running `npx browserslist@latest --update-db` fixed the build issue locally, how can we fix the same issue on build server (ci/cd), my build is failing due to this, which it shouldn't. Thanks.

**Comment by edgariscoding** [comment]
@khatekar I'm having the same issue. I've run `npx update-browserslist-db@latest` (also tried `npx browserslist@latest --update-db`) in my Azure build pipeline prior to building my angular project. Despite running this, the next line states that caniuse-lite is outdated. 

It seems like some of my packages have a caniuse-lite dependency and not all of them are updated.
