### ISSUE TITLE
No matching version found for browserslist@^4.11.0

### ISSUE THREAD

**Issue by mvshmakov** [postcss/autoprefixer#1296]
Guys, currently version `4.11.0` of `browserslist` does not exist according to npm. Typo was seeded in [this commit](https://github.com/postcss/autoprefixer/commit/db9fbe2a8031548bbb6f95795cbf9103e3fb93e7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2). Please, use the `4.9.1` version:

<img width="770" alt="Screenshot 2020-03-26 at 10 23 35" src="https://user-images.githubusercontent.com/28868855/77621413-78519980-6f4d-11ea-85c6-b42f2aca24dc.png">

**Comment by ai** [comment]
Are you sure that Browserslist 4.11 was not released?

Release tweet: https://twitter.com/Browserslist/status/1242179632369209350?s=19

Maybe you have problem with npm cache?

![Screenshot_20200326-033943](https://user-images.githubusercontent.com/19343/77621950-c6e24200-6f13-11ea-921d-a417577bea6e.png)

**Comment by mvshmakov** [comment]
Okay, you are right. After the `npm cache clean` it successfully installed. Thanks for your time!
