### ISSUE TITLE
Input Error: 

### ISSUE THREAD

**Issue by awnawnawn** [postcss/autoprefixer#1298]
How to solve this error report
![Snipaste_2020-04-03_00-17-43](https://user-images.githubusercontent.com/47672657/78273082-ed6e3180-7540-11ea-9a77-6f560c231746.png)

**Comment by ai** [comment]
You posted issue before image was uploaded. Can you post it again in the comment. But way few minutes before clicking on Comment.

**Comment by ai** [comment]
Sorry, seems like it is an error in text editor plugin code.

You need to report issue there.
