### ISSUE TITLE
transition-delay doesn't work

### ISSUE THREAD

**Issue by kolyadams** [postcss/autoprefixer#1299]
transition-delay: .3s, 0s;
transition-property: top, transform;

transform to

transition-property: top,transform,-webkit-transform;

this doesn't work

https://onetwostudy.com/css-animaciya-ikonki-gamburger-menyu/

**Comment by ai** [comment]
[Autoprefixer Online](https://autoprefixer.github.io/) returns different result:

```cs
    -webkit-transition-property: top, -webkit-transform;
    transition-property: top, -webkit-transform;
    transition-property: top, transform;
    transition-property: top, transform, -webkit-transform;
```

It seems like other CSS tools in your build process removes properties.

**Comment by kolyadams** [comment]
в оригинале у transition-property и transition-delay 2 параметра 

после преобразований у transition-property становится три параметра
transition-property: top, transform, -webkit-transform;

transition-delay перестает понимать какому параметру давать задержку и анимация не работает как положено

**Comment by ai** [comment]
Да, это ограничение метода. К сожалению, браузеры работают так, что для некоторых нужно только наращивать до 3-х.

Мы выводим предупреждение, что Автопрефиксер плохо работает с `transition-property` и просьбой прейти на `transition`

https://github.com/postcss/autoprefixer/blob/master/lib/transition.js#L135-L142
