### ISSUE TITLE
[Safari] Issue with flex rule not being inserted in the correct order

### ISSUE THREAD

**Issue by WeronikaWeglinska** [postcss/autoprefixer#1302]
Safari: Version 13.1 (14609.1.20.111.8)
"autoprefixer": "^9.7.6",
"postcss-loader": "^3.0.0",

<img width="276" alt="Screenshot 2020-04-14 at 17 17 06" src="https://user-images.githubusercontent.com/55077112/79241774-cafae300-7e73-11ea-82e6-ff95e16ab07d.png">

If I manually add in my css property:
```
display: flex;
display: -webkit-box;
```
it fixes the issue.

**Comment by ai** [comment]
Hi. Thanks for the report.

What is the problem in this screenshot? Do you worry about warning about having both `display: flex` and `display: -webkit-box`?

**Comment by WeronikaWeglinska** [comment]
No, display flex doesn't work, seems the order is breaking it, if I uncheck display: flex everything is fine. 
Wrong order:
```
display: -webkit-box
display: flex
```

Correct order:
```
display: flex
display: -webkit-box
```

**Comment by ai** [comment]
Why do you think this code is broken? What problem do you have exactly right now?

Often this behavior means that there is a problem in another CSS. Disabling `display: flex` switches Safari to old mode. It could help if there is an issue in the new unprefixed code. But the real problem is not `display: flex` (because Safari should work in new unprefixed mode), but in issue in another code.

**Comment by WeronikaWeglinska** [comment]
Ok, so the problem I see is that display flex doesn't work on Safari. 
The css rule as in screenshot that is taken into account is display: flex. If I uncheck it, the safari uses the rule: display: -webkit-box. 

I fixed it in my code adding in css:
Before:
.editor {
    display: flex;
    flex-direction: column;
...
}
After:
.editor {
    display: flex;
    display: -webkit-box;
    flex-direction: column;
...
}

But, I assume the autoprefixer should do that for me automatically and it does, just not in the order that would work. 

I don't fully understand what you mean the issue in not display flex.

**Comment by ai** [comment]
> Ok, so the problem I see is that display flex doesn't work on Safari.

Show me the full code and screenshots before and after the fix.

I need to check other CSS here. As I told, the most likely case here is that `display: -webkit-box` fixes some problem in another part of the code.

**Comment by WeronikaWeglinska** [comment]
Ah, yes, you are right, will try fixing other containers, that seem to be breaking. I will let you know and close the issue if I can fix it.
