### ISSUE TITLE
 Error installing package: Unexpected end of JSON input while parsing near '...ZnbB+sYXUNKxAVl9Bb18z'

### ISSUE THREAD

**Issue by AssouaAlbert** [postcss/autoprefixer#1306]
For while, I have been trying to install the latest version of the package. But I always end up with this error: 

> npm install --save-dev autoprefixer
> npm ERR! Unexpected end of JSON input while parsing near '...ZnbB+sYXUNKxAVl9Bb18z'

How can I solve this... The older versions will not install as well.
I have tried running the command as administrator ... Still not working.

**Comment by AssouaAlbert** [comment]
Solution: 
Get-ExecutionPolicy -List
  Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine    RemoteSigned

> Set the CurrentUser to RemoteSigned 
Command:
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser

**Comment by ai** [comment]
It is npm problem. Sorry I do not know how I can fix it from my side.

Try to clean npm cache.
