### ISSUE TITLE
Error while installing Autoprefixer (as a Sublime Text Package, using Package Control)

### ISSUE THREAD

**Issue by shrihanDev** [postcss/autoprefixer#1307]
# Hello!
Today, I was trying to install Autoprefixer in Sublime Text.
When I finished installing, it showed me this: 
![Capture](https://user-images.githubusercontent.com/54971391/80860201-d1ff5f00-8c83-11ea-9da8-07af086daf01.PNG)
**I tried to reinstall so many times, still no luck.
Please suggest me.**

**Comment by ai** [comment]
Sorry. We do not support Autoprefixer as a Sublime Text plugin. We think that it is bad practice.

The best way to use Autoprefixer is a build tool. For instance, Parcel.

Or you can report an issue on Autoprefixer as Sublime Text https://github.com/sindresorhus/sublime-autoprefixer
