### ISSUE TITLE
how to handler my node_modules by `npm link`

### ISSUE THREAD

**Issue by kagari2613** [postcss/autoprefixer#1308]
has any options to handler my node_modules add by run `npm link modules`?i just don't want publish it

**Comment by ai** [comment]
Add `node_modules` to `.gitignore` or `.npmignore`

**Comment by kagari2613** [comment]
> Add `node_modules` to `.gitignore` or `.npmignore`
no，i means  hope autoprefix can add css browser prefix to my style file that imported form node_module witch is by npm link。actually it is not work

**Comment by ai** [comment]
First, you need to write more details to issues in the future.

Second, Autoprefixer do not work with files.

There are another tool, called runner or builder, which load files and send it to Autoprefixer, Babel and other tools.

It could be postcss-cli, gulp-postcss, webpack, Parcel and many others. I do not know what will do you use to give you an advice. It could be very different systems, depends on how do you build your website.

But you should go to your build system docs to find why it doesn't send `node_modules` files to Autoprefixer.
