### ISSUE TITLE
the command generates sourceMappingURL without any prefixes

### ISSUE THREAD

**Issue by zskiredj** [postcss/autoprefixer#1309]
hello,

here is my css (just for example) :

```
.tata {
 display: flex;
}
```

then i use the command : 

> postcss style.css --use autoprefixer -o test.css

the problem is that the scritp generates no prefixes, but only a sourceMapping.

Here is what I get : 

```
.tata {
 display: flex;
}

/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInN0eWxlLmNzcyJ.... */

```
Any idea how I can fix this ?

**Comment by ai** [comment]
According to [postcss CLI docs](https://www.npmjs.com/package/postcss-cli) you need `--no-map` argument

**Comment by zskiredj** [comment]
OK the mapping is not generated anymore, but no autoprefix is generated either.
Thanks

**Comment by ai** [comment]
> but no autoprefix is generated either.

`display: flex` doesn’t need prefixes anymore.
