### ISSUE TITLE
Missing some CSS Logical Property Support

### ISSUE THREAD

**Issue by joezimjs** [postcss/autoprefixer#1316]
I found this: https://github.com/postcss/autoprefixer/issues/324 so I assumed that CSS Logical Properties were covered, but they are only covered to an extent.

Something like `margin-block-start: 1px;` gets converted to `-webkit-margin-before: 1px;` right now but using the shorthand versions like `margin-inline` doesn't get any conversion. Not only should it get converted to the prefixed versions, but should also have a fallback for browsers like IE by using the old standards of `margin-left` and `margin-right`. There's a PostCSS plugin that can do this: https://github.com/csstools/postcss-logical

I think that this support should exist in autoprefixer though

**Comment by ai** [comment]
> Not only should it get converted to the prefixed versions, but should also have a fallback for browsers like IE by using the old standards of margin-left and margin-right.

Autoprefixer is a tool for vendor prefixes. Polyfills are not prefixes and we [do not add CSS polyfills](https://github.com/postcss/autoprefixer#does-it-add-polyfills) for a many reasons (for instance, we need a different API for them).

You are looking for [postcss-preset-env](https://github.com/csstools/postcss-preset-env), a special PostCSS plugin preset to polyfill CSS features.

The recommended way to use Autoprefixer is to use it with `postcss-preset-env` and Stylelint.

**Comment by joezimjs** [comment]
OK, but shouldn't it still convert

```css
margin-inline: 5px;
```
to
```css
-webkit-margin-start: 5px;
       -moz-margin-start: 5px;
-webkit-margin-end: 5px;
       -moz-margin-end: 5px;
            margin-inline: 5px;
```
?

**Comment by ai** [comment]
Yeap, this case is more related to Autoprefixer, but I do not want to add it, because there are `postcss-logical`.

If you will send a PR with `margin-inline` I will help you and release it.

**Comment by mnr73** [comment]
still there is problem with logical properties for example autoprefixer remove this

`margin-inline-start: .3em;`

and when disable remove option autoprefixer change it to this

`-webkit-margin-start: 0.3em;`

and this not work in Mozilla

please fix this just let logical be preserve without any change

**Comment by Yeganloo** [comment]
Hello
I am supporting @mnr73 suggestion. As you see in [This Specification](https://drafts.csswg.org/css-logical/#margin-properties), logical properties are now part of the main CSS specification and auto-prefix is interrupting the main functionality of CSS.
Please reopen this conversation and consider this Bug as an important one.
