### ISSUE TITLE
flex-grow compiled wrongly to -webkit-flex-box

### ISSUE THREAD

**Issue by tonysamperi** [postcss/autoprefixer#1317]
With versions **8.9.0** and **8.6.1**
The following CSS:
![image](https://user-images.githubusercontent.com/5957244/83614481-89d6a380-a585-11ea-9f25-9a7050621870.png)
Produces:
![image](https://user-images.githubusercontent.com/5957244/83614529-9955ec80-a585-11ea-97a6-266ba1c0bb44.png)
But this is what I would expect:
![image](https://user-images.githubusercontent.com/5957244/83614602-b8547e80-a585-11ea-816b-c48da8c67929.png)

**Comment by ai** [comment]
For what browsers do you need `-webkit-flex-grow`?

**Comment by tonysamperi** [comment]
Sorry, but how is that relevant?
There's an obviously bad behaviour here, since it outputs the same property twice, so the second one overrides the first one.
Anyway I use the same settings I found on sassmeister.com, so in my package.json I have 
```
"browserslist": [
    "last 2 versions"
  ],
```
Which works as expected on sassmeister.com.
Maybe I have some bad config somewhere...

**Comment by ai** [comment]
`-webkit-box-flex` is a property from 2009 spec used by old webkit and old Chrome. `-webkit-flex-grow` is a property from the latest spec used by more modern Chrome.

You are asking to replace one property to another. If I do as you told me, I will break old webkit support (old Safari and Chinese browsers).

More likely, that you didn’t select more modern Chrome in your Browserslist (`last 2 versions` selected only Chrome, which does not need vendor prefixes for Flexbox).

**Comment by tonysamperi** [comment]
Ok I solved by restricting the browserslist.
Probably the issue is with some Safari version.

![image](https://user-images.githubusercontent.com/5957244/83640774-e600ee00-a5ac-11ea-87c7-0269fd30b29f.png)
