### ISSUE TITLE
-moz- prefix for "last * versions" vs "last * firefox versions"

### ISSUE THREAD

**Issue by tarunkolla** [postcss/autoprefixer#1321]
I'm currently working on figuring out why I see different views for the same property and noticed Autoprefixer doesn't prefix `height: stretch` with `-moz-` when `last 2 firefox versions` is used compared to `last 2 versions`. 

The prefix `-moz-` is for firefox vendor looking at the [CSS Prefixes](https://developer.mozilla.org/en-US/docs/Glossary/Vendor_Prefix). Although the property `height: stretch` is not [supported](https://caniuse.com/#search=height%3A%20stretch) on firefox and if [Autoprefixer doesn't detect the usage](https://github.com/postcss/autoprefixer/issues/1035#issuecomment-485343979) why do I not see the `-moz-` prefixed for `last 2 firefox versions`? And if does detect browsers why `-moz-` for `last 2 versions`?

*Last 2 firefox versions:*
<kbd>
![Last 2 firefox versions autoprefixer results screenshot](https://user-images.githubusercontent.com/35357999/84418338-aa81a780-abdc-11ea-80a1-b2970c8df9ba.png)
</kbd>

*Last 2 versions:*
<kbd>
![Last 2 versions autoprefixer results screenshot](https://user-images.githubusercontent.com/35357999/84418344-ac4b6b00-abdc-11ea-96af-0ba2651aca11.png)
</kbd>

I also made a [comment](https://github.com/postcss/autoprefixer/issues/1035#issuecomment-642820148) reg the same on one of the similar issues that's closed.

**Comment by ai** [comment]
Not only Firefox uses `-moz-` prefixes. See Can I Use page for details.

**Comment by ai** [comment]
It could cased because KaiOS Browser is also used this prefix.
