### ISSUE TITLE
autoprefixer@9.8.2: The engine "node" is incompatible with this module error.

### ISSUE THREAD

**Issue by yusufkayaer** [postcss/autoprefixer#1329]
Hi,
I upgrade autoprefixer@9.8.2 release and i started getting the error below. 
I am using node.js 11.6.0 version. 

Error: 
error autoprefixer@9.8.2: The engine "node" is incompatible with this module. Expected version "^6 || ^8 || ^10 || ^12 || >=13.7". Got "11.6.0"

FYI. 
Regards.

**Comment by ai** [comment]
Node.js 11 is deprecated by Node.js Foundation.

https://nodejs.org/en/about/releases/

It doesn't receive security updates for years. You should migrate to Node.js 12.

**Comment by yusufkayaer** [comment]
> Node.js 11 is deprecated by Node.js Foundation.
> 
> https://nodejs.org/en/about/releases/
> 
> It doesn't receive security updates for years. You should migrate to Node.js 12.

Thanks for helps.

**Comment by liby** [comment]
![image](https://user-images.githubusercontent.com/38807139/85934950-ecb92180-b91c-11ea-8946-324c585f6219.png)
Excuse me, is it no good even for version 13.3? @ai

**Comment by ai** [comment]
@liby Node.js < 13.7 have a problem with ES modules.

Also, note that Node.js 13 do not have security updates.
