### ISSUE TITLE
Older Flexbox syntaxes

### ISSUE THREAD

**Issue by dantz** [postcss/autoprefixer#133]
Autoprefixer adds some of the old flexbox syntaxes to the mix instead of just prefixing the actual CSS I wrote. That can be problematic because not all features are supported in the old syntax necessarily.

I'd much prefer it for Autoprefixer not trying to be smart and just keep Autoprefixing the stuff I write. In the current case it adds some `-webkit-box-ordinal-group`-stuff which breaks the layout on mobile safari.

**Comment by tlightsky** [comment]
@dantman does this [lib](https://github.com/10up/flexibility) help

**Comment by dantman** [comment]
@tlightsky No. -webkit-box bugs affect WebKit browsers. So a library for IE is of no help.

Fortunately, early versions of Android are disappearing. Unfortunately, the stock Android 4.3 browser still has 1.05% usage share and the UC Browser for Android has an 8.11% usage share. So -webkit-box rules are *still* being outputted.

**Comment by ai** [comment]
@dantman in next Autoprefixer 6.3 you will be able to disable `2009` spec prefixes output and use JS polyfill.

**Comment by tlightsky** [comment]
@ai what is the polyfill, support flexbox 2012?

**Comment by ai** [comment]
@tlightsky Flexibility does. There is simple PostCSS plugin to insert that `-js-` prefix for Flexibility.

**Comment by tlightsky** [comment]
@ai I thought it only work in IE 8&9, I'll try it later
