### ISSUE TITLE
engine node 11

### ISSUE THREAD

**Issue by Scrum** [postcss/autoprefixer#1330]
https://github.com/postcss/autoprefixer/blob/387a587614a44ab6824c03d8d751ed930c97199f/package.json#L24-L26
![Screenshot 2020-06-23 at 14 27 21](https://user-images.githubusercontent.com/2789192/85398374-cc284a80-b55d-11ea-9efa-34a7f52f8532.png)

Why not put `"node": ">=6"` ?

**Comment by Scrum** [comment]
I had to downgrade some packages fix the versions for:
1. `"postcss-preset-env": "6.6.0",`
2. `"stylelint": "11.0.0",`
3. `"autoprefixer": "9.5.1",`

**Comment by ai** [comment]
Because Node.js never was a LTS version and do not receive security updates.

Why you locked on this version?

**Comment by ai** [comment]
The reason of changing `engines` is that some Node.js versions contained the bug

**Comment by Scrum** [comment]
> Because Node.js never was a LTS version and do not receive security updates.
> 
> Why you locked on this version?

At the moment, we are stuck on this version and for migration to the nodes above we will need a lot of resources.

Yes, we will migrate, but we needed to know that this would happen in order to prepare for this in advance. Now we’ll be great forced to throw all resources to correct this situation

**Comment by ai** [comment]
Why did you stuck on non-LTS version?

**Comment by Scrum** [comment]
> Why did you stuck on non-LTS version?

I think there were two circumstances:
1. Spontaneous implementation of new tools
2. The period of floating developers
3. The lack of a leader at that time

**Comment by Scrum** [comment]
I think that such an update should have carried a `major` version

**Comment by ai** [comment]
Good point about breaking changes 8d6c6cc

But you should spend this time on updates Nodejs 11 to 12. Fixing Autoprefixer is like fixing the symptoms instead of the source of the problem. The problem is sticking on the non-LTS version.

**Comment by ai** [comment]
Released in 9.8.3

**Comment by Scrum** [comment]
> But you should spend this time on updates Nodejs 11 to 12. Fixing Autoprefixer is like fixing the symptoms instead of the source of the problem. The problem is sticking on the non-LTS version.

Of course, we are moving towards this, but in this case it was spontaneous for us and we did not take the very right measures, unfortunately at the moment they are necessary and we must now review the entire large project and slow down the overall processes which will not have a very positive effect on the product

**Comment by Scrum** [comment]
> Released in 9.8.3

Thank you for understanding 🚀
