### ISSUE TITLE
How to enable webkit flex box prefixes for "last 1 version, not dead, ie >= 11"

### ISSUE THREAD

**Issue by mesqueeb** [postcss/autoprefixer#1340]
I have a project with this in `package.json`
```
"browserslist": [
        "last 1 version, not dead, ie >= 11"
    ]
```
And this is my `postssrc.js`
```
// https://github.com/michael-ciniawsky/postcss-load-config

module.exports = {
  plugins: [
    // to edit target browsers: use "browserslist" field in package.json
    require('autoprefixer')
  ]
}
```

And the problem is, I noticed that  `flex-direction: column` is not getting any webkit prefixes for Safari, and my website is displayed without `flex-direction: column` working. (it shows up as "row" behaviour...)

Any ideas how I enable prefixes for Safari?

**Comment by ai** [comment]
The last Safari version doesn’t need `-webkit-` for Flexbox https://caniuse.com/#feat=flexbox

Very likely that you have a mistake in Flexbox CSS, which works in old syntax but do not work in new syntax.

**Comment by mesqueeb** [comment]
@ai I understand. Thank you for your comment.

I'm not sure why only on Safari my div with `flex-direction: column` is not showing correctly.

<img width="1274" alt="Screenshot 2020-07-14 09 57 02" src="https://user-images.githubusercontent.com/3253920/87368351-678a6980-c5b8-11ea-8d5d-2cad421e5195.png">

If you have any advice, let me know!
