### ISSUE TITLE
how to turn on prefixing for "grid-area"?

### ISSUE THREAD

**Issue by klin333** [postcss/autoprefixer#1342]
Hi,

Sorry to ask such a noob question but I am going insane with this...

I just can't seem to get grid-area prefixing to work in node js and autoprefixer. Help please.... Node js code snippet below with output I get vs output I want. 

```
var cssString = `.page {
  display: grid;
  grid-template-areas: "nav  main";
}
.page__main {
  grid-area: main;
}
`

var autoprefixer = require('autoprefixer')({ grid: "autoplace"})
var postcss = require('postcss')
 
postcss([ autoprefixer ]).process(cssString).then(result => {
  result.warnings().forEach(warn => {
    console.warn(warn.toString())
  })
  console.log(result.css)
})
```

Printed output from above code:

```
.page {
  display: -ms-grid;
  display: grid;
  grid-template-areas: "nav  main";
}
.page__main {
  grid-area: main;
}
```

Desired output, (copy and pasted from https://autoprefixer.github.io/):
```
.page {
  display: -ms-grid;
  display: grid;
      grid-template-areas: "nav  main";
}
.page__main {
  -ms-grid-row: 1;
  -ms-grid-column: 2;
  grid-area: main;
}
```

**Comment by ai** [comment]
Show `npm ls | grep autoprfixer` output

**Comment by klin333** [comment]
ok fixed thanks.

Turned out autoprefixer got installed as part of html-autoprefixer which was 5 years old, making my autoprefixer only version 6.7.7

I completely forgot to check package versions since I only installed node js and all packages today... 

very sorry for wasting your time...

**Comment by ai** [comment]
Writing a tweet about our funding page will be the best way to help us
https://opencollective.com/postcss/
