### ISSUE TITLE
Probably a Broom Icon

### ISSUE THREAD

**Issue by Jrock-ai** [postcss/autoprefixer#1345]
Probably a Broom Icon 

_Originally posted by @shishirraven in https://github.com/twbs/icons/issues/385_

**Comment by ai** [comment]
What do you mean? Do you suggest to remove an Autoprefixer icon?

**Comment by CalvinRodo** [comment]
I have a feeling this is a bot that is running loose.

It's been affecting some of our repos as well, 

You can see that it's linked to some PR's/Comments in our repositories that have no link to your stuff. 

https://github.com/postcss/autoprefixer/issues/1350
https://github.com/postcss/autoprefixer/issues/1349

I reported this to github and I recommend you do the same.
