### ISSUE TITLE
Latest version of colorette breaks autoprefixer

### ISSUE THREAD

**Issue by jroxendal** [postcss/autoprefixer#1348]
When trying to install tailwind into my existing webpack project I get 
`Error: No valid exports main found for '[redacted]/node_modules/colorette'`

The problem went away when adding this to my package.json:
`"resolutions": {
   "tailwindcss/**/colorette": "1.2.0"
}`

I assume the culprit has something to do with changes to the module definitions mentioned here:
https://github.com/jorgebucaran/colorette/releases/tag/1.2.1

**Comment by ai** [comment]
Do you use Node.is 13? It has problem with ESM modules (and was deprecated by Node.js team)?

**Comment by jroxendal** [comment]
Ah, you're right, works fine in node 14, thanks!

**Comment by TheMangoTrain** [comment]
This is still a problem with [nuxt.js](https://github.com/nuxt/nuxt.js); testing a fresh install of nuxt returns the same colorette error as OP. Tried node 14.0.0, 14.0.5, 14.08.

What worked: After deleting (moving) `./node_modules/autoprefixer/node_modules`, nuxt fully runs.

**Comment by ai** [comment]
@TheMangoTrain can you create a separated issue with a full error message?
