### ISSUE TITLE
autoprefixer breaks fresh nuxt.js

### ISSUE THREAD

**Issue by TheMangoTrain** [postcss/autoprefixer#1353]
With a fresh install of [nuxt.js](https://github.com/nuxt) (via create-nuxt-app), `npm run dev` fails with an error:

`ERROR  No valid exports main found for '/myProject/node_modules/autoprefixer/node_modules/colorette' `

To get around this (and continue work), the error is cleared by simply moving-or-deleting this folder:

`node_modules/autoprefixer/node_modules/colorette`

Tried with node 14.0.0, 14.0.5 and 14.8.0; same results all round.

**Comment by ai** [comment]
Could open `node_modules/autoprefixer/lib/autoprefixer.js` and put this code to the first line:

```js
console.log(process.versions);
```

Start Nuxt.js with Node.js 14 and show me output.

**Comment by TheMangoTrain** [comment]
Thanks for this clue!

So turns out for the project there was a specific older version of node (13.5.0) in use, even though `node -v` was reporting 14.8.0; I should use `console.log(process.versions)` more often.

I set `nvm use 14.8.0`, deleted the root node_modules dir, and ran `npm install` again. Everything is fine now.
