### ISSUE TITLE
Support Node 13

### ISSUE THREAD

**Issue by ArgonAlex** [postcss/autoprefixer#1361]
It seems a bit aggressive that we removed support for Node 13 when it is only the previous version.

**Comment by ai** [comment]
There are a few reasons to do it:

1. Node.js <13.7 have a painful bug in ES modules support.
2. 13.x has no security support.
3. Many Node.js developers do not understand LTS (even numbers, 12.x, 14.x) and development (11.x, 13.x) version system of Node.js. You should not use development version for production. Only for hack and local experiments. A project like PostCSS and Autoprefixer could be used to spread this best practice of avoiding non-LTS versions on production.
