### ISSUE TITLE
No moz-available for Firefox > 65

### ISSUE THREAD

**Issue by guilhermetod** [postcss/autoprefixer#1362]
Hey, I don't know if I'm missing something, but as far as I know, [Firefox is still using -moz-available for width: stretch](https://caniuse.com/?search=width%3A%20stretch). However, autoprefixer only corrects that until Firefox 65. Chrome is still fine with webkit.

#### >= 65
![image](https://user-images.githubusercontent.com/53096593/94278394-218b4380-ff21-11ea-9a9f-36eb52bcbe04.png)

#### > 65 only
![image](https://user-images.githubusercontent.com/53096593/94278445-31a32300-ff21-11ea-9188-a0bbbdf90c04.png)

**Comment by ai** [comment]
Can you try Autoprefixer from npm? The online tool is using Autoprefixer 9.x, which is not the latest version.

**Comment by Ajayman** [comment]
i am using mozilla version 85 will autoprefixer fix all in that version?

**Comment by ai** [comment]
@Ajayman I was not able to reproduce the error
