### ISSUE TITLE
CSS: column-width, column-count, & columns (Firefox issue)

### ISSUE THREAD

**Issue by vonscriptor** [postcss/autoprefixer#1368]
**[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/column-width):** `column-width`
> you must specify all related length values to achieve an exact column width

It seems a percentage unit is not accepted(?).

Given the following (**INPUT**):
```
column-width: 50%;
column-count: 2;
```

Autoprefixer (**OUTPUT**):
```
-moz-column-width: 50%;
-webkit-column-width: 50%;
-moz-column-count: 2;
-webkit-column-count: 2;
columns: 50% 2;
```

Firefox and Safari will invalidate the `columns` values due to using a percentage. Safari will still accept its prefix, but Firefox does not.

Solution (**Expected**):
```
column-width: 50%;
column-count: 2;
-moz-column-width: 50%;
-webkit-column-width: 50%;
-moz-column-count: 2;
-webkit-column-count: 2;
columns: 50% 2;
```

- Keep an unprefixed `column-count` (and `column-width`) property which will fix the Firefox fallback for invalid columns values as `-moz-column-count` no longer seems accepted, but might need to be maintained for older versions.

One could argue to just not use percentage values, but I'd counter by saying the fallback still needs to be compatible in Firefox and `-moz-column-count` no longer seems to be.

CodePen Example:
https://codepen.io/vanholtzco/pen/MWeVaaY?editors=1100

**Additional info:**
```
"browserslist": [
    "last 3 versions",
    "> 2%",
    "ie >= 11"
]
```

**Comment by ai** [comment]
Autoprefixer should not merge `column-width: 50%; column-count: 2;` to `columns: 50% 2;`

Maybe CSS minifier do it in your builder?

**Comment by vonscriptor** [comment]
Thank you—that's probably the actual issue. It's using CSSNano which I believe has a `mergeLonghand` option. I appreciate the quick reply!
