### ISSUE TITLE
Remove warning from grid-[column/row]-gap + grid-area combo

### ISSUE THREAD

**Issue by 75th** [postcss/autoprefixer#1371]
Similar to #1157, but also completely different. `grid-column-gap` affects the child grid, not the parent grid; it and `grid-area` have nothing to do with each other. But presumably because autoprefixer is looking for `grid-column-*` properties, it warns about it anyway:

```You already have a grid-area declaration present in the rule. You should use either grid-area or grid-column-gap, not both```

I think this should be removed.

**Comment by Dan503** [comment]
Ok yeah this is a valid bug.

It shouldn't be warning if using `grid-column-gap` (or `grid-row-gap`) in combination with `grid-area`.

The warning is more intended for uses of `grid-area` in combination with `grid-column`, `grid-column-start`, and `grid-column-end`.

We should be more specific when checking for a match when displaying the warning.

**Comment by ai** [comment]
Fixed 9c9107d

I will release it when we will find a solution for https://github.com/postcss/autoprefixer/issues/1369
