### ISSUE TITLE
User-Select: all is not supported in IE or Edge Legacy

### ISSUE THREAD

**Issue by coliff** [postcss/autoprefixer#1372]
Currently Autoprefixer `user-select: all` adds prefixes for IE and Edge Legacy with `-ms-user-select: all` - however, neither IE or Edge Legacy support this particular rule.

REF: https://caniuse.com/mdn-css_properties_user-select_all

It'd be good if Autoprefixer did not add `-ms-user-select: all` as it doesn't do anything.

**Comment by ai** [comment]
Thanks for the idea. Fixed e47d5db

I will release it after the Browserslist release.
