### ISSUE TITLE
clamp()

### ISSUE THREAD

**Issue by robsonsobral** [postcss/autoprefixer#1373]
Hi!

It's weird, but Safari until 2019-09 and iOS Safari until 2020-01 support `min()`, `max()`, but not `clamp()`.

[MDN web docs](https://developer.mozilla.org/en-US/docs/Web/CSS/clamp()) gives the necessary fallback:

> `clamp(MIN, VAL, MAX)` is resolved as `max(MIN, min(VAL, MAX))`

Is there a path to add this as a polyfill?

Thank you!

**Comment by ai** [comment]
https://github.com/postcss/autoprefixer#does-it-add-polyfills
