### ISSUE TITLE
PostCSS plugin autoprefixer requires PostCSS 8.

### ISSUE THREAD

**Issue by phoshenwen** [postcss/autoprefixer#1376]
"autoprefixer": "^10.0.2",
"gulp": "^4.0.2",
"gulp-postcss": "^9.0.0",

```
var autoprefixer = require('autoprefixer');
var postcss = require('gulp-postcss');

gulp.task('scss', function () {
    var stream = gulp
        .src('xxx',{sourcemaps:true})
        .pipe(sass())
        .pipe(postcss([autoprefixer()]))
        .pipe(gulp.dest(paths.css, {sourcemaps:true}));
    return stream;
});
```

Do I have to downgrade to postcss 8?

**Comment by ai** [comment]
`gulp-postcss` 9 supports PostCSS 8.

Call `npm install postcss`, new `gulp-postcss` requires you to have `postcss` in your own dependencies.

If it will not help, call `npm ls` to see who uses postcss 7.
