### ISSUE TITLE
Unknown event info in autoprefixer. Try to update PostCSS

### ISSUE THREAD

**Issue by thecrypticace** [postcss/autoprefixer#1379]
PostCSS 8.1.11 just released and now throws an error on unknown event types. It appears that the `info` event isn't supported and the presence of it now causes problems.

Should this be changed somehow or should PostCSS be updated to support it?

https://github.com/postcss/autoprefixer/blob/856a567b333b5c199613d28c89f33025c93a919f/lib/autoprefixer.js#L134-L140

**Comment by justnewbee** [comment]
i got this too today...
![image](https://user-images.githubusercontent.com/2276086/100956224-fccfcf80-3552-11eb-8cb6-9763cabea479.png)

**Comment by ai** [comment]
Fixed b3dbd91

**Comment by thecrypticace** [comment]
That was fast! 🎉

**Comment by ai** [comment]
The fix was released in PostCSS 8.1.12.

If you want to prevent out burning-out and keep our super-fast support, talk with your manager about [donating to PostCSS development](https://opencollective.com/postcss).

**Comment by GuttermanA** [comment]
Looks like that did the trick for me @ai. Thanks for the extremely fast turnaround.
