### ISSUE TITLE
Support for "@supports selector"

### ISSUE THREAD

**Issue by dvoytenko** [postcss/autoprefixer#1391]
The `@supports selector() {}` form is now supported in Chromium and Mozilla-based browsers. It'd be great if it was supported in PostCSS as well.

https://developer.mozilla.org/en-US/docs/Web/CSS/@supports

**Comment by ai** [comment]
What is the error message?

**Comment by dvoytenko** [comment]
"Unknown node type in node creation"

**Comment by ai** [comment]
PR is welcome. I am busy on another open-source project right now.

**Comment by cpmsmith** [comment]
It looks like this is specific to selectors starting with `:`, i.e. pseudo-classes and pseudo-elements.

```css
/* works: */
@supports selector(a) {}
/* throws error: */
@supports selector(:a) {}
```

**Comment by ai** [comment]
The fix by @Semigradsky was released in 10.2.5

**Comment by dvoytenko** [comment]
Thanks so much for the fix, @Semigradsky !

**Comment by itf2012** [comment]
I'm currently experiencing the issue mentioned by @KaelWD but i'm not seeing/understanding what the resolution is. Can anyone provide any guidance? Thanks.
