### ISSUE TITLE
Error: [object Object] is not a PostCSS plugin

### ISSUE THREAD

**Issue by HelloCandy0319** [postcss/autoprefixer#1392]
package.json file : "autoprefixer": "^10.2.4",  "postcss-loader": "^4.2.0",
运行 npm run build 打包命令，错误信息如下所示：Error: [object Object] is not a PostCSS plugin
![image](https://user-images.githubusercontent.com/38653822/106392110-5ce7d280-642b-11eb-82c2-801f2cbc692e.png)
![image](https://user-images.githubusercontent.com/38653822/106392124-6c671b80-642b-11eb-9eca-b1bdbff6ee4b.png)
百度后也没找到答案，去 postcss-loader 以及 autoprefixer GitHub 仓库查阅了一下用法，心想：可能是最新版本的用法或者写法发生了改变导致的。但是没有发现任何线索，于是就尝试将两个分别降级版本，得出结论：原来是 autoprefixer 插件版本太高导致的 postcss-loader 报错的问题，将 autoprefixer 从 10.2.4 降级到 9.7.3 版本就不会报错了。
![image](https://user-images.githubusercontent.com/38653822/106392150-8b65ad80-642b-11eb-9dce-754126b9dda0.png)

**Comment by ai** [comment]
Update AUtoprefixer to 10.

**Comment by HelloCandy0319** [comment]
postcss.config.js
```js
module.exports = {
  plugins: [
    require("autoprefixer")({
      // Error: Change `browserslist` option to `overrideBrowserslist` in Autoprefixer
      overrideBrowserslist: [
        "defaults",
        "not ie < 11",
        "last 2 versions",
        "> 1%",
        "iOS 7",
        "last 3 iOS versions",
      ],
    }),
  ],
};
```

**Comment by ai** [comment]
Also, remove `overrideBrowserslist` and create `.browserslistrc` with

```
defaults
not ie < 11
last 2 versions
> 1%
iOS 7
last 3 iOS versions
```

**Comment by HelloCandy0319** [comment]
According to your approach, the problem is indeed solved. I just only remove postcss.config.js file  and create .browserslistrc file, then the error is resolved.
But I want to konw why must remove postcss.config.js file?
There is no problem in using this way before, is it caused by the new version update?

**Comment by ai** [comment]
Maybe some strange cache problems.

PostCSS 8 should support Autoprefixer 9.

**Comment by HelloCandy0319** [comment]
Before a large package reported an error, I deleted postcss.config.js, and added a .browserslistrc file, just package it. Immediately afterwards, I deleted the .browserslistrc file, and created a new postcss.config.js file, copied and pasted the previous configuration, and it was all right. so amazing!
