### ISSUE TITLE
handle :is() :matches() :any()

### ISSUE THREAD

**Issue by dym-sh** [postcss/autoprefixer#1395]
as per https://developer.mozilla.org/en-US/docs/Web/CSS/:is

**Comment by ai** [comment]
What is the expected output for modern browsers?

**Comment by dym-sh** [comment]
> Support for forgiving selector list
only chrome and firefox

i guess, de-structuring each item within :is() into regular comma-separated rule is still the way to have most compatibility

**Comment by Semigradsky** [comment]
https://github.com/csstools/postcss-is-pseudo-class

https://github.com/IlyaUpyackovich/postcss-pseudo-is

**Comment by ai** [comment]
@dym-sh Autoprefixer is for prefixes, not for polyfills.

Use polyfills which @Semigradsky posted above.

**Comment by PixlRainbow** [comment]
I was expecting `:is()` to be expanded to prefixed selectors `:-webkit-any()` and `:-moz-any()` as indicated on [caniuse.com](https://caniuse.com/css-matches-pseudo)

**Comment by Semigradsky** [comment]
That makes sense.

**Comment by zouglou** [comment]
Hello, I don't get how this is not prefixes related? As stated by @PixlRainbow `:is()` should "prefixed" by `:-webkit-any()` and `:-moz-any()`, like any other prefixed CSS properties?

**Comment by ai** [comment]
> I was expecting :is() to be expanded to prefixed selectors :-webkit-any() and :-moz-any()

As I know, it is impossible. `is()` has a different specificity than `*-any()`.
