### ISSUE TITLE
Javascript - Pass location for `.browserslistrc` or `package.json` discovery

### ISSUE THREAD

**Issue by glenn2223** [postcss/autoprefixer#1399]
I was doing some testing in my package/vscode extension. 

It currently runs the below code

```JS
postcss(
    autoprefixer({
        overrideBrowserslist: browsers // <-- string[]
    })
).process(...)
```

I want to change it so, when I pass null, it picks up on the users `package.json` settings or `.browserslistrc` file

Obviously, autoprefixer has no idea where to search for these files so, when I do pass null, it just uses `"defaults"`

Rather than try and parse them myself I thought I can future proof and see if I can pass the file locations to autoprefixer

**Comment by ai** [comment]
You can use Browserslist env variables for that https://github.com/browserslist/browserslist#environment-variables

**Comment by ai** [comment]
There are two ways to set environment variables.

A good way is to set it in shell during the builder call:

```sh
BROWSERSLIST_DISABLE_CACHE=1 yarn build
```

Another, hacky way:

```js
process.env.BROWSERSLIST_DISABLE_CACHE = '1'
```

**Comment by glenn2223** [comment]
Ahh, so `env` is purely `BROWSERSLIST_ENV` 🤦‍♂️

Thanks

**Comment by glenn2223** [comment]
Hello, me again!

Rather than completely stopping caching, I thought I should try running `browserslist.clearCaches();` each time either a `package.json` or `.browserslistrc` is saved. However, autoprefixer doesn't seem to acknowledge this clearing.

Not a problem for now as I can still continue to hack it with `process.env.BROWSERSLIST_DISABLE_CACHE = '1';`. Just thought I should ask if this is something that can be supported/picked up on?

**Comment by glenn2223** [comment]
So it looks like the `Browserlists` cache is at a package level and not a global level.

I have forked this repo, did you want to review [the changes](https://github.com/postcss/autoprefixer/compare/main...glenn2223:main) before I submit a PR? Did you want me to open a separate issue with info?
