### ISSUE TITLE
webpack build TypeError: Cannot read property 'prefix_exceptions' of undefined

### ISSUE THREAD

**Issue by wanweiwang2012** [postcss/autoprefixer#1405]
npm upgrade
autoprefixer v10.2.4 -> v10.2.5

An error occurred:
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property 'prefix_exceptions' of undefined
    at Browsers.prefix (/Users/wanweiwang/Documents/zpparts/gits/zpparts-web/zp-buyer/node_modules/autoprefixer/lib/browsers.js:64:23)
    at /Users/wanweiwang/Documents/zpparts/gits/zpparts-web/zp-buyer/node_modules/autoprefixer/lib/prefixes.js:135:54

**Comment by ai** [comment]
Update `caniuse-lite`

**Comment by liveHarshit** [comment]
@wanweiwang2012 facing the same issue, let me know if you find any fix, thanks.

**Comment by wanweiwang2012** [comment]
> @wanweiwang2012 facing the same issue, let me know if you find any fix, thanks.

install and update caniuse-lite is ok

**Comment by liveHarshit** [comment]
Thanks, @ai @wanweiwang2012 it worked, it was due to workspace cache.

**Comment by wanweiwang2012** [comment]
> @wanweiwang2012 facing the same issue, let me know if you find any fix, thanks.

install and update  caniuse-lite  is ok
