### ISSUE TITLE
Cannot read property 'prefix_exceptions' of undefined

### ISSUE THREAD

**Issue by tsingksan** [postcss/autoprefixer#1406]
[You can find my environment here](https://github.com/lqsbznh/webpack)
![image](https://user-images.githubusercontent.com/68624192/117683436-a55f1b00-b1e6-11eb-8a2d-76a513aff5a8.png)

**Comment by Benamin** [comment]
`npm i caniuse-lite`
or
`npm update  caniuse-lite`

**Comment by ai** [comment]
The best way to update `caniuse-lite` to fix this issue:

```sh
npx browserslist@latest --update-db
```
