### ISSUE TITLE
width: stretch not expanding to width: -moz-available

### ISSUE THREAD

**Issue by sudofox** [postcss/autoprefixer#1422]
https://caniuse.com/?search=width%3A%20stretch

width: stretch is only producing:

```
width: -webkit-fill-available;
width: stretch;
```

I am expecting to also get

```
width: -moz-available
```

to support the latest version of Firefox per spec: https://developer.mozilla.org/en-US/docs/Web/CSS/width (stretch altname is -moz-available)

I am on
```
"autoprefixer": "^10.3.3",
```

**Comment by ai** [comment]
Fixed 089ac2f

**Comment by ai** [comment]
The fix was released in 10.3.4

**Comment by alexeymolchan** [comment]
Hi there. I think you have a regression bug.

`width: stretch` is producing for every browser:
`
width: -moz-available;
width: stretch;
`
`width: -webkit-fill-available` is missing for Chrome and Safari.

"autoprefixer": "^10.4.0".

**Comment by ai** [comment]
@alexeymolchan can you open a new issue with:

1. CSS input
2. CSS output
3. Expected output
4. Browserslist config and `npx browserslist --info` output

**Comment by alexeymolchan** [comment]
@ai sure - https://github.com/postcss/autoprefixer/issues/1441
