### ISSUE TITLE
Autoprefixer in PostCSS seems doesn't works

### ISSUE THREAD

**Issue by yourchoice** [postcss/autoprefixer#1423]
**Warning: [object Object] is not a PostCSS plugin Use --force to continue.**

```
postcss: {
	options: {
		processors: [										
			require(nmPathGlogal+'autoprefixer')({overrideBrowserslist: 'last 2 versions'}),					
		]				
	},		
	site: {
		src: '../dist/css/site/*.css'
	},
}
```

I get the above warning in grunt

**Comment by ai** [comment]
This error is coming when you use PostCSS 7 with PostCSS 8 plugin.

Update `gulp-postcss` to the latest version (and be sure that you are installed `postcss` to your `package.json` dependencies).
