### ISSUE TITLE
Map path is being duplicated

### ISSUE THREAD

**Issue by glenn2223** [postcss/autoprefixer#1437]
My VSCode extension uses autoprefixer, on it someone posted an issue - glenn2223/vscode-live-sass-compiler#135

I made a very basic sample - [zipped example](https://github.com/postcss/autoprefixer/files/7580865/Issue.135.zip)
 

Below is my code
```TS
const result = await prefixer.process(css, {
    from: filePath, // 'c:\\Users\\Glenn\\Documents\\GitHub\\TESTING\\vscode-live-sass-compiler\\Issue 135\\themes\\hold\\sass\\hold\\style.scss'
    to: savePath, // 'c:\\Users\\Glenn\\Documents\\GitHub\\TESTING\\vscode-live-sass-compiler\\Issue 135\\themes\\hold\\css\\style.css'
    map: {
        inline: false,
        prev: map,
    },
});

// REMOVED FOR BREVITY

return {
    css: result.css,
    map: generateMap ? result.map.toString() : null,
};
```

The inputs are as follows:
- CSS: `'.Test-Issue-135 {\n  color: pink;\n}'`
- MAP: `'{"version":3,"sourceRoot":"","sources":["../sass/hold/style.scss"],"names":[],"mappings":"AAAA;EACI","file":"file:///c:/Users/Glenn/Documents/GitHub/TESTING/vscode-live-sass-compiler/Issue%20135/themes/hold/sass/hold/style.css"}'`

And your outputs are:
- CSS: `'.Test-Issue-135 {\n  color: pink;\n}'`
- MAP: `'{"version":3,"sources":["../sass/sass/hold/style.scss","../sass/hold/style.scss"],"names":[],"mappings":"AAAA;EACI,WAAA;ACCJ","file":"style.css"}'`

As you can see it seems to be adding `"../sass/hold/style.scss"` again and changing it to `"../sass/sass/hold/style.scss"`

**Comment by ai** [comment]
Seems like `from` and `map.sources` is not valid.

What is arguments which you passed to Sass compiler to get this source map?

**Comment by glenn2223** [comment]
This is the data I'm providing to the sass compiler

![image](https://user-images.githubusercontent.com/33450392/142866223-9aa610a0-44ed-4f89-9493-3d635a8a0f93.png)

**Comment by ai** [comment]
The problem is that if you take `from` option and add `sassMap.source` to it, you will not get path to the Sass source.

It leads to sources duplication.

You need to fix paths, but I can’t help you where exactly is a mistake.

**Comment by glenn2223** [comment]
I'm sorry but I don't understand. From the docs, `from` is the source of the original file and `to` is the destination so `from` will never be navigable to any `sassMap.source`, whereas `to` will

**Comment by ai** [comment]
> From the docs, from is the source of the original file 

Origin file which you pass to PostCSS. Not origin file that you pass to Sass.

For your case it should be `sassMap.file`.

But Sass source map looks broken too. Try to add `sassMap.source` to `sassMap.file`, it will point to a wrong file.

Maybe you set a wrong root to Sass compiler.

**Comment by glenn2223** [comment]
Thanks for your help on this btw.

So it now doesn't add the duplicate invalid line but is adding a new source as the output file itself.

Map after SASS compilation: `'{"version":3,"sourceRoot":"","sources":["../sass/hold/style.scss"],"names":[],"mappings":"AAAA;EACI","file":"style.css"}'`

Map after autoprefixing: `'{"version":3,"sources":["../sass/hold/style.scss","style.css"],"names":[],"mappings":"AAAA;EACI,WAAA;ACCJ","file":"style.css"}'`

As you can see it's added `"style.css"` as a source and also added new mappings `,WAAA;ACCJ`

**Comment by ai** [comment]
Show example of input options to Sass and to PostCSS

**Comment by glenn2223** [comment]
Sass input

![image](https://user-images.githubusercontent.com/33450392/143075734-4dbd93a0-af14-4825-b256-4a8139fae412.png)

PostCSS input

```ts
const result = await prefixer.process(css, {
  from: savePath, //'c:\\Users\\Glenn\\Documents\\GitHub\\TESTING\\vscode-live-sass-compiler\\Issue 135\\themes\\hold\\css\\style.css'
  to: savePath, //'c:\\Users\\Glenn\\Documents\\GitHub\\TESTING\\vscode-live-sass-compiler\\Issue 135\\themes\\hold\\css\\style.css'
  map: {inline: false, prev: map,//'{"version":3,"sourceRoot":"","sources":["../sass/hold/style.Scss"],"names":[],"mappings":"AAAA;EACI","file":"style.css"}'
  },
});

```

**Comment by ai** [comment]
It could be because of the parts which was not marked by Sass in their source map.

Investigate both source map by https://sokra.github.io/source-map-visualization/

**Comment by glenn2223** [comment]
So the sourcemap provided by SASS gave me the below

![image](https://user-images.githubusercontent.com/33450392/143227909-ffa25e88-2d0b-41bb-97c6-56759784b749.png)

And the sourcemap after running it through PostCSS gave me this

![image](https://user-images.githubusercontent.com/33450392/143228507-673810aa-46e9-412b-9fa3-a8e058e33fe9.png)

It's like PostCSS is picking up on the commented map file reference and mapping it 🤷‍♂️

**Comment by ai** [comment]
Yeap, the problem is `}`. Sass doesn’t add mapping or it. This is why PostCSS doesn’t know where to map it and map to `style.css`.

**Comment by glenn2223** [comment]
Sorry, just so I'm clear. 

So you're saying that, technically, the map data that [sass/dart-sass](https://github.com/sass/dart-sass) is creating is invalid? Or should PostCSS be ignoring these "unknowns"

**Comment by ai** [comment]
> So you're saying that, technically, the map data that sass/dart-sass is creating is invalid?

Not. It is correct, but it is not full.

**Comment by glenn2223** [comment]
> Not. It is correct, but it is not full.

Is there a way of stopping PostCSS from guessing where these lines belong, causing unnecessary bloat to files?

**Comment by ai** [comment]
> Is there a way of stopping PostCSS from guessing where these lines belong, causing unnecessary bloat to files?

You can write a JS script which will clean source map.

But I suggest you to ignore this problem. We spend too many time for this small issue.
