### ISSUE TITLE
How to set AutoPrefixer to work only on files saving?

### ISSUE THREAD

**Issue by offirpeer** [postcss/autoprefixer#1443]
I would like auto prefixer to work **ONLY** when I save the document.
I didn't find that option yet.

I am asking because what happens in vscode is that every time I type all the prefixes jumps and it is very difficult to ctrl+z them because they are regenerated on keyup or keydown.

**Comment by ai** [comment]
Sorry, this repo is about Autoprefixer core.

For text editor plugin you need to go to a specific repository.

What text editor and what plugin for Autoprefixer do you use?

**Comment by offirpeer** [comment]
@ai 
I wasn't aware to that, I use VSCode and Autoprefixer v3.0.1.

**Comment by ai** [comment]
Here is a repo https://github.com/mrmlnc/vscode-autoprefixer
