### ISSUE TITLE
Build Failed: due to normalize-range package usage

### ISSUE THREAD

**Issue by codeeshop-oc** [postcss/autoprefixer#1447]
Issue 
Gradient JS file have used normalize-range package that generates build issues
https://github.com/postcss/autoprefixer/blob/main/lib/hacks/gradient.js#L2

Issue by Package
https://www.npmjs.com/package/normalize-range

![Screenshot from 2022-03-14 12-48-36](https://user-images.githubusercontent.com/54684361/158123406-efb45978-6ff7-4360-b5c1-add63f9d5855.png)

**Comment by ai** [comment]
This is Yarn registry error. Nothing I can do here.
