### ISSUE TITLE
Browserslist is outdated

### ISSUE THREAD

**Issue by Draghmar** [postcss/autoprefixer#1456]
Not sure how to deal with this issue:
![obraz](https://user-images.githubusercontent.com/275348/163976166-2003d3f3-6e23-4c02-9c20-0f40de874473.png)
Should I try to update Browserslist by myself or should I wait for Autoprefixer to get updated? And if it's the first one, how should I do it without risking screwing something? ;)

**Comment by ai** [comment]
You should ask the author of text editor to update Browserslist version in their bundle.

Autoprefixer Core uses the latest version from npm.

But when you are putting all dependencies to the bundle you are locking versions.
