### ISSUE TITLE
Type errors in autoprefixer.d.ts

### ISSUE THREAD

**Issue by ollar** [postcss/autoprefixer#1460]
Hello.
I am trying to add autoprefixer to our stencil project and added a clean configuration 

```
plugins: [
    postcss({
      plugins: [autoprefixer()]
    })
  ]
```

but typescript gives me the error below 

```
[stencil] [ ERROR ]  TypeScript: ./node_modules/autoprefixer/lib/autoprefixer.d.ts:6:4
[stencil]            Generic type 'Plugin<T>' requires 1 type argument(s).
[stencil] 
[stencil]       L5:    ...args: [...T, autoprefixer.Options]
[stencil]       L6:  ): Plugin & autoprefixer.ExportedAPI
[stencil] 
[stencil] [58:30.7]  build failed, watching for changes... in 1.95
```

any suggestions how to fix this?
Thanks.

**Comment by ai** [comment]
Try to update PostCSS to the latest version. Maybe you have old version with old types?

**Comment by ollar** [comment]
Thanks, that helped! I think I need to write an issue to `@stencil/postcss` repo
