### ISSUE TITLE
Please make remove this notification: " Replace color-adjust to print-color-adjust."

### ISSUE THREAD

**Issue by michaelrodov** [postcss/autoprefixer#1463]
Hi, can you please make this notification "Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated." as info or something but not a warning/error

This is 3rd level dependency for us and our build fails on CI because of this warning (warn > errors on CI)

Thanks

**Comment by ai** [comment]
> CI because of this warning

Change your CI settings config or fix the dependency.

By the nature, it is a warning. Changing text to `info` to fix CI is a treating the symptoms of the disease rather the source of the problem.

**Comment by michaelrodov** [comment]
We are using CRA, and there's no way to disable this behavior without setting CI=false which is wrong

**Comment by ai** [comment]
The whole idea of thinking that a warning is an error on CI is to be sure that your code doesn’t have any problem.

Using deprecated CSS properties is a problem.

Hiding this warning do not solve the problem.

Avoid broken 3rd level dependency. Or send PR with fix. It will solve the source of the problem.
