### ISSUE TITLE
1.4.7 color adjust issue added

### ISSUE THREAD

**Issue by Temepest74** [postcss/autoprefixer#1464]
Tailwind form had this issue with color-adjust which they fixed (https://github.com/tailwindlabs/tailwindcss/issues/8277). 
The error is back up in 1.4.7. The error is in the latest autoprefixer version, because 1.4.5 does not bring this error into the console.
![image](https://user-images.githubusercontent.com/28103890/170710798-ae33021d-720b-4691-8d82-2cd97b0d9a2f.png)

**Comment by ai** [comment]
Maybe you didn’t updated Tailwind to fixed version? Check the output sources (but disable css minification/cleaner first) for `color-adjust` properties.

**Comment by Temepest74** [comment]
It is updated 100% 
![image](https://user-images.githubusercontent.com/28103890/170717683-b5fe96c7-85eb-4c67-8538-a53da0ab46c4.png)
Beside this, I am not the only one having this issue, check [this ](![image](https://user-images.githubusercontent.com/28103890/170717767-4353c0fc-0682-4ccb-8906-c9204050b59c.png)) reply to my linked post.

I checked the output file and it has color-adjust in it
```
select{
    background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%236b7280' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M6 8l4 4 4-4'/%3e%3c/svg%3e");
    background-position: right 0.5rem center;
    background-repeat: no-repeat;
    background-size: 1.5em 1.5em;
    padding-right: 2.5rem;
    -webkit-print-color-adjust: exact;
       color-adjust: exact;
            print-color-adjust: exact;
}

[multiple]{
    background-image: initial;
    background-position: initial;
    background-repeat: unset;
    background-size: initial;
    padding-right: 0.75rem;
    -webkit-print-color-adjust: unset;
       color-adjust: unset;
            print-color-adjust: unset;
}

[type='checkbox'],[type='radio']{
    -webkit-appearance: none;
       -moz-appearance: none;
            appearance: none;
    padding: 0;
    -webkit-print-color-adjust: exact;
       color-adjust: exact;
            print-color-adjust: exact;
    display: inline-block;
    vertical-align: middle;
    background-origin: border-box;
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;
    flex-shrink: 0;
    height: 1rem;
    width: 1rem;
    color: #2563eb;
    background-color: #fff;
    border-color: #6b7280;
    border-width: 1px;
    --tw-shadow: 0 0 #0000;
}
```

This may be a problem from autoprefixer running twice, as stated at the end of this issue https://github.com/tailwindlabs/tailwindcss-forms/pull/115

**Comment by ai** [comment]
Autoprefixer do not add `color-adjust`.

Sorry, I can’t help with environment problems. You need to dig into it on your own.
