### ISSUE TITLE
Cannot find module 'caniuse-lite/data/features/css-unicode-bidi' in autofixer 10.2.4

### ISSUE THREAD

**Issue by SJ4372** [postcss/autoprefixer#1477]
We are getting following error in angular builds.

- Angular version - 11.x
- Angular Cli - 11.x

> An unhandled exception occurred: Cannot find module 'caniuse-lite/data/features/css-unicode-bidi'
> Require stack:
> - \node_modules\autoprefixer\data\prefixes.js
> - \node_modules\autoprefixer\lib\autoprefixer.js
> - \node_modules\@angular-devkit\build-angular\src\webpack\configs\styles.js
> - \node_modules\@angular-devkit\build-angular\src\webpack\configs\index.js
> - \node_modules\@angular-devkit\build-angular\src\browser\index.js
> - \node_modules\@angular-devkit\build-angular\src\dev-server\index.js
> - \node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
> - \node_modules\@angular-devkit\architect\node\index.js
> - \node_modules\@angular\cli\models\architect-command.js
> - \node_modules\@angular\cli\commands\serve-impl.js
> - \node_modules\@angular-devkit\schematics\tools\export-ref.js
> - \node_modules\@angular-devkit\schematics\tools\index.js
> - \node_modules\@angular\cli\utilities\json-schema.js
> - \node_modules\@angular\cli\models\command-runner.js
> - \node_modules\@angular\cli\lib\cli\index.js
> - \node_modules\@angular\cli\lib\init.js
> - \node_modules\@angular\cli\bin\ng
> See "\Temp\ng-Hc0kTy\angular-errors.log" for further details.

**Verified with downgraded "caniuse-lite@1.0.30001393", builds are working.** 

But this has potential to create issue in autofixer versions before latest 10.4.9 as the "css-unicode-bidi" file deletion changes done in "caniuse-lite" are available in patch version  instead of minor/major version upgrade.

Any suggestions to fixing this issue other than manually downgrading  to  "caniuse-lite@1.0.30001393" ?

**Comment by igun997** [comment]
same issues !

**Comment by nicholaszuccarelli** [comment]
Please refer to:
https://github.com/postcss/autoprefixer/issues/1476
https://github.com/postcss/autoprefixer/issues/1475

Fix was released in Autoprefixer 10.4.9.

**Comment by gch116620** [comment]
I found the previous version , download and unzip , find the css-unicode-bidi.js file, and copy it to the node_modules/caniuse-lite/data/features/

**Comment by ai** [comment]
Dublicate https://github.com/postcss/autoprefixer/issues/1475
