### ISSUE TITLE
Gradient has outdated direction syntax. New syntax is like `closest-side at 0 0` instead of `0 0, closest-side

### ISSUE THREAD

**Issue by ColbyMay** [postcss/autoprefixer#1482]
Using radial-gradient, recieving a new syntax warning to move to 'at' 

```
.example{   

background: radial-gradient(100% 200%, rgba(color) 0,rgba(color) 15%, rgba(color) 30%, $black300 30%);

}
```

'at' is not supported by Safari yet for radial-gradient's?

[ radial-gradient's Can I Use](https://caniuse.com/mdn-css_types_image_gradient_radial-gradient_at)

**Comment by ai** [comment]
You may want to add some CSS polyfill for Safari. Maybe `postcss-preset-env` does it?

**Comment by ColbyMay** [comment]
Thanks for this. 
The issue was directed to the wrong repo. 
Closing now.
