### ISSUE TITLE
What configuration is needed for `background-clip: text`

### ISSUE THREAD

**Issue by DenizUgur** [postcss/autoprefixer#1486]
Regarding the issue with #1081, I don't seem to get the `-webkit-` prefix. The browserslist I'm using is `>0.1%, defaults`. Am I missing something?

**Comment by ai** [comment]
You need to select very very old versions mentioned here
https://caniuse.com/background-img-opts

**Comment by DenizUgur** [comment]
What do you mean by that? Can you give an example?

**Comment by ai** [comment]
According to https://autoprefixer.github.io/ `last 1 chrome versions` will be enough

**Comment by DenizUgur** [comment]
Perfect, thank you.
