### ISSUE TITLE
`dvh` fallback

### ISSUE THREAD

**Issue by nsaunders** [postcss/autoprefixer#1490]
A hack people use for [`100dvh`](https://caniuse.com/?search=dvh) is to create a fallback declaration, e.g.

```css
height: 100dvh;
height: 100vh;
```

It doesn't look like Autoprefixer currently supports this. Would there be any interest?

**Comment by ai** [comment]
No. Since it is not a prefix. You may ask `postcss-present-env` developers for sort of polyfill.
