### ISSUE TITLE
@supports rules need autoprefixing

### ISSUE THREAD

**Issue by neave** [postcss/autoprefixer#150]
[@supports rules](http://dev.opera.com/articles/view/native-css-feature-detection-via-the-supports-rule/) aren't autoprefixed, as far as I can tell. For example:

```
@supports (transform: translateZ(0)) {
    /* etc. */
}
```

should be prefixed into something like this:

```
@supports (-webkit-transform: translateZ(0)) or
          (-moz-transform: translateZ(0)) or
          (transform: translateZ(0)) {
    /* etc. */
}
```

**Comment by michael7213** [comment]
i want a new atmosphere on star atlas https://staratlas.com/ https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRaonFqUZRsOGV55mL_ocRCJzUct3cx07Gc7-gAxcSWnzcjePG6

**Comment by michael7213** [comment]
https://staratlas.com/ please improve the atmosphere i want a new https://youtu.be/YZWgOYobygo the link of youtube of atmosphere i m ansious to see the time lapse side to side
