### ISSUE TITLE
Prefix apparance: none

### ISSUE THREAD

**Issue by SuperPat45** [postcss/autoprefixer#1508]
Autoprfixer does not prefix `apparance: none;` to:
```
-moz-appearance: none;
-webkit-appearance: none;
appearance: none;
```
for browsers older than Firefox 80, Chrome 84, Opera 73, and Safari 15.4

`-webkit-appearance` is also recognized in Firefox since version 64, `-moz-appearance:` required for older versions.

Other values (like `apparance: auto;`) may be prefixed for a very small number of versions (only Chrome 83 and Opera 70, 71, 72) according:

https://developer.mozilla.org/en-US/docs/Web/CSS/appearance#browser_compatibility

**Comment by ai** [comment]
Is it a problem in Can I Use data?
