### ISSUE TITLE
Unexpected vendor prefix "::-moz-placeholder"

### ISSUE THREAD

**Issue by r3dDoX** [postcss/autoprefixer#1512]
We noticed in our output that we see autoprefixer adding `::-moz-placeholder` vendor prefix when it does not seem to be necessary by the browsers we selected. I tried it on the Playground by using the `defaults` browsers and input:

```
::placeholder {
  color: red;
}
```

The output I get is this:

```
/*
* Prefixed by https://autoprefixer.github.io
* PostCSS: v8.4.14,
* Autoprefixer: v10.4.7
* Browsers: defaults
*/

::-moz-placeholder {
  color: red;
}
::placeholder {
  color: red;
}
```

As far as I can see, this placeholder vendor prefix should not be added, no selected browser needs this. Or am I missing something?

**Comment by ai** [comment]
It will be missed on `last 1 FF version` Browserslist.

Seems like Autoprefixer adds it because of Firefox ESR.
