### ISSUE TITLE
Threshold for dropping "mixed support" warnings?

### ISSUE THREAD

**Issue by knulpi** [postcss/autoprefixer#1513]
I was wondering what the threshold is for a value to not be considered as `mixed support` anymore. Taking as example the 6 year-old [mixed-support-warning for using `start/end` instead of `flex-start/flex-end`](
https://github.com/postcss/autoprefixer/blob/90dc18d7201608ccf1a02aba476feec28f60257e/lib/processor.js#L154). The support for `start/end` is marked as 94% across browsers based on [caniuse.com](https://caniuse.com/mdn-css_properties_justify-content_flex_context_start_end).

I personally would consider this not being a case of "mixed support" anymore, but is there any rule for this?

**Comment by ai** [comment]
It was a bigger problem a few years ago. But still is good advice since 6% is still more 6% for free.

If we have no reasons to remove it, I prefer to keep it.

**Comment by knulpi** [comment]
But as the [CSS Box Alignment Module Level 3](https://www.w3.org/TR/css-align/) is to be the new baseline for these values, wdyt about making the warning a bit more verbose?

Something like "'end' value might not be supported in older browsers, consider using legacy 'flex-end' for broader support (see https://caniuse.com/mdn-css_properties_justify-content_flex_context_start_end for supported browsers).

**Comment by ai** [comment]
We can remove the warning if you will present me rational reasons why `end` could be better than `flex-end`.

**Comment by knulpi** [comment]
I got new input on this. While I thought that the `flex-` versions are equivalents, they aren't actually. The behaviour is different, based on the `flex-direction` property, as can be seen in [this codepen](https://codepen.io/rachelandrew/pen/KKmazZR).

So this is even a better reason to reword/remove the warning, as this is not only a topic of mixed support, but also of different/unintended behavior.

**Comment by ai** [comment]
Good reason. I will disable warning today.

**Comment by ai** [comment]
Done https://github.com/postcss/autoprefixer/commit/fe7bae45970d38eee86c4d26e5f19fa100df3039

Thanks for good arguments.
