### ISSUE TITLE
`width: fit-content` receives an unnecessary `-moz-fit-content` prefix

### ISSUE THREAD

**Issue by stof** [postcss/autoprefixer#1520]
```css
.example {
    width: fit-content
}
```

With this CSS and a browserslist config of `last 4 versions`, autoprefixer generates a `width: -moz-fit-content` declaration.
But Firefox supports the unprefixed declaration since Firefox 94 (and latest version is 128): https://developer.mozilla.org/en-US/docs/Web/CSS/min-width#browser_compatibility

**Comment by ai** [comment]
The fix ee43652

But note, that you will need `-moz-` for KaiOS.

**Comment by ai** [comment]
The fix was released in 10.4.20.

Please consider tell your company to support open source.
