### ISSUE TITLE
Flexbox bug in Safari with possible fix and workaround

### ISSUE THREAD

**Issue by orloxx** [postcss/autoprefixer#1522]
Autoprefixer: 9.2.1

The autoprefixer takes this code:

```
display: flex;
```

And it compiles it by adding the vendor prefixes first and then it adds the original property, like this:

```
// renders vendor properties first
display: -webkit-box;
display: -ms-flexbox;
// And original property last
display: flex;
```

## The issue

[Here](https://codesandbox.io/p/sandbox/tytlgy?file=%2Fsrc%2FApp.tsx%3A50%2C18) I created a Sandbox to better demonstrate the problem I found in Safari (it's probably a browser bug).

By having the vendor prefixes before the original one, Safari for some reason compiles `flex` as valid, even though it seems they don't support it. They support `-webkit-box` instead, and that works.

### First solution

Be able to swap the order of vendor prefixes:

```
display: flex;
display: -webkit-box;
display: -ms-flexbox;
```

This fixes the issue (as you can see in the sandbox by clicking on the button "Open modal (Fix)")

### Workaround

Without having to change the way autoprefixer works, there's a workaround by specifically defining the full `flex: 1 0 auto` behavior in the child element with the problem:

```
flex: 1; // <--- problem
flex: 1 0 auto; // workaround
```

This also fixes the issue and doesn't require any change from the autoprefixer.

## Proposed new option

Is it possible to add an option to swap the order the vendor properties are compiled so they appear after the original property?

Apologies beforehand if this is out-of-scope.

**Comment by ai** [comment]
> By having the vendor prefixes before the original one, Safari for some reason compiles flex as valid, even though it seems they don't support it

Modern Safari doesn’t need prefixes for flexbox. Why do you think they don’t support it?

Safari support it since version 8, the latest version is 18 https://caniuse.com/?search=flexbox

**Comment by orloxx** [comment]
It seems it's a bug in Safari. They do support `display: flex`. But in this particular case they don't do it as expected (as demonstrated in the sandbox). There's also a workaround by changing the `flex` property in the child element.

I guess it doesn't make sense to make this change just because of Safari having this issue. Thanks for looking into it anyway.
