### ISSUE TITLE
Autoprefix background-clip and text-fill-color?

### ISSUE THREAD

**Issue by leoj3n** [postcss/autoprefixer#156]
Preface: Not sure if this is an "issue" or something you care to implement. Just something I notice while testing.

Using this trick: http://css-tricks.com/snippets/css/gradient-text

Autoprefixer isn't adding prefixes (`-webkit-`) to `background-clip` and `text-fill-color`.

http://caniuse.com/#search=background-clip
http://caniuse.com/#search=text-fill-color

```
background: linear-gradient(#eee, #333);
background-clip: text;
text-fill-color: transparent;
```

Is currently prefixed as:

```
background: -webkit-linear-gradient(#eee, #333);
background: linear-gradient(#eee, #333);
background-clip: text;
text-fill-color: transparent;
```

Should be prefixed as:

```
background: -webkit-linear-gradient(#eee, #333);
background: linear-gradient(#eee, #333);
-webkit-background-clip: text;
background-clip: text;
-webkit-text-fill-color: transparent;
text-fill-color: transparent;
```

**Comment by nickensoul** [comment]
There is 2017 now and I just want to show you this:
![screenshot at mar 28 13-32-48](https://cloud.githubusercontent.com/assets/14836054/24400990/318e7234-13bb-11e7-9c39-93eae4feb5ed.png)
It works in Firefox 52.0.1 (x64), but not in Safari 10.0.3, Safari still needs vendor prefixed `background-clip: text`.

**Comment by ai** [comment]
I am on conference right now. Ping me in Friday if I will forget to look into it.

**Comment by wzup** [comment]
`background-clip` doesn't work. 
The issue was raised in 2013. Now there is September 2017 `background-clip` doesn't work

**Comment by jeerbl** [comment]
Any news on when this could be done?

**Comment by benjarwar** [comment]
Repro'd in Chrome as well.
