### ISSUE TITLE
Transform property actually not working?

### ISSUE THREAD

**Issue by mismith** [postcss/autoprefixer#223]
Not a typo like #198, but same behaviour. Any ideas? Using the version built-in to CodeKit 2

This does not get auto-prefixed in any way:

```
.arrow {
    transform: rotate(90deg);
}
```

**Comment by murpy** [comment]
The very same problem here, Codekit 2.0.5 running Autoprefixer 1.1.20140319

**Comment by ai** [comment]
Maybe you dod not need prefixes for `transform` at all? http://caniuse.com/#search=transform
