### ISSUE TITLE
autoprefixer drop linear-gradient prefixed with -ms

### ISSUE THREAD

**Issue by magsout** [postcss/autoprefixer#226]
```
$ autoprefixer -v
autoprefixer 1.1.20140319
$ autoprefixer style.css
```

input : 

```
.bg {
 background-image: -ms-linear-gradient(to top, #000 50%, #fff 50%);
}

```

Result:

```
.bg{
}
```

**Comment by zba** [comment]
> Yes it's why I closed that issues. Microsoft unprefixed gradient when IE 10 was released.. 

It is strange, doesn't autoprefixer made to autoprefix ? if I set `browsers: ['ie >6']`  I expect to support IE>6 and not IE>10 ... please reopen.

**Comment by iamvdo** [comment]
@zba: IE before 10 never implement `linear-gradient`, even prefixed. That's why it's closed.

**Comment by zba** [comment]
but why it  removes
` background-image: -ms-linear-gradient(to top, #000 50%, #fff 50%);`

with 'revome: true' than ?

**Comment by ai** [comment]
@zba set `remove: false` if you didn’t want to remove properties.

**Comment by zba** [comment]
i understand, but this will also  leave other prefixes which not need, why it touch something that it not supports.

**Comment by ai** [comment]
@zba What Autoprefixer versions do you use?

[Interactive demo](http://simevidas.jsbin.com/gufoko/quiet) dooesn’t remove `-ms-linear-gradient` without `linear-gradient` below;
