### ISSUE TITLE
display: inline-flex not translated correctly for WebKit browsers using the 2009 spec

### ISSUE THREAD

**Issue by ghost** [postcss/autoprefixer#238]
When targeting `'last 2 versions', '> 5%', 'ie >= 9', 'ff >= 17', 'chrome >= 10', 'safari >= 6', 'ios >= 6'`, the declaration `display: inline-flex` was translated to:

```
display: -webkit-inline-flex;
display: -ms-inline-flexbox;
display: inline-flex;
```

I would have expected `display: -webkit-inline-box` to be included as well.

**Comment by gavindawson3825** [comment]
Thank you so much..signed up on git hub just to thank you, saved me from a lot of trouble..
