### ISSUE TITLE
Add support for old IE gradients

### ISSUE THREAD

**Issue by jhned** [postcss/autoprefixer#240]
When using Autoprefixer, I expected this:

```
background: linear-gradient(to bottom, #000 0%, #fff 100%);
```

to become this: 

```
background: #000000; /* Old browsers */
background: -moz-linear-gradient(top, #000000 0%, #ffffff 100%); /* FF3.6+ */
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#000000), color-stop(100%,#ffffff)); /* Chrome,Safari4+ */
background: -webkit-linear-gradient(top, #000000 0%,#ffffff 100%); /* Chrome10+,Safari5.1+ */
background: -o-linear-gradient(top, #000000 0%,#ffffff 100%); /* Opera 11.10+ */
background: -ms-linear-gradient(top, #000000 0%,#ffffff 100%); /* IE10+ */
background: linear-gradient(to bottom, #000000 0%,#ffffff 100%); /* W3C */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#000000', endColorstr='#ffffff',GradientType=0 ); /* IE6-9 */
```

But even with the browser string of "last 6 versions, Explorer >= 7, Firefox ESR, Opera 12.1," I'm not getting filter support for IE 6-9. I also didn't see anything about filter support in the source files.

Am I running into a browser string issue here, or does Autoprefixer not support simple gradients for IE6-9?

**Comment by Grawl** [comment]
so do you know any postcss processor to do that? `cssgrace` seems to do nothing with gradients.

**Comment by ai** [comment]
@Grawl nope, maybe @yisibl can help?

**Comment by yisibl** [comment]
@ai About IE old version, some of the characteristics that I don't have much to support its current plan.

**Comment by mehas** [comment]
https://www.npmjs.com/package/postcss-filter-gradient
