### ISSUE TITLE
Proposed improvements for flex fallbacks

### ISSUE THREAD

**Issue by jasonkuhrt** [postcss/autoprefixer#25]
After reading different articles on the topic, I've begun to summarize the ways to fallback the flex spec.

![screen shot 2013-05-16 at 10 47 17 pm](https://f.cloud.github.com/assets/284476/516126/49b8cd6e-be9c-11e2-964d-253a303f8f7b.png)

I will make a PR that implements as much as I can.

Of particular difficulty is `flex-grow` `flex-shrink` and `flex-basis`. To have these fallback we need to assign the flex shorthand for `-ms-` but that seems dubious since we cannot assume the three individual properties are all coming from one selector. It also appears impossible to support shrink and basis in the 2009 spec. In short it doesn't seem like there is a way to provide fallback for the grow/shrink/basis properties.

**Comment by jamie-pate** [comment]
Just curious, where did you get the table that is shown at the top of this issue?

**Comment by jasonkuhrt** [comment]
@jamie-pate I made it. I researched various articles, like 5 or so at the time.

**Comment by jamie-pate** [comment]
It looks very comprehensive, I was hoping there was an online source i could bookmark ;) (sometimes i want to tweak the autoprefixer output, and there's no good sites i could find that have a 'caniuse' style for the old flexbox (android 4.3 still uses it :( )

**Comment by jasonkuhrt** [comment]
@jamie-pate Ah ok. Well lucky you can bookmark this issue if its helpful you : )
