### ISSUE TITLE
HTML5 Input range styling

### ISSUE THREAD

**Issue by jasonkuhrt** [postcss/autoprefixer#279]
It seems that autoprefixer could help here.

When styling HTML5 range input we have various pseudo selectors:

```
::-webkit-slider-thumb
::-moz-range-thumb
::-moz-range-track
```

I haven't done the careful research about how to maximize compatibility etc. and other possible selectors, but just wanted to first get this out and see if there's something to be done or not.

**Comment by fabb** [comment]
[`postcss-input-range`](https://github.com/jonathantneal/postcss-input-range) does the trick.

**Comment by ai** [comment]
Are we sure about unprefixed version?

**Comment by Dan503** [comment]
It looks like the plugin fabb linked doesn't output any unprefixed code in the final CSS.

It seems to introduce it's own syntax and split it into the various browser specific prefixes. It removes it's proprietary CSS from the output.

FYI, this is a good thing. It means that the pseudo selectors fabb used could still be turned into a real W3C spec one day.
