### ISSUE TITLE
add docs about what is not autoprefixed

### ISSUE THREAD

**Issue by timaschew** [postcss/autoprefixer#337]
currently there is a note that `appearance` is not autoprefixed [here](https://github.com/postcss/autoprefixer#why-doesnt-autoprefixer-support-appearance)

but there are some more or is this a bug for these prefixes?

```
-webkit-overflow-scrolling: touch;
-webkit-box-align: center;
display: -webkit-box;
```

I

**Comment by felquis** [comment]
Hi @ai, `overflow-scrolling: touch` isn't prefixed with `-webkit-`..

I use
```js
autoprefixer({ browsers: ['last 4 versions']})
```

**Comment by ai** [comment]
Does this property is a standard property or WebKit only thing?

**Comment by felquis** [comment]
@ai I don't know, looks lile a Safari thing https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariCSSRef/Articles/StandardCSSProperties.html#//apple_ref/css/property/-webkit-overflow-scrolling

from https://developer.mozilla.org/pt-BR/docs/Web/CSS/-webkit-overflow-scrolling

thanks

**Comment by ai** [comment]
@felquis sorry, we don’t support complete non-standard properties, because there is no `overflow-scrolling`, only `-webkit-overflow-scrolling`.
