### ISSUE TITLE
Support text-align-last

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#372]
http://www.w3.org/TR/css3-text/#text-align-last-property

```
Value:	auto | start | end | left | right | center | justify
```
IE must be set:  `text-align: justify` and not support `start | end` value.

## DOC

* MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/text-align-last
* webplatform: http://blogs.adobe.com/webplatform/2014/02/25/improving-your-sites-visual-details-css3-text-align-last/
* MSDN: http://msdn.microsoft.com/en-us/library/ie/ms531163%28v=vs.85%29.aspx

## Browser support

IE: 5.5+
Chrome: 35+ (chrome://flags/#enable-experimental-web-platform-features)
Firefox: 12 + `-moz`
Opera:  22+
Safari: No

**Comment by ai** [comment]
I created PR to Can I Use https://github.com/postcss/autoprefixer/issues/372

**Comment by ai** [comment]
Fixed https://github.com/postcss/autoprefixer-core/commit/993a2a50b5fb8898595b1ccd172125805b559f69
