### ISSUE TITLE
Support object-fit/object-position

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#373]
http://caniuse.com/#feat=object-fit

MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit
          https://developer.mozilla.org/en-US/docs/Web/CSS/object-position

Opera 10.6 - 12.1 `-o`

**Comment by ai** [comment]
What prefixes it needs? Opera 11.60 is very old.

**Comment by yisibl** [comment]
Opera 10.6 - 12.1 -o

This is before the Opera switch kernel, we need to support it.

**Comment by ai** [comment]
Done https://github.com/postcss/autoprefixer-core/commit/26d0c8f18380508725f417eed0562f288e117deb
