### ISSUE TITLE
Add all support the properties list document

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#374]
You can open the wiki page.

**Comment by ai** [comment]
Yeap, nice idea. Riht now you can use [this coffee file](https://github.com/postcss/autoprefixer-core/blob/master/data/prefixes.coffee).

**Comment by yisibl** [comment]
If no caniuse property?What should we do?

**Comment by ai** [comment]
Create Can I Use pagw first

**Comment by ai** [comment]
I added link to README

**Comment by yisibl** [comment]
All right.
https://github.com/postcss/autoprefixer/wiki/support-list
