### ISSUE TITLE
Support text-emphasis

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#375]
-webkit-text-emphasis

http://momdo.s35.xrea.com/web-html-test/CSS3-memo/text-emphasis.html

**Comment by ai** [comment]
I will need some links to send Can I Use PR

**Comment by yisibl** [comment]
https://github.com/Fyrd/caniuse/pull/854#issuecomment-70790160

**Comment by yisibl** [comment]
https://github.com/postcss/autoprefixer-core/commit/46cc1ece3aae44e41916b41545f69d84db10ba7f

**Comment by ai** [comment]
@yisibl can you please send PR next time? I miss this commit and add them to Autoprefixer Rails :(.
