### ISSUE TITLE
Firefox don't support intrinsic & extrinsic sizing

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#377]
Firefox doesn't support:

`height: -moz-min-content` or `height: min-content`

Include the following properties:
* height
* min-height
* max-height

Test: http://yisibl.github.io/css3test/#css3-sizing

**Comment by ai** [comment]
So because this is a bug, we decide to do not remove prefixes. One unncecessary prefix is not a problem and maybe it will be fixed in next version.

**Comment by yisibl** [comment]
Like this problem: https://github.com/postcss/autoprefixer-core/commit/5ee3de82bdc5e143378849233914e2ebaeb63b38
