### ISSUE TITLE
flex-basis generate  wrong property for ie10

### ISSUE THREAD

**Issue by JackZhang1988** [postcss/autoprefixer#378]
I use flex-basis property in my Ipad project, i found that the autoprefixer transform this property to -ms-flex: 0 1 flexbasiswidth, and this cause layout problem in ie10.

The reason is autoprefixer set the -ms-flex-positive to 0, but should 1 in default, i don't understand why should set this property to 0. 

I fixed this problem by setting -ms-flex:1 manually in my css file. but i want to know it's that really bug in autoprefixer or something wrong in my code.

**Comment by ai** [comment]
Can you show small input example and what outbut you you want? (I think I miss something)
