### ISSUE TITLE
-webkit-gradient for list-style and list-style-image

### ISSUE THREAD

**Issue by ai** [postcss/autoprefixer#379]

**Comment by yisibl** [comment]
Properties:
* list-style
* list-style-image
* content

**Comment by ai** [comment]
Done https://github.com/postcss/autoprefixer-core/commit/ebea4335b46d65910714d902d8c41d89d31de4de

@yisibl we should add prefix for old WebKit (`-webkit-gradient(linear`) or new one (`-webkit-linear-gradient`) too? Can you investigate it before 5.0 release?

**Comment by yisibl** [comment]
## Legacy webkit syntax 
Chrome 4-9, Safari 4

The syntax is as follows:

-webkit-gradient(<type>, <point> [, <radius>]?, <point> [, <radius>]? [, <stop>]*)

You can use gradients in the following places:

* background-image
* border-image
* list-style-image
* content property

## Legacy from syntax (without to)

Chrome 10.0 (534.16) - 25, Safari 5.1

## See also

*https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient#Browser_compatibility
