### ISSUE TITLE
Autoprefixing and stacking browser-specific pseudo-selectors

### ISSUE THREAD

**Issue by FranzSkuffka** [postcss/autoprefixer#383]
http://stackoverflow.com/questions/2610497/change-an-inputs-html5-placeholder-color-with-css

convert

*:input-placeholder {
color: red;
}

to

::-webkit-input-placeholder {
color: red;
}
*:-moz-placeholder {
/ FF 4-18 /
color: red;
}
*::-moz-placeholder {
/ FF 19+ /
color: red;
}
*:-ms-input-placeholder {
/ IE 10+ */
color: red;
}

**Comment by ai** [comment]
Already supported by `::placeholder`
