### ISSUE TITLE
Support text-overflow

### ISSUE THREAD

**Issue by Justineo** [postcss/autoprefixer#387]
Opera used `-o-text-overflow` in versions 9 & 10 according to [caniuse.com](http://caniuse.com/#search=text-overflow).

**Comment by yisibl** [comment]
Done! https://github.com/postcss/autoprefixer-core/commit/a37e2d2e310f2064222b1f6993e673cfaa53f6f4

Thank you for your feedback. :+1:

**Comment by ai** [comment]
Released today in 5.1
