### ISSUE TITLE
Jekyll Installation Instructions

### ISSUE THREAD

**Issue by ajkochanowicz** [postcss/autoprefixer#388]
Linking to https://github.com/ixti/jekyll-assets/issues/67#issuecomment-70160216

I'm having trouble getting this to work with Jekyll. I wonder if there is a bit more to your instructions as I don't see where autoprefixer actually runs against the CSS file.

I've added `jekyll-assets` and `autoprefixer-rails` to my Gemfile and bundled. Is that really it?

Do I still run `bundle exec jekyll serve` as usual?

**Comment by ai** [comment]
You should ask in Jekyll team. I am really don’t use it, so I have no idea :).
