### ISSUE TITLE
Return autoprefixer.default

### ISSUE THREAD

**Issue by ai** [postcss/autoprefixer#389]
https://github.com/postcss/autoprefixer-core/issues/26

**Comment by ai** [comment]
@simevidas  Done. https://github.com/postcss/autoprefixer-core/commit/f444e4a816cd68e4d411b868af09fdaa14acbcf8

But I rename them to `defaults` instead of old `default`. To use same name as in Browserslist.

**Comment by lydell** [comment]
Don’t you mean: @sindresorhus?

**Comment by ai** [comment]
Oops. Yeap, I mean @sindresorhus :)

**Comment by ai** [comment]
@sindresorhus released today in 5.1

**Comment by sindresorhus** [comment]
I know. Thanks. Already updated atom-autoprefixer.
