### ISSUE TITLE
Extra lines with prefixes

### ISSUE THREAD

**Issue by docentq2** [postcss/autoprefixer#390]
Applied to the input:

    @-webkit-keyframes preloader__motion {
      to {
        -webkit-transform: rotate(360deg);
      }
    }
    @keyframes preloader__motion {
      to {
        transform: rotate(360deg);
      }
    }

Output:

    @-webkit-keyframes preloader__motion {
      to {
        -webkit-transform: rotate(360deg);
      }
    }
    @keyframes preloader__motion {
      to {
        -webkit-transform: rotate(360deg); /* this line is superfluous  */
        transform: rotate(360deg);
      }
    }

There have line is superfluous, and if there will be a lot of lines that css file will grow strongly.

**Comment by MoOx** [comment]
Maybe you should translate to english since the project is mainly written/documented in english.
That would help.

**Comment by docentq2** [comment]
@MoOx ok. I done. Is that better? :)

**Comment by MoOx** [comment]
Yep :)

**Comment by ai** [comment]
Autoprefixer adds prefix to unprefixed keyframes, because Chrome may stop to support `-webkit-keyframes` before `-webkit-transform`. Or it may fix some logic in unprefixed version.

**Comment by docentq2** [comment]
@ai thanks :)
