### ISSUE TITLE
Command not appearing in Atom command menu

### ISSUE THREAD

**Issue by smlombardi** [postcss/autoprefixer#391]
I am using Atom .174 and AP 2.2.0 for Atom.

Create a simple CSS file, like
````
.foo {
  -moz-border-radius: 4px;
  border-radius: 4px
}
````
Bring up the command palette, type auto...  no autoprefixer anywhere.

**Comment by MoOx** [comment]
This property was using prefix before Firefox v4. We are now at v35. So it's just useless & autoprefixer remove it. 
What do you expect?

**Comment by smlombardi** [comment]
I know that's an unneeded prefix, I just tried to type a very fast example.

What I am saying is that Autoprefixer does not show in the command palette.  Not for this file, not for complex files. That's my issue.

**Comment by MoOx** [comment]
That's probably a atom-autoprefixer issue https://github.com/sindresorhus/atom-autoprefixer

**Comment by smlombardi** [comment]
Thanks, I thought that's the repo I was in.  Sorry.
