### ISSUE TITLE
Autoprefixer breaks sourcemaps on compass

### ISSUE THREAD

**Issue by bl4ckdu5t** [postcss/autoprefixer#392]
When the following is added to the config.rb of a compass project:
```ruby
require 'autoprefixer-rails'
on_stylesheet_saved do |file|
  css = File.read(file)
  File.open(file, 'w') do |io|
    io << AutoprefixerRails.process(css)
  end
end
```
and the same config.rb has a 
```ruby
sourcemap = true
```
The sourcemap fails to display in Chrome but when the autoprefixer is commented out, it works perfect again

**Comment by ai** [comment]
Because you use some old code for Autoprefixer. [New one](https://github.com/postcss/autoprefixer#compass) has special map support.
