### ISSUE TITLE
CLI Documentation Errors

### ISSUE THREAD

**Issue by bdkjones** [postcss/autoprefixer#393]
There are several errors in the CLI documentation (the text that shows up when you run `autoprefixer -h`)

## Error 1

The `-h` docs indicate that there is a `--no-inline` option. In fact, if you open `binary.js`, you'll see that the name of this option is `--no-inline-map`. 

## Error 2

The description for `--no-map-annotation` says "skip source map annotation comment is CSS", but should be: "skip source map annotation comment in CSS".

## Ambiguous Sources-Content Description

the `--no-sources-content` option is unclear. If Autoprefixer overwrites the origin CSS file with the new, prefixed CSS file, why would this option be any use? The origin CSS file now IS the output file, how can it be included in the sources-content array for the source map?

Are these options meaningless if the input and output filepaths are the same?

**Comment by ai** [comment]
Done 38c1f06

I change ` --no-map-annotation` description to “do not add source map annotation comment in CSS”. Is it become more clear?
