### ISSUE TITLE
-ms- prefixed flex props removed

### ISSUE THREAD

**Issue by cazala** [postcss/autoprefixer#397]
autoprefixer is removing all my -ms- prefixed flex properties:

before:

```
.flex-auto {
-webkit-flex: auto;
-ms-flex: 1 1 auto;
flex: auto;
}
```

after: 

```
.flex-auto  {
-webkit-flex: auto;
flex: auto;
}
```

**Comment by ai** [comment]
Autoprefixer doesn’t remove `-ms-` on default set of browsers. You can try fresh Autoprefixer in [interactive demo](http://simevidas.jsbin.com/gufoko/quiet).

What browsers you select for Autoprefixer?

**Comment by cazala** [comment]
Sorry, it was my mistake, I used autoprefixer generated by yeoman's generator-angular 0.9.5, which targets browsers: ['last 1 version'], I wasn't aware of this feature of autoprefixer, I changed it to ['last 2 versions'] and now it works fine on IE 10 (with all the `-ms-` prefixed properties). Thank you!

**Comment by ai** [comment]
I recommended to use default browsers (just remove `browsers` option)
