### ISSUE TITLE
autoprefixer and autoprefixer-cli

### ISSUE THREAD

**Issue by ai** [postcss/autoprefixer#402]
Maybe we should a rename npm packages in some future major release:

* `autoprefixer-core` will become `autoprefixer`
* `auoprefixer` will become `autoprefixer-cli`

Reasons: 

* Now Autoprefixer with PostCSS requires long `-core`.
* Many users doesn’t know what repo they should uses for issue.
* New names is more semantic.

**Comment by ai** [comment]
I think we will not have many problems with migration because CLI is not very popular and `autoprefixer` JS API is same as `autoprefixer-core`.

**Comment by lydell** [comment]
+1

**Comment by yisibl** [comment]
+1

**Comment by ai** [comment]
Should we release a `autoprefixer-core` 6.0 gag?

```js
throw 'Use autoprefixer instead of autoprefixer-core';
```

**Comment by lydell** [comment]
No need to break anything. Just show a deprecation message and let it work like before.

**Comment by ai** [comment]
But they can miss warning and will wait next updates :)

**Comment by lydell** [comment]
They can miss the 6.0 update too.

**Comment by ai** [comment]
Why they will miss it. They will run `npm update` and will receive error. So they will update `package.json` and will be good.

**Comment by lydell** [comment]
You can `npm deprecate` it and I think that `npm update` will tell you so then.

**Comment by ai** [comment]
`npm update` will print warning, which can easy missed because of many warnings from some native package.

**Comment by ai** [comment]
I think to remove `autoprefixer` CLI in 6.0, because we will have `postcss-cli`

**Comment by bfred-it** [comment]
As a confused user of point 2, :+1: to this. Much clearer now.

**Comment by tjconcept** [comment]
> I think to remove `autoprefixer` CLI in 6.0, because we will have `postcss-cli`

I really think "plugins" should be developed as if they weren't plugins. That way they aren't tied to some framework that might become outdated some day or is simply not required for the task at hand.

**Comment by ai** [comment]
First step was finished: https://github.com/postcss/autoprefixer-core/commit/2ed21515f40beefac9d90e2295fb5674d7af2ea8

**Comment by ai** [comment]
Old CLI will be left too, but on different name and with non-official status https://github.com/ai/autoprefixer-cli

**Comment by ai** [comment]
Done. Project was merged.
