### ISSUE TITLE
Add support for -webkit-clip-path in transition

### ISSUE THREAD

**Issue by bfred-it** [postcss/autoprefixer#407]
`clip-path` and `transition` are supported, but `transition: clip-path` is not.

## Test input

```js
    a {
        clip-path: polygon(0 0, 0 10px, 10px 10px, 10px 0);

        transition: clip-path 1s;
    }
```

## Current output (5.1.0)

```js
    a {
        -webkit-clip-path: polygon(0 0, 0 10px, 10px 10px, 10px 0);
                clip-path: polygon(0 0, 0 10px, 10px 10px, 10px 0);

        -webkit-transition: clip-path 1s;

                transition: clip-path 1s;
    }
```

## Expected output

```js
    a {
        -webkit-clip-path: polygon(0 0, 0 10px, 10px 10px, 10px 0);
        clip-path: polygon(0 0, 0 10px, 10px 10px, 10px 0);

        -webkit-transition: -webkit-clip-path 1s;
        -webkit-transition: clip-path 1s;
        transition: -webkit-clip-path 1s; //maybe?
        transition: clip-path 1s;
    }
```

**Comment by ai** [comment]
What of this properties should be in `transition` too?

```js
'clip-path', 'mask', 'mask-clip', 'mask-composite', 'mask-image', 'mask-origin', 'mask-position', 'mask-repeat', 'mask-size'
```

**Comment by ai** [comment]
I add to `transition` this peroperties: `clip-path`, `mask`, `mask-position`, `mask-size` https://github.com/postcss/autoprefixer-core/commit/ef331f1dc8f60695a3aa9fc5900072859c2bd331

**Comment by ai** [comment]
Released in 5.1.5.

**Comment by bfred-it** [comment]
Whoah! Fast! Thanks

**Comment by qgustavor** [comment]
As `transition` allows invalid proprieties the second transition is overwriting the first one, even if a property isn't recognized. Example: in `a{transition: color 1s; transition: foo 1s;}` color isn't transitioned as `transition` is overwritten.

Here is also a image showing how browsers interpret @bfred-it snippet and a possible solution:

![Image showing how Chrome interprets the CSS rules and a possible soluton](https://i.imgur.com/f8jURPf.png?1)

As you can see in the suggestion both properties are in transition. In this way browsers will ignore properties they don't recognize while still transitioning the others.
