### ISSUE TITLE
Deactivate one css property from prefixing.

### ISSUE THREAD

**Issue by philipisik** [postcss/autoprefixer#408]
Hi,

is it possible to deactivate one css property from prefixing globally e. g. in the grunt configuration? In my case I don't want that autoprefixer prefixes the css property flexbox for any browser. Thank you for your help.

cheers

Philip

**Comment by ai** [comment]
There is no config for it.

Tell my why you wan’t prefixes for flexbox and maybe I can suggest you a solution.

**Comment by ai** [comment]
You can disable Autoprefixer in some file or rule by `/* autoprefixer: off */` comment https://github.com/postcss/autoprefixer#disabling

**Comment by philipisik** [comment]
Hi, thank you for your quick response. I know `/* autoprefixer: off */`, but I've to update existing scss files and it's stupid monkey work to put this comment manually before each flexbox property in a lot of files ;-)

But thank you again for your help!

Cheers Philip

**Comment by ai** [comment]
But why you doesn’t need prefix for flexbox?

**Comment by philipisik** [comment]
Safari has a flex bug while using flexbox for sticky footer with unkown height and because the latest Safari is using vendor prefix, I don't want a -webkit prefix.

**Comment by ai** [comment]
But it is only a one `-webkit- old` prefix. There is also `-ms-`, `-moz-` and `-webkit- new` prefix :).

**Comment by ai** [comment]
I think we can fix yoour sitiation with unlimited power of [PostCSS](https://github.com/postcss/postcss). Lets write a small custom PostCSS plugin to remove `-webkit- old` prefixes.

Autoprefixer is a PostCSS plugin too. So you can execute Autoprefixer and your plugin together in `gulp-postcss` or `grunt-postcss`.

```js
postcss([
    require('autoprefixer'),
    require('./safari-no-flexbox')
]);
```

`safari-no-flexbox.js` will looks like:

```js
module.exports = function (css) {
    css.eachDecl('display', function (decl) {
        if ( decl.value  == '-webkit-box' ) decl.removeSelf();
    });
    css.eachDecl('-webkit-box-ordinal-group', function (decl) {
        decl.removeSelf();
    });
    css.eachDecl('-webkit-box-flex', function (decl) {
        decl.removeSelf();
    });
    css.eachDecl('-webkit-box-orient', function (decl) {
        decl.removeSelf();
    });
    css.eachDecl('-webkit-box-direction', function (decl) {
        decl.removeSelf();
    });
    css.eachDecl('-webkit-box-pack', function (decl) {
        decl.removeSelf();
    });
    css.eachDecl('-webkit-box-align', function (decl) {
        decl.removeSelf();
    });
};
```

**Comment by philipisik** [comment]
Man, that's awesome :-D Thank you so much for your help!

**Comment by paazmaya** [comment]
This is great example. Could it be incorporated to the `autoprefixer` documentation?

**Comment by ai** [comment]
@paazmaya does Safari flexbox removing is a common task?

**Comment by simevidas** [comment]
@philipisik You’re having trouble with the old `-webkit-` flexbox features? But don’t the new features override the old ones? E.g. 

```css
display: -webkit-box;
display: -webkit-flex;
display: -ms-flexbox;
display: flex
```

Is `display: -webkit-box;` causing issues? Isn’t it overridden by `display: -webkit-flex;` in modern Safari?

**Comment by paazmaya** [comment]
@ai perhaps not specifically the given Safari use case, but it would demonstrate the simplicity of adding such a method.

**Comment by paazmaya** [comment]
@simevidas The order of the prefixes matters. The last one understood by Safari will be used, hence it is better to remove the old one all together, in order to avoid any mistakes.

**Comment by simevidas** [comment]
@paazmaya I see. Since Autoprefixer generates prefixes in the correct order, no further edits are needed, and this issue can only be caused by prefixed that were already in the source code before applying Autoprefixer, in which case it seems logical to run the custom plugin *before*, instead of after:

```js
postcss([
    require('autoprefixer'),
    require('./safari-no-flexbox')
]);
```

**Comment by brookjordan** [comment]
I'd really like to be able to disable autoprefixer for `transition-*` properties.

Right now, `transition` is only a nice-to-have and if a browser doesn't support it unprefixed, I'm fine for it not to have it.
Having to convert all of my `transition-property` properties to `transition` is going to make complex transition overrides even more complex 😖

**Comment by ai** [comment]
Just write custom PostCSS plugin to remove prefixed transitions and run it after Autoprefixer. It will be 8 LOC.

**Comment by BB-000** [comment]
I'm trying to add a similar plugin (remove -ms-flexbox prefixes) to my grunt task but can't get it working from this or https://github.com/postcss/autoprefixer/issues/107 example
'Fatal error: postcss.eachDecl is not a function'

postcss-no-ms-flex.js

`    module.exports = function (css) {    

          css.eachDecl('display', function (decl) {
            if ( decl.value  == '-ms-flexbox' ) decl.removeSelf();
    });
    css.eachDecl('-ms-flex', function (decl) {
        decl.removeSelf();
    });
    css.eachDecl('-ms-flex-align', function (decl) {
        decl.removeSelf();
    });
    css.eachDecl('-ms-flex-item-align', function (decl) {
        decl.removeSelf();
    });
    css.eachDecl('-ms-flex-direction', function (decl) {
        decl.removeSelf();
    });
    css.eachDecl('-ms-flex-wrap', function (decl) {
        decl.removeSelf();
    });
};`

Gruntfile.js

`  postcss: {
      options: {

           processors: [
                   require('autoprefixer')({browsers: 'last 2 versions'}),
                   require('./postcss-no-ms-flex')
            ]
        },
...
},`

How can I get this to work? Thanks!

**Comment by ai** [comment]
@BB-000 first function receives plugin option, not `css`. It should return a function, receives`css`.

```js
var postcss = require ("postcss")
module.exports = postcss.plugin("ms-flexbox-cleaner", function () {
  return function (css) {
    // write your plugin here
  }
}
```

**Comment by BB-000** [comment]
Amazing thanks for quick reply!

Problem was I was using old functions, i swapped 

```
css.eachDecl('display', function (decl) {
    if ( decl.value  == '-ms-flexbox' ) decl.removeSelf();
});
```
for
```
css.walkDecls('display', function (decl) {
    if ( decl.value  == '-ms-flexbox' ) decl.remove();
});
```

👍

**Comment by carlokid** [comment]
> I'd really like to be able to disable autoprefixer for `transition-*` properties.
> 
> Right now, `transition` is only a nice-to-have and if a browser doesn't support it unprefixed, I'm fine for it not to have it. Having to convert all of my `transition-property` properties to `transition` is going to make complex transition overrides even more complex 😖

Have you fixed this?
