### ISSUE TITLE
translate3d into translate if the third argument equals 0

### ISSUE THREAD

**Issue by sladex** [postcss/autoprefixer#409]
`translate` value for css `transform` property has slightly better support than `translate3d` (Android 2.3, Opera 12, IE9).
Would it make sense to add `translate` version before `translate3d` if the third argument equals `0`?
eg.
```css
transform: translate3d(50px, 20px, 0);
```
```css
transform: translate(50px, 20px);
transform: translate3d(50px, 20px, 0);
```
Or am I missing something?

**Comment by ai** [comment]
If you want to make 2D transformation, why you use `translate3d`? O_o

Write `translate` directly:

```css
a {
    transform: translate(50px, 20px);
}
```

**Comment by jbelfodil** [comment]
it would actually make sense for the retro compatibility and avoid this kind of fix :

**Comment by ai** [comment]
PR is welcome ;-)

**Comment by ben-eb** [comment]
If these values are indeed equivalent, why do you need to specify the `transform: translate3d(-50%, -50%, 0)` at all? If you can just write the shorter syntax, a PR would be welcome for https://github.com/ben-eb/postcss-reduce-transforms. :smile:

**Comment by jbelfodil** [comment]
because de translate3d is more efficient for compatible browsers (use of the GPU)

Thx for your answer :)

**Comment by ai** [comment]
It is not effective. Creating a new layout (it is reason of better performance, not GPU) uses much more memory. So it is technically trade-off CPU vs. RAM.

**Comment by ai** [comment]
BTW, to force creating new layout you can set `backface-visibility: none`.

**Comment by jbelfodil** [comment]
true :)
