### ISSUE TITLE
SASS solid strings causing 'unknown word' error

### ISSUE THREAD

**Issue by tctc91** [postcss/autoprefixer#410]
See this http://stackoverflow.com/questions/27314697/sass-compiler-custom-rules-exceptions/27315081#27315081 question of what I'm trying to do.

This works great in SASS but autoprefixer gives me the following errror:

Autoprefixer failed to process the CSS file. It returned this error message: autoprefixer:/Users/xx/custom.css:119:16: Unknown word
right: 0;
background: {theme="header"};
^
width: 100%;

**Comment by ai** [comment]
You try to send Sass file to Autoprefixer? [PostCSS](https://github.com/postcss/postcss) (it is inside Autoprefixer) works with CSS.

Compile Sass before Autoprefixer or use PostCSS [simple-vars](https://github.com/postcss/postcss-simple-vars) plugin.

**Comment by tctc91** [comment]
I'm using the default setup in CodeKit...

**Comment by ai** [comment]
@tctc91 write to CodeKit author. Autoprefixer can’t work with Sass.
