### ISSUE TITLE
[npm install -g] CLI tool should use stdout

### ISSUE THREAD

**Issue by NHQ** [postcss/autoprefixer#419]
Usually a CLI tool like this will default to spitting the results of the operation through stdout.  

Autoprefixer rewrites the users file.  That is bad form.

With stdout, I would be able to do:
```
$ autoprefixer style.css > site.css  
```
Which writes the stdout to a file (site.css).  Or I could pipe the results to another program...

**Comment by NHQ** [comment]
This also sux for editing the CSS again, now with prefixes everywhere.  but it doesn't matter, cuz autoprefixer won't rewrite pre-prefixed rules!

**Comment by ai** [comment]
`autoprefixer` CLI will be deprecated in 5.1 and will be replaced to `postcss-cli` in 6.0.

I will use your semantic in `postcss`cli`.
