### ISSUE TITLE
Excluding browser prefixes

### ISSUE THREAD

**Issue by alebelcor** [postcss/autoprefixer#42]
This is more of a question/feature request.

Is there a way to exclude browsers (and their prefixes)?

Say, to prefix considering the latest two versions of browsers, but leave out Opera prefixes completely.

``` javascript
autoprefixer.compile(css, ['last 2 version', '!opera']);
```

Awesome tool by the way. Thank you.

**Comment by thiemeljiri** [comment]
I still think it is a good idea to disable prefixing of selected properties in configuration.
Is it possible now, four years later?
Thanks.

**Comment by ai** [comment]
@thiemeljiri it is possible with writing small custom PostCSS plugin:

```js
root.walkDecls(prop, decl => decl.remove())
```

But I don’t recommend it. Why you should remove prefix if you support this browser. This behaviour will be unexpected for new developers.

**Comment by thiemeljiri** [comment]
I've found that it's possible to disable old flexbox properties in options. This was my main issue, because the old specification was very different and mot using it is better than breaking the layout for such browsers. If I'll think find another problematic property, I'll let you know.

I'm glad you made grid prefixing disabled by default. No need for that, plus it's basically impossible.

**Comment by ai** [comment]
@thiemeljiri Autoprefixer fixes most of flexbox spec difference (it is a smart tool, not just prefix injector). There are only a few rare and small things not covered.

Also, [check 7.2 changelog](https://github.com/postcss/autoprefixer/releases/tag/7.2.0), Autoprefixer is really smart about grid prefixes as well (even `grid-template-areas` are covered). We don’t cover `grid-gap`, if you will remember it and will emulate it with `padding` you can use same Grid for IE as well.

**Comment by thiemeljiri** [comment]
I don't want to prefix grid at all. That's not necessary and not recommended.

As for flexbox, browsers supporting the old -webkit-box syntax do not support wrapping which is a huge stopper why not to use it in many cases and not break the site for the users. Not perfect layour is still 1000x more better than broken layout often with inaccessible content.

Profressive enhancement is the way. What you just wrote me about the obscure things you do with grid, I don't like this approach. Not in 2018. If someone wants to use grid, using it with some fallback (usually flexbox) is still necessary, except for micro pages. And using @supports for the grid definitions and related styling is just enough and the recommend approach. But this option is disabled by default which is great.

Anyway thanks a lot for your precious time.
