### ISSUE TITLE
BROWSERSLIST environment variable not honored

### ISSUE THREAD

**Issue by moll** [postcss/autoprefixer#420]
Hey,

According to the Browserslist module, the `BROWSERSLIST` environment variable is checked for the config file location. It doesn't seem to work with at least the `autoprefixer` executable when called with `-i` for info. Haven't tried other invocation ways.

```sh
BROWSERSLIST=config/browserslist ./node_modules/.bin/autoprefixer -i
```

**Comment by ai** [comment]
`BROWSERSLIST` environment variable stores browsers, not config path. I will add better examples, when I will deprected `autoprefixer` CLI in 5.1 release.

**Comment by moll** [comment]
Ah, okay. Thanks. I guess I'll make another suggestion in the browserslist project as I find clogging up the project root is a little shabby. ;-)
