### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by ai** [postcss/autoprefixer#422]
PostCSS 4.1 will have Messages API and Auutoprefiser should use it. We need to create warning on:

* [x] Wrong direction syntax in gradient.
* [x] Old `::placeholder` selector.
* [x] `display: box`
* [x] `crisp-edges`

**Comment by MoOx** [comment]
This will be very nice !
You can also add info messages when autoprefixer removes some useless prefixed stuff ;)

**Comment by ai** [comment]
@MoOx I want this warning too (specially om removing -ms-border-radius is this kind of non-existent things) :). But many developers uses CSS from libraries and they will not have a interface to hide some warnings. So by default we should show warning about broken CSS or abouut Auutoprefixer’s stuff.

But maybe we can add `warningOnRemove` options.

**Comment by MoOx** [comment]
That's why I were suggesting simple messages (info) not warning ;)
I think by default (without a verbose option or something like a logLevel (default to warning)) we won't show the simple message (nor debug one ;))

**Comment by yisibl** [comment]
This will be very nice !

**Comment by ai** [comment]
Warning for `::placeholder` is ready https://github.com/postcss/autoprefixer-core/commit/54dab9f3cd045c89d3e965f7d7d61f810ea513f7

**Comment by ai** [comment]
`display: box` is ready too https://github.com/postcss/autoprefixer-core/commit/1fef5d75cbbd9210f2053fb447fcc6e5f54ef0e2

**Comment by ai** [comment]
`image-rendering: crisp-edges` was finished too https://github.com/postcss/autoprefixer-core/commit/804c4d14ddc6d19778f78f6432bca1464c918e81

**Comment by ai** [comment]
Gradient warnings is ready too https://github.com/postcss/autoprefixer-core/commit/cb600e551dcb9c1eac2ed9283c6cc7e18e8c9dbd
