### ISSUE TITLE
multiple backgrounds

### ISSUE THREAD

**Issue by CarlosJeurissen** [postcss/autoprefixer#423]
Autoprefixer doesn't autoprefix linear-gradient if used as a second background:
background: url("logo.png"), linear-gradient(#fff, #000);

**Comment by ai** [comment]
I can’t reproduce it. Try on [Autoprefixer demo](http://simevidas.jsbin.com/gufoko/quiet).

**Comment by ai** [comment]
I make tests better https://github.com/postcss/autoprefixer-core/commit/71cbf0fefe9e482dae01f2c0e825674f9b83d303
