### ISSUE TITLE
_filter causes syntax error in output.

### ISSUE THREAD

**Issue by kassens** [postcss/autoprefixer#424]
I use the webpack loader and some third party CSS I use contains:

```css
.example {
  _filter: chroma(color=red);
}
```

This gets transformed to

```css
.example {
  _-webkit-filter: chroma(color=red);
  _        filter: chroma(color=red);
}
```

where the stray `_` causes a syntax error in a later webpack step. The `_` hack should probably remain in front of declarations.

**Comment by ai** [comment]
Do you use `_` hack to prevent property on IE?

You can disable cascade to fix your case by `autoprefixer({ cascade: false })`.
