### ISSUE TITLE
How to use CSS logical directional properties

### ISSUE THREAD

**Issue by askmatey** [postcss/autoprefixer#425]
Let's assume, I am using a css file with a `-moz-margin-left` property.

How should I configure autoprefixer, to transform the property to `-webkit-margin-left` (see #324) automatically ?

**Comment by askmatey** [comment]
Well, it does not work because the recommended [grunt plugin](https://github.com/nDmitry/grunt-autoprefixer) has not updated the dependency, see grunt-autoprefixer#99

**Comment by ai** [comment]
Nope. Autoprefixer only adds prefixes for unprefixed versions.
