### ISSUE TITLE
IE 10 issues with rem in font property

### ISSUE THREAD

**Issue by jwhitley** [postcss/autoprefixer#427]
A heads-up on an issue I just filed on caniuse: IE 10 doesn't support rem in the shorthand `font` property, but does in the individual `font-*` properties.  I'm calling this out as it's an odd case and I'm unsure whether there's precedent in autoprefixer for this kind of syntactic break-out.

Details at Fyrd/caniuse#915.

(In other news, autoprefixer rocks. :heart:)

**Comment by ai** [comment]
Autoprefixer is not for polyfills. It is only for prefixes.

But you can do `font` prooperties unpack by [PostCSS](https://github.com/postcss/postcss).

Code will be like:

```js
function (css) {
    css.eachDecl('font', function (decl) {
        var props = unpackFont(decl);
        for ( var prop in props ) {
            decl.cloneBefore({ prop: prop, value: props[prop] });
        }
    });
};
```

Autoprefixer is just a PostCSS plugin too, so it is very easy to build your own “autoprefixer”.

**Comment by jwhitley** [comment]
Nice, thanks for both the scope clarification and the example.
