### ISSUE TITLE
multiple backgrounds webkit error

### ISSUE THREAD

**Issue by nwtn** [postcss/autoprefixer#429]
(Cross-posted from https://github.com/nDmitry/grunt-autoprefixer/issues/103. Note that this is a different issue than #423.)

I'm getting an error with `-webkit-gradient` syntax when using multiple backgrounds.

Input:

````
background-image: linear-gradient(transparent, transparent), url('/img/arrow-right.svg');
````

Output:

````
background-image: -webkit-gradient(linear, left top, left bottom, from(transparent), color-stop(transparent)), to(url('/img/arrow-right.svg'));
background-image: -webkit-linear-gradient(transparent, transparent), url('/img/arrow-right.svg');
background-image: -moz-linear-gradient(transparent, transparent), url('/img/arrow-right.svg');
background-image: -o-linear-gradient(transparent, transparent), url('/img/arrow-right.svg');
background-image: linear-gradient(transparent, transparent), url('/img/arrow-right.svg');
````

That first like is wrong. I believe it should be:

````
background-image: -webkit-gradient(linear, left top, left bottom, from(transparent), to(transparent)), url('/img/arrow-right.svg');
````

As is, it's generating this error in CSS Lint:

````
WARNING: Expected end of value but found 'to(url('/img/arrow-right.svg'))'. Properties should be known (listed in CSS3 specification) or be a vendor-prefixed property. (known-properties) Browsers: All
````

**Comment by ai** [comment]
I will start to solve this issue only after Wednesday. Sorry about it, but this issue is not critical and I have not even a weekend because of my workshop :(.

If I will not answer anything after Wednesday, feel free to ping me again.

**Comment by nwtn** [comment]
No problem. Thanks.

**Comment by ai** [comment]
I can’t reproduce it. You can check your self in [interactive demo](http://simevidas.jsbin.com/gufoko/quiet).

I think you have issue because of:

* Maybe you use old Autoprefixer. I remember, that I fix gradient parameter splitter.
* Maybe some ither CSS tool make this issue?
