### ISSUE TITLE
Character encoding at-rule in css from sass breaks sourcemap

### ISSUE THREAD

**Issue by JacobDorman** [postcss/autoprefixer#430]
A unicode character in SCSS causes libsass to add ```@charset "UTF-8";``` to the CSS. The sourcemap works correctly.

After running through autoprefixer, the new sourcemap points at the CSS instead of the SCSS.

```
body {
  background: #BADA55;
  /*  ≠  */
}
```

```grunt-sass@0.18.1``` ```grunt-postcss@0.3.0``` with ```autoprefixer-core@5.1.8```

https://github.com/nDmitry/grunt-autoprefixer/issues/88

**Comment by ai** [comment]
Can you put here sources and map files.

**Comment by JacobDorman** [comment]
*scss:*
```
body {
  background: #BADA55;
  /*  ≠  */
}
```

--> **grunt-sass@0.18.1**

*pre.css*
```
@charset "UTF-8";
body {
  background: #BADA55;
  /*  ≠  */ }

/*# sourceMappingURL=pre.css.map */
```

*pre.css.map:*
```
{
	"version": 3,
	"file": "pre.css",
	"sources": [
		"../app.scss"
	],
	"sourcesContent": [],
	"mappings": "AAAA;EACE,AAAY",
	"names": []
}
```

--> **grunt-postcss@0.3.0** with **autoprefixer-core@5.1.8**

*app.css*
```
@charset "UTF-8";
body {
  background: #BADA55;
  /*  ≠  */ }
/*# sourceMappingURL=app.css.map */
```

*app.css.map* (unminified)
```
{
  "version": 3,
  "sources": [
    "../app.scss",
    "pre.css"
  ],
  "names": [],
  "mappings": "AAAA,kBAAA;ACCA;EACE,qBAAoB;EACpB,UAAS,EAAE",
  "file": "app.css"
}
```

**Comment by JacobDorman** [comment]
https://github.com/JacobDorman/libsass-autoprefixer-test/compare/master...works?diff=split&name=works

**Comment by ai** [comment]
@JacobDorman I mean zip file with all file inside :).

But maybe you can help me. Can you check output CSS and maps by [source map vizializer](http://sokra.github.io/source-map-visualization/). Click “Custom…”, select all necessary files, and pt link with base64 here.

**Comment by JacobDorman** [comment]
I'll check out source map visualizer, but that repo contains a minimal test case with css and map output committed, as well as the node dependencies.

[master branch](https://github.com/JacobDorman/libsass-autoprefixer-test/tree/master) produces the broken sourcemap: 
[works branch](https://github.com/JacobDorman/libsass-autoprefixer-test/tree/works) produces a correct sitemap: 

You can see a comparison of app.scss -> pre.css pre.css.map -> app.css app.css.map by [Comparing the Branches](https://github.com/JacobDorman/libsass-autoprefixer-test/compare/master...works?diff=split&name=works)

```
1. git clone git@github.com:JacobDorman/libsass-autoprefixer-test.git or [Download Zip](https://github.com/JacobDorman/libsass-autoprefixer-test/archive/master.zip)
2. grunt sass
3. grunt postcss #broken sitemap
4. git checkout works
5. grunt sass
6. grunt postcss #working sitemap
```

**Comment by JacobDorman** [comment]
Visualizer results:

[Without unicode character]http://sokra.github.io/source-map-visualization/#base64,Ym9keSB7CiAgYmFja2dyb3VuZDogI0JBREE1NTsgfQovKiMgc291cmNlTWFwcGluZ1VSTD1hcHAuY3NzLm1hcCAqLw==,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uL2FwcC5zY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBO0VBQ0UscUJBQVksRUFBQSIsImZpbGUiOiJhcHAuY3NzIn0=,Ym9keSB7CiAgYmFja2dyb3VuZDogI0JBREE1NTsKfQo=)

[With Unicode Character](http://sokra.github.io/source-map-visualization/#base64,QGNoYXJzZXQgIlVURi04IjsKYm9keSB7CiAgYmFja2dyb3VuZDogI0JBREE1NTsKICAvKiAg4omgICAqLyB9Ci8qIyBzb3VyY2VNYXBwaW5nVVJMPWFwcC5jc3MubWFwICov,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uL2FwcC5zY3NzIiwicHJlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQSxrQkFBQTtBQ0NBO0VBQ0UscUJBQW9CO0VBQ3BCLFVBQVMsRUFBRSIsImZpbGUiOiJhcHAuY3NzIn0=,Ym9keSB7CiAgYmFja2dyb3VuZDogI0JBREE1NTsKICAvKiAg4omgICAqLwp9Cg==,QGNoYXJzZXQgIlVURi04IjsKYm9keSB7CiAgYmFja2dyb3VuZDogI0JBREE1NTsKICAvKiAg4omgICAqLyB9CgovKiMgc291cmNlTWFwcGluZ1VSTD1wcmUuY3NzLm1hcCAqLw==)

Both times the site prompts for "Provide original source file "../app.scss"" but the second (broken) time it then asks for "Provide original source file "pre.css":". The sourcemap shouldn't be referencing the intermediate css file.

**Comment by ai** [comment]
It is a Sass issue https://github.com/postcss/postcss/issues/308
