### ISSUE TITLE
-webkit- prefix is not being added for transform properties on Safari

### ISSUE THREAD

**Issue by tomoguisuru** [postcss/autoprefixer#431]
When using the default options, ['> 1%', 'last 2 versions', 'Firefox ESR', 'Opera 12.1'], the -webkit- prefix is not being applied to css transform properties for Safari which according to CanIUse, http://caniuse.com/#feat=transforms2d, are still required

Here are two example where I'm seeing this with the included -webkit- stub I had to include

```
  .vertically-centered {
    transform-style: preserve-3d;
    -webkit-transform-style: preserve-3d; // manually added for Safari

    > div {
      position: relative;
      top: 50%;
      transform: translateY(-50%);
      -webkit-transform: translateY(-50%); // manually added for Safari
    }
  }
```

**Comment by ai** [comment]
Everything fine in [interactive demo](http://simevidas.jsbin.com/gufoko/quiet).

Are you sure, that you run Autoprefixer in right way? Why you CSS example contains nesting?

**Comment by mattandrews** [comment]
I'm seeing this too.
