### ISSUE TITLE
How can i autoprefix inline styles

### ISSUE THREAD

**Issue by tlightsky** [postcss/autoprefixer#433]
I want to use this with facebook vjeux,it uses inline styles

**Comment by ai** [comment]
You mean your CSS is inlined to HTML? Try this: https://github.com/RebelMail/html-autoprefixer

**Comment by azproduction** [comment]
@ai it is about autoprefixing inline css styles:
```js
let styles = {
  block: {
    display: 'flex',
    flexDirection: 'column'
  }
}
```
There are some unprefixeable cases like `display:flex; display: -webkit-flex;`, but still.

**Comment by ai** [comment]
@azproduction I will create `postcss-js` in September.

**Comment by azproduction** [comment]
@ai great to hear that, thanks!

**Comment by ai** [comment]
@azproduction right now you can use [styling](https://github.com/andreypopp/styling), but it didn’t support dynamic properties
