### ISSUE TITLE
WebKit Autoprefix for text-decoration-color

### ISSUE THREAD

**Issue by jonicious** [postcss/autoprefixer#441]
Safari and Chrome both need the ``-webkit`` prefix for ``text-decoration-color``. See [caniuse](http://caniuse.com/#search=text-decoration-color). It would be really great if you add ``-webkit`` prefix for ``text-decoration-color``.  Thanks in advice!

**Comment by ai** [comment]
No problem. I will add it to 5.2. Right afte I will finish PostCSS Plugins Guidelines.

**Comment by ai** [comment]
Hm. Very strange, `text-decoration-color` is already supported by Autoprefixer: https://github.com/postcss/autoprefixer-core/blob/master/data/prefixes.coffee#L244

**Comment by ai** [comment]
Seems like I use wrong regexp for Can I Use :).

**Comment by jonicious** [comment]
Thank you very much!

![tumblr_m6704u3ryp1r2oa9ko1_500](https://cloud.githubusercontent.com/assets/2546998/7322117/4b26f3a0-eaa6-11e4-96bb-f728e9939163.gif)

**Comment by ai** [comment]
Fixed https://github.com/postcss/autoprefixer-core/commit/19a744d90e7187837164411d5f093ce72673d93e
