### ISSUE TITLE
Removal only option.

### ISSUE THREAD

**Issue by ben-eb** [postcss/autoprefixer#446]
Consumers of autoprefixer may want to only use it for compression purposes, not to add any properties to the CSS.

**Comment by ai** [comment]
My current API vision:

```js
{ mode: ['add', 'remove'] }
```

So we can use only `remove` or only `add`.

**Comment by ben-eb** [comment]
Looks good to me. :+1:

**Comment by ai** [comment]
Done https://github.com/postcss/autoprefixer-core/commit/eccda61703318f5c08526ff59edcf8a22dc6e1c4
