### ISSUE TITLE
Support image-rendering

### ISSUE THREAD

**Issue by magsout** [postcss/autoprefixer#449]
`input.css`

```
foo {
  image-rendering: pixelated;
}
```

`output.css`

``` 
foo {
/* IE */
  -ms-interpolation-mode: nearest-neighbor;
  /* Firefox */
  image-rendering: -moz-crisp-edges;
  /* Safari */
  image-rendering: -webkit-optimize-contrast;
  /* Chrome and Opera */
  image-rendering: pixelated;
}
```

source : http://www.simevidas.com/2015/05/10/Blowing-up-pixel-art-on-the-Web.html and http://dev.w3.org/csswg/css-images-3/#the-image-rendering

**Comment by ai** [comment]
@magsout what you mean? What is bad in current workaround? What we should add to Autoprefixer?

**Comment by magsout** [comment]
oops I deleted the beginning of my message

If it were possible to add support for this property in autoprefixer

**Comment by ai** [comment]
Strange, Autoprefixer supports `https://github.com/postcss/autoprefixer-core/blob/master/data/prefixes.coffee#L315`

**Comment by ai** [comment]
I found a problem. You need to set input:

```css
foo {
  image-rendering: crisp-edges;
}
```

**Comment by ai** [comment]
We can also set this behaviour to `pixelated` value.

**Comment by magsout** [comment]
thanks :+1:

**Comment by ai** [comment]
@yisibl @simevidas are you agree that we should have some prefixed values for `pixelated` and for `crisp-edges`?

**Comment by magsout** [comment]
@ai there are 3 values : `auto` `crisp-edges` `pixelated`

See http://dev.w3.org/csswg/css-images-3/#the-image-rendering

**Comment by simevidas** [comment]
@ai The problem is that the 3 prefixed declarations:

```css
-ms-interpolation-mode: nearest-neighbor;
image-rendering: -moz-crisp-edges;
image-rendering: -webkit-optimize-contrast;
```

behave like `image-rendering: pixelated`. The spec includes screenshots which show that `pixelated` fully preserves pixels, whereas `crisp-edges` does not. If I remember correctly, Mozilla even acknowledged that their `-moz-crisp-edges` algorithm corresponds to the spec’s `pixelated` algorithm.

Maybe the state of implementations is too unstable for Autoprefixer. My current recommendation is to use a CSS utility class for the “preserve pixels” use case, anyway.

**Comment by ai** [comment]
@simevidas for example, Autoprefixer adds prefixes for flexbox even if specs has big difference.

If `-moz-crisp-edges` is equal to `pixelated`, it is OK.

But maybe we should not add prefixes for `crisp-edges` if all prefixed values do different thing?

**Comment by simevidas** [comment]
@ai Ah oh. All 3 prefixed declarations correspond to `image-rendering: pixelated` since they fully preserve pixels. For the `crisp-edges` algorithm, there are no prefixes that I am aware of.

**Comment by ai** [comment]
@simevidas so, what you think about this plan to 5.2:

1. Remove prefixes for `crisp-edges`
2. Add warning on `crisp-edges`.
3. Add prefixes for `pixelated`

Is there some case, when user will write `crisp-edges` right now?

**Comment by simevidas** [comment]
Sounds good. I’ve checked Mozilla, Chromium, and WebKit bug trackers. The `crisp-edges` value/algorithm is not even in development anywhere.

**Comment by ai** [comment]
Done:

https://github.com/postcss/autoprefixer-core/commit/39484758380dec7f820edf78f8ddfad09b49705a
https://github.com/postcss/autoprefixer-core/commit/804c4d14ddc6d19778f78f6432bca1464c918e81

**Comment by yisibl** [comment]
Good job!

**Comment by magsout** [comment]
:+1: thanks

**Comment by mathiasbynens** [comment]
I don’t understand why this change was made… `image-rendering: -moz-crisp-edges;` should not be stripped as it’s still the only way to achieve this effect in Firefox. Am I missing something here?

http://caniuse.com/#feat=css-crisp-edges

**Comment by mathiasbynens** [comment]
Turns out what I was missing was this bug: #632.
