### ISSUE TITLE
Imported less files are not being prefixed

### ISSUE THREAD

**Issue by Dakuan** [postcss/autoprefixer#452]
see https://github.com/Dakuan/postcss-webpack-bug

`bar.less` imports `foo.less`, 

`bar` gets prefixed correctly: https://github.com/Dakuan/postcss-webpack-bug/blob/master/bug.css#L6

but `foo` gets ignored: https://github.com/Dakuan/postcss-webpack-bug/blob/master/bug.css#L2

**Comment by ai** [comment]
@Dakuan any PostCSS plugins (and Autoprefixer) of course can work oonly with CSS (right now). So you must put `postcss-loader` **after** `less-loader`.

If you will have error after this change, please open a issue in [postcss-loader](https://github.com/postcss/postcss-loader). I can’t be a error in Autoprefixer.

**Comment by Dakuan** [comment]
moved to: https://github.com/postcss/postcss-loader/issues/9
