### ISSUE TITLE
CLI autoprefixer breaks source maps from node-sass

### ISSUE THREAD

**Issue by danielknell** [postcss/autoprefixer#453]
When I run autoprefixer over the output of node-sass the sourcemap seems to map to incorrect locations in the original files.

I am not entirely sure what is going wrong here but have managed to extact the relevant bits from my build script here as a simple gist https://gist.github.com/danielknell/367b44171767aec9ab59

Excuse the code screenshots but it seems the quickest way to explain things...

![devtools inspect](http://f.cl.ly/items/1m2F1s2H3c1l1W1C260L/Image%202015-05-24%20at%2011.02.01%20pm.png)

Inspecting body element, claims the rule is on line 12

![devtools source](http://f.cl.ly/items/1S3B1s1c042e2B0V1T0Y/Image%202015-05-24%20at%2011.02.37%20pm.png)

Is actually on line 19

I have tried a more minimal src.scss file but could not recreate the issue, and if i remove the sourcemap reference from the screen.css before running autoprefix, then use a third party tool like [sorcery](https://github.com/rich-harris/sorcery) to combine the two resulting source maps then the resulting source map works fine and maps everything correctly.

**Comment by ai** [comment]
Very strange. Can you help me with debug?

I need map file before and after Autoprefixer.

**Comment by danielknell** [comment]
https://gist.github.com/danielknell/8662a1b9ca5f09e15891 before and after

**Comment by ai** [comment]
Nice. Right now I am in the bed and will be able to look only tomorrow.

But my next step will be check this maps by source map visualizer: http://sokra.github.io/source-map-visualization/

If you need quicker, you can try look by you own. Just press "Custom..." button there. Maybe you find a source of issue.

**Comment by danielknell** [comment]
i have updated the gist with full output from the script, screen.css is the raw output from node-sass and screen2.css is the output of running that through autoprefixer.

unfortunately I do not know enough about source maps to help debug the actual files but if i can be of any further help i will do what i can.

**Comment by ai** [comment]
Sorry, I had no time today. Please pig me in Thursday if I will forget.

**Comment by ai** [comment]
Can you remove `compressed` mode and check it again? My first idea that it is a source of problem (I found some broken maps in Sass map)

If issue will be still there, please create a gist with css/map before and after PostCSS again (it is very difficult to compare compressed style with uncompressed).

**Comment by danielknell** [comment]
hrm, it seems to work fine without the compressed option.

when i use the folowing the source maps seem to tie up...

 node-sass --source-map dst/screen.css.map --source-map-contents --include-path node_modules/bootstrap-sass/assets/stylesheets screen.scss dst/screen.css

https://gist.github.com/danielknell/f4b6fdf170b6c4e29c6c

have you filed the bug with node-sass?

**Comment by ai** [comment]
Can you please start issue and describe it on high-level (works without compressing and doen’t wotk with compression). And I will post relative tech info.

**Comment by ai** [comment]
@danielknell BTW, there are many CSS minifiers, that works much better that sass with compression. I can recommend you [cssnano](https://github.com/ben-eb/cssnano). It is a PostCSS plugin too (same as Autoprefixer), so you doesn’t need to parse CSS twice.

You can use [postcss-cli](https://github.com/code42day/postcss-cli) to run PostCSS plugins. Anyway `autoprefixer` CLI was deprecated in 5.2.

**Comment by ai** [comment]
@danielknell here is a example of broken source mappings http://i.imgur.com/CMFUg2t.png

**Comment by danielknell** [comment]
https://github.com/code42day/postcss-cli/issues/3 makes it unviable so i guess ill just peg autoprefixer at its current version.
