### ISSUE TITLE
Throws when using inside cssnext

### ISSUE THREAD

**Issue by Antontelesh** [postcss/autoprefixer#454]
Since version 5.2 it throws when compiling.
I use webpack postcss-loader with cssnext plugin.
Cssnext creates a collection of plugins. The last plugin should be Autoprefixer, but it returns `undefined` when trying to access:

```
autoprefixer: function(options) {
    return require("autoprefixer-core")(options).postcss
},
```

Then undefined is being passed to postcss `LazyResult.run(plugin)` where it throws.

It took me two hours to get it :)

**Comment by ai** [comment]
`cssnext` issue `require("autoprefixer-core")(options).postcss` never was legal.

**Comment by MoOx** [comment]
Another release that should be a major one... It's not about being legal or not, but being public/private. Anything that is accessible is somehow public. You should be more careful when introducing breaking changes. Lot's of tools have .postcss property since you introduced this...

**Comment by ai** [comment]
`.postcss` property was introduced to run PostCSS plugins as `plugin` without `plugin(opts)` call.

This usage was very unexpected :).

**Comment by ai** [comment]
I understand that I should not broke API. But Autoprefixer is used in many different way, I failed here, but only because I really doesn’t think that it was used in that way.

**Comment by MoOx** [comment]
Ok. I will handle that in cssnext asap.

**Comment by ai** [comment]
@MoOx thanks. Sorry for broken API.

**Comment by iamvdo** [comment]
>`require("autoprefixer-core")(options).postcss` never was legal.

@ai: Look ma, from PostCSS's README a while ago (gulp section): https://github.com/postcss/postcss/blob/481cbc4ad213512a5c469e61b68382f17824be99/README.md#gulp

I also use this syntax...

**Comment by ai** [comment]
Fuck :-D You catch me :-). But I thought to use `.postcss` only for optionsless calls.

**Comment by iamvdo** [comment]
Don't know. I've anticipated updates by using `~5.1.0` instead of `^5.1.0`. ;)
