### ISSUE TITLE
AP should not care about file extensions

### ISSUE THREAD

**Issue by bdkjones** [postcss/autoprefixer#455]
Hi guys,

I got an email from one of my users today. He has a CSS file that is named `file.css.liquid` for compatibility with a CMS. The presence of `.liquid` causes AutoPrefixer to not run on this file, even though it is 100% valid CSS. 

Autoprefixer should not care what the file extension is. All it cares about is if the contents of a file can be parsed as CSS. Here is the original email from my user:

---
Working on a shoppify store and in order to access images from a css file I have to use the liquid syntax. 

For example, background-image: url("{{ ‘some-asset.jpg’ | asset_url }}”);

In order for shopify to turn that code into a proper url the extension on the file has to be .css.liquid. You’ve made this process really easy. But I’ve noticed that if I have a .liquid extension on the end of my css file that autoprefixer will not run. Remove .liquid, works fine, add it back, nothing. 

Let me know if there’s anything I can send you to help debug this issue. 

Here’s a quickcast for a little more detail. 

http://quick.as/rayxug3lg

**Comment by bdkjones** [comment]
The one challenge here is that files like this could contain syntax that Autoprefixer does not understand, such as:

```
#div {
    color: {{something}};
}
```

But the Autoprefixer parser could be updated to simply ignore non-standard tokens, correct? In other words, when the parser sees something it doesn't understand, it can just "skip" that token and spit it out to the output file as-is, assuming that the user had a good reason for putting it into the input file.

**Comment by ai** [comment]
You are right. Autoprefixer doesn't care about file names at all. Any PostCSS plugins and Autoprefixer too works only with file content. File name is used only on source map generator and it doesn't care for file extension.

How do you run Autoprefixer? Maybe it is a problem of runner?

**Comment by bdkjones** [comment]
I don't think it's my call to Autoprefixer, because the same method works perfectly on standard CSS files. I think it's related to the fact that this CSS file contains some syntax that's throwing off the Autoprefixer parser.

**Comment by bdkjones** [comment]
Changed the title to be more appropriate.

**Comment by ai** [comment]
`{{` is not a valid CSS token. But PostCSS 4.2 will has support for custom parser, which you can use to write a custom parser to parse these construction.

**Comment by bdkjones** [comment]
Cool. I don't have the expertise to do that, but could you guys modify AP to handle CSS files with non-standard tokens like this?

**Comment by ai** [comment]
@bdkjones handling `{` is really difficult part, because it is a part very important part of rules handling. of course, I am always open for PR, that will gives us this possiblities. But I am just afraid to do it :D.

**Comment by ai** [comment]
I think `{{`/`}}` is just a bad design for template engine for CSS. We can spend a man-week for a `{{` support. Or just a use `$(var)` syntax and get it by man-hour.
