### ISSUE TITLE
Has `autoprefixer().postcss` been deprecated?

### ISSUE THREAD

**Issue by renatoi** [postcss/autoprefixer#457]
I'm getting errors now. It is how [grunt-postcss](https://github.com/nDmitry/grunt-postcss#usage) explains the usage. I switched to just `autoprefixer()` and it works. However, this is a breaking change, should've either changed the major version or kept backwards compatibility (maybe it was missed)?

**Comment by ai** [comment]
Yeap, it a accidental API change in Autopefixer :(.

It is a difficult question, was it a part of public API. But let’s think that I miss it.

We can add few abstraction to Autoprefixer to support it, but I think, that this change is not so important. Clean code from `.postcss` is a better way.

**Comment by rguanghui** [comment]
is it mean other postcss plugins will  alse remove `.postcss` ?

**Comment by MoOx** [comment]
This property was a sort of trick. So it should not be use widely.
