### ISSUE TITLE
writing-mode css style.

### ISSUE THREAD

**Issue by DylanPiercey** [postcss/autoprefixer#460]
https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode

Doesn't get any vendor prefixes?

**Comment by ai** [comment]
Nope. We need a Can I Use page. Can you check it and send a PR if it is missed?

**Comment by simevidas** [comment]
Firefox Nightly just shipped `writing-mode` unprefixed ([demo](https://twitter.com/simevidas/status/616701200671465472)). All 4 browser engines should have it now, so it’s a great time to start adding prefixes.

**Comment by ai** [comment]
I will start it only afterr PostCSS 4.2. But you can help me by adding this information to Can I Use. It is easy, but require some time.

**Comment by simevidas** [comment]
Can I Use seems to have a voting system via GitHub issues now. You can vote for `writing-mode` [here](https://github.com/Fyrd/caniuse/issues/996).

**Comment by ai** [comment]
Can I Use is just a GitHub repo with JSONs. Just fork it, add addition JSON by other examples and send PR. Maintainer accepts Autoprefixer's related PRs with day or two.

**Comment by simevidas** [comment]
@ai I submitted a PR for a new feature once ([see here](https://github.com/Fyrd/caniuse/pull/793/files)) and I remember disliking how I have to manually compose the JSON. Would it make sense to create a web UI for generating such JSONs? Nothing special, just a bunch of form elements which would help entering the data.

**Comment by ai** [comment]
You should write it to @Fyrd

**Comment by ai** [comment]
Done, I made PR https://github.com/Fyrd/caniuse/pull/1874

**Comment by ai** [comment]
Done https://github.com/postcss/autoprefixer-core/commit/b2994725da52f0a0fb54395bb63c7e2ababc105c
