### ISSUE TITLE
Radial-gradient no -ms prefix. Doesn't work in IE

### ISSUE THREAD

**Issue by kmob2** [postcss/autoprefixer#464]
I just came across this project. I did a quick test and I noticed radial-gradient gets not -ms prefix in IE. (only tested IE11) 
 ```background-image: radial-gradient(center bottom, ellipse cover, #000, #CCC);```
IE11 still requires the -ms prefix. Doesn't work without.
http://jsfiddle.net/n78zkrLn/

**Comment by ai** [comment]
Can I Use says that IE doesn’t need a prefix http://caniuse.com/#feat=css-gradients

Do you use correct direction syntax, because it was changed in unporefixed version.
