### ISSUE TITLE
environnement n'est pas compatible avec Autoprefixer

### ISSUE THREAD

**Issue by sandroazerty** [postcss/autoprefixer#465]
bonjour,

j'utilise coda 2.5 et malheureusement autoprefixer n'as pas l'air compatible.

merci d'avance si jamais une solution est trouvée.

**Comment by ai** [comment]
Ouh, I didn't understand French :-(. @MoOx maybe you can help?

**Comment by magsout** [comment]
@sandroazerty pourquoi dis-tu qu'autoprefixer n'est pas compatible ? Could you speak english ?

**Comment by MoOx** [comment]
@magsout is there any specific intregration with coda? You use coda right ?

**Comment by sandroazerty** [comment]
ho ! sorry 

yes i am coda user. thank for translation @MoOx .

and my question is exactly that ! or more simply did autoprefixer works with coda.

thank you to respond me so quickly.

**Comment by magsout** [comment]
@MoOx yep I use coda but @sandroazerty there is no plugin for Coda 2  like sublime texte or Atom.

**Comment by magsout** [comment]
BTW @sandroazerty cli is better than a plugin. Try cssnext ;)

**Comment by ai** [comment]
Yeap, text editor plugin is very bad way: code with prefixes is difficult to read. Try Gulp, postcss-cli or cssnext CLI.

**Comment by inceng** [comment]
China
