### ISSUE TITLE
Add support for image-set()

### ISSUE THREAD

**Issue by bfred-it** [postcss/autoprefixer#467]
All the browsers that support `image-set()` only support its prefixed version. Can this be added to autoprefixer?

Support: http://caniuse.com/#feat=css-image-set
Test page: http://cloudfour.com/examples/image-set/
Fallback: https://github.com/alex499/postcss-image-set (which at the moment doesn't seem to make much sense since there's no autoprefixer)

**Comment by yisibl** [comment]
+1

**Comment by ai** [comment]
@yisibl we can use `url()` in unprefixed `image-set` too:

```
image-set() = image-set( <image-set-option># )
<image-set-option> = [ <image> | <string> ] <resolution>
<image> = <url> | <image()> | <image-set()> | <element()> | <cross-fade()> | <gradient>
```

**Comment by ai** [comment]
Done https://github.com/postcss/autoprefixer-core/commit/bb8a043c4c2231784a5056898d55169ec25f8cb0

**Comment by yisibl** [comment]
Yeah, we must be support `url()` too.

**Comment by ai** [comment]
@yisibl fixed `url()` too https://github.com/postcss/autoprefixer-core/commit/3d3264dec052ec7f5a4fef21302d1828f907c372
