### ISSUE TITLE
WebStorm / IntelliJ plugin

### ISSUE THREAD

**Issue by dandv** [postcss/autoprefixer#470]
Would be great to have autoprefixes as a WebStorm plugin!

**Comment by ai** [comment]
I think PostCSS plugin is a best idea, because it will cover other PostCSS plugins too

**Comment by ai** [comment]
But it is a wrong place to create WebStorm issues ;)

**Comment by dandv** [comment]
Sorry for posting in the wrong place. I saw this in [your CSS-tricks guest blog post](https://css-tricks.com/autoprefixer/):

> If your environment doesn’t support Autoprefixer yet, please, [report it](https://github.com/ai/autoprefixer/issues/new) and I’ll try to help.

**Comment by dandv** [comment]
Posted on YouTrack: https://youtrack.jetbrains.com/issue/WEB-17171
