### ISSUE TITLE
Autoprefixer params with JS API

### ISSUE THREAD

**Issue by verybigman** [postcss/autoprefixer#471]
In examples:
``` js
var autoprefixer = require('autoprefixer-core');
var postcss      = require('postcss');

postcss([ autoprefixer ]).process(css).then(function (result) {
    result.warnings().forEach(function (warn) {
        console.warn(warn.toString());
    });
    console.log(result.css);
});
```

How i can set browsers for autoprefixer if next code don't work:
``` js
var autoprefixer = require('autoprefixer-core');
var postcss      = require('postcss');

postcss([ autoprefixer({ browsers: ['last 2 versions'] }) ]).process(css).then(function (result) {
    result.warnings().forEach(function (warn) {
        console.warn(warn.toString());
    });
    console.log(result.css);
});
```

**Comment by ai** [comment]
Next code definatly should work. Maybe we miss something. What second code output?

**Comment by verybigman** [comment]
Sorry, code really work. The problem occurs when i use autoprefixer with [enb-postcss](https://github.com/verybigman/enb-postcss). Another plugins work fine. And the problem occurs when i send autoprefixer as: `autoprefixer({ browsers: ['last 2 versions']`. If i send it as function `autoprefixer` all work fine :( Plugins concat https://github.com/verybigman/enb-postcss/blob/master/techs/enb-postcss.js#L22 Magic?;)

**Comment by ai** [comment]
O_o
