### ISSUE TITLE
Disable warnings

### ISSUE THREAD

**Issue by rnsloan** [postcss/autoprefixer#473]
Is it possible to disable warnings? Project i am working on has warnings coming from a vendor file and I would prefer not to have to fork the plugin in-order to upgrade autoprefixer and annoy the team with constant warnings.

Thanks

**Comment by ai** [comment]
I thought to add option to hide warnings, but I didn’t do it, because all warnings are very important. Wrong gradient direction creates real problems.

**Comment by ai** [comment]
But I can add this option in 5.3.

**Comment by ai** [comment]
Right now you can add additional custom PostCSS plugin to clean warnings:

```js
var postcss = require('postcss');

module.export = postcss.plugin('postcss-warn-cleaner', function () {
    return function (css, result) {
        result.messages = [];
    };
});
```

**Comment by MoOx** [comment]
Indeed hiding warnings is not a good idea. You should avoid them or just configure your runner to hide those messages.
I think you should not add an option for that in autoprefixer @ai.

**Comment by rnsloan** [comment]
While the warnings are a nice feature, for this project we use autoprefixer to prefix; not to flag up invalid css. We have other tools available to do this.

**Comment by jdelStrother** [comment]
We also ran into this where we support the old flexbox syntax - most browsers will use our `display: flex` rules, but we have some alternative rules with `display: box` for older browsers.   Would be nice to be able to wrap the latter with an autoprefixer comment to disable the warning on it.

**Comment by ai** [comment]
There is no old browsers, which support `display: box`. Please, remove this lines of code.

**Comment by jdelStrother** [comment]
There are browsers that support `display: -webkit-box` etc though, right?

**Comment by ai** [comment]
@jdelStrother yeap, but Autoprefixer do not show warnings on `-webkit-box`. Only on `box`. And there is no browsers, which support `box`.

**Comment by jdelStrother** [comment]
Oh gotcha.   Feel free to ignore my initial comment then.

**Comment by ai** [comment]
I thought about it and my decision is close this issue.

This warnings is not a lint warnings. It is a very bad problems in CSS, which should be fixed immediately. There is not reasons for wrong direction syntax.

And simple option will promote irresponsible behavior.

If you want to hide warnings by good reason, you can use that cleaner plugin above.

**Comment by crvst** [comment]
I also came here to find a way to supress that nonsense warnings about `display: box` in logs. There's no `display: box` in my code, but the autoprefixer still complains about it for some reason.

**Comment by ai** [comment]
@crvst just put `console.log(node.parent.toString())` before warning code in Autoprefxier to find source.

**Comment by crvst** [comment]
@ai Thanks, I've discovered that the preprocessor (Stylus) output is quite odd here, there are all possible prefixes in it, so the autoprefixer job now is not putting necessary in it, but just eliminate unnecessarily. But why is so I haven't investigated yet.

**Comment by crvst** [comment]
I've figured out that was the `nib` plugin which emmits overpprefixed CSS

**Comment by fea17e86** [comment]
There is one reason though. I use wlhtmltopdf to create pdf from html. It can handle the old notation left, right etc. but not the new one.

**Comment by ai** [comment]
@fea17e86 Autoprefixer converts direction notation in `-webkit-gradient(liner` automatically.

**Comment by Telofy** [comment]
I would like to selectively hide warnings. There’s a deprecation warning for some CSS in some third-party library (I don’t know which), and the sheer amount of completely identical warnings makes sure that I won’t notice if there’s another actually important warning somewhere in between them.

**Comment by Songoo7** [comment]
Hello, is there some simple way to turn off warnings ? I just jumped from webpack 3 to 4 with all its needed configs. And autoprefixer shows hardcore spam of IE warnings (I do not care about IE) when running npm dev, there are so many that commandline cant cache all of them and they even push out error logs, so more or less its making devepopment impossible :D .

**Comment by ai** [comment]
You can add PostCSS which will clean warning on `OnceExit`: ` result.messages = []`

**Comment by Songoo7** [comment]
I see there it is mention of it in 2015 post , is it still valid ? This : 
var postcss = require('postcss');

```
module.export = postcss.plugin('postcss-warn-cleaner', function () {
    return function (css, result) {
        result.messages = [];
    };
});
```
Do I also need to some "npm install postcss" or where do I aply this "OnceExit: result.messages = []" ?

**Comment by ai** [comment]
> I see there it is mention of it in 2015 post , is it still valid

It uses old plugin API but will still work (with extra warning :D)

**Comment by Songoo7** [comment]
How to I add that in webpack config ?

```
const path = require('path');
const VueLoaderPlugin = require('vue-loader/lib/plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');

module.exports = {
  entry: {
    'app-v2': [
      'babel-polyfill',
      path.resolve(__dirname) + '/src/app.js',
      path.resolve(__dirname) + '/src/assets/scss/global.scss'
    ]
  },
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "scripts/index.bundle.js"
  },
  devtool: 'source-map',
  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.esm.js'
    },
    extensions: ['*', '.js', '.vue', '.json']
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [{
          loader: 'babel-loader'
        }]
      },
      {
        test: /\.vue$/,
        use: [{
          loader: 'vue-loader'
        }]
      },
      {
        test: /\.(sa|sc|c)ss$/,
        use: [
          MiniCssExtractPlugin.loader,
          "css-loader",
          "postcss-loader",
          "sass-loader"
        ]
      },
      {
        test: /\.(png|jpe?g|gif)$/i,
        use: [
          {
            loader: "file-loader",
            options: {
              name: "[path]/[name].[ext]",
            },
          },
        ],
      }
    ]
  },
  plugins: [
    new VueLoaderPlugin(),
    new MiniCssExtractPlugin({
      filename: 'styles.css',
      path: path.resolve(__dirname) + 'dist/'
    })
  ],
  optimization: {
    minimizer: [
      new UglifyJSPlugin({
        uglifyOptions: {
          compress: {
            drop_console: true,
          }
        }
      })
    ]
  }
};
```

**Comment by ai** [comment]
You need to add it to PostCSS config

**Comment by ai** [comment]
Open Wiring PostCSS Plugin doc from PostCSS repo

**Comment by ai** [comment]
Sorry, can't help with step by step guide.

**Comment by Git-I985** [comment]
# 2023 solution (works for me) 🔥 

```
postcss([
  autoprefixerPlugin,
  {
    postcssPlugin: 'autoprefixer-warnings-cleaner',
    OnceExit(_, result) {
      result.result.messages = result.result.messages.filter((msg) => {
        return msg.plugin !== 'autoprefixer';
      });
    }
  }
])
```

usage with gulp in my case:
```
gulpStuff....pipe(
      postcss([
        autoprefixerPlugin,
        {
          postcssPlugin: 'autoprefixer-warnings-cleaner',
          OnceExit(_, result) {
            result.result.messages = result.result.messages.filter((msg) => {
              return msg.plugin !== 'autoprefixer';
            });
          },
        },
      ]),
    )
```

you can write custom separate plugin with this little peace of code

```
// removes only autoprefixer warnings
{
    postcssPlugin: 'autoprefixer-warnings-cleaner',
    OnceExit(_, result) {
      result.result.messages = result.result.messages.filter((msg) => {
        return msg.plugin !== 'autoprefixer';
      });
    }
  }
  
  // removes all messages from postcss
{
    postcssPlugin: 'autoprefixer-warnings-cleaner',
    OnceExit(_, result) {
      result.result.messages = []
    }
  }
```

result has `messages: Message[]` property that contains array of 

```
export interface Message {
  /**
   * Message type.
   */
  type: string

  /**
   * Source PostCSS plugin name.
   */
  plugin?: string

  [others: string]: any
}
```
