### ISSUE TITLE
Doesn't appear to be doing anything?

### ISSUE THREAD

**Issue by tconroy** [postcss/autoprefixer#477]
Hi, 

I've used grunt-autoprefixer in the past without any issues, figured I'd try postcss-autoprefixer.

I've installed:
├── autoprefixer-core@5.2.1
├── grunt@0.4.5
├── grunt-contrib-sass@0.9.2
├── grunt-postcss@0.5.5
├── load-grunt-tasks@0.6.0

my grunt task configuration:

        sass: {
            dist: {
                files: {
                    '<%= yeoman.app %>/styles/main.css' : '<%= yeoman.app %>/styles/scss/main.scss'
                }
            }
        },
        postcss: {
            options: {
                map: true,
                processors: [
                    require('autoprefixer-core')({
                        browsers: ['last 2 versions', 'ie 8', 'ie 9']
                    })
                ]
            },
            dist: {
                src: '<%= yeoman.app %>/styles/main.css'
            }
        },

and I am invoking the task inside of a grunt `watch` task like so:

            sass: {
                files: ['<%= yeoman.app %>/styles/scss/**/*.scss'],
                tasks: ['sass', 'postcss:dist']
            },

CLI states:
```
    Running "postcss:dist" (postcss) task
    >> 1 processed stylesheet created.
    >> 1 sourcemap created.
```

however, when I inspect my element (in this case, an anchor with a `transition` property), nothing has been prefixed. It's just the plain old `transition`. 

Any ideas?

**Comment by ai** [comment]
Can you please open a issue in [grunt-postcss](https://github.com/nDmitry/grunt-postcss)?

I used Grunt only few times, so I can’t help you in this case :(.
