### ISSUE TITLE
Some example code is wrong in the README

### ISSUE THREAD

**Issue by helm168** [postcss/autoprefixer#483]
At section 'Outdated Prefixes'
There has some example code
```
var cleaner  = postcss([ autoprefixer({ add: false, browsers: [] }) ]);
var prefixer = postcss([ autoprefixer ]);

cleaner.process(css).then(function (cleaned) {
    prefixer.process(cleaned.css, function (result) {
        console.log(result.css);
    });
});
```

The inner function call `prefixer.process' should use promise's syntax, but it use callback's.

**Comment by ai** [comment]
@helm168 yeap, you are right.

Do you want to send a PR to save your name in history? :)

**Comment by helm168** [comment]
yes, my pleasure. I never did this, so thank you very much.

**Comment by ai** [comment]
Nice. I will wait your PR. Ask me any question if you will have problems.

**Comment by ai** [comment]
Done by #484
