### ISSUE TITLE
Document the format of warning objects

### ISSUE THREAD

**Issue by callumlocke** [postcss/autoprefixer#486]
Example from the readme:

```js
var autoprefixer = require('autoprefixer-core');
var postcss      = require('postcss');

postcss([ autoprefixer ]).process(css).then(function (result) {
    result.warnings().forEach(function (warn) {
        console.warn(warn.toString());
    });
    console.log(result.css);
});
```

The use of `.toString()` implies there are other ways you could consume the `warn` object... are there line/column numbers, etc? What are the property names?

Also, could you give an example of the kind of things that will cause warnings?

**Comment by ai** [comment]
OK, I will add links to PostCSS docs.

**Comment by ai** [comment]
But only when I finish PostCSS 4.2. Is it OK?

**Comment by callumlocke** [comment]
:) ok sure

**Comment by ai** [comment]
Done fa34569
