### ISSUE TITLE
Is the grunt example wrong?

### ISSUE THREAD

**Issue by renestalder** [postcss/autoprefixer#490]
The additional require statement looks strange to me. I'm used it from gulp, but not from grunt.

See nDmitry/grunt-postcss#41

**Comment by ai** [comment]
Seems like you are right. Sen a PR.

**Comment by giovannipds** [comment]
I would have send the PR myself, but I'm having a related issue. See nDmitry/grunt-postcss#3. Any ideas?

**Comment by ai** [comment]
@giovannipds O_o, I think it is some mistake. There is no way, how nmp can loose `autoprefixer-core`. maybe it was installed global or in other subdir?

**Comment by giovannipds** [comment]
Hey @ai!

The Grunt example at http://github.com/postcss/autoprefixer/blob/master/README.md#grunt was previously wrong, and I was guided by it. Today, @renestalder fixed it, at postcss/autoprefixer@bf85b68ba9b440b7a372b6b1d820e184c4ee7738. Thanks @renestalder.

Another thing that I was doing wrong, is that, I was trying to load http://github.com/postcss/autoprefixer-core with `grunt.loadNpmTasks('autoprefixer-core');`, which was unnecessary.

If anyone land here, I hope the comment help to make it through also. Thanks!
