### ISSUE TITLE
Add support for -webkit-column-break-*

### ISSUE THREAD

**Issue by Chris-May** [postcss/autoprefixer#491]
Looks like Webkit (and Chrome) have added a few prefixed items to columns:
`-webkit-column-break-before`
`-webkit-column-break-inside`
`-webkit-column-break-after`

Would it be worth including?

**Comment by ai** [comment]
I need more info. Do we have Can I Use page for this props? What other browsers supports?

**Comment by Chris-May** [comment]
Sadly, there is no Can I Use page for it.
I see it working correctly in desktop Safari and Chrome and mobile Safari.
Firefox has no support for this.

I don't yet know about IE or any other browsers.

The values are the same as [`css-page-break`](http://caniuse.com/#feat=css-page-break)

**Comment by Chris-May** [comment]
I will also add an issue with Can I Use, since I've only now found it.

**Comment by ai** [comment]
Does webkits support `break-before`?

[MDN says](https://developer.mozilla.org/ru/docs/Web/CSS/break-before), that it is a non-standard alias for standard `break-before`.

**Comment by ai** [comment]
@yisibl I think you report some issue about this. Maybe you can helps us (you the best in browser support investigation).

**Comment by Chris-May** [comment]
I don't know about `break-before`, but webkit definitely supports `-webkit-column-break-before`.

**Comment by ai** [comment]
@Chris-May I mean, maybe we do not need to support `column-break-before`. We should just insert `-webkit-column-break-before` instead of current `-webkit-break-before`.

Can you investigation relationships between this two props?

**Comment by Chris-May** [comment]
Interesting, if [this MDN article](https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-before) is correct, `page-break-before` is migrating to `break-before`, which is supposed to be more generic for use in column and region breaks.

`break-before` is [currently not supported anywhere](https://developer.mozilla.org/en-US/docs/Web/CSS/break-beforeBrowser_compatibility), but as the footnote marks:
>WebKit and Blink browsers don't support this property, but some have the non-standard -webkit-column-break-before and -webkit-region-break-before with similar parameters as page-break-before.

**Comment by yisibl** [comment]
It looks like this problem https://github.com/postcss/autoprefixer/issues/177 

See also: https://css-tricks.com/almanac/properties/b/break-inside/

**Comment by ai** [comment]
@interpaul maybe you can help us in this issue too?

**Comment by ai** [comment]
I think tis issues is fixed right now https://github.com/postcss/autoprefixer-core/commit/276a6d573941f02ec65cbcea402f64a316f572ee
