### ISSUE TITLE
Add Specific Error Message For Invalid Browser String

### ISSUE THREAD

**Issue by bdkjones** [postcss/autoprefixer#492]
Currently, if you supply an invalid browser string to Autoprefixer, the tool fails with the message: `internal error`. 

This is not helpful at all. Several of my customers have wasted quite a lot of time trying to figure out why Autoprefixer won't run, only to discover that they made a typo in the browser string parameter. 

It would be very useful to provide a descriptive error message in this case. Something like: "Autoprefixer failed to run because the supplied browser string parameter is not valid: [browser string parameter]"

**Comment by bdkjones** [comment]
What would be *really* cool is to add a function to the CLI that lets you pass a proposed browser string to Autoprefixer and have the tool return whether or not that string is valid. This would let me validate browser strings as soon as the user enters them rather than waiting until AP runs and fails.

**Comment by ai** [comment]
Autoprefixer had good error name before, but seems like I miss a code, when I splited Autoprefixer and Browserslist.

**Comment by ai** [comment]
Should be fixed in `autoprefixer-cli` https://github.com/ai/autoprefixer-cli/blob/master/test/binary.js#L392-L394
