### ISSUE TITLE
Un-deprecate AP CLI

### ISSUE THREAD

**Issue by bdkjones** [postcss/autoprefixer#494]
Could you guys un-deprecate the Autoprefixer CLI? It's much, much cleaner for implementors compared to using the `postcss-cli` (which requires a JSON file of options). 

That extra layer of abstraction just makes things messy. A clean, direct CLI to Autoprefixer would be greatly appreciated.

**Comment by ai** [comment]
@bdkjones you can pass browsers list to `postcss-cli` still by option. Do `postcss-cli` docs miss it?

**Comment by bdkjones** [comment]
Yea, I saw that. It's just very messy to go through a whole extra layer when all I want to call is autoprefixer. It makes sense for folks that want to chain plugins together, but makes little sense in the context of implementors. 

If AP already has to support the plugin API from `postcss-cli`, it should be virtually no effort to maintain a "direct" interface to AP through its own specific command line interface.

**Comment by ai** [comment]
I have no problem if somebody create `autoprefixer-cli` package. Problem is that I have no time to support all my projects. So I try to convince them to support our carry of one about few of them.

**Comment by Siilwyn** [comment]
Just noticed this too, really a bummer to see the CLI capability being removed.

**Comment by lydell** [comment]
@bdkjones @Siilwyn One way is of course to copy the current CLI code into a new repository and then maintain it yourselves. It'd be better maintained by people really enthusiastic about it :) Just an idea.

**Comment by ai** [comment]
I am planing to copy current `autoprefixer` repo to `autoprefixer-cli`. But I will not have time to maintain it. Why will be a volunteer?

**Comment by ai** [comment]
So, who want to support `autoprefixer-cli`?

**Comment by ai** [comment]
I move CLI to new repo: https://github.com/ai/autoprefixer-cli

**Comment by bdkjones** [comment]
Why does the CLI require maintenance and time? Do the options for AP change that frequently? What makes it so difficult to maintain a good, simple CLI?

**Comment by ai** [comment]
@bdkjones anyway it requires extra day in month. Not too much, but I didn't have really weekend in these months. Extra day will be very helpful for me.
