### ISSUE TITLE
Add support for -webkit-backdrop-filter

### ISSUE THREAD

**Issue by simevidas** [postcss/autoprefixer#495]
**Spec:** https://drafts.fxtf.org/filters-2/#BackdropFilterProperty
**Browser support:** Safari 9 (upcoming)

(source: https://www.webkit.org/blog/3632/introducing-backdrop-filters/)

**Comment by iamvdo** [comment]
Yep. I'm currently on it, but had to fix CanIUse data first: https://github.com/Fyrd/caniuse/pull/1796#issuecomment-129710715
:)

**Comment by ai** [comment]
Done in `next6` by @iamvdo
