### ISSUE TITLE
background image with gradient

### ISSUE THREAD

**Issue by CodyMoore240** [postcss/autoprefixer#497]
background-image: linear-gradient(top, rgba(0,0,0, .5) 0%,rgba(0,0,0,0) 100%),url(/example.png);

Nothing is added to this when compiled. I found that this is needed.

background-image: -moz-linear-gradient(top, rgba(0,0,0, .5) 0%,rgba(0,0,0,0) 100%),url(/example.png);
background: -ms-linear-gradient(top, rgba(0,0,0, .5) 0%,rgba(0,0,0,0) 100%),url(/example.png);

Don't know if this is an issue or maybe im just missing something.

**Comment by ai** [comment]
Please read FAQ about gradients (also Autoprefixer should warn you about wrong direction syntax in console).

**Comment by CodyMoore240** [comment]
Thank you sir. Apologize for the issue submission

**Comment by ai** [comment]
No problem. I mention FAQ only because I was on the way and can’t post a direct link :).

**Comment by OnkelTem** [comment]
I can't find nothing in the FAQ about linear-gradients.
Would you explain why prefixing linear-gradients doesn't work?

**Comment by ai** [comment]
Look at Autoprefixer warnings. I think you uses old direction gradient and Autoprefixer warn you about it.

**Comment by OnkelTem** [comment]
@ai thanks for quick reply. 

My finding is — using a version specification how it's seen in the manual:
```
.pipe(autoprefixer({ browsers: ['last 2 versions'] }))
```
makes no warning to appear and no prefixes added. The same happens for "last 3 versions" and "last 1 versions" (Although I had no chance to learn browserlist queries and thus my attempts more an educated guess)

Using no version specs at all or using higher versions count makes prefixes (and warning) to appear.

**Comment by ai** [comment]
Please show me the input CSS for gradient

**Comment by OnkelTem** [comment]
```css
body {
  background: linear-gradient(left, black, white);
}
```

**Comment by ai** [comment]
Yeap, this is wrong direction syntax. What version of `gulp-postcss` you use to run Autoprefixer?

**Comment by OnkelTem** [comment]
I don't use it, instead I use ```gulp-autoprefixer``` 2.3.1 which depends on ```postcss``` (resolved to 4.1.16) and ```autoprefixer-core``` (resolved to 5.2.1).

**Comment by ai** [comment]
Strange, `gulp-autoprefixer` has code to print warnings to console on building CSS.

But because of `gulp-autoprefixer` is not a official way to run Autoprefixer, post issue in `gulp-autoprefixer` tracker to display warnings.

**Comment by OnkelTem** [comment]
Just tried ```gulp-postcss``` (6.0.0) + ```autoprefixer-core``` (5.2.1)  combo - the same behavior. 
Plus there are warnings:
```
Container#eachAtRule is deprecated. Use Container#walkAtRules instead. ...
```
which seems to be fixed now (according to the issue queue)

**Comment by ai** [comment]
I find a reason. Autoprefixer do not print anything, because `gradient` rule doesn’t used.

**Comment by ai** [comment]
I create a issue in best CSS linter for this cases: https://github.com/stylelint/stylelint/issues/362

**Comment by OnkelTem** [comment]
@ai 

Sorry, I didn't quite get how does ```stylelint``` relate to this issue?
And If you have found the reason, does this mean it's a bug which you gonna fix?

**Comment by ai** [comment]
@OnkelTem there is no bug in Autoprefixer, because it insert prefixes correctly. Problem is in input CSS. You use wrong direction syntax. The correct CSS is:

```css
body {
  background: linear-gradient(to right, black, white);
}
```

So it is not a problem with prefixing, it is problem with CSS linting. That some tool should warn you on broken CSS. Because it is not Autoprefixer goal, it is not a Autoprefixer bug.

**Comment by OnkelTem** [comment]
@ai  You are reading uncarefully man. I wrote several times: *prefixing doesn't work no matter what property is used — ```left``` or ```to right```*.

**Comment by ai** [comment]
@OnkelTem why Autoprefixer should add prefixes? Check [Can I Use page](http://caniuse.com/#search=gradient).

**Comment by OnkelTem** [comment]
@ai Because this is what it intended for, isn't it?

I think you'd better concentrate on the essence of the bug report, which I can summarize like this:

```
autoprefixer({ browsers: ['last 1 versions'] }) - doesn't work == no warnings, no prefixes
autoprefixer({ browsers: ['last 2 versions'] }) - doesn't work == no warnings, no prefixes
autoprefixer({ browsers: ['last 3 versions'] }) - doesn't work == no warnings, no prefixes
autoprefixer({ browsers: ['last 4 versions'] }) - does work == warnings + prefixes
autoprefixer({ browsers: ['last 10 versions'] }) - does work == warnings + prefixes
autoprefixer() - does work == warnings + prefixes
```
Or if ```left`` property is fixed:
```
autoprefixer({ browsers: ['last 1 versions'] }) - doesn't work == no prefixes
autoprefixer({ browsers: ['last 2 versions'] }) - doesn't work == no prefixes
autoprefixer({ browsers: ['last 3 versions'] }) - doesn't work == no prefixes
autoprefixer({ browsers: ['last 4 versions'] }) - does work == prefixes
autoprefixer({ browsers: ['last 10 versions'] }) - does work == prefixes
autoprefixer() - does work == warnings + prefixes
```
Is it getting clearer now?

**Comment by ai** [comment]
Can ypou fix `left` to `to right` and then check in browsers. You will see, that gradients works.

**Comment by ai** [comment]
Problem is very simple. Old direction syntax do not work in unprefixed version, but works in prefixed. So modern borwsers read CSS as:

```css
a {
  background: -moz-linear-gradient(to right, black, white); // Hm, it is unnecessary prefix, but I can understand it for legacy code
  background: linear-gradient(to right, black, white); // Fuck, I can't understand direction, I will look above
}
```

**Comment by ai** [comment]
So `autoprefixer({ browsers: ['last 10 versions'] })` works only bbecause of dirty hack: wrong direction + unnecessary prefix.

**Comment by OnkelTem** [comment]
I think I start getting what you mean. It is: prefixes just not needed in last 3 versions, right?
Last question: missing version specification (default) makes autoprefixer to behave like what? Like how many versions it tracks back?

**Comment by ai** [comment]
Default browsers query is: `> 1%, last 2 versions, Firefox ESR`. So it is 2-3 depends on current browser populariity.

**Comment by OnkelTem** [comment]
Hm, "last 2 versions" substring is what I used and got prefixes not added. So probably the rest of the string makes difference. I'm gonna learn browserlist query language and then I'm back.

**Comment by OnkelTem** [comment]
@ So I have tested different ```browserslist```' options and it seems to work fine. Thank you.

**Comment by ai** [comment]
@OnkelTem stop, fix the CSS. You CSS if hardly broken.

**Comment by ai** [comment]
Autoprefixer 6.0 will always show warnings about broken direction in gradients 25b36742b8a8af7490cc69a1f9b98dadfa98c358

**Comment by OnkelTem** [comment]
@ai thanks, I have all directions now fixed. This was just an example.
