### ISSUE TITLE
Is this intended behavior? (css keyframes & transform)

### ISSUE THREAD

**Issue by cbier** [postcss/autoprefixer#498]
Regarding the Autoprefixer output: Does `@-webkit-keyframes` need `-webkit-transform` AND `transform`? Shouldn't it only need `-webkit-transform`?

Conversely the same thing is happening for `@keyframes`. It has `-webkit-transform` in it.

Is this intended behavior? If so, why? Thanks!

**CSS**
```
.hidden {
    animation: slide-out linear .2s forwards;
}

@keyframes slide-out {
    0% {
        transform: translateY(-275px);
    }
    100% {
        transform: translateY(0px);
    }
```

**Autoprefixer output**
```
.hidden {
  -webkit-animation: slide-out linear 0.2s forwards;
          animation: slide-out linear 0.2s forwards; 
}

@-webkit-keyframes slide-out {
  0% {
    -webkit-transform: translateY(-275px);
            transform: translateY(-275px); }
  100% {
    -webkit-transform: translateY(0px);
            transform: translateY(0px); }
}

@keyframes slide-out {
  0% {
    -webkit-transform: translateY(-275px);
            transform: translateY(-275px);
}
  100% {
    -webkit-transform: translateY(0px);
            transform: translateY(0px); }
}
```

**Comment by ai** [comment]
https://github.com/postcss/autoprefixer#why-autoprefixer-uses-unprefixed-properties-in--webkit-keyframes

**Comment by cbier** [comment]
Sorry for not looking at the FAQs! Didn't know there were FAQs down there.. Have a good day @ai

**Comment by cbier** [comment]
But why does it add prefixed properties in the unprefixed `@keyframes`?

**Comment by ai** [comment]
For case, when `-webkit-keyframes` will be remove before `transform`.

**Comment by cbier** [comment]
Makes sense. Thanks so much man!
