### ISSUE TITLE
Some is deprecated

### ISSUE THREAD

**Issue by yustnip** [postcss/autoprefixer#500]
```postcss``` was renewed recently - https://github.com/postcss/postcss/releases/tag/5.0.0 and now I get following:

```
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#style() is deprecated. Use Node#raw()
Node#before is deprecated. Use Node#raws.before
Node#_value was deprecated. Use Node#raws.value
```

**Comment by ai** [comment]
It is in my TODO list :).. But I think I release 6.0 only in next month, sorry :(.

**Comment by yustnip** [comment]
Thanks! Will wait.

**Comment by yoyurec** [comment]
+1

**Comment by tgabi333** [comment]
package.json contains `"postcss":           "~4.1.11"`

so, using 5.0 is a broken npm installation.

**Comment by ai** [comment]
Nope, because npm has tree structure and PostCSS inside Autoprefixer can be different than outside

**Comment by nkabardin** [comment]
Yeah, Andrey, please fix this shit! ;)

**Comment by ai** [comment]
Fixed in `next6` by @ben-eb

**Comment by unindented** [comment]
@ai I'm still seeing one of the warnings with `6.0.0`:

```
Container#eachDecl is deprecated. Use Container#walkDecls instead.
```

**Comment by ai** [comment]
@unindented I grep `eachDecl` in Autoprefixer codebase and didn’t see nothing.

Can you open `node_modules/postcss/lib/container.js`, put `throw` before this warning and post stacktrace here?

**Comment by unindented** [comment]
@ai Ah, my bad. It was `postcss-calc` the one emitting these. Sorry!

**Comment by cardeo** [comment]
I'm getting the following which is very similar. What's the fix?

Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#style() is deprecated. Use Node#raw()
Container#remove is deprecated. Use Container#removeChild
Node#before is deprecated. Use Node#raws.before

**Comment by TrySound** [comment]
@cardeo Upgrade postcss to 5

**Comment by vk92kokil** [comment]
upgrading css-loader to the latest version (0.23)  solved my issue.

**Comment by dickeylth** [comment]
Upgraded to `"autoprefixer": "~6.2.0"`, however warning messages still show:

```
Running "webpack:build" (webpack) task                                                                   60% 37/44 build modulesContainer#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Node#style() is deprecated. Use Node#raw()                                                              49% 99/150 build modulesNode#before is deprecated. Use Node#raws.before  
```

**Comment by ai** [comment]
@dickeylth this warnings should be from other PostCSS plugins. Autoprefixer is clean from it.

**Comment by dickeylth** [comment]
@ai Sorry, I've checked again and it's really css-next's problem, my bad. Thank you!
