### ISSUE TITLE
Prefix for transform-origin

### ISSUE THREAD

**Issue by limzykenneth** [postcss/autoprefixer#501]
I noticed that prefixes for `transform-origin` is not being added for me. I am currently converting from Less to CSS before piping to Autoprefixer. I don't suppose that is the problem though is it?

Thanks in advance.

**Comment by ai** [comment]
Everything fine in [online demmo](http://simevidas.jsbin.com/gufoko/quiet), so I think problem with your environment.

Was `transform` prefixed?

**Comment by limzykenneth** [comment]
Don't know why but it works now. Sorry to take up your time. Thanks!

**Comment by CREEATION** [comment]
Well, this is just happening to me. Also from Less to CSS.
You really don't know what fixed the issue? :(
