### ISSUE TITLE
Coda 2 Support?

### ISSUE THREAD

**Issue by ArcaneTheWoof** [postcss/autoprefixer#503]
Saw Autoprefixer on CSS-Tricks and, since you said to report it if your favorite tool is not supported, I just thought I'd throw in that I would LOVE to see Autoprefixer in Coda.

I think I saw somewhere that you don't have a Mac to develop on. Fortunately I do. If you're unable to make this happen, do you have any idea where I'd need to get started to help out?

**Comment by ai** [comment]
Using Autoprefixer in text editor is very bad practice, because:

* Code with prefixes has worse readability.
* Prefixes will not be update automatically.

Use Gulp or webpack.

**Comment by ArcaneTheWoof** [comment]
Not sure I understand your response at all.

Autoprefixer is a postprocessor, right? Meaning it takes your written code and modifies it after the fact to create a desired result, ala SASS. I use SASS here because SASS has a perfectly usable plugin for Coda that generates the CSS file every time you save the SCSS file. If SASS can do it, surely Autoprefixer could.

And doesn't Autoprefixer support Sublime Text, which is a text editor? I'm completely confused here.

**Comment by ai** [comment]
I do not support Autoprefixer for Sublime Text too. It is all bad way to use Autoprefixer.

Sass plugin for Coda is much much worse that normal Gulp build tool too.

Sorry, for my rudeness, but having build tool is very important for current frontend developer.
