### ISSUE TITLE
Re-add cli to autoprefixer

### ISSUE THREAD

**Issue by agauniyal** [postcss/autoprefixer#514]
I don't want to use postcss/postcss-cli just for calling out autoprefixer on my code. Not everyone uses postcss and I am definitely satisfied with my current Sass setup so won't be using postcss soon. Why add another layer for calling autoprefixer to the code?

**Comment by ai** [comment]
First: https://github.com/ai/autoprefixer-cli

**Comment by agauniyal** [comment]
> this tool is for legacy code

Is that okay for me to use?

**Comment by ai** [comment]
Second: you miss a point. PostCSS is not a preprocessor to replace Sass. Autoprefixer is PostCSS. So right now you uses PostCSS. Because PostCSS can works with Sass. Using `postcss-cli` *do not* mean, that you should convert Sass mixins to PostCSS. Not. You can use `postcss-cli` after Sass.

**Comment by ai** [comment]
> Is that okay for me to use?

@agauniyal nope, `postcss-cli` is much better way. Even with Sass sources.
