### ISSUE TITLE
Examples for using autoprefixer with postcss cli and source map

### ISSUE THREAD

**Issue by getriebesand** [postcss/autoprefixer#516]
I generate my css with sass. sass is building the source map.
After execute autoprefixer the line number in chrome doesn't match with the scss files anymore. I think autoprefixer doesn't rebuild the source map. 
How can I tell autoprefixer to rebuild it with command line options?
I have tried a configfile:
module.exports = {
    "use": ["autoprefixer"],
    "map": true,
    "autoprefixer": {
        "map": true
    }
};

but line number still doesnt match.

**Comment by ai** [comment]
What tool are you using to run Autoprefixer? grunt-autoprefixer?

**Comment by getriebesand** [comment]
No tool...I execute it with the postcss comand 
postcss -c config.js -o style.css style.css

**Comment by ai** [comment]
You should ask in postcss-cli repo.

Do Sass save map to separated file or inline maps to CSS? Maybe postcss-cli do not read map file and requires inline map.

**Comment by ai** [comment]
Here is a link https://github.com/code42day/postcss-cli

**Comment by ai** [comment]
Poke @code42day

**Comment by getriebesand** [comment]
Thanks a lot. 
I'm  using separate map file. Then I will try it inline or ask in postcss-cli repo

**Comment by getriebesand** [comment]
FYI I use now autoprefixer-cli with option -m and source map is ok now :)
