### ISSUE TITLE
bug with postcss.processors

### ISSUE THREAD

**Issue by hitmands** [postcss/autoprefixer#517]
grunt task:

I've some difficult to run autoprefixer with grunt-postcss!
All works fine if I don't call autoprefixer with options, ex:
```javascript
options: {
      map: false,
      processors: [
        autoprefixer
      ]
    }
```

I've a problem when I do the following:
```javascript
options: {
      map: false,
      processors: [
        autoprefixer({ browsers: [ 'last 2 versions' ] /*, ecc... */ })
      ]
    }
```
___
running grunt postcss --verbose I obtain:
```
Options: processors=[null], map=false, diff=false, safe=false
```

and, of course, nothing happens to my css!

Can anyone help me?

**Comment by ai** [comment]
Try add `.postcss` to the end of autoprefixer.

But you should open this issue in grunt-postcss repo. I am Gulp user and didn't know anything about Grunt.

Poke @nDmirty.
