### ISSUE TITLE
Different packages on hacks and fixes

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/autoprefixer#518]
Maybe separate all fixes and hack on different packages started with postcss-*. This would include in their assembly only necessary fixes and exclude options for configurable.

**Comment by ai** [comment]
Good idea. But right now it will too complicated. It is works and I don't see practice result. So right now I think this case can be described as "making better is enemy of having working things" :-).

But if I started project right now, I uses your idea.

And I can change my mind if you suggest some real practice cases.

**Comment by evilebottnawi** [comment]
@ai 
1. Modularity (plugins) is good.
2. Sometimes I write css for specific platforms require only support webkit, but also required special prefixes only for webkit, configured via browsers and other options is not very convenient.
3. Add-ons for postcss written all the plug-ins, it would be correct to write and autoprefixer via plugins.
4. Some plug-ins can be used inside other plugins for postcss.  Also with autoprefier it would be convenient to use in other parts of plug-ins. Example: image-set. My own plugin can generate images (for retian also) and insert them through a image-set plugin.
5. Also can be rewritten on es6.
6. This solution is much easier to maintain.
7. It is also possible to add in each individual plug-in advanced settings that make the system more customizable.
8. Если что-то не понятно, я хорошо разговариваю на русском.

**Comment by ai** [comment]
I am totally agree with this features, but main problem that all of that are theoretically benefits.

They helps only with code health, but have no real result for end-users.

I agree that cod health is important too. But as with ES6 rewritten, I have much more practical task to do (like `postcss-js` to use Autoprefixer in CSS-in-JS).

**Comment by ai** [comment]
Как говорят в России «лучшее — враг хорошего» :D

**Comment by ai** [comment]
But maybe we should do something about feature number 4. Can you example, how we can help for plugin developers?

For example, everything is fine with `image-set`. You just combine Autoprefixer and postcss-image-set and get good result.

**Comment by evilebottnawi** [comment]
@ai Maybe you're right, if you decide to rewrite to plugins let me know, I'll help.
