### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by AnatoliyLitinskiy** [postcss/autoprefixer#520]
/home/ncb/project/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:152
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined

**Comment by ai** [comment]
PostCSS do not support node.is 0.10 anymore. Update it or add Promise polyfill (Usage section in PostCSS docs contains a link, sorry I am from the phone).
