### ISSUE TITLE
Browsers 'last 2 versions' option not generating prefixes

### ISSUE THREAD

**Issue by GimliLongBow** [postcss/autoprefixer#523]
Hi, all,

I've run into an issue using Autoprefixer through [grunt-postcss](https://github.com/nDmitry/grunt-postcss). During debugging, I found that the error also existed when running postcss directly through the Node REPL. 

Here's what I did:

```
postcss([ require('autoprefixer')({browsers: ['last 2 versions']}) ])
  .process(css, { from: 'css/screen.css', to: 'css/screen2.css' })
  .then(function (result) { fs.writeFileSync('css/screen2.css', result.css); if ( result.map ) fs.writeFileSync('css/screen2.css.map', result.map); });
```

This does not generate prefixes, but the following does:

```
postcss([ require('autoprefixer')({browsers: ['> 5%']}) ])
  .process(css, { from: 'css/screen.css', to: 'css/screen2.css' })
  .then(function (result) { fs.writeFileSync('css/screen2.css', result.css); if ( result.map ) fs.writeFileSync('css/screen2.css.map', result.map); });
```

When manually creating the processor and running the info function (`console.log(processor.plugins[0].info());`) the browser lists are displayed correctly.

Any thoughts? Thanks!

**Comment by ai** [comment]
What CSS you use to test prefixing? Most of old properties (like `border-radius`) do not need prefixes anymore.

**Comment by GimliLongBow** [comment]
Ah, I was using CSS3 transition settings. Looking at CanIUse, it's supported on the last two of all browsers. Thanks!
