### ISSUE TITLE
Are you guys interested in doing a de-prefixing function?

### ISSUE THREAD

**Issue by viziionary** [postcss/autoprefixer#524]
One of the most effective ways to edit CSS realistically, testing the behavior of styles in various browsers and (most importantly) seeing the styles update in real time, is to use browser debug tools to view and edit the CSS. 

However, once CSS is served in prefixed form, when the CSS is edited, copied, and pasted back into the source code, it's now packaged with all of the prefixes. 

There should be a module which I can run in Node.js to de-prefix the css files in a directory or a specific file. Or better yet, you could allow developers to set a listener on all CSS files within a certain directory and de-prefix all of the files when they update. 

Because autoprefixing CSS is an important part of development too!

**Comment by viziionary** [comment]
See: http://programmers.stackexchange.com/questions/298104/how-do-web-developers-deal-with-editing-pre-processed-vendor-prefixed-css-in-b/298157#298157

**Comment by ben-eb** [comment]
You can use postcss-remove-prefixes for this. :smile:

https://github.com/johnotander/postcss-remove-prefixes
