### ISSUE TITLE
Add option skipUnknownBrowsers

### ISSUE THREAD

**Issue by tamtakoe** [postcss/autoprefixer#526]
I use universal browser's list for old browser checking and Autoprefixer. There is `phantomJS` in my list and Autoprefixer throws error: `Unknown browser phantomjs`.

Add option `skipUnknownBrowsers: true` for skip unknown browsers

**Comment by ai** [comment]
Just add filter for you browsers list:

```js
let apBrowsers = commonBrowsers.filter( i => i !== 'phantomJS' );
```
