### ISSUE TITLE
 Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".

### ISSUE THREAD

**Issue by KrunchMuffin** [postcss/autoprefixer#530]
The line is actually
`background-image: linear-gradient(top, #fdd49a, #fdf59a);`
not sure where `right` is coming from? Not even using right at all in the file.

v3.0.2 Gulp

**Comment by TrySound** [comment]
@KrunchMuffin Yeah, a little mistake, but hope you understood. Instead of `top` you should use `to bottom` value.

**Comment by KrunchMuffin** [comment]
Ok, thx. Thought it was `to top`.

**Comment by TrySound** [comment]
Need to fix warning

**Comment by ai** [comment]
@TrySound what we need to fix in warning?

**Comment by ai** [comment]
I checked warnings. Everything is fine.

**Comment by bl4ckdu5t** [comment]
For me there was neither a `right` or a `top`. I had a `to right` which should be correct considering the `to bottom` for `top`. Here's my code:
```css
background-image: linear-gradient(to right, #aaa 80%, #555);
```

**Comment by ai** [comment]
@bl4ckdu5t maybe you have some legacy code or CSS from libraries?

**Comment by bl4ckdu5t** [comment]
That was the case exactly. Thanks

**Comment by BockwurstJoe** [comment]
actually I had the same warning for: 
  position: absolute;
  left: 10px;
  right: 10px;
I guess it would not be interpreted correctly if I take to right and to left here :P

**Comment by DominicTobias** [comment]
This error is really getting to me, postcss vendor prefix is outputting:

```css
background-image: -webkit-linear-gradient(top, #78932b, #8cb434);
  background-image: -moz-linear-gradient(top, #78932b, #8cb434);
  background-image: -o-linear-gradient(top, #78932b, #8cb434);
  background-image: linear-gradient(to bottom, #78932b, #8cb434);
```

Is that not correct? Doesn;t it make sense old vendor prefixes have the old syntax?

**Comment by ai** [comment]
@DominicTobias show full text of your warning

**Comment by ai** [comment]
Maybe it is different line? Your code is correct.

**Comment by DominicTobias** [comment]
@ai whoops, thanks for confirming, I've found the culprit now (y)

**Comment by andreas83** [comment]
just want to point out, its 2019 and this issue is still helpful. not sure if this is a good or bad thing.

**Comment by OttoTrezza** [comment]
> For me there was neither a `right` or a `top`. I had a `to right` which should be correct considering the `to bottom` for `top`. Here's my code:
> 
> ```css
> background-image: linear-gradient(to right, #aaa 80%, #555);
> ```
i have this..
-moz-linear-gradient(top, #ffffff, #f0f0f0);
and i change it for...
-moz-linear-gradient(to right, #ffffff, #f0f0f0);

the same error disapear!

**Comment by abdullaachilov** [comment]
Just to be clear, we should change

`top` - > `to bottom`
`left` - > `to right`
`right` - > `to left`  ??

**Comment by ai** [comment]
@abdullaachilov yeap

**Comment by dragoscv** [comment]
> 

2022 and this post still helpful

**Comment by dragoscv** [comment]
> 

Just to be clear, we should change

top - > to bottom
left - > to right
right - > to left ??

2022 and this post still helpful

**Comment by KrunchMuffin** [comment]
And green means stop and red means go. Glad I could be of assistance all these years later. 😁
