### ISSUE TITLE
Add autoprefixer 6 support

### ISSUE THREAD

**Issue by Atorich** [postcss/autoprefixer#531]
There is another autoprefixer syntax (via postcss) in autoprefixer 6+
https://github.com/postcss/autoprefixer/releases/tag/6.0.0

**Comment by TrySound** [comment]
@Atorich Is it question?

**Comment by Atorich** [comment]
Sorry, this is issue for https://github.com/miracle2k/webassets.

**Comment by TrySound** [comment]
@Atorich So, close this?

**Comment by Atorich** [comment]
Yes, sure :)
