### ISSUE TITLE
Allow loud comments for disabling autoprefixer

### ISSUE THREAD

**Issue by Uncaught-Exception** [postcss/autoprefixer#532]
Could you please make the `/* autoprefixer: off */` syntax a bit less strict, so that it also matches `/*! autoprefixer: off */`, too?
Sass does not remove the exclamation marks from loud comments.
Thank you

**Comment by ai** [comment]
Done 23afb41

**Comment by ai** [comment]
@Uncaught-Exception BTW, why do you need a control comments? Every case of control comments usage could be a bug in Autoprefixer API.

**Comment by ai** [comment]
Released in 6.1
