### ISSUE TITLE
Please add support for text-stroke-xxx

### ISSUE THREAD

**Issue by cannedconcept** [postcss/autoprefixer#533]
Hi,

As title says. Just added text-stroke-width, text-stroke-color and text-fill-color attributes and found out they aren't being prefixed. Or is this because not in w3c spec?

Cheers

**Comment by yisibl** [comment]
Yes, this is  not in W3C spec.

**Comment by aosmichenko** [comment]
is it fixed, now?

**Comment by bathos** [comment]
no

**Comment by strarsis** [comment]
`text-stroke` is now widely supported, but often with `-webkit` prefix:
https://caniuse.com/text-stroke
Please re-open the issue.

**Comment by ai** [comment]
Sure. Send PR.

**Comment by lukewarlow** [comment]
Text stroke and fill (despite being in caniuse) still aren't even draft specs. Not a single browser implements them unprefixed. So I think this issue should be closed until at least a draft spec is available.
