### ISSUE TITLE
Background-size support in bg shorthand for older Android

### ISSUE THREAD

**Issue by trubit** [postcss/autoprefixer#534]
According to http://caniuse.com/#feat=background-img-opts Android < 4.4 or others "Does not support background-size values in the background shorthand".

Can this be fixed by extracting size value from shorthand?

**Comment by ai** [comment]
Nope, Autoprefixer is only about prefixes.

You can create very simple PostCSS plugin and add it to cssnext.

Plugin will be really easy. Sorry, right now I am on holiday and can't write it for you.
