### ISSUE TITLE
Warnings when using Bourbon's "display(flex)"

### ISSUE THREAD

**Issue by benjamindean** [postcss/autoprefixer#536]
Bourbon using `box` and `flex` values in [their mixin](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/css3/_flex-box.scss#L72), which produces following warning: 

```
You should write display: flex by final spec instead of display: box
```

Is there any way to suppress these warnings?

**Comment by TrySound** [comment]
@benjamindean Seems like old flex syntax was only prefixed. [See here](http://caniuse.com/#feat=flexbox). In this case it's Bourbon issue

**Comment by TrySound** [comment]
@benjamindean Check https://github.com/hallvors/postcss-flexboxfixer

**Comment by TrySound** [comment]
@benjamindean Hm.. I found. You don't need to use these mixins, if you use autoprefixer. ap will add necessary prefixes and versions own. So stop using mixins for prefixes.

**Comment by benjamindean** [comment]
@TrySound Yes, I guess that the only right way to do it. Thanks!
