### ISSUE TITLE
Appearance property

### ISSUE THREAD

**Issue by ashleynolan** [postcss/autoprefixer#540]
It seems support for prefixing the appearance CSS property is a bit mixed.

When I code `appearance: none;` this gets prefixed as expected when compiled, however when writing `appearance: button;`, it doesn’t.

As this property and value is in both Chrome and Firefox I’m guessing it should get prefixed?  Should there be support for values other than `none` for the appearance property?

**Comment by ai** [comment]
Problem is that W3C standaard contains only `none`, as I understand.

So `-webkit-appearance: button` is Chrome hack. Write it with prefix.

**Comment by ashleynolan** [comment]
I’ve had a look and it seems it’s no longer in any specification document relating to CSS3 UI.

[Mozilla docs say it isn’t included in any specs, and may never be included](https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-appearance).  Therefore, should Autoprefixer be adding this prefix at all if it’s not a potential future property?

Problem I’m having is when linting my CSS with stylelint.io – which uses Autoprefixers [data to find valid uses of prefixes in CSS](http://stylelint.io/?http%3A%2F%2Fcdn.rawgit.com%2Fstylelint%2Fstylelint%2F1.2.0%2F%2Fsrc%2Frules%2Fproperty-no-vendor-prefix%2FREADME.md).  Because Autoprefixer is converting some of the `appearance` properties, but not all, it’s returning false positive linting errors.

Not sure if this is an issue of inconsistency with Autoprefixer or if it should be raised as an issue with stylelint.io, but seems it would be better if Autoprefixer didn’t convert any of the properties for the `appearance` property as it isn’t valid CSS. (?)

**Comment by TrySound** [comment]
@ashleynolan http://www.w3.org/TR/2015/WD-css-ui-4-20150922/#appearance-switching

**Comment by ashleynolan** [comment]
I just stumbled across the same link – thanks :)

**Comment by ai** [comment]
But maybe we can miss `none` check. And left standard compatibility in developer responsibility.

**Comment by TrySound** [comment]
@ai I'd like to make it optional and maybe true by default. I usually use only `appearance: none;`

**Comment by ashleynolan** [comment]
I came up against it from using normalise.css – they use a [couple of the other old-style properties](https://github.com/necolas/normalize.css/blob/master/normalize.css#L294).

Problem is that this conflicts when trying to use a linter to spot when devs add unnecessary prefixes into the CSS (as stylelint apparently uses [Autoprefixer prefix data](http://stylelint.io/?http%3A%2F%2Fcdn.rawgit.com%2Fstylelint%2Fstylelint%2F1.2.0%2F%2Fsrc%2Frules%2Fproperty-no-vendor-prefix%2FREADME.md)).

**Comment by ai** [comment]
Done f713e1f

**Comment by ai** [comment]
Released in 6.1
