### ISSUE TITLE
Sourcemaps are breaking when autoprefixer is included

### ISSUE THREAD

**Issue by samuel99** [postcss/autoprefixer#553]
First off, I'm pretty new to Gulp. If I did something wrong here I apologize in advance.

So, this is my current task for compiling SASS, run autoprefixer, append hash to filename and create sourcemaps:

```javascript
var autoprefixerOptions = {
      browsers: ['last 2 versions', 'ie 9-10']
    },
    inputScss = "./ui/customer/scss/**/*.scss",
    output = "../Sitecore/website/ui/customer/dist/",
    sourceMapPath = "maps/",
    sassOptions = {
        outputStyle: 'compressed'
    },
    revManifestOptions = {
        base: output,
        merge: true
    };

gulp.task('sass', function () {
    gulp.src(inputScss)
        .pipe(sourcemaps.init())
        .pipe(sass(sassOptions).on('error', sass.logError))
        //.pipe(autoprefixer(autoprefixerOptions))
        .pipe(rev())
        .pipe(sourcemaps.write(sourceMapPath))
        .pipe(gulp.dest(output))
        .pipe(rev.manifest({
            base: output,
            merge: true
        }))
        .pipe(gulp.dest(output));
});
```

If I run it like this, the sourcemaps works great:
```
"sources":["lib/bootstrap/_bootstrap.scss","lib/bootstrap/bootstrap/_normalize.scss","lib/bootstrap/bootstrap/_print.scss","lib/bootstrap/bootstrap/_glyphicons.scss","lib/bootstrap/bootstrap/_scaffolding.scss","lib/bootstrap/bootstrap/mixins/_vendor-prefixes.scss","lib/bootstrap/bootstrap/_variables.scss","lib/bootstrap/bootstrap/mixins/_tab-focus.scss","lib/bootstrap/bootstrap/mixins/_image.scss","lib/bootstrap/bootstrap/_...
```

But, if I remove the comment on the autoprefixer line the sourcemaps are not "compiling" from source, but from the generated file:
```
"sources":["framework.css"]
```

Any ideas? All packages are latest version.

Best regards, Samuel

**Comment by ai** [comment]
Try official [gulp-postcss](https://github.com/postcss/gulp-postcss) with `autoprefixer` instead of unofficial `gulp-autoprefixer`.

**Comment by KillerJK** [comment]
I am unable to replicate your issue. I tried the gulpfile.js you posted, with my own .scss files, and the source maps have the correct sources.

This is the list of packages I'm using:

gulp@3.9.0
gulp-autoprefixer@3.1.0
gulp-rev@6.0.1
gulp-sass@2.1.0
gulp-sourcemaps@1.6.0

**Comment by ai** [comment]
I am closing this use, because anyway it is not part of Autoprefixer
