### ISSUE TITLE
Upgrade from 5.1.11 to 5.2.0 or 6.0.x breaks relative sourcemaps

### ISSUE THREAD

**Issue by quintenvk** [postcss/autoprefixer#554]
Situation: we build our CSS with libsass through grunt, after which it gets passed on to postcss through grunt-postcss. 

Our folder structure looks something like this:
```
project
  dist
    css
      dist.css
      dist.css.map
    scss
      screen.scss (which imports _module)
      _module.scss
  src
    scss
      screen.scss (imports _module)
      _module.scss
```

Everything in `dist` is copied/generated by grunt from the `src` directory. The issue we have is that, after upgrading, postcss reads the sources from the `dist.css.map` file correctly as `../scss/screen.scss` but searches the file relative to the working directory (so it searches for a `scss` folder next to `project`) rather than searching relative to the location of the dist.css file. 

Am I missing a setting which allows me to configure a relative path? Setting absolute paths obviously isn't a solution; our sourcemaps would be useless otherwise.

**Comment by ai** [comment]
Autoprefixer do not generates source maps. PostCSS does. But you should ask in grunt-postcss because it is related to it.

**Comment by quintenvk** [comment]
This is only when I upgrade Autoprefixer though... I'm not sure how that's related to grunt-postcss but I'll check with them too.
