### ISSUE TITLE
Не понятные префиксы

### ISSUE THREAD

**Issue by Laxiston** [postcss/autoprefixer#555]
Когда работает только автопрефиксер, происходит вот такая штука
http://joxi.ru/1A5Q5j3CB150AE
Из-за этого по крайней мере в хроме анимации ведут себя неадекватно.

Если же он выключен, но префиксы проставляются миксинами (например в бурбоне), то все красиво работает
http://joxi.ru/KAg7ZQxs16dXAl

**Comment by ai** [comment]
@Laxiston чем именно ведут себя неадекватно. Можешь показать на одном и том же примере (в одном у тебя `top`, в другом `bottom`) и записать видео, чем именно работа неправильно.

**Comment by ai** [comment]
Проблема в том, что `transition-property: top, transform, -webkit-transform` не содержит никаких неправильных значений.
