### ISSUE TITLE
Error in pipeline from node-sass stdout to autoprefixer stdin

### ISSUE THREAD

**Issue by EightArmCode** [postcss/autoprefixer#557]
I'm creating a new CSS build pipeline in NPM. Currently I have the following modules:

postcss version 5.0.9
node-sass	3.4.1	(Wrapper)	[JavaScript]
libsass  	3.3.1	(Sass Compiler)	[C/C++]
node v4.2.1
npm 2.14.7

If I run 
```node_modules/.bin/node-sass --source-map build/web/default.css.map src/styles/main.scss ``` it prints the compiled CSS to the  console, followed by the source-map. If I try to read that from stdin by adding onto the previous line with 

``` | postcss -u autoprefixer``` 

I get an error when postcss interprets the map - 

```<css input>:5837:2: Unknown word
	"version": 3,
	"file": "../../src/styles/main.css",
 ^
	"sources": [```

presumably because the map is a json format. Am I missing something about how this should work? I've spent days trying to figure out a syntax that will work, and so far, I can only get it to work in multiple steps. Postcss even breaks when you let node-sass use an inline map comment, as opposed to a separate map file.

**Comment by ai** [comment]
There is no way to send 2 files by UNIX pipe (at least proper way).

You should inline source map into CSS file by base64 or use Gulp for two files stream.

**Comment by EightArmCode** [comment]
Hello @ai Thanks for your quick reply. Of course you are right!
