### ISSUE TITLE
Use NodeGYP3

### ISSUE THREAD

**Issue by jgacuca567** [postcss/autoprefixer#559]
I tried installing AutoPrefixer, but this was the error I was getting below. 

<img width="862" alt="screen shot 2015-11-15 at 9 50 19 am" src="https://cloud.githubusercontent.com/assets/4000076/11169184/73062cbe-8b7e-11e5-9d60-3e1e4fc9c574.png">

**Comment by ai** [comment]
Autoprefixer or PostCSS has no native addons, so it doesn’t use any `gyp`.

I think you have installed `pangyp` globally in your system.

**Comment by TrySound** [comment]
@jgacuca567 sass uses gyp to build cpp code

**Comment by jgacuca567** [comment]
@TrySound Would I know how I would remove, it because when I opened the CLI, and tried uninstalling it, I got the Not Found in Directory. 

@Ai, how would I suggest I fix it.

**Comment by ai** [comment]
Have no idea, sorry :-).

Maybe you should update node our try look to node_modules dir in system dirs.
