### ISSUE TITLE
`flex-direction` duplicates

### ISSUE THREAD

**Issue by Ashot-KR** [postcss/autoprefixer#560]
When `webkit` and `ms` prefixed `flex-direction` properties already defined, autoprefixer adds them again on each run.

**Comment by ai** [comment]
@Ashot-KR unfortunately, `flex-direction` is very complicated property and it is very complicated to avoid duplicates.

Anyway, the Autoprefixer main API is to work on unprefixed CSS as input. So all that magic with prefixes input CSS is just a tricky hacks, which can be work or not.

**Comment by ai** [comment]
PR is welcome :)
