### ISSUE TITLE
does it recognize the `flex` property?

### ISSUE THREAD

**Issue by callmecavs** [postcss/autoprefixer#561]
does autoprefixer recognize the [flex shorthand property](https://developer.mozilla.org/en-US/docs/Web/CSS/flex)?

encountering an issue where writing:

```css
flex: 0 1 auto;
```

doesn't compile to:

```css
/* required to support IE10, old flexbox spec */
-ms-flex-positive: 0;
-ms-flex-negative: 1;
-ms-flex-preferred-size: auto;
```

my browser string is: `last 2 versions, ie >= 9, Android >= 4.1`

**Comment by ai** [comment]
MSDN says that IE 10 supports `-ms-flex`: https://msdn.microsoft.com/en-us/library/hh673531(v=vs.85).aspx

But IE 10-12 have some issues with `flex` property implementation. Use [postcss-flexbugs-fixes](https://github.com/luisrudge/postcss-flexbugs-fixes) to automatically fix them.

**Comment by callmecavs** [comment]
thanks for the quick response. currently using `gulp-autoprefixer`, might need to switch up my config to use `gulp-postcss`. will let you know if I get it working
