### ISSUE TITLE
request support: ime-mode

### ISSUE THREAD

**Issue by LiaoSept** [postcss/autoprefixer#562]
see https://msdn.microsoft.com/en-us/library/ms530767(v=vs.85).aspx

**Comment by ai** [comment]
Autoprefixer prefer to work with W3C standard. Or at least. 2 browsers should support property.

If it is vendor specific hack (only for webkit or ms), there is no to sense to add it to Autoprefixer.

**Comment by LiaoSept** [comment]
see https://developer.mozilla.org/en-US/docs/Web/CSS/ime-mode

**Comment by ai** [comment]
```
IE8 introduced -ms-ime-mode as a synonym for ime-mode. Don't use the -ms- prefix.
```
