### ISSUE TITLE
cursor: grab and grabbing are not getting prefixes

### ISSUE THREAD

**Issue by kmiyashiro** [postcss/autoprefixer#563]
`cursor: grab` and `cursor: grabbing` should both be prefixed in all browsers that support it, but autoprefixer is not adding any prefixes for it using `last 1 versions`. Also, if I add prefixes manually, it is stripping those lines out, preventing me from using `cursor: grab`.

**Comment by ai** [comment]
Yeap, seems like we need separated Can I Use page for `grab`.

**Comment by ai** [comment]
Sorry, I will be able to fix it only tomorrow or after tomorrow. Right now I am in travel between Riga and Moscow.

**Comment by kmiyashiro** [comment]
np, safe travels :airplane:

**Comment by ai** [comment]
Done, I sent PR to Can I Use: https://github.com/Fyrd/caniuse/pull/2103

**Comment by kmiyashiro** [comment]
:smiley_cat:

**Comment by ai** [comment]
Fixed 1502379

**Comment by ai** [comment]
Released in 6.1.1
