### ISSUE TITLE
Autoprefixer is not prefixing

### ISSUE THREAD

**Issue by musamanyama** [postcss/autoprefixer#564]
Hi, I'm using gulp version 3.8.11 CLI and 3.9.0 in local project. 
I'm running postcss as the example shows with only one plug-in (autoprefixer) and it's not prefixing.
My css file starts with stylus compiler which postcss is piped to.
I think it's just autoprefixer that doesn't work, cause I replaced autoprefixer with csswring and it minified well my css files.
Help.. :sob:

**Comment by ai** [comment]
What is you input CSS? Show some minimum example

**Comment by musamanyama** [comment]
Hi, Thank You for reply.
Well here is some output from my stylus css which gets
piped to autoprefixer.

```
.termsBox ul:nth-child(2n+1) {
    background-color: #2ecc40;
    border-radius: 4px;
    box-shadow: 0 0 6px rgba(0, 0, 0, 0.05) inset;
    margin: 20px 0 10px;
    padding: 15px;
}
```

Ps. I copied that from my browser not the css file itself.

**Comment by ai** [comment]
This input CSS has no properties for prefixing. `border-radius` has no prefixes for 3 years.

**Comment by musamanyama** [comment]
Aww .. I also got this in the first lines too..
```
html,
body {
  display: 'flex';
}
```
Plus my support is not limited in the browsers: array.

**Comment by ai** [comment]
> Plus my support is not limited in the browsers: array.

What is your browsers config?

Please, show me your Gulpfile.

**Comment by musamanyama** [comment]
Sure, 
```
gulp = require 'gulp'
stylus = require 'gulp-stylus'
nib = require 'nib'
rupture = require 'rupture'
axis = require 'axis'
jeet = require 'jeet'
postcss = require 'gulp-postcss'
csswring = require 'csswring'
autoprefixer = require 'autoprefixer'
gulp.task 'css', ->
    processors = [
        autoprefixer
            cascade: no
            add: yes
    ]
    gulp.src stylusFiles
        .pipe stylus
            use: [axis(), nib(), rupture(), jeet()]
            import: ['axis', 'rupture', 'nib', 'jeet']
        .pipe postcss(processors)
        .pipe plumber()
        .pipe(connect.reload())
        .pipe plumber()
        .pipe gulp.dest 'app/css'
```

**Comment by ai** [comment]
BTW, you should not use `nib` with `Autoprefixer`, because `nib` did same job.

**Comment by ai** [comment]
Please create `test.styl` file with

```styl
html
  display flex
```

And show me its output from `app/css`

**Comment by musamanyama** [comment]
Woah..! How did you do that!?
```
html {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: box;
  display: flex;
}
```
Thank You ..! So there is something wrong with my main styl file!?

**Comment by ai** [comment]
Maybe. Or maybe it is conflict between `nib` and Autoprefixer.

**Comment by musamanyama** [comment]
It's just now when i saw your nib comment, I didn't remove it when I made, run and post that prefixed file.
Plus that gulp file was made before without postcss and then when I saw it I added it in there. So I didn't change much in it.

**Comment by PhilippeVay** [comment]
I've never used Stylus but the `'` seem strange in:

```html,
body {
  display: 'flex';
}
```

Shouldn't it be `display: flex`? Though there should be some error reporting I guess. Is the CSS compiled by Stylus already valid and as you expect it to be?
