### ISSUE TITLE
Mac osx Terminal not installing Autoprefixer, but its running gulp and sass with Yeti App from Foundation.

### ISSUE THREAD

**Issue by code-a-la-mode** [postcss/autoprefixer#565]
Here's the message I get (below). I'm new to CLI, Foundation, Sass and Yeti, but so far set-up has gone well. Being a newbie, I'm only as good as the instructions I follow, so bear with me and keep in mind I'll need support like driving directions as opposed to technical expressions and explanation. 

>>>>>>> terminal response<<<>>>>>

TODD-HANEYs-MacBook:~ toddhaney1$ $ npm install --save-dev gulp-autoprefixer
-bash: $: command not found
TODD-HANEYs-MacBook:~ toddhaney1$ npm install --save-dev gulp-autoprefixer
npm WARN locking Error: EACCES, open '/Users/toddhaney1/.npm/_locks/gulp-autoprefixer-059a2cbd40a1bb2f.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/toddhaney1/.npm/_locks/gulp-autoprefixer-059a2cbd40a1bb2f.lock failed { [Error: EACCES, open '/Users/toddhaney1/.npm/_locks/gulp-autoprefixer-059a2cbd40a1bb2f.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/toddhaney1/.npm/_locks/gulp-autoprefixer-059a2cbd40a1bb2f.lock' }
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save-dev" "gulp-autoprefixer"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2

npm ERR! Attempt to unlock /Users/toddhaney1/node_modules/gulp-autoprefixer, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/toddhaney1/npm-debug.log
TODD-HANEYs-MacBook:~ toddhaney1$

**Comment by ai** [comment]
Sorry, I ma not familiar with npm on Mac. You should ask on Stackoverflow.

At least, try to remove `/Users/toddhaney1/.npm` dir and run `npm install --save-dev gulp-autoprefixer` again.
