### ISSUE TITLE
background-position-x in Firefox.

### ISSUE THREAD

**Issue by sashamjolnir** [postcss/autoprefixer#570]
Can Autoprefixer change `background-position-[x|y]` to work cross browser? It's not in [caniuse](http://caniuse.com), but it'll be very helpful.

[Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=550426)
[Stackoverflow answer to crossbrowser solution (CSS Variables)](http://stackoverflow.com/questions/14844407/background-position-y-doesnt-work-in-firefox-via-css/29282573#29282573)

**Comment by ai** [comment]
@sashamjolnir https://github.com/postcss/autoprefixer#does-it-add-polyfills

**Comment by sashamjolnir** [comment]
Ok, thanks!
