### ISSUE TITLE
Disabling old flexbox

### ISSUE THREAD

**Issue by wheresrhys** [postcss/autoprefixer#573]
I've just done the following to disable flexbox in older webkit browsers

```
	// Prevents autoprefixer from outputting display: -webkit-box;, which is buggy
	/*autoprefixer: off*/
	display: -webkit-flex;
	display: -ms-flexbox;
 	display: flex;
	/*autoprefixer: on*/
```

Is there a better approach to this problem? (bearing in mind that I still want most other features to get prefixed in these older webkit browsers)

**Comment by ai** [comment]
Nope, only this one.

Old webkits are pretty dead right now, so I think we should just wait. But if you will send PR, I will accept it.
