### ISSUE TITLE
Wrong prefix -moz-llinear-gradient

### ISSUE THREAD

**Issue by slackero** [postcss/autoprefixer#574]
The Mozilla linear gradient prefix is wrong
Is `-moz-llinear-gradient`but should `-moz-linear-gradient`

**Comment by ai** [comment]
It is in docs or Autoprefixer produce it?

Show your CSS input.

**Comment by slackero** [comment]
Oh damn, shame on me. Sometimes there are too many trees. It was in the Less source.
