### ISSUE TITLE
Whitespace for browser should be ignored during comparison

### ISSUE THREAD

**Issue by joelpittet** [postcss/autoprefixer#576]
postcss --use autoprefixer --autoprefixer.browsers "last 1 versions, ie 9, ie 10, ie 11, Android >= 4" --replace `git ls-files "*.css" | grep -E -v '(tests|vendor)/.*'`

![3__html_core__less__and_2__local_opt__bash_](https://cloud.githubusercontent.com/assets/70129/11491425/9042622e-9796-11e5-9785-617c7320236f.png)

Seems to have added a prefix where one wasn't needed and forgot to put a space after the comma.

**Comment by ai** [comment]
Main Autoprefixer API is to add prefixes to clean CSS without prefixes.

Accurate work with all legacy hell is too hard task for me ;). Especially when it do not break CSS.

I highly recommend to clean your CSS sources from prefixes (by `autoprefixer({ browser: [] })`).

But if you will send PR, I will accept it.

**Comment by ben-eb** [comment]
@ai @joelpittet You can also use https://github.com/johnotander/postcss-remove-prefixes. :smile:

**Comment by joelpittet** [comment]
@ai So I'm curious as to why not put the space after the comma?

**Comment by ai** [comment]
@joelpittet Autoprefixer copy your own format. You didn’t put a space in unprefixed version, so Autoprefixer miss it too.

**Comment by joelpittet** [comment]
@ai that screenshot above is a diff, the duplicate green line is what autoprefixer added.  The lines are identical besides that missing space in the new line.

**Comment by joelpittet** [comment]
@ai Oh I see what you mean, it's copying from below, that's where the mistake is!

**Comment by joelpittet** [comment]
NM, this issue, our fault;)
