### ISSUE TITLE
pointer events

### ISSUE THREAD

**Issue by stephenway** [postcss/autoprefixer#577]
I was about to create a pull request to add this feature for IE10, however I'm unsure of your thoughts on it, so I'd like to pose the question. Would it be considered if I made a new hack for `pointer-events` => `-ms-pointer-events`?

http://caniuse.com/#search=pointer%20events

**Comment by ai** [comment]
`pointer-events` has no relations with Pointer Events spec ;)

http://caniuse.com/#feat=pointer-events
