### ISSUE TITLE
autoprefixer throwing error with gulp-less on iOS

### ISSUE THREAD

**Issue by LukasSilo** [postcss/autoprefixer#584]
When we updated our gulp dependencies and gulp-autoprefixer to "3.1.0" it threw 

"Plumber found unhandled error: Error: no writecb in Transform class" on our iOS machines.

My guess is that the problem lies with how gulp-autoprefixer works with gulp-less version "3.0.5". after reverting gulp-autoprefixer back to "2.3.1" it's working with the latest gulp-less again.

**Comment by TrySound** [comment]
@LukasSilo It's not autoprefixer issue. Report it to gulp-autoprefixer

**Comment by TrySound** [comment]
@LukasSilo Or use [gulp-postcss](https://github.com/postcss/gulp-postcss) which is official runner unlike gulp-autoprefixer

**Comment by LukasSilo** [comment]
You can ignore this as I jumped the gun and found the problem internally, sorry about that
