### ISSUE TITLE
Support text-underline-position

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#590]
Safari support `-webkit-text-underline-position`
MDN: https://developer.mozilla.org/zh-CN/docs/Web/CSS/text-underline-position
We need caniuse data.

**Comment by yisibl** [comment]
I'll add the caniuse data.

**Comment by ai** [comment]
We can’t autogenerete `-ms-` prefix, because IE values is very different.

And there is no sense for `-webkit-` prefix, because it doesn’t work without a flag, so it will not work on users machnines.
