### ISSUE TITLE
More understandable release notes

### ISSUE THREAD

**Issue by simevidas** [postcss/autoprefixer#595]
I’ve been following Autoprefixer’s progress for a while now, and I’ve noticed that its release notes often leave me confused about what has changed or how the improvements affect my CSS code. Since Autoprefixer plays an important role in web development, I thought it should have more polished and organized release notes, with more code examples.

Here’s my take on that, based on the [existing release notes for version 6.2](https://github.com/postcss/autoprefixer/releases/tag/6.2.0).

---

### `fill` value

The CSS Sizing module has renamed the `fill-available` value to `fill` ([spec](https://drafts.csswg.org/css-sizing/#valdef-width-fill)).

```css
width: fill;
▼
width: -webkit-fill-available;
width: -moz-available;
width: fill;
```

*Note:* The behavior for the old `fill-available` value is still active, but a warning will be shown ([screen](https://twitter.com/simevidas/status/680230523852185600)).

### Issue: `transition-property` with multiple values https://github.com/postcss/autoprefixer/issues/566

```css
transition-property: color, filter;
▼
-webkit-transition-property: color, -webkit-filter;
transition-property: color, -webkit-filter;
transition-property: color, filter;
transition-property: color, filter, -webkit-filter; // issue with other transition-* properties
```

*Note:* We recommend that you use the `transition` shorthand **instead**, when transitioning multiple properties.

### `text-emphasis-position` property https://github.com/postcss/autoprefixer/issues/578

```css
text-emphasis-position: over;
▼
-webkit-text-emphasis-position: over;
        text-emphasis-position: over;
```

```css
text-emphasis-position: over right;
▼
-webkit-text-emphasis-position: over;
        text-emphasis-position: over right;
```

### `rad`, `grad`, and `turn` units in linear gradients https://github.com/postcss/autoprefixer/issues/589

```css
background-image: linear-gradient(0.25turn, red, blue);
▼
background-image: -webkit-linear-gradient(left, red, blue);
background-image: linear-gradient(0.25turn, red, blue);
```

### Fixed bugs:

 - Missing parentheses in generated `@supports` code (in some cases) https://github.com/postcss/autoprefixer/issues/568

**Comment by ai** [comment]
Yeap, I will try to use more strict format in net release notes.

BTW, do you see formal ChangeLog? https://github.com/postcss/autoprefixer/blob/master/CHANGELOG.md

**Comment by simevidas** [comment]
👍 cool! forgot to check the changelog.
