### ISSUE TITLE
source maps are incorrect when compiling from SCSS

### ISSUE THREAD

**Issue by alvint** [postcss/autoprefixer#596]
I have this Gulp code which compiles three SCSS files (first.scss, last.scss, and app.scss). All plugins are gulp-sourcemaps compatible:

```javascript
return gulp.src(cssFiles)
    .pipe(plugins.if(addSourceMaps, plugins.sourcemaps.init({loadMaps: true})))
    .pipe(plugins.sass())
    .pipe(plugins.autoprefixer())

    // I have verified this code is not the issue--if commented out the problem remains.
    .pipe(plugins.if(!!config.cssFile,plugins.order(
      [
        config.sourceFolder + '**/first.css',
        '!' + config.sourceFolder + '**/*',
        '!' + config.sourceFolder + '**/last.css'
      ],
      {base: '.'}
    )))

    .pipe(plugins.if(!!config.cssFile, plugins.concat(config.cssFile)))
    .pipe(plugins.if(addSourceMaps, plugins.sourcemaps.write('.', {sourceRoot: '../src'})))
    ...
```

When autoprefixer is commented out, the source maps are produced properly:

```
{"version":3,"sources":["sass/first.scss","sass/app.scss","sass/last.scss"],"names":[],"mappings":"AAAA;ACAA;ACAA","file":"all.css","sourcesContent":["// All CSS files are combined into one big file called \"all.css\". This file is\n// guaranteed to be the first file added (the contents of this file will be at\n// the beginning of \"all.css\").\n\n","// app.scss\n\n","// All CSS files are combined into one big file called \"all.css\". This file is\n// guaranteed to be the last file added (the contents of this file will be at\n// the end of \"all.css\").\n\n"],"sourceRoot":"../src"}
```

When autoprefixer is enabled, the source maps are incorrect and point to nonexistent CSS files:
```
{"version":3,"sources":["sass/app.css","sass/first.css","sass/last.css"],"names":[],"mappings":"AAAA;ACAA;ACAA","file":"all.css","sourceRoot":"../src","sourcesContent":[]}
```

**Comment by ai** [comment]
Use `gulp-poscss`. We do not recommend to use `gulp-autoprefixer`, check Autoprefixer docs for correct example.

**Comment by alvint** [comment]
Thanks for the swift reply. I tried replacing the line:

    .pipe(plugins.autoprefixer())

with:

    .pipe(plugins.postcss([plugins.autoprefixer]))

but the issue is still present. I actually simplified my gulp file code above; it really does this because some source files are CSS and some are SCSS:

```javascript
var sassFilter = plugins.filter(['**/*.scss', '**/*.sass'], {restore: true})
return gulp.src(cssFiles)
    .pipe(plugins.if(addSourceMaps, plugins.sourcemaps.init({loadMaps: true})))
    .pipe(sassFilter)
    .pipe(plugins.sass())
    .pipe(sassFilter.restore)
    .pipe(plugins.sass())
    ...
```

Because of that, I don't think I can use the second approach. Any suggestions?

**Comment by ai** [comment]
Ask, `gulp-postcss` author :).

**Comment by alvint** [comment]
Ok. Just out of curiosity, is this plugin no longer supported? Or is it unfeasible to fix this for technical reasons?

**Comment by ai** [comment]
> is this plugin no longer supported?

You ask about `gulp-autoprefixer`?

**Comment by alvint** [comment]
yep

**Comment by ai** [comment]
@alvint it is not a `gulp-autoprefixer` repository ;). It is just a `autoprefixer`. It is plugin for PostCSS. PostCSS is a tool to transform one CSS to other by JS plugins. So PostCSS generates source maps.

Autoprefixer is a plugin, which use power of PostCSS to add prefixes. So you need take a PostCSS, add Autoprefixer plugin to PostCSS and process your CSS content.

But because you use Gulp, you need to take `gulp-postcss`. It is a plugin for Gulp, which contains PostCSS inside.

**Comment by ai** [comment]
@alvint does `plugins.autoprefixer` is your example is `gulp-autoprefixer`? It is wrong. You need to set just `autoprefixer` to `gulp-postcss`.

**Comment by alvint** [comment]
Whoops, I'm sorry for wasting your time! I did not pay attention and posted in the wrong place. Sorry!

**Comment by alvint** [comment]
In my defense, the gulp-autoprefixer page prominently links here so I assumed it was their tracker.

**Comment by ai** [comment]
@alvint yeap, no problem :)
