### ISSUE TITLE
Better support for tab-size property

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#599]
Firefox and Opera 12.1 does not support support `<length>` values. So we should:

1. Does not support the `<length>` values  browser does not generate a prefix.
2. Output corresponding warning.

See also:

* http://caniuse.com/#feat=css3-tabsize
* https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size

**Comment by ai** [comment]
Looks like `unset` is not specified to `tab-size`, it is a global value https://developer.mozilla.org/ru/docs/Web/CSS/unset

**Comment by ai** [comment]
So we should clean this prefixes in every property.

**Comment by yisibl** [comment]
Yes, in this we talk about `tab-size: 18px`.

**Comment by ai** [comment]
I think it is too small optiimization. You should write a separated `postcss-clean-unset-prefixes` plugin, because you can remove any `-o-` prefix for `unset`.
