### ISSUE TITLE
@keyframes prefixer isn`t  entire

### ISSUE THREAD

**Issue by zd1010150** [postcss/autoprefixer#605]
use '@keyframes' to define a animation. From the [page](http://www.w3school.com.cn/cssref/pr_keyframes.asp) of w3School ,I know that there are some prefix to  compatible all the broswers ,which are '-moz-keyframes','-o-keyframes','-webkit-keyframes'.

I have used the autoprefixer to translate the css,But only get the '-webkit-keyframes'.I don`t know if that is a bug .

**Comment by ai** [comment]
`-o-keyframes` and `-moz-keyframes` don’t need right now: http://caniuse.com/#search=animation

This is why w3school pages are bad, because often contains outdated information.
