### ISSUE TITLE
sourceMappingURL causes "unknown word"

### ISSUE THREAD

**Issue by jamesarosen** [postcss/autoprefixer#606]
Simplest reproduction:
```js
var autoprefixer = require('autoprefixer');
var postcss      = require('postcss');
var css = "div {color: blue;}//# sourceMappingURL=vendor.css.map\n";

postcss([ autoprefixer ]).process(css).catch(function (error) {
  console.error(error);
});
```

**Comment by ben-eb** [comment]
`//` comments *are not valid CSS*. If you need to parse this, load the SCSS syntax.

https://github.com/postcss/postcss-scss

**Comment by jamesarosen** [comment]
https://developers.google.com/web/updates/2013/06/sourceMappingURL-and-sourceURL-syntax-changed?hl=en says the official syntax for `sourceMappingURL` starts with `//#`

**Comment by ai** [comment]
@jamesarosen `//` is possible for JS, not for CSS

**Comment by jamesarosen** [comment]
That may only apply to JS. The [proposal doc](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.lmz475t4mvbx) does state,
```
This recommendation works well for JavaScript, it is expected that other source files will have other conventions:
CSS
/*# sourceMappingURL=<url> */
```

**Comment by jamesarosen** [comment]
OK. I'll look at my CSS preprocessor to see why it's emitting JS syntax. Thanks.
