### ISSUE TITLE
Not adding prefixes for user-select

### ISSUE THREAD

**Issue by satazor** [postcss/autoprefixer#609]
It seems that autoprefixer is not adding prefixes for `user-select: none` event though it should according to http://caniuse.com/#feat=user-select-none 

Is this a bug or intended?

Thanks

**Comment by ai** [comment]
Online demo shows that everything is OK. http://autoprefixer.github.io/

Seems like you have problem in your environment. Maybe some other tool.

**Comment by satazor** [comment]
You were right, I needed to use `postcss-import` plugin to see and process my import declarations.

Thanks for the headsup and sorry to bother you.
