### ISSUE TITLE
Disable flexbox using control comments

### ISSUE THREAD

**Issue by slavanga** [postcss/autoprefixer#610]
The new option to disable old flexbox prefixes is very useful. Is it possible to trigger the option selectively with control comments like ```autoprefixer: off```?

**Comment by ai** [comment]
Nope :)

**Comment by ai** [comment]
I can add it. But honestly it will not be in coming monthes :D. I am in the middle of installing Witcher 3 :D.

**Comment by ai** [comment]
What is your use case, where you need to add flexbox prefixes only in few rules?

With power of PostCSS you can make a hack for it :D.

**Comment by slavanga** [comment]
The biggest concern with the old flexbox syntax is that it doesn't support wrapping. I would disable it for the grid but keep it in the rest of the project.

**Comment by ai** [comment]
@slavanga you can write a custom PostCSS plugin to delete unnecessary properties after Autoprefixerr is some rules.

```js
(css) => {
    css.walkDecls('prop-name', decl => {
        if ( checkRuleSelector(decl.parent.selector) ) decl.remove();
    });
}
```

**Comment by slavanga** [comment]
@ai Thank you for the example. This is manageable with a custom workflow. But for people who are working with simple tools like Codekit or Prepros that's not an option. I think it would be easier to control Autoprefixer with control comments in this case.

**Comment by ai** [comment]
Yeap, we should add it to comments. But it really will not be soon — you defintably should trry gulp

**Comment by ai** [comment]
Sorry, right now this fix will slow down Autoprefixer for every users.

If you need to disable some option you need to ask Codekit and Prepros to add option.
