### ISSUE TITLE
No prefixes for transform inside transition

### ISSUE THREAD

**Issue by radist2s** [postcss/autoprefixer#612]
Version of autoprefixer is 6.3.1, for this issue i used this code autoprefixer:
```javascript
autoprefixer({browsers: ['last 9999 version']})
```
CSS rules:
```css
transition: transfrom 0.2s ease;
transform: scale(1);
```
Prefixed CSS rules below:
<img width="142" alt="screenshot at 22 16-04-48" src="https://cloud.githubusercontent.com/assets/725645/12508449/f2ecea70-c121-11e5-8f82-61bbc6a7e703.png">
Am I doing something wrong?

**Comment by ai** [comment]
Strange. I will look later.

BTW, `last 9999 versions` is a bad practice.

**Comment by radist2s** [comment]
Of course is bad, just for this test. I tried all combinations browser rules and still no effect.

**Comment by radist2s** [comment]
Shame on me, it's misprint in transform. Close the issue please.
