### ISSUE TITLE
Lack of .json file-ending in prefixes.coffee necessitates jspm registry override

### ISSUE THREAD

**Issue by MeoMix** [postcss/autoprefixer#618]
Hey,

I'm wondering if you would be open to a PR which adds `.json` to all require statements which interact with `caniuse-db`. @guybedford and I have been talking a bit about how to properly load autoprefixer with jspm.

It's possible to fix the issue on our end by essentially overriding how autoprefixer requires its dependencies, but a more elegant solution would be to resolve the problem at it's source.

You can see a bit more of the conversation here: https://github.com/jspm/registry/issues/749

If you're open to the idea I'll submit a PR adding the file endings ASAP.

**Comment by ai** [comment]
So, adding `.json` will fix Autoprefixer for JSPM and have no effect for `node`, `webpack`, `browserify` or `rollup`?

Of course, it will be very useful PR. But could you try to protect 80 columns line length, please?

**Comment by MeoMix** [comment]
Well, I suspect that the require statements work as-is only because they're unambiguous. If there was another file in the same directory with a different ending then problems would be encountered. Being more explicit with what file you'd like to load feels like it shouldn't break anything.

A quick glance online:

- Node: http://stackoverflow.com/a/9804910/633438 shows that file extension can be omitted, but is valid with it, as well.
- Webpack: https://github.com/webpack/json-loader shows `.json` file-ending for their JSON loader.
- Browserify: http://stackoverflow.com/a/17502924/633438 shows an example with `.txt`, but I wasn't able to find one for `.json` explicitly.
- Rollup: https://github.com/rollup/rollup-plugin-json shows an example with `.json`

**Comment by MeoMix** [comment]
Oh, even better, as I look at the file more closely I see several features which are already being loaded with `.json`. So, I think I can confidently say this won't introduce any issues.

Do you have a preferred formatting for lines which would exceed 80 characters? I'm looking for an example, but all of the `feature require...` lines appear to just be short enough.

**Comment by guybedford** [comment]
@MeoMix thanks for opening this, sounds like a good direction!

**Comment by ai** [comment]
Released in 6.3.2.
