### ISSUE TITLE
Ignore dynamic tags like Liquid/Shopify

### ISSUE THREAD

**Issue by millerpils** [postcss/autoprefixer#622]
Hi guys,

Not so much an issue, but a query: we use some Liquid tags in the CSS to dynamically add colours to each deployment of a theme. I can get SASS to ignore the tags thusly:

```
background: #{'{{theme_preferences.header_background_colour}}'};
```

But Autoprefixer fails with a syntax error? Is there anything I can do?

**Comment by millerpils** [comment]
Something like this wouldn't appear to work:

```
body {
	/* autoprefixer: off */
	background: #{'{{theme_preferences.header_background_colour}}'};
}
```

**Comment by ai** [comment]
@millerpils try [postcss-scss](https://github.com/postcss/postcss-scss) parser instead of default CSS parser in PostCSS. SCSS has interpolation like `#{}`, but I am not sure about inherit `{`.

If SCSS parser will fails too, you should create a new parser for it. It will be very useful. Write me if you have problems with SCSS parser, I will give you simple result how to write new parser for PostCSS.

**Comment by millerpils** [comment]
I just ran it through another function in the end, that doesn't try and do any autoprefix magic.

Cheers.

**Comment by gabrielloeb** [comment]
The postcss-scss parser also fails. This would be a huge help to anyone building on Shopify.

If you have simple instructions for creating a parser to handle `{{ }}` I would be interested in giving it a shot.

```
Fatal error: Unknown word
$colorPrimary: {{ settings.color_primary }};
                  ^
```

**Comment by ai** [comment]
@gabrielloeb https://github.com/postcss/postcss/blob/master/docs/syntax.md

**Comment by mattsince87** [comment]
I'm having exactly this issue.. 
I'm compiling my Sass and then using `.pipe(rename('theme.scss.liquid')` to rename the sass file for Shopify. I'm then using `.pipe(postcss([ autoprefixer() ]))` inside my autoprefixer task but it's pumping out the same old syntax error.

Has anyone managed to fix this issue. I'm afraid my site's going to fall on it's arse if i just opt out of using autoprefixer.

**Comment by ai** [comment]
Sorry, creating a parse is not a easy task. Nobody did it.
