### ISSUE TITLE
Doesn't remove or add prefix. Not sure which?

### ISSUE THREAD

**Issue by JonWallsten** [postcss/autoprefixer#623]
```
Settings: { browsers: ['last 2 versions', 'safari 5', 'opera 12.1', 'ios 6', 'android 4']}

Input:
.test {
   -webkit-border-radius: 50%;
   -moz-border-radius: 50%;
   -ms-border-radius: 50%;
   -o-border-radius: 50%;
   border-radius: 50%;
}

Output:
.test {
   -webkit-border-radius: 50%;
   -moz-border-radius: 50%;
   -ms-border-radius: 50%;
   -o-border-radius: 50%;
   border-radius: 50%;
}

Expected:
?


Settings: { browsers: ['last 2 versions', 'safari 5', 'opera 12.1', 'ios 6', 'android 4']}
Input:
.test {
   border-radius: 50%;
}

Out: 
.test {
   border-radius: 50%;
}

Expected:
?
```

One of these are wrong, right? Either it should remove, or add? 
Am I doing something wrong?

**Comment by ai** [comment]
I tested your input in [online demo](http://autoprefixer.github.io/) and everything works fine. Seems like you have a problem in environment (Stylus mixins?)

**Comment by JonWallsten** [comment]
I'm not using any mixins other than variables. It's a really simple setup.
I tried in another file now. And that seems to work. It's really weird. 
I'll continue debugging in my environment. Thanks!
