### ISSUE TITLE
Adding a prefixed value to `transition-property` doesn't correspond to an added value to `transition-duration` also

### ISSUE THREAD

**Issue by fabiospampinato** [postcss/autoprefixer#624]
Let's say I have the following CSS:
```
.foo {
  transition-property: opacity, transform;
  transition-duration: 1s, 2s;
}
```
If we configure autoprefixer so that it will prefix `transform` with `-webkit-` we'll get:
```
.foo {
  transition-property: opacity, transform, -webkit-transform;
  transition-duration: 1s, 2s;
}
```
The problem is, as you probably already guessed, we added a new value to `transition-property` without also adding a value to `transition-duration`, this will result, at least on Chrome, in a transform transition happening in `1s` instead of the desired `2s`, since that as stated in the MDN: "If there are fewer durations specified than in the master list, the user agent repeat the list of durations.".

**Comment by ai** [comment]
Yeap, and this is why Autoprefixer print a warning on this cases with suggestion to use 1 property `transition` instead of 2.

There is no way to correctly add prefix in all possible cases (for example, some `transition-duration` could be in other rule with cascade).
