### ISSUE TITLE
value changing automaticaly

### ISSUE THREAD

**Issue by Kunthu** [postcss/autoprefixer#625]
[Autoprefixer.mov.zip](https://github.com/postcss/autoprefixer/files/150524/Autoprefixer.mov.zip)

I entered 80 deg and when I used autoprefixer it added webkit with and changed 80 to 10 deg

**Comment by ai** [comment]
1. Do not use Autoprefixer as text editor plugin. Code with prefixes is hard to read and manually excution is a worse maintaining. Use webpack or Gulp.
2. You should post input/output CSS code examples. It is much better than video.

**Comment by ai** [comment]
`linear-gradient()` use different direction, than `-webkit-gradient`. So Autoprefixer fix direction angle.

It is totally expected behaviour https://github.com/postcss/autoprefixer/blob/master/test/cases/gradient.out.css#L2-L4
