### ISSUE TITLE
:placeholder-shown

### ISSUE THREAD

**Issue by tremby** [postcss/autoprefixer#627]
It seems that the official name for the input element placeholder pseudo-class will be `:placeholder-shown` according to the [selectors level 4 draft](https://drafts.csswg.org/selectors-4/#placeholder). Perhaps `::placeholder` should be updated to this?

**Comment by iamvdo** [comment]
For the record, both are in specs and have different meaning. See for `::placeholder` : https://drafts.csswg.org/css-pseudo-4/#placeholder-pseudo

**Comment by ai** [comment]
@tremby yeap, `:placeholder-shown` is a input itself, but `::placeholder` is a text inside this input.

Maybe we should add this question to FAQ. Do you want to send PR?

**Comment by tremby** [comment]
Oh! Not sure how I missed that. Thanks! Sorry for the noise.
