### ISSUE TITLE
.autoprefixerrc config file

### ISSUE THREAD

**Issue by adamcbrewer** [postcss/autoprefixer#628]
In a similar vein to something like a [.babelrc file](https://babeljs.io/docs/usage/babelrc/), or any 'rc' file for that matter.

My thinking is this would help keeping browser settings consistent between using IDE plugins, build tasks , npm scripts or command line scripts.

**Comment by ai** [comment]
It already exists `browserslist` https://github.com/ai/browserslist#config-file

**Comment by adamcbrewer** [comment]
Awesome, cheers!
