### ISSUE TITLE
-webkit- prefix not applied to 'transform: translate(...'

### ISSUE THREAD

**Issue by rfelliot** [postcss/autoprefixer#631]
The code `transform: translate(-50%, -50%);` does not function properly on iOS without adding the webkit prefix `-webkit-transform: translate(-50%, -50%);`, a case that does not appear to be currently handled by autoprefixer:

[https://github.com/postcss/autoprefixer/blob/1647330f1db28a6ebee6165651820fbdd126d99a/lib/hacks/transform-decl.coffee#L6](url)

**Comment by ai** [comment]
I tested on [online demo](http://autoprefixer.github.io/) and Autoprefixer with default browsers adds `-webkit-transform`.

That code line only about 3D transforms for IE 9. It doesn’t relevant with `-webkit-transform`.
