### ISSUE TITLE
Add WebKit prefixes for Grid Layout 

### ISSUE THREAD

**Issue by pepelsbey** [postcss/autoprefixer#633]
Can I Use data for WebKit nightlies and Safari TP [is there](https://github.com/Fyrd/caniuse/blob/master/features-json/css-grid.json#L164), it’s your turn now. Don’t make me write all prefixes myself for my Grid Layout demos please. It makes me sick:

```
.table__cell-1 {
	-webkit-grid-area: 2 / 2 / 3 / 3;
	grid-area: 2 / 2 / 3 / 3;
	}
.table__cell-2 {
	-webkit-grid-area: 6 / 2 / 7 / 3;
	grid-area: 6 / 2 / 7 / 3;
	}
.table__cell-3 {
	-webkit-grid-area: 4 / 6 / 5 / 7;
	grid-area: 4 / 6 / 5 / 7;
	}
```

**Comment by ai** [comment]
Webkit doesn’t need any syntax changes? Only prefix all properties?

**Comment by pepelsbey** [comment]
AFAIK, yes. WebKit’s implementation looks 100% compatible with Chromium’s one. There are some rendering differences in Firefox, but it’s not a question of a different syntax, some implementation details maybe.

**Comment by ai** [comment]
Browserslist 1.3.1 with Safari TP support was released

**Comment by ai** [comment]
Done 62f03b0

**Comment by ai** [comment]
Released in 6.3.6. Can you check that everything is OK?

**Comment by pepelsbey** [comment]
It’s not okay at all :(

```
postcss --use autoprefixer before.css -o after-actual.css
```

[See](https://gist.github.com/pepelsbey/40b26f68c67fee8a366542d8ea4875f5) `before.css` without any prefixes that works fine in all _behind-the-flags_ browsers, `after.css` that works fine in WebKit and Safari TP and `after-actual.css` made by AP that’s pretty much useless since there’s no prefixes for WebKit and it doesn’t make sense to add `-ms-` prefixes since IE10+ inplementation is outdated and not compatible with the rest implementations.

**Comment by ai** [comment]
Can you create a two separated issues:
* config to disable `-ms-` prefixes (old webkit flexbox implementation was not 100% compatible too but we add prefixes)
* clear description about `-webkit-` issue

**Comment by pepelsbey** [comment]
@ai, Grid Layout [will be unprefixed](https://bugs.webkit.org/show_bug.cgi?id=157137) in the next Sarari TP, so you can relax and roll back prefixes for Safari.
