### ISSUE TITLE
consider handling old gradients which are still supported in browsers

### ISSUE THREAD

**Issue by davidmaxwaterman** [postcss/autoprefixer#634]
I recently incorporated autoprefixer (via postcss-cssnext) into a project I am refactoring. It uses some css rules that set the background to a gradient - there are a few, but here's one :

<https://github.com/01org/webapps-scientific-calculator/blob/master/app/css/lazy.css#L690>

```
    background: -webkit-gradient(linear, left top, right top, from(#3f4140), to(#1d2021));
```

When adding postcss-cssnext, I decided to remove all `-webkit-` prefixes assuming that autoprefixer would add the back in again along with versions for other browsers.
For other instances that were prefixed, that was indeed the case, but not for `gradient()`. I didn't get any warning either.
The odd thing is, if I add the prefixes back in, they still work (in Google Chrome	50.0.2661.57 (Official Build) beta (64-bit)).

As a user, I would have expected something other than silence.

Ideally, I would want them to be converted into the newer version and prefixed appropriately; and for there to be a warning to tell me to change them in the source.

Alternatively, a message to warn me I'm using old versions of property values would be useful (perhaps with a reference to how to convert them).

Either way, this issue is purely to have the problem - and a fix for it - considered.

In case anyone finds this issue, I fixed the problem by manually converting the gradients - and autoprefixer handles this without any problem :

<https://github.com/01org/webapps-scientific-calculator/blob/maxw-pwa/app/css/lazy.css#L690>

```
    background: linear-gradient(to right top, #3f4140, #1d2021);
```

**Comment by ai** [comment]
Sorry, the Autoprefixer API is simple: you write CSS by specs without prefixes and Autoprefixer do the rest.

In some prefix-less future users will remove Autoprefixer. And CSS sources should be correct for future browsers. This is why we can’t support old prefixes as input CSS.

Also it was very bad practice to write webkit-only CSS code. You should think about it and never make this mind mistake.

**Comment by davidmaxwaterman** [comment]
Actually, it's fine to write webkit only css code if you're only targeting webkit - this was the case here since it was a chrome app and we didn't care about other browsers. Of course, now I *do* care, and it's one of the reasons I'm refactoring it...hence my use of autoprefixer.

I totally understand not fixing it - it would be nice, but fair enough. However, I think it would be a good thing to consider giving a warning...but perhaps that's not in the scope of this tool and I should be looking at using some other tool for that (I seem mention of stylelint)? What do you think?

**Comment by ai** [comment]
We can write other PostCSS plugin to convert webkit gradients.

Warnings is nice, but sometimes people need a browser-specific hacks. What do you think about it?

**Comment by davidmaxwaterman** [comment]
Sure, it's up to you. I just wanted to make sure it could be considered. It seems a little out-of-scope for this, and it's only my work flow (ie removing -webkit- and expecting them to be added back in) that made me think this might be the correct place for a warning (or fix).
If not, then no problem...feel free to close. At least this is here for someone else, if they have the same problem :)
Thanks for your time.

**Comment by ai** [comment]
We can write other PostCSS plugin to convert webkit gradients.

Warnings is nice, but sometimes people need a browser-specific hacks. What do you think about it?

**Comment by ai** [comment]
@davidmaxwaterman I remember! We already have a good plugins to fix webkit-only code https://github.com/postcss/autoprefixer#how-to-work-with-legacy--webkit--only-code

**Comment by davidmaxwaterman** [comment]
That's interesting. I'll consider using it (I think I've already converted all mine)...thanks!
