### ISSUE TITLE
`filter` property is not prefixed when inside `transition`

### ISSUE THREAD

**Issue by simevidas** [postcss/autoprefixer#636]
Currently, Autoprefixer transforms this:

```css
transition: 1s filter linear;
```

into this:

```css
-webkit-transition: 1s filter linear;
transition: 1s filter linear;
```

However, the Chromium browsers currently still require `-webkit-filter` ([Can I use](http://caniuse.com/#feat=css-filters)). Additionally, there seems to be a further complication (according to [@zachleat on Twitter](https://twitter.com/zachleat/status/717380812358836225)). The correct output could be this (not sure):

```css
-webkit-transition: 1s -webkit-filter linear, 1s filter linear;
transition: 1s -webkit-filter linear, 1s filter linear;
```

**Comment by ai** [comment]
Wrong transition syntax (as I know). Try: `transition: filter 1s linear`.

**Comment by simevidas** [comment]
Ah, I see. My bad :) The output seems to check out.
```css
-webkit-transition: -webkit-filter 1s linear;
transition: -webkit-filter 1s linear;
transition: filter 1s linear;
transition: filter 1s linear, -webkit-filter 1s linear;
```

**Comment by zachleat** [comment]
Wow, look at that output! Impressively comprehensive.

**Comment by yisibl** [comment]
See also https://bugs.webkit.org/show_bug.cgi?id=157606
