### ISSUE TITLE
`transition` shorthand duration and delay order

### ISSUE THREAD

**Issue by zachleat** [postcss/autoprefixer#637]
As discovered in https://github.com/postcss/autoprefixer/issues/636, the order of the duration and delay values is more flexible in the specification that autoprefixer allows.

See: https://www.w3.org/TR/css3-transitions/#single-transition

> Note that order is important within the items in this property: the first value that can be parsed as a time is assigned to the transition-duration, and the second value that can be parsed as a time is assigned to transition-delay.

A simple test case would be that `transition: 1s filter linear;` and `transition: filter 1s linear;` should produce the same output. But there are many more combinations, with two time values allowed.

cc @simevidas

**Comment by ai** [comment]
Done e8b2359

**Comment by ai** [comment]
Released in 6.4.
