### ISSUE TITLE
Browserslist issue - some kinds of query don't work.

### ISSUE THREAD

**Issue by panteng** [postcss/autoprefixer#639]
postcss: [ autoprefixer({ browsers: ['last 10 versions'] }) ]

This works when running `webpack-dev-server --inline --hot`.

    postcss: [ autoprefixer({ browsers: ['not ie <= 8'] }) ]

This doesn't work when running `webpack-dev-server --inline --hot`.

    postcss: [ autoprefixer({ browsers: ['last 10 versions'] }) ]

This doesn't work when running `webpack -p` but works when running `webpack-dev-server --inline --hot`.

Waiting for help. Thank you.

System: Win7 x64
Node: v5.10.0
Npm: 3.8.3

**Comment by ai** [comment]
What “doesn't work” means exactly? It fails with error (I need stacktrace)? It doesn’t add prefixes (I need input CSS)?

**Comment by panteng** [comment]
My fault.
For example, if I set `browsers: ['not ie <= 8']` these css:

    transform: rotate(45deg) translateX(-50%) translateY(-50%);

should be prefixed like:

    -webkit-transform: rotate(45deg) translateX(-50%) translateY(-50%);
         -ms-transform: rotate(45deg) translateX(-50%) translateY(-50%);
             transform: rotate(45deg) translateX(-50%) translateY(-50%);

But it isn't. No prefix is added.

**Comment by panteng** [comment]
if I set browsers: ['last 10 versions'], and these css:

    transform: rotate(45deg) translateX(-50%) translateY(-50%);

is correctly prefixed when I run command `webpack-dev-server --inline --hot`:

    -webkit-transform: rotate(45deg) translateX(-50%) translateY(-50%);
     -ms-transform: rotate(45deg) translateX(-50%) translateY(-50%);
         transform: rotate(45deg) translateX(-50%) translateY(-50%);

but not correct prefixed when I run command `webpack -p`. The result is like: 

    -webkit-transform: rotate(45deg) translateX(-50%) translateY(-50%);
         transform: rotate(45deg) translateX(-50%) translateY(-50%);
    
The `-ms-` prefix is missing.

**Comment by ai** [comment]
Hm. Seems `"not ie <= 8"` remove browsers from previous queries. So you should write `"> 1%", "not ie <= 8"`.

If you set `"not ie <= 8"` it return empty browsers list.

You can debug your browsers queries by `browserslist` CLI tool: https://github.com/ai/browserslist#usage

**Comment by panteng** [comment]
@ai 
This is weird. I thought `not ie <= 8` should return all browsers except IE <=8.

**Comment by panteng** [comment]
@ai 
After reading the [browserslist doc](https://github.com/ai/browserslist#queries) again. I know it's my mistake about the `not ie <= 8` query.

> `not ie <= 8`: exclude browsers **selected before** by previous queries. You can add not to any query.

Sorry about this.

**Comment by panteng** [comment]
I find the reason why the `-ms-` prefix is missing.
It is removed by the css-loader. https://github.com/webpack/css-loader#minification
Css-loader treat `-ms-transform` as outdated prefix and removes it.
I have to use the `-autoprefixer` tag to disable it.

Thank you for helping. @ai

**Comment by ai** [comment]
@panteng Nice. On this Saturday I will go to Shanghai. Do you want to meet? I want to know about Chinese web development.

**Comment by panteng** [comment]
@ai oh really? No problem. I'd like to meet. Do you have a wechat account?

**Comment by ai** [comment]
Awesome! =^_^= My wechat: +79117696571
