### ISSUE TITLE
Prefix needed for background-clip: text

### ISSUE THREAD

**Issue by mikeesouth** [postcss/autoprefixer#643]
Hi,

If I understood it correctly, background-clip is supported well on different browsers but the value "text" is new and only supported on webkit (and safari?):

```
background-clip: text;
```

This does not get prefixed by autoprefixer so I have to add `-webkit-background-clip: text;` manually and then it works.

I hope that this setting gets adopted by other browsers in the future, it's a great feature.

See more here: [Using background clip for text with CSS fallback](http://nimbupani.com/using-background-clip-for-text-with-css-fallback.html)

**Comment by ai** [comment]
Autoprefixer adds prefixes only to standard properties. It is a -webkit- only hack.

**Comment by carlosjeurissen** [comment]
Can we reconsider this? Seems like this is supported unprefixed in Edge and Firefox. And prefixed with webkit in chrome, edge, opera and safari. 
See: https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip
It's also in the CSS Backgrounds module level 4 W3C Editor's draft:
https://drafts.csswg.org/css-backgrounds-4/#background-clip

**Comment by ai** [comment]
Sure. I will think about it in January.

**Comment by ai** [comment]
Closing it as https://github.com/postcss/autoprefixer/issues/831 duplicate
