### ISSUE TITLE
Gradient isn't being prefixed

### ISSUE THREAD

**Issue by reneruiz** [postcss/autoprefixer#644]
Hey all, so I'm using the latest version of AutoPrefixer and I've run into a small issue.

Everything else is being prefixed just fine, except for `linear-gradient`:

```
background: linear-gradient(135deg, $primary-color 0%, $primary-shade 62%);
```

It's just simply compiling to

```
background: linear-gradient(135deg, #0c4b90 0%, #06192d 62%);
```

It seems like I'm using the right syntax, and the web version seems to prefix it just fine. But I can't quite figure out what the issue is.

Config:
`['last 2 versions', 'ie >= 9']`

**Comment by ai** [comment]
https://github.com/postcss/autoprefixer#why-doesnt-autoprefixer-add-prefixes-to-border-radius

**Comment by reneruiz** [comment]
I should take time to read more carefully. Apologies!
