### ISSUE TITLE
Support for keyframes

### ISSUE THREAD

**Issue by aug-riedinger** [postcss/autoprefixer#648]
I'm refactoring my code using autoprefixer.

I have this code in my base:

```
@-webkit-keyframes spin {
    0% { -webkit-transform: rotate(0deg); }
    100% { -webkit-transform: rotate(359.999deg); }
}

@-moz-keyframes spin {
    0% { -moz-transform: rotate(0deg); }
    100% { -moz-transform: rotate(359.999deg); }
}


@-ms-keyframes spin {
    0% { -ms-transform: rotate(0deg); }
    100% { -ms-transform: rotate(359.999deg); }
}

@-o-keyframes spin {
    0% { -o-transform: rotate(0deg); }
    100% { -o-transform: rotate(359.999deg); }
}

@keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(359.999deg); }
}
```

With autoprefixer I get:

```
@-webkit-keyframes spin {
  0% {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
  }

  100% {
    -webkit-transform: rotate(359.999deg);
            transform: rotate(359.999deg);
  }
}

@keyframes spin {
  0% {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
  }

  100% {
    -webkit-transform: rotate(359.999deg);
            transform: rotate(359.999deg);
  }
}
```

which is coherent with 
```
rake autoprefixer:info | grep keyframes  
  @keyframes: webkit
```

I know autoprefixer **is** better documented than me (or whoever I copied the code from), I'm *guessing* the other ones aren't necessary, but how can be sure about this? Shouldn't there be a page in a wiki or something that explains for every prefixable rule how the decision has been made?

I cannot afford a regression in production...

**Comment by TrySound** [comment]
@aug-riedinger autoprefixer rely on caniuse data. [Sorry, no wiki](http://caniuse.com/). List of browsers you can pass as `browsers` options
https://github.com/postcss/autoprefixer#browsers

**Comment by ai** [comment]
Here is a answer
https://github.com/postcss/autoprefixer#why-autoprefixer-uses-unprefixed-properties-in--webkit-keyframes
