### ISSUE TITLE
Autoprefixer reduces sourceMap

### ISSUE THREAD

**Issue by aslushnikov** [postcss/autoprefixer#649]
Hi Andrey,

The autoprefixer turned out to output reduced sourceMap, i.e. it reduces the amount information in the initial sourcemap. The example repo is here: [aslushnikov/autoprefixer-breaks-sourcemap](https://github.com/aslushnikov/autoprefixer-breaks-sourcemap)

SourceMap **without** autoprefixer: [sourceMap](https://sokra.github.io/source-map-visualization/#base64,ZGl2IHsKICBjb2xvcjogcmVkOyB9CgovKiMgc291cmNlTWFwcGluZ1VSTD1zdHlsZS5jc3MubWFwICovCg==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic3R5bGUuY3NzIiwic291cmNlcyI6WyJzdHlsZS5zY3NzIl0sIm1hcHBpbmdzIjoiQUFFQSxBQUFBLEdBQUcsQ0FBQztFQUNBLEtBQUssRUFIRCxHQUFHLEdBSVYiLCJuYW1lcyI6W119,JGNvbG9yOiByZWQ7CgpkaXYgewogICAgY29sb3I6ICRjb2xvcjsKfQoK) - notice how `red` sass variable is mapped to css property value.
SourceMap **with** autoprefixer: [sourceMap](https://sokra.github.io/source-map-visualization/#base64,ZGl2IHsKICBjb2xvcjogcmVkOyB9CgovKiMgc291cmNlTWFwcGluZ1VSTD1zdHlsZS5jc3MubWFwICovCg==,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInN0eWxlLnNjc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBRUE7RUFDSSxXQUhPLEVBSVYiLCJmaWxlIjoic3R5bGUuY3NzIn0=,JGNvbG9yOiByZWQ7CgpkaXYgewogICAgY29sb3I6ICRjb2xvcjsKfQoK) - notice how mapping is done property-wise.

Could this be fixed?

**Comment by ai** [comment]
I could be fixed only in PostCSS 6.0. (Autoprefixer is just a small plugin all work is done by PostCSS)

Where did you use value parts source maps? As I know Google Chrome uses source map for entire declaration.

**Comment by aslushnikov** [comment]
Not really, you can **Ctrl-Click** (or **Cmd-Click** on Mac) on property value to jump to the value declaration in source. (Unfortunately, we did a somewhat poor job surfacing this functionality...)

**Comment by ai** [comment]
Could you please open a issue in postcss repo? (I am in Iran and have bad Internet)

**Comment by aslushnikov** [comment]
Sure, my pleasure!
