### ISSUE TITLE
transform is never prefixed

### ISSUE THREAD

**Issue by wouterlemoine** [postcss/autoprefixer#650]
Hello, 

The property "transform" and "flexbox"  is never prefixed with webkit-prefixes. This is bad because it really needs to be prefixed for ipad (safari8) and so on. I configured my settings to "iOS >= 6, safari >= 6, chrome > 2" to force a prefix, but this didn't help. 
It does prefix for -ms.

Can you fix this? 

Kind regards.
W.

**Comment by TrySound** [comment]
@wouterlemoine There is no `flexbox` property

**Comment by wouterlemoine** [comment]
Indeed, this is a value of the "display" property, as seen on https://css-tricks.com/using-flexbox/ . 
I can understand that it is not included in this project. :) 

The main issue however is about the "transform" property. As Autoprefixer creates prefixes for "-ms", it's stange it doens't do this for "-webkit".

**Comment by wouterlemoine** [comment]
i fixed this issue by removing the IE : just "last 5 versions" instead of  "ie >= 9, last 5 versions"

**Comment by ai** [comment]
Autoprefixer [online demo](http://autoprefixer.github.io/) works with `transform` normally.

So problem is in your environment or input CSS. Show me your input CSS, maybe I can help you with it.

**Comment by jitendravyas** [comment]
I also have this problem https://github.com/postcss/autoprefixer/issues/930

**Comment by teloe** [comment]
in case this helps anyone. adding
```
"browserslist": [
    "last 2 versions"
]
```
to your package.json should do the trick.
