### ISSUE TITLE
Flexbox webkit prefixes are missing for flex

### ISSUE THREAD

**Issue by BarTsouri** [postcss/autoprefixer#656]
Hi,

I use autoprefixer with the following argument: `{browsers: ['last 3 versions']}`.
The -webkit prefix was working fine for flex attributes until 5 days ago, when it suddenly stopped. After a small investigation I found out that caniuse-db is responsible for this bug. 
In the moment of writing, the dependencies of autoprefixer in package.json includes `"caniuse-db": "^1.0.30000382"`. caniuse-db was updated recently to version 1.0.30000466, which apparently causes the bug. After removing this version and installing 1.0.30000464 things came back to normal.

I would advise you to set caniuse-db version 1.0.30000464

**Comment by ai** [comment]
Doublicate https://github.com/postcss/autoprefixer/issues/655
