### ISSUE TITLE
display: -webkit-box breaks Safari on iOS 7 & 8

### ISSUE THREAD

**Issue by mdix** [postcss/autoprefixer#657]
Hi,

## gulp setup:
```
                    require('autoprefixer')({
                        remove: false,
                        browsers: [
                            'last 2 Chrome versions',
                            'last 2 Firefox versions',
                            'Explorer >= 11',
                            'last 1 Edge versions',
                            'last 2 iOS versions',
                            'last 1 Safari versions',
                            'last 2 ChromeAndroid versions',
                            'Android >= 4.1'
                    ] })
```

## css before autoprefixer:
```
.product-view {
    .product-essential {
        display: flex;
   }
}
```

## css after autoprefixer:
```
.product-view .product-essential {
  display: -webkit-box;
  display: flex;
}
```

The first container inside product-essential now gets the whole height, resulting in the second container beeing invisible. Seems to be related to https://github.com/ai/autoprefixer-core/issues/55.

<img width="556" alt="screen shot 2016-05-18 at 10 14 53" src="https://cloud.githubusercontent.com/assets/1155015/15353681/7c34bc12-1cea-11e6-8404-ff164ef75cba.png">
<img width="550" alt="screen shot 2016-05-18 at 10 15 07" src="https://cloud.githubusercontent.com/assets/1155015/15353682/7c46e662-1cea-11e6-98f4-a58f1739323d.png">

**Comment by ai** [comment]
Last 2 iOS version is 9.3 and 9.2. You can always debug your browsers set with `browserslist` CLI.

**Comment by mdix** [comment]
Are you sure that last 2 iOS versions are 9.3 and 9.2? In the [browserlist documentation](https://github.com/ai/browserslist) you mention 

> last 2 versions: the last 2 versions for each major browser.
> last 2 Chrome versions: the last 2 versions of Chrome browser.

Why is this different for iOS and where is the documentation for that?

Thanks and best
Marc

**Comment by ai** [comment]
@mdix “major browser”, but not “major release” ;). `last 2 versions` is a last 2 version according Can I Use (row in the support table).

**Comment by ai** [comment]
Browsers has very different versions policy, so it will be impossible to parse version.

**Comment by mdix** [comment]
So, to get it right,

`last 3 versions` 

for iOS would be 9.3, 9.2 and 8.4, because
<img width="159" alt="screen shot 2016-05-18 at 15 03 00" src="https://cloud.githubusercontent.com/assets/1155015/15359452/b582bf18-1d09-11e6-90e3-d1647f5f881b.png">

for Chrome would be 50, 49, 48, because
<img width="153" alt="screen shot 2016-05-18 at 15 03 04" src="https://cloud.githubusercontent.com/assets/1155015/15359480/d95dd242-1d09-11e6-85b3-ad554f3e563f.png">

Is that right?

**Comment by ai** [comment]
:+1:

**Comment by mdix** [comment]
Mind mentioning this in the browserslist README, close to the example part? I'm pretty sure I'm not the only one confused by this.

**Comment by ai** [comment]
@mdix yeap, could you send a PR?
