### ISSUE TITLE
cursor: grab needs -webkit prefix

### ISSUE THREAD

**Issue by baptistebriel** [postcss/autoprefixer#659]
Hi,
Given this CSS property and value:

```css
cursor: grab;
```

...the output result is:

```css
cursor: -moz-grab;
cursor: grab;
```

...while it should be:

```css
cursor: -webkit-grab;
cursor: -moz-grab;
cursor: grab;
```

The thing is that if I add these lines by myself, `-webkit` will still be removed.
I tried adding `remove: false` to the autoprefixer options, but with no result.

```javascript
.pipe(autoprefixer({
  browsers: ['last 2 versions'],
  remove: false,
  cascade: false
}))
```

Any ideas? Thanks a lot!

**Comment by ai** [comment]
`-webkit- prefix exists in [online demo](http://autoprefixer.github.io/)

P.S. we don’t need `-moz-` according [Can I Use](https://github.com/Fyrd/caniuse/blob/master/features-json/css3-cursors-grab.json).

**Comment by developerdizzle** [comment]
Having a similar issue with webpack/postcss; installed autoprefixer today.  I don't get `-webkit-` or `-moz-`.  FYI the online demo is using a 5-month old build of Autoprefixer.

```js
  postcss: function () {
    return [autoprefixer({
      browsers: ['> 1%', 'last 2 versions'],
    })];
  },
```

**Comment by ai** [comment]
@developerdizzle try this first https://github.com/postcss/autoprefixer#no-prefixes-in-production

**Comment by ai** [comment]
@developerdizzle I tested in my Autoprefixer porject dir:

```js
var autoprefixer = require('./');
var css = 'a { cursor: grab; }'
console.log(autoprefixer.process(css).css)
```

Output was `a { cursor: -webkit-grab; cursor: grab; }`
