### ISSUE TITLE
Angle unit `rad` can not be translated into right `deg` value.

### ISSUE THREAD

**Issue by gucong3000** [postcss/autoprefixer#663]
360deg should be equal to 2π rad

**Comment by gucong3000** [comment]
`rad` which represents an [angle](https://developer.mozilla.org/en-US/docs/Web/CSS/angle) in [radians](https://en.wikipedia.org/wiki/Radian).  One full circle is 2π [radians](https://en.wikipedia.org/wiki/Radian) which approximates to 6.2832rad. 1rad is 180/π degrees. E.g. 0rad, 1.0708rad, 6.2832rad.

**Comment by ai** [comment]
Does issue not critical you? I need finish PostCSS 5.1 before next Autoprefixer release :(

**Comment by ai** [comment]
Thanks. Released in 6.4.
