### ISSUE TITLE
Sourcemaps corruption (nested blocks?)

### ISSUE THREAD

**Issue by winamp** [postcss/autoprefixer#665]
Autoprefixer affects mapping of sourcemaps, so it always points to the first line of the file.

Here is a sourcemap without autoprefixer:
![pure](https://cloud.githubusercontent.com/assets/996918/15555281/e416c554-227c-11e6-9cfe-7b8e217b21b6.png)
After autoprefixer was applied:
![autoprefixed](https://cloud.githubusercontent.com/assets/996918/15555280/e4164f20-227c-11e6-99c3-19e7b13f7e4f.png)

I've created a small setup https://github.com/winamp/autoprefixer-sourcemaps based on simplified stack we are currently using in our project. To utilize it, please run `npm install`, `gulp sass`, open files in html folder, inspect red Test.

**Comment by ai** [comment]
Autoprefixer is just a plugin for PostCSS, so this issue is related to PostCSS.

If you remove Autoprefixer from PostCSS, will you still have problems?

**Comment by winamp** [comment]
Yes, the issue it still there if I pass empty array to PostCSS

**Comment by ai** [comment]
Could I ask you to create a issue in PostCSS repo for better organizing :)

**Comment by winamp** [comment]
https://github.com/postcss/postcss/issues/814
