### ISSUE TITLE
transform property not getting prefixed

### ISSUE THREAD

**Issue by thykka** [postcss/autoprefixer#666]
So i've been using the same gulp setup for many months, but today as I was updating an old project, I noticed it doesn't look right on Android (4.2). Turned out the compiled css was missing -webkit prefix for the transform property (which previously did receive the prefix as it should).

According to caniuse, this prefix is needed for all pre-5 Androids.

Here's my gulpfile and a simple test case, which demostrates the issue:
https://gist.github.com/thykka/b450db9742246245818807d7642e9247

There is no issue when using the same settings with the online autoprefixer though, which is weird.

Any ideas?

**Comment by ai** [comment]
@thykka we have too many issues about this behavior and I even posted a tweet how to fix it http://twitter.com/autoprefixer

1. Old Android and Safari is not in default `"last 2 versions"` anymore. So you need be sure to have them in browsers list.
2. Right now many tools contains Autoprefixer. For example, webpack uses Autoprefixer to minify CSS. So you should store your browsers list in `browserslist` config in your project root — so you will be sure, that all tools use same browsers list (this config is not only for Autoprefixer, but for doiuse, cssnext and many other tools).

**Comment by thykka** [comment]
This is not just "last 2 versions" though, I also have "android 4" in my config, yet the prefixes remain to be seen.

**Comment by ai** [comment]
@thykka show me input, output and expected output CSS

**Comment by thykka** [comment]
@ai a sample input and output is included in the gist I linked in my first comment.

**Comment by ai** [comment]
Do you read my 2 point in first post? You need to have `browserslist` config, because many other tools uses Autoprefixer inside.

If you will go and test pure Autoprefixer on [online demo](http://autoprefixer.github.io/), you will see that it add prefixes correctly. So problem is in some place after Autoprefixer.

Also, you should use `gulp-postcss` with `autoprefixer`. `gulp-autoprefixer` is not official way.

**Comment by thykka** [comment]
Changing the autoprefixer() arguments into a single array fixed my problem.

I'm not interested in setting up postCSS at this point. I just wanted my old project files to work again...

**Comment by ai** [comment]
@thykka `gulp-autoprefixer` anyway contains PostCSS ;). But with official `gulp-postcss` I found this mistake in options (because I don’t know API of non-official tools).

**Comment by ai** [comment]
Also you should create `browserslist` as I told you. It fix a problem with wrong ` gulp-autoprefixer` API too
