### ISSUE TITLE
calc() is not prefixed for Chrome v23

### ISSUE THREAD

**Issue by artin-phares** [postcss/autoprefixer#667]
Hey,

```calc() ``` is not prefixed for Chrome v23.

[caniuse](http://caniuse.com/#search=calc) shows it should be prefixed with ```-webkit-```

Using autoprefixer v6.3.6 via postcss-loader v0.8.2 via webpack v1.13.0 like:
```
webpack({
       postcss: function () {
            return {
                defaults: [autoprefixer({ browsers: ['Chrome >= 23'] })]
            };
        }
})
```

My css: ```.description { height: calc(100% - 330px); }```

Tell me where am I wrong?

**Comment by ai** [comment]
Hi. Chrome 23 is very old and is not in default browsers list. If Of course, you set own browsers list. But webpack has own Autoprefixer to minify CSS.

So you need set your browsers in `browserslist` config in project root (sorry, I can get you a links from phone). Webpack will use same browserslist config and will not remove prefixes.

**Comment by artin-phares** [comment]
Webpack `css-loader` [is removing](https://github.com/webpack/css-loader#minification) deprecated vendor prefixes by default.

Fixed like this:
```
{
    test: /\.css$/,
    loader: 'style!css-loader?-autoprefixer'
}
```
Thanks for advise.
