### ISSUE TITLE
Different prefixes cross platform

### ISSUE THREAD

**Issue by Zashy** [postcss/autoprefixer#669]
Developing on Windows and Mac OSX I noticed that my compiled CSS was different. Namely some things were not getting the webkit prefix when running my build on windows. I was able to fix it by changing the autoprefixer config to be `['>5%', 'last 2 versions']`. Not sure if this is an issue, but it was really weird and confusing for a bit.

Autoprefixer config:
```
autoprefixer({ browsers: ['last 2 versions'] })
```

CSS Input:
```
.example {
    display: flex;
}
```

CSS Output Windows:
```
.example {
    display: -ms-flexbox;
    display: flex;
}
```

CSS Output OSX:
```
.example {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
}
```

**Comment by ai** [comment]
You have different versions of caniuse-db on different machines (no related with OS).

If you want a solid output, use npm-shrinkwrap.json and browserslist config.

**Comment by Zashy** [comment]
Ahh, thanks for clarifying what was going on here. I should prolly just be more explicit with what browser I'm supporting.
