### ISSUE TITLE
background: Linear-gradient not prefixing

### ISSUE THREAD

**Issue by spakerleza** [postcss/autoprefixer#670]
Please i use autoprefixer in my sublime text, But i notice Linear-gradien don't prifix.
I try prifixing it manualy but. The plugin removes it. How can i prevent this from happning.

`background: linear-gradient(top, #fb0, #f50);`

**Comment by ai** [comment]
Check FAQ section in main README (sorry, I am from phone, can't give a direct link)

**Comment by ai** [comment]
Also you should really consider to use Autoprefixer in Gulp. Prefixes reduce readability. And Gulp prints warnings from Autoprefixer (it has special warning from this case with wrong direction syntax).

**Comment by spakerleza** [comment]
Oh! thanks tried it with gulp, found out I was using outdated direction syntax. Gulp seams to be cool. Have to explore more on what it can do. Thanks a lot anyway.
