### ISSUE TITLE
background: Linear-gradient not prefixing

### ISSUE THREAD

**Issue by spakerleza** [postcss/autoprefixer#671]
Please i use autoprefixer in my sublime text, But i notice Linear-gradien don't prifix.
I try prifixing it manualy but. The plugin removes it. How can i prevent this from happning.

**This is the code before prifixing**
`.MethodWrapper li:after {
    content: "✼";
    display: flex; 
     justify-content: center;
    padding: .8em 0;
    color: #eee; 
    background: blue; 
    background: linear-gradient(top, #fb0, #f50);`

**After autoprifix**
`.MethodWrapper li:after {
    content: "✼";
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-justify-content: center;
        -ms-flex-pack: center;
            justify-content: center;
    padding: .8em 0;
    color: #eee;
    background: blue;
    background: linear-gradient(top, #fb0, #f50);`

**Comment by ai** [comment]
A already answered 😉

1. Check FAQ in README
2. Don't use Autoprefixer in Sublime. Learn Gulp.
