### ISSUE TITLE
columns not prefixed -moz

### ISSUE THREAD

**Issue by mdix** [postcss/autoprefixer#672]
**I'm building with the following config:**
```
'Chrome >= 49',
'Firefox >= 45',
'Explorer >= 11',
'Edge >= 12',
'iOS >= 8',
'Safari >= 9',
'ChromeAndroid >= 49',
'Android >= 4'
```

**My css:**
```
.categories-list {
    columns: 4 50px;
}
```

When checking on http://caniuse.com/#search=columns we can see that even the current Firefox version is not supporting `columns`, but after autoprefixer ran the output is

```
.categories-list {
    -webkit-columns: 4 50px;
    columns: 4 50px;
}
```

but should contain `-moz-columns: 4 50px;` to support Firefox 45 and above as written in the config.

**Comment by ai** [comment]
I tested in [online demo](http://autoprefixer.github.io/) and everything works. Maybe your issue is realated with https://github.com/postcss/autoprefixer#no-prefixes-in-production

**Comment by mdix** [comment]
Updated autoprefixer from 6.3.3 to 6.3.6 - now it's working. Thanks for your help.
