### ISSUE TITLE
linear-gradient not prefixed with android 2

### ISSUE THREAD

**Issue by Ski-lleR** [postcss/autoprefixer#673]
Hi

I use autoprefixer with gulp, prefix work with all my css, except for linear-gradient.

I tested with only :
```
.test {
    background: linear-gradient(to bottom, #000 2%, #3c3c3c 50%, #000 100%);
}
```

And here is my gulp file : 
```
var gulp = require("gulp")
var plumber = require("gulp-plumber")
var autoprefixer = require("gulp-autoprefixer")

gulp.task("prefixcss", function() {
    gulp.src("./src/stylesheets/*.css")

    .pipe(plumber())
    .pipe(autoprefixer("last 2 versions", "> 1%", "Android 2"))

    .pipe(gulp.dest("./public/assets/css/"))
})
```

caniuse say gradient need -webkit on android 2.x, the old -webkit-gradient, i tested manually and yes that work with this (but not with -webkit-linear-gradient).

Anyway, i've read all closed request about gradient or prefix not added, nothing seem to correspond to my problem.

**Comment by ai** [comment]
Please check "No prefixes in production" FAQ section in main README
