### ISSUE TITLE
webpack and autoprefixer - how to make it work

### ISSUE THREAD

**Issue by Krysisx** [postcss/autoprefixer#676]
I'm using `webpack` with `autoprefixer`, `css-loader`, `postcss-loader`, `precss`, `sass-loader`, `less`, `less-lodaer modules`. I tried to make `autoprefixer` work for my `css` files. Here is my `webpack.config.js` file:

```
...
var webpack = require('webpack');
var autoprefixer = require('autoprefixer');
var precss       = require('precss');
module.exports = {
...
    module: {
        loaders: [
            { 
                test: /\.css$/, 
                exclude: /\.useable\.css$/, 
                loader: "style-loader!css-loader!postcss-loader?pack=cleaner"
            }, 
            {
                test: /\.useable\.css$/, 
                loader: "style/useable!css" 
            },

            {
                test: /\.less$/,
                loader: "style!css!less"
            },
            {
                test: /\.scss$/, 
                loader: 'style!css!sass'
            }, 
        ]
    },

    postcss: function () {

        return {
            defaults: [autoprefixer, precss],
            cleaner:  [autoprefixer({ browsers: ['IE 10', 'IE 11', 'firefox 20', 'ios_saf 8.4', 'android 4.3'] })]
        };

    },

...  

};
```
Note that I use `.scss` and `.less` files that are converted to `.css` by the `webpack` modules.
The problem is that I don't think it's working. For instance, I have these CSS rules:

```
@keyframes spinner {
    to {transform: rotate(360deg);}
}
.animation {
    animation: spinner .6s linear infinite;
}
#elem {
    display: flex;
    flex-grow: 1;
}
```

and I expect it to become at least something like this:

```
@keyframes spinner {
    to {transform: rotate(360deg);}
}
@-webkit-keyframes spinner {
    to {-webkit-transform: rotate(360deg);}
}
.animation {
    animation: spinner .6s linear infinite;
    -webkit-animation: spinner .6s linear infinite;
}
#elem {
    display: flex;
    display: -webkit-flex;
    flex-grow: 1;
    -webkit-flex-grow: 1;
}
```
but I can't see those rules in my page. Is it the correct way to apply browser list query with webpack?
How can I make it work?

Thanks

**Comment by ai** [comment]
You apply `postcss-loader` only for CSS files. You don’t apply it to LESS and SCSS sources. In webpack config you need to specify all loaders for every file extension.

**Comment by ai** [comment]
Anyway, issues is not good way for asking help. Issues is for errors.

If you want a help with working a tools, ask in webpack chat or in stackoverflow.

**Comment by Krysisx** [comment]
Great it works now, thank you and sorry for the mistake.
