### ISSUE TITLE
I want to get all prefix in use or not.

### ISSUE THREAD

**Issue by onigetoc** [postcss/autoprefixer#679]
I want to get all prefix in use or not.

I'm creating a CSS generator and i need to show every prefix in the result.

How can i do that?

**Comment by ai** [comment]
`All prefix` = `prefixes for all possible browsers version` or you need what prefixes Autoprefixer will add with current browsers settings?

**Comment by onigetoc** [comment]
Thank's, 
Do it work with the javascript version?
and how can i use it.
this is for a project i want to do.
Form to CSS.
https://jsfiddle.net/onigetoc/qhatbqr7/25/

**Comment by ai** [comment]
I asked a question, it was not a solution ;)

**Comment by ai** [comment]
I don’t understand what you mean, when you talk “all prefixes”

**Comment by onigetoc** [comment]
I want to add all prefix to css, that's all.

**Comment by ai** [comment]
@onigetoc just use Autoprefixer. It adds all actual prefixes to CSS :).

**Comment by onigetoc** [comment]
Hi, the test here http://autoprefixer.github.io/ with for example 
`border-radius: 5px;`
do not generate all prefix.

**Comment by ai** [comment]
@onigetoc modern browsers don’t need prefix for `border-radius`. It is completely non-actual.

You can configure, what browsers you need to support https://github.com/postcss/autoprefixer#browsers

**Comment by onigetoc** [comment]
I want it to work for old browser

**Comment by ai** [comment]
@onigetoc why do you need Chrome 5 support?

**Comment by ai** [comment]
What exactly old browsers you need to support?

**Comment by onigetoc** [comment]
ALL old Browser

**Comment by ai** [comment]
Use "> 0%". But it is very very bad technique. I don't know good use cases for it.

**Comment by onigetoc** [comment]
Ok thank you

**Comment by chrisblossom** [comment]
@ai Is there a reason you say it is a bad technique? My increased css bundle size using ``> 0%`` over ``> 1%`` is only 0.5k gzipped (11k raw).

**Comment by ai** [comment]
@chrisblossom because you really don’t support Chrome 3 or Firefox 3. You browsers config should shows  your real browsers support policy.

**Comment by chrisblossom** [comment]
Thanks for the quick response! Unless I am missing something, there isn't any negatives outside of a very small increase in css size for **my use case**. Is this correct or is there something I am missing about css/vendor prefixes?

**Comment by ai** [comment]
Yeap, there is no short-term negatives.

But `babel-preset-env` and `eslint-plugin-compact` use same `browserslist` config with Autoprefixer, so you will increase your JS files too and linting will not be helpful.
