### ISSUE TITLE
Missing flex-grow, flex-shrink, flex-basis webkit autoprefix

### ISSUE THREAD

**Issue by andreareginato** [postcss/autoprefixer#682]
I've been testing this code in [autoprefixer.github.io](http://autoprefixer.github.io/) and I miss the translation for `-webkit`.

```
// source code 
.example {
    flex-grow: 2;
    flex-shrink: 2;
    flex-basis: 10%;
}

// autoprefixed code
.example {
    -webkit-box-flex: 2;
        -ms-flex-positive: 2;
            flex-grow: 2;
    -ms-flex-negative: 2;
        flex-shrink: 2;
    -ms-flex-preferred-size: 10%;
        flex-basis: 10%;
}
```

Do you have any idea on why the -webkit autoprefix is missing?
Thanks a lot

**Comment by ai** [comment]
Because, "final flexbox spec" browsers doesn't need prefix anymore.

**Comment by ai** [comment]
And `-webkit-box-flex` needs for "2009 spec" browsers, which doesn't support other properties.

**Comment by andreareginato** [comment]
Thanks @ai for your explanation. I started to experiment with the `browsers` option and got to better understand how autoprefixer works. 

I'm still facing one strange behaviour. I'm testing ">0%" as option on [Autoprefixer CSS online](http://autoprefixer.github.io/) and I see the following output.

```
    // origin
    flex: flex: 1 1 20%;
    // parsed
    -webkit-box-flex: 1;
    -webkit-flex: 1 1 20%;
       -moz-box-flex: 1;
        -ms-flex: 1 1 20%;
            flex: 1 1 20%;
```

In my local installation I've the following setup on webpack.

```
// ...
loaders: ['style', 'css', 'postcss', 'sass'],
// ...  
postcss: [ autoprefixer({ browsers: ['>0%'] }) ],  
```

With the following result

```
    // origin
    flex: flex: 1 1 20%;
    // parsed
    -webkit-box-flex: 1;
    -ms-flex: 1 1 25%;
    flex: 1 1 25%;
```

Having installed Safari 8 (I know it has a little impact) the miss of `-webkit-flex: 1 1 20%;` causes layout problems. It feels like I'm making something wrong in the setup.

Thanks again for your help.

**Comment by ai** [comment]
Maybe this case is related? https://github.com/postcss/autoprefixer#no-prefixes-in-production

Try to use `browserslist` config

**Comment by andreareginato** [comment]
`browserlist` solves the problem. 
Thanks @ai for your time and help.
