### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by eigenmannmartin** [postcss/autoprefixer#683]
I recently noticed that the builds are not running any more:
[https://travis-ci.org/eigenmannmartin/autoprefixer](https://travis-ci.org/eigenmannmartin/autoprefixer)

I guess it is caused by the new release 1.3.4 [https://github.com/ai/browserslist](https://github.com/ai/browserslist)

**Comment by ai** [comment]
Strange, I will look on this week.

**Comment by ai** [comment]
Issues happened because `Safari TP` removed prefixes. I fix tests: https://github.com/postcss/autoprefixer/commit/26da3e2378825da9d5c47c15708ec6378d299307

**Comment by eigenmannmartin** [comment]
thanks man! :+1:
