### ISSUE TITLE
Autoprefixer wont prefix scss-input when used with gulp-postcss

### ISSUE THREAD

**Issue by epavletic** [postcss/autoprefixer#685]
#### Problem
I'm in the midst of setting up a new workflow where the central ingredients are gulp, sass, autoprefixer and stylelint. While doing so I ran into an issue with autoprefixer not prefixing sass-input:

#### Setup
This is the setup I tried to get to work initially:

``` js

var gulp = require('gulp');
var postcss = require('gulp-postcss');
var reporter = require('postcss-reporter');
var autoprefixer = require('autoprefixer');
var stylelint = require('stylelint');
var scss = require('postcss-scss');
var sass = require('gulp-sass');
var sourcemaps = require('gulp-sourcemaps');

gulp.task('sass', function () {

  var processors = [
    stylelint(), // See .stylelintrc.yml for configuration.
    autoprefixer({
      map: true,
      browsers: ['> 1% in SE', 'ie >= 9', 'last 2 versions', 'Firefox ESR', 'Opera 12.1']
    }),
    reporter({
      formatter: function(input) {
        return reportFormatter(input);
      },
      clearMessages: true
    })
  ];

  return gulp.src(paths.styles.src)
    .pipe(postcss(processors, {syntax: scss}))
    .pipe(sourcemaps.init())
    .pipe(sass({outputStyle: 'compact'}).on('error', throwSassCompileError))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(paths.styles.dest));
});
```
Nothing special here; the interesting part is that I chose to put the postcss-process first in the gulp-pipeline – mostly because I wanted Stylelint to lint the scss-source, and not the generated css-file. However, this hade the unfortunate result that the `autoprefixer`-plugin did nothing – I suspect that it has something to do with it being fed a bunch of scss-files rather than css-ditos? Anyway, I managed to make it work by splitting the postcss-tasks apart, and applying the autoprefixer-task _after_ the css has been generated, like so:

``` js
gulp.task('sass', function () {

  var preCompilePlugins = [
    stylelint(), // See .stylelintrc.yml for configuration.
    reporter({
      formatter: function(input) {
        return reportFormatter(input);
      },
      clearMessages: true
    })
  ];

  var postCompilePlugins = [
    autoprefixer({
      browsers: ['Chrome > 10']
    }),
    reporter({
      formatter: function(input) {
        return reportFormatter(input);
      },
      clearMessages: true
    })
  ];

  return gulp.src(paths.styles.src)
    .pipe(sourcemaps.init())
    .pipe(postcss(preCompilePlugins, {syntax: scss}))
    .pipe(sass({outputStyle: 'compact'}).on('error', throwSassCompileError))
    .pipe(postcss(postCompilePlugins))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(paths.styles.dest));
});
```

This works, but feels like a workaround. Is there something I can do to make Autoprefixer accept the scss-input as is (and therefore return to the previous setup where I only call postcss once), or is this actually the way to go about it? Or have I (most likely…) missed something obvious?

Appologies in advance if this actually is an issue with `gulp-postcss` or some of the other moving parts I'm using above!

**Comment by ai** [comment]
Autoprefixer works with SCSS, maybe you have a issue somewhere.

But in your case you should run Autoprefixer after Sass compiler. Because your sources could have some dynamic properties like `#{ $sassVar }` owe some other hacks.

I agree that it will not be a best solution. This is why the best solution will be replace Sass to PreCSS or even cssnext - you will have 1 parser for all your task, it will be 3-4 times faster.
