### ISSUE TITLE
order spawns -webkit-box-ordinal-group but no -webkit-order

### ISSUE THREAD

**Issue by nainy** [postcss/autoprefixer#688]
Hey!

We've recently encountered the aforementioned issue. The source css looks like:

       .img {
            width: 40%;
            max-width: 210px;
            order:1;
        }

which after autoprefixer yields:

    .img {
           width:40%;
          max-width:210px;
          -webkit-box-ordinal-group:2;
          -ms-flex-order:1;
          order:1
     }

Is this the expected behavior? Seems like this is breaking the layouts on earlier iOSs.

Appreciate any advice.

**Comment by ai** [comment]
Everything give. Old Safari supports different spec with different values and properties.

**Comment by nainy** [comment]
I'm not sure I understand what you mean?

**Comment by ai** [comment]
Sorry, phone keyboard is not accurate

Everything fine in output example. Or what is your expected output?

**Comment by nainy** [comment]
The behavior seems to normalize as soon as `-webkit-order: 1` is added before `order: 1`. 

Actually, it seems that autoprefixer yields different results with windows and unix, the main difference being that, on windows, the property `-webkit-order` does get appended. yet doesn't on linux. That's how we essentially found out about the issue.

**Comment by ai** [comment]
There is no `order` in flexbox 2009 specification. It had different properties and Autoprefixer converts syntax.

I think you have different version of `caniuse-db` on different machines. Use npm-shrinkwrap to lock all dependecies versions

**Comment by nainy** [comment]
I think you're right about the different caniuse-db versions.
However, I meant iOS versions higher than 6, and it seems like the ones before 9 need the `-webkit` prefix for the `order`. Perhaps I'm wrong, but it does work with the prefix.

**Comment by ai** [comment]
What is your `browsers` options?

**Comment by nainy** [comment]
It is currently empty.

**Comment by ai** [comment]
Empty is mean `[]` or default value (you don't set it).

**Comment by nainy** [comment]
Yeah, sorry. It wasn't set. No options are specified.

**Comment by ai** [comment]
Default browsers is `> 1%, last 2 versions, Firefox ESR`. It doesn't include old Safari that need prefix. If you need it, add them to `browsers`.

**Comment by nainy** [comment]
I've done a few test builds to check whether it works.

`{browsers: ['iOS 7.1', 'iOS 8', 'iOS 8.4']}` yields `.img{width:40%; max-width:210px; order:1}` which is strange, because Can I Use states that those three versions can use `order` with the `-webkit` prefix.

`{browsers: ['> 1%', 'last 2 versions', 'Firefox ESR', 'iOS 7.1', 'iOS 8', 'iOS 8.4']}` yields the same result as in the OP.

Is there anything I am doing wrong?

**Comment by ai** [comment]
Maybe you have hidden Autoprefixer in your build tool? For example, webpack has inner Autoprefixer in cssnano.

Try to set browsers to `browserslist` config, you will have one browsers across all tools.

**Comment by nainy** [comment]
Okay, specifying BROWSERSLIST_CONFIG did fix the issue. Great. :)

Sorry I took your time. Appreciate your help.
