### ISSUE TITLE
Add support for text-decoration-skip 

### ISSUE THREAD

**Issue by nhoizey** [postcss/autoprefixer#690]
The standard: https://drafts.csswg.org/css-text-decor-3/#text-decoration-skip-property

Supported in Safari 8+ Mac and Safari iOS8+ with the `-webkit-` prefix.

**Comment by ai** [comment]
Sure. Can we use this Can I Use data? http://caniuse.com/#feat=text-decoration

**Comment by nhoizey** [comment]
Unfortunately not:
https://github.com/Fyrd/caniuse/issues/1257

**Comment by ai** [comment]
I added support based on `text-decoration`: 05a3251

If you want more accurate — please send PR to Can I Use (it is really easy). Do you want to do it?

**Comment by nhoizey** [comment]
I did this PR, I hope it's the way to do it to have `text-decoration-skip` prefixed in Autoprefixer…

**Comment by ai** [comment]
Updated: 5e9f795

**Comment by nhoizey** [comment]
Now I just have to wait for 6.4 to be released, thanks!

**Comment by ai** [comment]
Released in 6.4.

**Comment by nhoizey** [comment]
Great, thanks!
