### ISSUE TITLE
Add :any-link selector

### ISSUE THREAD

**Issue by simevidas** [postcss/autoprefixer#692]
The current state of support: Firefox supports `:-moz-any-link`, while Safari and Chrome/ium support `:-webkit-any-link`. Mozilla has decided to [unprefix this selector](https://www.fxsitecompat.com/en-CA/docs/2016/any-link-css-pseudo-class-has-been-unprefixed/), which indicates that it’s a stable feature. (Firefox Nightly already supports the unprefixed version.)

Now is a good time for Autoprefixer to start adding `-moz-` and `-webkit-` prefixes, so that developers can just write `:any-link`.

**Comment by ai** [comment]
Do we have Can I Use data? Could you make a PR to Can I Use?

**Comment by simevidas** [comment]
Will do 😊

**Comment by ai** [comment]
@simevidas do you need help with PR to `caniuse-db`?

**Comment by simevidas** [comment]
I can do it; it’s just that I didn’t get around to doing it last weekend 😅. Here’s a few notes that I’ve written for myself:

* the test case should properly test support on all of `<a>`, `<area>` and `<link>` elements
* a cross-browser testing service would be preferable (I’ve never used one, so I’ll have to see how that works and what’s available for free)

**Comment by ai** [comment]
@simevidas just use MDN data to fill Can I Use JSON, you don’t need really cross-browser testing service :)
https://developer.mozilla.org/en-US/docs/Web/CSS/:any-link

Or you can send PR with MDN data and after it test it with actual browsers :)

**Comment by ai** [comment]
I added PR https://github.com/Fyrd/caniuse/pull/2685

@simevidas feel free to correct data if you tested it in better way.

**Comment by ai** [comment]
Done 7cb5d47

**Comment by ai** [comment]
Released in 6.4.
