### ISSUE TITLE
Delete the attribute that should not be deleted.

### ISSUE THREAD

**Issue by QuietHeartThinkingFar** [postcss/autoprefixer#693]
when I set gulp-autoprefixer attribute remove:true
before
.input_date_group{
width: -webkit-calc(100% - 135px);
width: -moz-calc(100% - 135px);
width: calc(100% - 135px);
}
after
.input_date_group{
width: calc(100% - 135px);
}

**Comment by ai** [comment]
What output do you expect?

**Comment by QuietHeartThinkingFar** [comment]
expect no change
because width: calc(100% - 135px);  works only in the general browser

**Comment by ai** [comment]
Set browsers that you need to support in `browsers` option.

**Comment by QuietHeartThinkingFar** [comment]
I set browsers many parameters like
'last 1 Chrome versions'
'last 2 Explorer versions'
'last 3 Safari versions'
'Firefox ESR'
'> 1% '
but it not work

**Comment by ai** [comment]
But all this browsers don't need prefixes for `calc()`
http://caniuse.com/#feat=calc
