### ISSUE TITLE
Option to force autoprefixer ignore unknown words

### ISSUE THREAD

**Issue by Demitrius** [postcss/autoprefixer#695]
Hello,

I have  patterns inside CSS file.

Looks like:
```
div.myclass {
   width: 100px;
   /* autoprefixer: off */
   height: {{MY-HEIGHT}};
}
```

Autoprefixer exit with error - Unknown word at {{MY-HEIGHT}}

I tried to add /* autoprefixer: off */ before height, but this don't helps.

How can I force autoprefixer to skip pattern parts?

**Comment by ai** [comment]
This error happens, because PostCSS could not parse CSS into a objects. So I can’t add this option, Autoprefixer after this error has no CSS objects to work with them.

You should just write a custom parser for CSS to parse this files: https://github.com/postcss/postcss/blob/master/docs/syntax.md
