### ISSUE TITLE
Error: no writecb in Transform class

### ISSUE THREAD

**Issue by crdo** [postcss/autoprefixer#696]
Hi, I am getting [Error: no writecb in Transform class] when using gulp-autoprefixer on 
Node v4.4.7
gulp-less v3.1.0
gulp-autoprefixer v3.1.0

when autoprefixer pipe line is commented, it works.

**Comment by ai** [comment]
`gulp-autoprefixer` is unofficial way to use Autoprefixer. Please, use `gulp-postcss` as mentioned in Autoprefixer docs ;)

**Comment by crdo** [comment]
Used as recomended - no change, still [Error: no writecb in Transform class]. Any idea?

**Comment by ai** [comment]
Show your gulpfile
