### ISSUE TITLE
New Color function syntax

### ISSUE THREAD

**Issue by nilssolanki** [postcss/autoprefixer#697]
Recently, the csswg decided to remove commas from a few functions (such as `rgb`, `rgba` etc.), effectively rendering `rgb(123, 123, 123);` legacy syntax. The reasons were discussed here: https://github.com/w3c/csswg-drafts/issues/266 (and for more details: https://github.com/w3c/csswg-drafts/blob/master/css-color/Overview.bs)

To ease the transition, and since the new syntax wont be usable in the real world of browser compatibility for quite a while, it would be nice if autoprefixer turned the new syntax into the old:

E.g.
`rgb(123 123 123);` to `rgb(123, 123, 123);`
`rgb(123 123 123 / 50%);` to `rgba(123, 123, 123, 0.5);`

**Comment by ai** [comment]
Autoprefixer is not for polyfills. You should add this feature to postcss-cssnext.
