### ISSUE TITLE
Autoprefixer not working in NPM project

### ISSUE THREAD

**Issue by baasdesign** [postcss/autoprefixer#699]
Hi,

I am making a taskrunner in NPM which is run from my package.json with the command `npm run start`. This triggers `start.js` which has the autoprefixer code, amongst other code.
I have the following code. But it is not prefixing neither is it logging anything to my terminal.

```javascript

var autoprefixer = require('autoprefixer');
var postcss = require('postcss');

    postcss([ autoprefixer ]).process({
        from: "static/css/site.min.css",
        to: "static/css/site-prefixed.min.css"
    }).then(function (result) {
        result.warnings().forEach(function (warn) {
            console.warn(warn.toString());
        });
        console.log(result.css);
    });

```

What am I not understanding?

**Comment by ai** [comment]
What is CSS input and output? Do you check by Can I Use, that it requires prefixes?

**Comment by baasdesign** [comment]
I figured it out. I had to give it the result.css from the node-sass render :)
