### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by jurom** [postcss/autoprefixer#701]
Hi,

I've installed this package, and noticed that it uses module `caniuse-db`, which is published under **CC-BY-3.0** license. While I see that you gave attribution to the `caniuse-db`, do I have to do the same if this `autoprefixer` package is published under **MIT** license?

**Comment by ai** [comment]
Hi. Good questions — after years in Wikipedia I love all this copyright law things :D.

Short answer: this licences are compatible.

Long answer: in copyright you can do only what author allowed. MIT allow you to use, modify and distribute. CC-BY allows you to use, modify and distribute too.

Also MIT allow you to use different licences in subprograms.

**Comment by jurom** [comment]
Well, I understand that you've made no mistake by licensing it with MIT now :) but do I have to attribute the author of `caniuse-db`, if I only use this `autoprefixer` module?

**Comment by ai** [comment]
My thoughts (I am now a lawyer):

> You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

If you develop a open source npm module, `package.json` already contains that you use `autoprefixer` and Can I Use.

If you develop a stand-alone program or website, you could just mention “Based on Autoprefixer and Can I Use data” with a links.
