### ISSUE TITLE
Error executing autoprefixer

### ISSUE THREAD

**Issue by juanmiguel431** [postcss/autoprefixer#702]
autoprefixer works in html documents or is only .css docs?

![error-autoprefixer](https://cloud.githubusercontent.com/assets/10950943/17827283/1f7677ca-6648-11e6-8170-5c8ec0b48c3a.png)

**Comment by ai** [comment]
Autoprefixer is PostCSS plugin. Your text editor plugin could support HTML or not. It depends on text editor plugin, not on Autoprefixer itself :).

I don’t use text editor plugins for Autoprefixer (and didn’t recommend) — so I don’t know :(.

Ask here https://github.com/sindresorhus/sublime-autoprefixer

And I highly recommend to move to Gulp/webpack.
