### ISSUE TITLE
radial-gradient is wrong

### ISSUE THREAD

**Issue by mvrhov** [postcss/autoprefixer#703]
If one uses the radial gradient to the spec.
E.g. `background-image: radial-gradient(circle farthest-corner at top, red, green 80%);`
the autoprefixer just prepends various prefixes. Which is clearly wrong as the official spec differs from the one in draft. e.g `background-image: radial-gradient(top, circle cover, red, green 80%);` Which every browser which supports prefixes expects.

If your answer to the above will be then you should provide both syntaxes.. Well then autoremoval of prefixes for gradients should not be on the list.

**Comment by ai** [comment]
Hm. Could you help me. What browsers used old direction syntax? How to cover new syntax to old?

**Comment by mvrhov** [comment]
I don't know which one uses which one, but the specs are here:

[old spec](https://www.w3.org/TR/2011/WD-css3-images-20110217/#radial-gradients)
[new spec](https://www.w3.org/TR/css3-images/#radial-gradients)

**Comment by ai** [comment]
Seems like we have `X at Y` → `Y, X` fix https://github.com/postcss/autoprefixer/blob/master/lib/hacks/gradient.coffee#L136-L144

**Comment by ai** [comment]
Here is a test with this fix: https://github.com/postcss/autoprefixer/blob/master/test/cases/gradient.out.css#L71-L75

**Comment by ai** [comment]
Maybe this logic doesn’t work only on this example. Could you test some other direction fix cases?

**Comment by DmitryEfimenko** [comment]
+1

**Comment by ai** [comment]
@DmitryEfimenko if you need this fix, help me with logic ;)

**Comment by DmitryEfimenko** [comment]
Not sure what exactly logic there is to clarify. I just saw the word "gradient" in the issue title and thought it's relevant to my use case :)

My use case is very simple: I'm using jquery theme called `afterdark`. It uses gradients as you can see [here](https://github.com/vanderlee/Afterdark/blob/master/afterdark.css#L87-L96).
After running this css file through autoprefixer the `-webkit` prefix (and possibly others), which is required by latest Chrome is removed.

Hope this clarifies things a bit.

**Comment by ai** [comment]
@DmitryEfimenko nope, your case is unrelevant for this issue ;) Autoprefixer removes prefixes in gradients because all modern browsers doesn’t need them http://caniuse.com/#feat=css-gradients

But maybe problem is because `afterdark` uses old direction syntax for gradient direction.

**Comment by DmitryEfimenko** [comment]
you are correct! Thanks for pointing in the right direction! I was not even aware of the old vs new direction situation.
