### ISSUE TITLE
details-marker pseudoclass

### ISSUE THREAD

**Issue by gampleman** [postcss/autoprefixer#704]
When I write `summary::details-marker { /*something */}` I would expect autoprefixer to emit something like `summary::-webkit-details-marker, summary::details-marker { /* something */}` for me, but it doesn't appear to do so.

**Comment by ai** [comment]
Does it described in any CSS specification or it private extension for Safari?

**Comment by gampleman** [comment]
It's supported by Chrome as well. I found this discussion about it: https://github.com/whatwg/html/issues/722. Seems like this feature might not be going anywhere much. The main reason you want it is to call `display: none` on it, so that it doesn't show up in those browsers. My main motivation in filing this issue, is that I sort of expected it to add the prefix for me, but it didn't.

**Comment by ai** [comment]
Sorry, there is no unprefixed version yet, so it is just `::-webkit-details-marker`, there is no `::details-marker`
