### ISSUE TITLE
Transform for older versions of IE

### ISSUE THREAD

**Issue by Jazcash** [postcss/autoprefixer#705]
Baffled as to why some prefixes for `transform` aren't being added. Not sure if ticket belongs in gulp-autoprefixer or here, but here goes:

My gulp task:

```
gulp.task("sass", function () {
	gulp.src(["./public/styles/styles.scss", "./public/styles/qubase/qubase.scss"])
	.pipe(sourcemaps.init())
	.pipe(plumber())
	.pipe(sassGlob())
	.pipe(sass())
	.pipe(autoprefixer({
		browsers: ["last 50 versions", "ie >= 9"],
		cascade: false
	}))
	.pipe(cssnano())
	.pipe(rename({
		suffix: ".min"
	}))
	.pipe(sourcemaps.write("../maps"))
	.pipe(gulp.dest("./public/build"))
	.pipe(livereload());
});
```

My scss:

```
...
&-center{
    display: flex;
    transform: translateX(-50%);
}
```

Output:

```
display: -webkit-box;
display: -ms-flexbox;
display: flex;
-webkit-transform: translateX(-50%);
transform: translateX(-50%);
```

So flexbox is fine, but where's the `-ms-` and `-moz-` prefixes for transform?

The thing that really stumps me is it works just fine in the demo: http://autoprefixer.github.io/

Any ideas?

**Comment by ai** [comment]
You have this issue because you ignore Autoprefixer install instructions and use `gulp-autoprefixer` and `gulp-cssnano` instead of `gulp-postcss` with `autoprefixer` and `cssnano` plugins:

1. If you will `gulp-postcss` then  `autoprefixer` and `cssnano` will use same AST and will work much faster.
2. `cssnano` has built-in Autoprefixer. In one PostCSS chain `cssnano` could detect that you use own Autoprefixer. But in this case `cssnano` didn’t see that you use other PostCSS in `gulp-autoprefixer`.

**Comment by orest22** [comment]
@ai I've test this code example [here](http://autoprefixer.github.io/) [ie >= 9] and autoprefixer doesn't work in some cases:
```
.not-wotking-test {
  transform: translateX(-50%) translateZ(0);
}
.working-test {
 transform: translateX(-50%);
}
.translate-3d {
  transform: translate3d(0, 10px, 20px);
}
```

Result:
```
.not-wotking-test {
  transform: translateX(-50%) translateZ(0);
}
.working-test {
 -ms-transform: translateX(-50%);
     transform: translateX(-50%);
}
.translate-3d {
  transform: translate3d(0, 10px, 20px);
}
```

What I'm doing wrong?

**Comment by ai** [comment]
Only IE 9 needs prefix for `transform`, but IE 9 doesn’t support 3D transforms.

**Comment by orest22** [comment]
@ai hah just notice it as well. Thanks!

**Comment by clhenrick** [comment]
Mozilla states that IE11 requires the `-webkit-` vendor prefix: https://developer.mozilla.org/en-US/docs/Web/CSS/transform

**Comment by ai** [comment]
@clhenrick it is not accurate data (should we fix it in MDN?) IE understand `-webkit-` but works with `-ms-` as well.

**Comment by clhenrick** [comment]
@ai MDN states the `-webkit-` for `transform` is required for IE11, but using `transform: translate` and `transform: rotate` appears to work in my project on IE11 without the vendor prefix. Perhaps it is incorrect or incomplete information on MDN?

<img width="1068" alt="screen shot 2018-05-26 at 8 18 39 am" src="https://user-images.githubusercontent.com/161748/40577619-75aa43d0-60bd-11e8-9040-f17ba465e7ac.png">
