### ISSUE TITLE
Flex-basis fallback not being added. 

### ISSUE THREAD

**Issue by wguldin** [postcss/autoprefixer#706]
I'm using gulp-autoprefixer (wasn't sure whether to post it there or here) and have the following config:

```
gulp.task('sass', function(){
    return gulp.src('static/css/global/**/*.scss')
        .pipe(sass({outputStyle: 'nested'}))
        .pipe(autoprefixer({
            browsers: ['> 5%', 'ie >= 8'],
            cascade: false
        }))
        .pipe(gulp.dest('static/css/global'));
});
```

And I have this SCSS:

```
    .o-grid__large--1-3 > .o-grid__cell {
        flex: 0 0 33.3333%;
    }
```

Which is converted to:

```
.o-grid--1-3 > .o-grid__cell {
  -webkit-box-flex: 0;
  flex: 0 0 33.3333%; }
```

I was expecting the fallbacks for flex-basis to be set. If I declare the 'flex-basis' without the shorthand property, it still generates the same result. 

Thanks for any help!

**Comment by wguldin** [comment]
I updated my config from 'ie 8', to 'ie >= 8', but didn't realize I needed to rerun gulp. Gulp watch was relying on the outdated config.

**Comment by ai** [comment]
Also, please use `gulp-postcss` instead of `gulp-autoprefixer` as described in README
