### ISSUE TITLE
Order of

### ISSUE THREAD

**Issue by marvindanig** [postcss/autoprefixer#707]
So on my rails 5 app, I have a `_reusable.scss` containing a class rule:

```

.flex {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    justify-content: center;
}

```
which the autoprefixer processes & prefixes to the following:

```
.flex {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
}

```

Now my chrome canary (Version 54.0.2840.0 canary (64-bit)) interprets `display:-webkit-box;` on line 1 correctly but that is soon overwritten by the rule at line no 3 `display: flex;` (which canary doesn't seem to support at the moment) and thus the site design falls apart. 

A simple fix here is swap the lines for `display:flex;` and `display:-webkit-box;`.  

To test visit homepage: [https://bubbl.in](https://bubbl.in) on stable chrome and the following is a screenshot on chrome canary where `.flex` isn't effectively applied:

[ [screenshot](http://imgur.com/FP8DL7L) ]

**Comment by ai** [comment]
Please check 2. point in your previous issue 😉

**Comment by nerdgrass** [comment]
Hey, so I'm running across the same issue and I cannot seem to find the previous issue @ai is mentioning. Any chance to get a link? I did a search for previous issues from the OP, but found nothing.
