### ISSUE TITLE
Autoprefixers break CSS transform

### ISSUE THREAD

**Issue by wilmardo** [postcss/autoprefixer#712]
Hi,

Today I started with Gulp, prefixer and SASS so I hope I am not missing something obvious here.

I made [this](http://www.wdrfree.com/103/fullscreen-responsive-menu-pure-css) CSS example and converted it to SASS with [this](http://css2sass.herokuapp.com/) tool. So far so good.
But with autoprefixer enabled the transform of the before and after stops working, instead of a smooth transition there is none. When I disable autoprefixer everything is fine so I suspect there is something wrong with autoprefixer.
Who could provide me with some insights?

Thanks!

**Comment by ai** [comment]
Please, check Autoprefixer warnings.

Problem is because of separated `transition-property` and `transition-duration`/`transition-delay`. Autoprefixer tells about it in warnings.

Rewrite code with `transition`, instead of `transition-property`, `transition-duration`, and `transition-delay`
