### ISSUE TITLE
Box-sizing prefixing

### ISSUE THREAD

**Issue by catalinfeier** [postcss/autoprefixer#713]
I know there already are some closed issues with this subject, but this particular one seems to be missing.

I am using autoprefixer for mobile devices so i've set the browsers to:`browsers:['Android >= 4', 'iOS >= 8']`. From what i understand that should include all android versions above (and including) 4.0. However, the end result is unchanged, even though  [Can i use](http://caniuse.com/#feat=css3-boxsizing) states that only android 4.4 and above accepts the standard `box-sizing`, without the `-webkit-` prefix.

Using the online [autoprefixer](http://autoprefixer.github.io/) with the filter applied with `Android >= 4, iOS >= 8`, gives the same result (without adding the prefixed rule). For reference, the css i used:
```.example {
    box-sizing: border-box;
}```

Am i missing something?

**Comment by ai** [comment]
Android 4 accepts `box-sizing` without prefix: http://i.imgur.com/PIGdYVy.png
