### ISSUE TITLE
some background attachment disappear with gradients

### ISSUE THREAD

**Issue by paulwasit** [postcss/autoprefixer#718]
I am trying to create a responsive table, with shadows indicating an overflow on mobile from [this article](http://www.the-haystack.com/2013/09/24/responsive-scrollable-tables/).

I wrap my tables in a div with the following css:

    .table-wrapper {
        border-radius:1px; // required due to a bug with bg-attachment: local in chrome android
        overflow-x: auto;
        background: 
            // these gradients hide the shadows when scrolling to the edges
            linear-gradient(to right, white 30%, rgba(0,0,0,0)),
            linear-gradient(to left, white 30%, rgba(0,0,0,0)) 100% 0,
            // shadow ellipsis - do not move when scrolling
            radial-gradient(farthest-side at   0 50%, rgba(0,0,0,.15), rgba(0,0,0,0)),
            radial-gradient(farthest-side at 100% 50%, rgba(0,0,0,.15), rgba(0,0,0,0)) 100% 0;
				
      	background-repeat: no-repeat;
     	background-color: white;
     	background-size: 20px 100%, 20px 100%, 14px 100%, 14px 100%;
      	background-attachment: local, local, scroll, scroll; 	
    }

The css output for `background-attachment` is `background-attachment: local, scroll;`, which does not work.

However, if I use `background-attachment: local, local, scroll, scroll, local, local, scroll, scroll;`, the output is `background-attachment: local, local, scroll, scroll;` and my css works.

I did not test with regular backgrounds, so I am not sure if it is only with gradients.

**Comment by ai** [comment]
How `background-attachment` is relevant with prefixes?

Could you show output and expected output?

**Comment by paulwasit** [comment]
Oops I apologize my issue was not due to autoprefixer but to another plugin called postcss-unprefix. I will post my issue there.
