### ISSUE TITLE
Flex: "flex: 0 1 100%;" evaluates to "-webkit-box-flex:0 0;" instead of "..: 1;"

### ISSUE THREAD

**Issue by rejhgadellaabsl** [postcss/autoprefixer#720]
Hi,

I have a css rule where I want a flexbox (flex child) to take all the space it can but still leave space for other boxes. I achieved this by using: `flex: 0 1 100%;` (so no-grow, do-shrink and initial width = 100%) but when I run autoprefixer it evaluates this to: `-webkit-box-flex: 0;` - which doesn't do what I want, it makes the flexbox just take up the speed it needs for its content. If I change it to `-webkit-box-flex: 1;` it does work.

It's possible that this is by design but thought it's maybe worth reporting.

**Comment by ai** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/box-flex

> The -moz-box-flex and -webkit-box-flex CSS properties specify how a -moz-box or -webkit-box grows to fill the box that contains it, in the direction of the containing box's layout.

So, as I understand, `-webkit-box-flex` should contains `flex-grow` value (it is the first in `flex`).

Initial values in `-webkit-box-flex` and `flex-grow` are same, that proof it too.

**Comment by rejhgadellaabsl** [comment]
So I guess this is just iOS UIWebView doing weird stuff (that's nothing new but still)? Because setting `-webkit-box-flex: 1;` makes it shrinkable, at least on iOS8 :P

Anyway, thanks for looking into it.
