### ISSUE TITLE
Order of -webkit-flex and -webkit-box is wrong order

### ISSUE THREAD

**Issue by GustavSt** [postcss/autoprefixer#721]
When trying to have display: flex work for ios 8 `display: -webkit-box` is lower than `display: -webkit-flex` and then it doesn't work. If i go into dev tools and remove `-webkit-box` and `-webkit-flex` is used it works fine.

Is there some way to change the order of these with some setting?

**Comment by ai** [comment]
Could you show input, current output and expected output? ;)

**Comment by GustavSt** [comment]
Sorry! Seems like I was a bit tired and did stuff in the wrong order. The thing was I wanted to have `-webkit-flex` but at first autoprefixer removed the ones i had added manually. Then I found `remove: false`, so I used that, and then it seem I had wrong browser-value since default didn't include `-webkit-flex`. 

I then changed some versions to include the -webkit prefix. However the problem was my own prefixes that now wasn't removed by autoprefixer was still there, above all the generated ones, and i thought autoprefixer had ordered them wrong. 

So, my bad! But do you have any suggestions on what values I should have in the browser-value? currently I have `"browsers": ["> 1%", "last 2 versions", "Firefox ESR", "last 5 IOS versions"]` but I chose that a bit at random, just adding ios versions to the defaults in order to get the -webkit-prefix.
