### ISSUE TITLE
Generate display: box;?

### ISSUE THREAD

**Issue by mz3** [postcss/autoprefixer#723]
`display: flex;` generates:

```
display: -webkit-box;
display: -ms-flexbox;
display: flex;
```

Is there a way to also get `display: box;` included? The only reason is that PageSpeed insights uses the ancient flexbox spec.

**Comment by ai** [comment]
Nope. Autoprefixer generates *prefixes* and only for browsers. But you could write custom PostCSS plugin for it:

```js
postcss.plugin('postcss-flex-boxer' () => {
  return root => {
    root.eachDecl(decl => {
      if (decl.prop === 'display' && decl.value === 'flex') {
        decl.cloneBefore({ value: 'box' })
      }
    })
  }
})
```
