### ISSUE TITLE
Document direct (no build tools) usage

### ISSUE THREAD

**Issue by medikoo** [postcss/autoprefixer#726]
Current documentation explains how to use autoprefixer with various build tools grunt, gulp, webpack etc, but it seems to miss clean instructions on how to use it on its own.

```javascript
var autoprefixer = require('autoprefixer');

var autoPrefixedCssText = autoprefixer(cssText); // Will it work?
```

I would expect it to be first item in [Usage](https://github.com/postcss/autoprefixer#usage) section.

**Comment by ai** [comment]
Here is a JS API section from `README.md` https://github.com/postcss/autoprefixer#javascript

**Comment by medikoo** [comment]
This one is also not really _direct_, It suggests, that to use autoprefixer, one have to also install [postcss](https://github.com/postcss/postcss)? What's the reason?

**Comment by bmeck** [comment]
@medikoo autoprefixer is a postcss plugin so that makes sense

**Comment by ai** [comment]
@medikoo Autoprefixer just a plugin for PostCSS. Autoprefixer can’t parse CSS, can’t generate source maps. All this stuff is done by PostCSS.

If you want to use some Sass mixin, you load Sass, right? Same here :)

**Comment by medikoo** [comment]
@ai for long time in one of the projects I'm using it as:

```javascript
var autoprefixer = require('autoprefixer')
var autoPrefixedCssText = autoprefixer.process(cssText).css;
```

I actually came here, to remind myself how to use it (for other project), and was surprised by lack of clean instructions.

Why such non-plugin usage is not recommended (as not mentioned in doc)?

**Comment by ai** [comment]
@medikoo because there is no way to set options (like `browser`) in this PostCSS plugin shortcut (all PostCSS plugin have this shortcut).
