### ISSUE TITLE
Radial gradients require -ms prefix on IE11

### ISSUE THREAD

**Issue by vaidotas-adf** [postcss/autoprefixer#727]
To make radial-gradient property work on IE11 and IE10 -ms prefix is required. linear-gradient works without any prefixes.
Autoprefixer should add -ms prefix to radial-gradient properties when >= IE10 browser versions are selected.

**Comment by ai** [comment]
Autoprefixer takes data from Can I Use http://caniuse.com/#feat=css-gradients

If this page is wrong, let's fix it. What proof do you have?

Also, do you use correct direction syntax? There is a difference between final and prefixed syntax. Autoprefixer shows warning if you use old syntax.

**Comment by vaidotas-adf** [comment]
This one doesn't work on IE10 and IE11 and autoprefixer adds only new property with -webkit prefix:
`background-image: radial-gradient(50% 80%, circle farthest-side, #91bf28 0%, #409e3e 43%, #005c37 65%, #001409 100%);`

But after manually adding -ms- prefix, gradient is rendered correctly and property appears as valid one in Code Inspect tool:
`background-image: -ms-radial-gradient(50% 80%, circle farthest-side, #91bf28 0%, #409e3e 43%, #005c37 65%, #001409 100%);`

And the worst part is, that if I add -ms- prefixed version in my styles - it is removed completely.

**Comment by ai** [comment]
Did you check, that you use latest gradient syntax? Seems like you use old one, this is why IE 11 ignores unprefixed gradient, but works with prefixed.

**Comment by vaidotas-adf** [comment]
You are right, after fixing syntax like this (move position after "at"), it is working without any prefixes:
`background-image: radial-gradient( circle farthest-side at 50% 80%, #91bf28 0%, #409e3e 43%, #005c37 65%, #001409 100%);`
