### ISSUE TITLE
flex does not prefix -webkit-flex

### ISSUE THREAD

**Issue by daanschaeffer** [postcss/autoprefixer#728]
It seems that flex only prefixes only -webkit-box but does not prefix -webkit-flex.
Why is this removed? And is this a bug or a feature?
Even in the REAMDE it says flex will compile to -webkit-flex but it doen't.

**Comment by ai** [comment]
Browsers, that use set by `browserslist` config doesn’t need `-webkit-flex`

**Comment by PRR24** [comment]
Can you please elaborate bit more on the topic. I use autoprefixer with list "Chrome >= 21" that I would expect -webkit-flex to appear, but no. What should I change to get it? Thank you.
