### ISSUE TITLE
Possible to use Autoprefixer without NPM?

### ISSUE THREAD

**Issue by wguldin** [postcss/autoprefixer#729]
Hi, 

This is probably a silly question, but is there a way to use Autoprefixer without NPM?

We use NPM for our css authoring tools, but we're looking to automate the compile process on release, and our team has reservations about the large number of NPM dependencies that have to be downloaded for compiling scss and running autoprefixer, since that's the only part of our build that relies on NPM.

There are a lot of alternative ways to compile scss outside of NPM (libsass, for example), but I haven't found any substitutes for Autoprefixer – it's a great tool. 

So, is there a way to use it outside of NPM? Thanks for your time!

**Comment by ai** [comment]
Nope, there is no way, because npm is only way to `caniuse-db`.

You can use some hack, it in result you will not have latest Can I Use updates.

What exactly problem do you have with npm? It uses really small dependencies set:

```
└─┬ autoprefixer@6.5.0 
  ├── browserslist@1.4.0 
  ├── caniuse-db@1.0.30000548 
  ├── normalize-range@0.1.2 
  ├── num2fraction@1.2.2 
  ├─┬ postcss@5.2.4 
  │ ├─┬ chalk@1.1.3 
  │ │ ├── ansi-styles@2.2.1 
  │ │ ├── escape-string-regexp@1.0.5 
  │ │ ├─┬ has-ansi@2.0.0 
  │ │ │ └── ansi-regex@2.0.0 
  │ │ ├── strip-ansi@3.0.1 
  │ │ └── supports-color@2.0.0 
  │ ├── js-base64@2.1.9 
  │ ├── source-map@0.5.6 
  │ └─┬ supports-color@3.1.2 
  │   └── has-flag@1.0.0 
  └── postcss-value-parser@3.3.0
```

**Comment by wguldin** [comment]
Thanks for the quick response! 

Our package to compile scss, autoprefix it, and minify it doesn't have a ton of dependencies in and of itself, you're right. But, this has other dependencies that download (300 files in total), and it's causing issues with our release when these files all download from NPM. 

If we used NPM more extensively, I'm sure we could figure out a better way to handle it, but being the only web designer on our team, it's hard for me to justify changing our release process to accommodate this tool, so we'll see. 

Thanks again for your clarification!
