### ISSUE TITLE
generated sourcemaps missing path

### ISSUE THREAD

**Issue by dungdm93** [postcss/autoprefixer#731]
I use autoprefixer with gulp, but generated sourcemaps seem to have only files name in `sources` attribute.
```
src
|- app
|   \- components.css
\- main.css
```

```js
// gulpfile.js
var $ = require("gulp-load-plugins")({ lazy: true });

gulp.task("compile:styles", function () {
    return gulp
        .src("./src/**/*.css")
        .pipe($.sourcemaps.init())
        .pipe($.autoprefixer())
        .pipe($.concat("styles/all.css"))
        .pipe($.sourcemaps.write(".", {includeContent: false, sourceRoot: '../src'}))
        .pipe(gulp.dest("./dist"));
});
```
Actual result:
```json
// dist/styles/all.css.map

{"version":3,"sources":["styles.css","components.css"],"names":[],"file":"styles/all.css","sourceRoot":"../src","mappings":"..."}
// missing path ------------------------^
```
Expected result (when I disable autoprefixer):
```json
{"version":3,"sources":["styles.css","app/components.css"],"names":[],"file":"styles/all.css","sourceRoot":"../src","mappings":"..."}
```

**Comment by ai** [comment]
You need to set sourceContent option to PostCSS.

**Comment by dungdm93** [comment]
I don't use autoprefixer as PostCSS plugin.
I use **standalone** `gulp-autoprefixer`

**Comment by ai** [comment]
There is no standalone Autoprefixer 😉. gulp-autoprefixer just have hidden PostCSS inside.

In Gulp you need to enable sourceContent in gulp-sourcemaps. PostCSS will use previous source map settings.

**Comment by dungdm93** [comment]
`gulp-sourcemaps` has no `sourceContent` option.
The only similar one is `includeContent`, but I'd like to use external source so... as you see, I set it to false 
`{includeContent: false, sourceRoot: '../src'}`

**Comment by ai** [comment]
`includeContent` is what you need, it will add `sourceContent` to map.

**Comment by ai** [comment]
Ouh, I found what you mean 😕

**Comment by ai** [comment]
Could you try `gulp-postcss` with `autoprefixer`. And if you will have problem open a issue in PostCSS repo?

Autoprefixer doesn't add maps, only PostCSS does it

**Comment by dungdm93** [comment]
:) Let me try.

**Comment by dungdm93** [comment]
`gulp-postcss` with `autoprefixer` work fine 👍 
But should `gulp-autoprefixer` also support sourcemaps?

**Comment by ai** [comment]
It should, but maybe it contains some mistake?
