### ISSUE TITLE
Not getting `-webkit-flex-basis` for Safari 8

### ISSUE THREAD

**Issue by srhmgn** [postcss/autoprefixer#732]
Some of our flex layouts were failing on Safari 8, and I realized our processed CSS was missing `-webkit-flex-basis` (although it seemed to have all other webkit prefixes).

I updated the `browserslist` file from `Safari >= 8` to `Safari >= 7` and nothing changed, but changing to `Safari >= 6` solved the issue.

Could autoprefix be updated to include `-webkit-flex-basis` for `Safari >= 8`?

**Comment by ai** [comment]
Autoprefixer uses Can I Use database to get browser flexbox support.

Right now Can I Use tells that only Safari >= 6 uses old 2009 flexbox specification.

So browsers support seems fine. Maybe we have a issue in some other place? Can you show me CSS input, output and expected output?

**Comment by jabacchetta** [comment]
Just to note, I ran into the same issue today — a lot of missing webkit prefixes for flexbox support on Safari 8. I'll look into this more and provide details hopefully this weekend if it hasn't been figured out yet.

**Comment by arctouch-brunowolff** [comment]
I have something like this happening now.. 

But it's weird.. if I access "MYIP:8080/page" from an old iPad mini everything works fine.. if I access the deployed branch of that I get no -webkit prefix for flex-basis.. (again, the -webkit is there if I point to my local environment).

**Comment by ai** [comment]
@arctouch-brunowolff sorry, I think you have a problem in your environment, where I don’t have a experience to help.

**Comment by arctouch-brunowolff** [comment]
why is this closed when using safari >= 8 is not working properly?

**Comment by albertmatyi** [comment]
flex-basis is only supported with -webkit prefix - according to caniuse.com

![2017-08-11-143326_797x492_scrot](https://user-images.githubusercontent.com/1370078/29213130-31ba0b68-7ea2-11e7-82ac-267b420516fc.png)


so this is obviously a compiler issue.

# reopen?
