### ISSUE TITLE
`webkit-touch-callout`

### ISSUE THREAD

**Issue by jakwuh** [postcss/autoprefixer#736]
Hi,

Want to report that for the `user-select` feature the prefix `webkit-touch-callout` [should be added](http://stackoverflow.com/questions/826782/how-to-disable-text-selection-highlighting-using-css).

**Comment by ai** [comment]
Sorry, but Autoprefixer is just for prefixers.

`-webkit-touch-callout` has a different meaning, it is not just prefixed version of `user-select`.

But you can write a custom PostCSS plugin very easy:

```js
module.exports = postcss.plugin('postcss-touch-callout', () => {
  return root => {
    root.walkDecls('user-select', decl => {
      decl.cloneBefore({ prop: '-webkit-touch-callout' })
    })
  }
})
```

**Comment by ai** [comment]
Will you publish a plugin?

**Comment by jakwuh** [comment]
@ai yes, I will publish it this weekend
Thank you for the fast response

**Comment by jakwuh** [comment]
https://www.npmjs.com/package/postcss-touch-callout

**Comment by ai** [comment]
Great! I will promote it on next week.

**Comment by jakwuh** [comment]
Would be great, thank you!
