### ISSUE TITLE
Netbeans and autoprefixer

### ISSUE THREAD

**Issue by torvicv** [postcss/autoprefixer#738]
Is there any plugins for netbeans? 

Or how can I use autoprefixer?

**Comment by ai** [comment]
You should use Autoprefixer from Gulp/webpack. We do not recommend to use it from text editor, because prefixes is sources decrease readability.

**Comment by drakopablodev** [comment]
![image](https://github.com/postcss/autoprefixer/assets/135961183/2bfcf19f-257f-40f5-b77d-d5a0be37ca7b)
1. (optional) Create a project
2. Create a `package.json` file in the project root folder
3. Rigth-click on project folder > Properties
4. Go to JavaScript Libraries > npm (or whatever you want to use)
5. Add -> search the package name -> by default the latest version will be installed
6. ???
7. Profit
