### ISSUE TITLE
trouble with inline style

### ISSUE THREAD

**Issue by oo6890049** [postcss/autoprefixer#739]
```javascript
let prefixer = postcssJs.sync([ autoprefixer ]);

let style = prefixer({
    display: 'flex'
});

style //=> { display: ['-webkit-box', '-webkit-flex', '-ms-flexbox', 'flex'] }
class Test extends Component {
     render(){
     return (<div style={style}>test</div>)
    }
}
```
the value of  style.display  is an Array ,but react inline style seems not accept this format.

![qq 20161105141832](https://cloud.githubusercontent.com/assets/8954811/20028089/f7eb1f96-a362-11e6-80bb-345512500dfc.jpg)
![qq 20161105141318](https://cloud.githubusercontent.com/assets/8954811/20028063/42523796-a362-11e6-89ff-5d1a31798fe5.jpg)

and i use Radium convert the style to ` display: '-webkit-box; display: -moz-box; display: -ms-flexbox; display: -webkit-flex; display: flex',`,but it still not work.

![333](https://cloud.githubusercontent.com/assets/8954811/20028342/c12acd1a-a369-11e6-9d09-87957d5bda20.jpg)

the div's style is always empty 
![qq 20161105141318](https://cloud.githubusercontent.com/assets/8954811/20028346/fc6c2f4a-a369-11e6-8814-e7bf2e765246.jpg)

how can i deal with it?

**Comment by ai** [comment]
Add [JSS](https://github.com/cssinjs/jss) or some more advanced CSS-in-JS solution, which will support different for same property.

**Comment by oo6890049** [comment]
finally,i found solution by [inline-style-prefixer](https://github.com/rofrischmann/inline-style-prefixer),which can add prefix decided by userAgent

**Comment by adrivelasco** [comment]
@ai I have the same issue! Can you explain me more about how to use JSS with autoprefixer? Thanks

**Comment by 11bit** [comment]
Hi @adrivelasco, @ai is currently on vacation without a good internet connection so he won't be able to answer until Jun 6.
By the way, did you try [inline-style-prefixer](https://github.com/rofrischmann/inline-style-prefixer) mentioned above?

**Comment by adrivelasco** [comment]
Thanks for answer, @11bit! Yes, I've solved my problem with inline-style-prefixer, (dyanmic version). That is the only way to fix this issue, right?
