### ISSUE TITLE
the results has changed when I reload the page

### ISSUE THREAD

**Issue by Loatheb** [postcss/autoprefixer#741]
when I open the web page in chrome.

**sometimes**

![2016-11-08 15 16 22](https://cloud.githubusercontent.com/assets/18140164/20090171/70c87fd4-a5c6-11e6-9945-de31cc1594a6.png)

**when I refresh the page for several times, it become:**

![2016-11-08 15 16 40](https://cloud.githubusercontent.com/assets/18140164/20090173/7279e61a-a5c6-11e6-8c6b-6c193296d6d3.png)

here is some of my config files:
**webpack.config.js**
![2016-11-08 15 24 53](https://cloud.githubusercontent.com/assets/18140164/20090345/91636e10-a5c7-11e6-9f14-587eb9ff5c2f.png)

**browserslist**
![2016-11-08 15 22 51](https://cloud.githubusercontent.com/assets/18140164/20090299/59a8265a-a5c7-11e6-8119-7f56b4b68b47.png)

I do not know what the problem is with my configuration

sorry for bothering

**Comment by ai** [comment]
BTW, Autoprefixer has no `config` option.

Sorry, it is not a issue, because related with your environment. I have no big experience with webpack, so I can't really help.

Try to ask on StackOverflow.
