### ISSUE TITLE
[node 5.x] caniusedb-1.0.30000580 will break this package

### ISSUE THREAD

**Issue by catalin-miron-hs** [postcss/autoprefixer#744]
https://github.com/Fyrd/caniuse/issues/2981#issuecomment-260299050

**Comment by ai** [comment]
@catalin-miron-hs how we could fix it in `autoprefixer`?

**Comment by catalin-miron-hs** [comment]
@ai just because you're using a `patch` version that's broken? Just use a freaking `shrinkwrap` or freeze the versions. like instead of https://github.com/postcss/autoprefixer/blob/master/package.json#L21 add `"caniuse-db":           "1.0.30000579"`. 

Care more about your users and  maintaining a fucking great product that's used around the world.

Thanks!

**Comment by ai** [comment]
>  just because you're using a patch version that's broken?

If we will not use `^` dependency, I will be forced to release Autoprefixer on every `caniuse-db` release. It means twice more work.

I have no such free time. If you care about 100% project stability, you can contact with `surrender@evilmartians.com` and we will make a special commercial Autoprefixer with per-year payments.

If you will pay for extra testing and `caniuse-db` updates, my company will move me from my current project to 100% Autoprefixer support. So I will have time for `^`-less dependency.

What do you think about it?

**Comment by catalin-miron-hs** [comment]
What do you think about adding `node 5.9.x` or `node 5.x` in travis?

**Comment by ai** [comment]
@catalin-miron-hs node.js 5 was removed from Travis CI, because it doesn’t supported by node.js: https://github.com/nodejs/LTS

Also Travis will not find this issue. Travis is executed only on next commits, not on npm dependecies updates.

**Comment by catalin-miron-hs** [comment]
@ai thanks!
