### ISSUE TITLE
gulp-autoprefixer causing jenkins builds to fail

### ISSUE THREAD

**Issue by Fayde** [postcss/autoprefixer#745]
Not sure what happened but on Thursday there was no issues, and now it will cause a 
'npm ERR! cb() never called!' 

error.  All I can see if that one of the dependencies was updated within that time span but I have no idea.  Our builds are chain failing now after never failing before

**Comment by ai** [comment]
https://github.com/Fyrd/caniuse/issues/2981

**Comment by ai** [comment]
Please, update node.js to 6 or 7. node.js 5 are not maintained anymore

**Comment by Fayde** [comment]
mate this CI build was working on thursday what changed

**Comment by ai** [comment]
caniuse-db made a “patch” release, which break node.js 5 support.

**Comment by Fayde** [comment]
well that's rude we can't upgrade node this is an enterprise application :/

**Comment by ai** [comment]
In enterprise application you should *never* use non-LTS releases.

node.js 5 has no security updates, because it is not supported by Node Foundation. What kind of enterprise could use so dangerous release?

**Comment by Fayde** [comment]
you'd be surprised.
