### ISSUE TITLE
BrowserslistError: Unknown version 9.9 of and_uc

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#746]
I have old config:

```js
browsers: ['and_uc 9.9']
```

```sh
BrowserslistError: Unknown version 9.9 of and_uc
    at error (/Users/yisi/works/gulp-workflow/node_modules/.npminstall/browserslist/1.4.0/browserslist/index.js:25:15)
```

Caniuse upgrade led to the present does not exist 9.9, see also: https://github.com/Fyrd/caniuse/issues/2888

**Comment by ai** [comment]
@yisibl `caniuse-db` always change latest UC browser version. And they have only latest version.

Use `last 1 and_uc version` :)
