### ISSUE TITLE
-webkit for flex is not prefixed

### ISSUE THREAD

**Issue by italodr** [postcss/autoprefixer#747]
I'm using gulp-autoprefixer with this setting:

```js
browsers : [
        'ie >= 10',
        'ie_mob >= 10',
        'ff >= 30',
        'chrome >= 21',
        'safari >= 6',
        'opera >= 23',
        'ios >= 7',
        'android >= 4.4',
        'bb >= 10'
    ]
```

I am using `flex-wrap: wrap;` and it generates the following

```css
.row {
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
}
```

I've test this on iPad 8.4.1 and of course, it is broken as it expects to have `-webkit-flex-wrap: wrap;`.
Don't know what to do from here. I just tried to change browser versions in options but with the same result. Thanks in advance!

**Comment by italodr** [comment]
Just realize that this is affecting to all flexbox package

**Comment by ai** [comment]
Move your browsers to `browserslist` and please write comment in this issue https://github.com/webpack/css-loader/issues/281
