### ISSUE TITLE
Transition property is broken after prefixing

### ISSUE THREAD

**Issue by DaSchTour** [postcss/autoprefixer#748]
transition-property with to properties is prefixed wrong.
From this line

```
transition-property: bottom, transform;
```

I get this prefixed version. The third entry breaks the transition.
```
transition-property: bottom, -webkit-transform;
transition-property: bottom, transform;
transition-property: bottom, transform, -webkit-transform; 
```

**Comment by ai** [comment]
Yeap. Check Autoprefixer warnings. It warn you that there is no 100% safe way to prefix `transition-property` so it recommends to always use `transition`.

**Comment by DaSchTour** [comment]
Autoprefixer doesn't show any warnings. It shouldn't be that hard to fix this simple problem. You just have to make sure, that a transition-property with 2 values doesn't end up with 3.

**Comment by ai** [comment]
1. How did you run Autoprefixer? Maybe we should create a issue, because you runner doesn't show warnings.
2. Some browsers need 3 values.
3. You could write a custom PostCSS plugin to have your own custom logic for this case (if you couldn't change sources).
