### ISSUE TITLE
Expose feature name in prefixes data

### ISSUE THREAD

**Issue by cvle** [postcss/autoprefixer#754]
Hi everyone!

I am contributing over at [JSS](https://github.com/cssinjs/jss), a CSS in JS solution. We are using our own [vendor prefixer](https://github.com/cssinjs/css-vendor) which uses feature detection instead of the caniuse database. Currently we are implementing a [test suite](https://github.com/cssinjs/css-vendor/pull/11) to test our implementation against yours.

For that purpose we are using your prefixes data at `data/prefixes` to generate our test fixture. But it is incomplete. We would need to have the caniuse feature name as well to query the database, because our library not only does prefixing but also return whether a feature is supported or not.

It would help us a lot if the feature name would be exposed in your prefixes data, e.g.:

~~~coffee
# Border Radius
feature require('caniuse-db/features-json/border-radius.json'), (browsers) ->
  prefix 'border-radius', 'border-top-left-radius', 'border-top-right-radius',
         'border-bottom-right-radius', 'border-bottom-left-radius',
          mistakes: ['-khtml-', '-ms-', '-o-']
          browsers: browsers
          feature: 'border-radius'
~~~

Would you accept a PR?

**Comment by ai** [comment]
Yeap, send a PR.

**Comment by ai** [comment]
But I think using `data/prefixes` is not the best solution for JSS. If you run on client side, you should care about JS file size. In other hand, because CSS-in-JS is new solution, you don’t need to remove outdated prefixes.

As result, you should not care about very old prefixes like `border-radius` and could dramatically reduce JS file size by removing them.

**Comment by cvle** [comment]
We use `data/prefixes` only for the test suite. Everything else is done via feature detection. The library is quite small 3.4kb minified.

**Comment by ai** [comment]
@cvle ouh, greet! :) Sorry I missed it.

**Comment by cvle** [comment]
Would it work doing a dynamic require or will this cause issues? 
Just trying to find a way avoiding typing the feature name twice.

~~~coffee
# require is done inside the feature function
feature 'border-radius', (browsers, feature) ->
  prefix 'border-radius', 'border-top-left-radius', 'border-top-right-radius',
         'border-bottom-right-radius', 'border-bottom-left-radius',
          mistakes: ['-khtml-', '-ms-', '-o-']
          browsers: browsers
          feature: feature
~~~

instead of 

~~~coffee
# Border Radius
feature require('caniuse-db/features-json/border-radius.json'), (browsers) ->
  prefix 'border-radius', 'border-top-left-radius', 'border-top-right-radius',
         'border-bottom-right-radius', 'border-bottom-left-radius',
          mistakes: ['-khtml-', '-ms-', '-o-']
          browsers: browsers
          feature: 'border-radius'
~~~

**Comment by ai** [comment]
Nope 😕

**Comment by cvle** [comment]
Thought so, I'll send a PR soon. Thanks!
