### ISSUE TITLE
IE 10 -ms-flex: 1 1 0

### ISSUE THREAD

**Issue by AdamKettani** [postcss/autoprefixer#755]
Hey guyz

Little issue on IE10 -ms-flex-box
I think the default value for -ms-flex on the child element should be : 1 0 auto.

Here is the situation that made me notice:

I have a parent container with a display of flex

2 child elements

With the default values, the child elements are getting a width of 0. Which is the opposite of the default behavior in recent broswers, where the elements take all the space available

I should mention that if I precise the positive value to 1 the nagative value to 1 and the prefered size to 0, if gives the right behavior. However, oddly, if I let the default of "-ms-flex: 1 1 0" it give my elements a width of 0.

I fix the problem by giving the child element -ms-flex: 1 0 auto

It sounds like a pretty obvious bug, so I obviously might be missing something

Thanks for the awesome product.

Adam Kettani

**Comment by ai** [comment]
Could you show input/output examples to make issue more clear?

**Comment by basovaelizaveta** [comment]
Hi. I fixed that problem by changed my gulpfile to autoprefixer({browsers: ['> 0%', 'IE 9'],	cascade: false})
