### ISSUE TITLE
`font-family: system-ui;` support

### ISSUE THREAD

**Issue by jltrv** [postcss/autoprefixer#762]
See https://github.com/Fyrd/caniuse/issues/2918 for caniuse feature inclusion.

It would be nice if autoprefixer replaced `font-family: system-ui;` with this: 
```
font-family: system-ui, 
    -apple-system, BlinkMacSystemFont, 
    "Segoe UI", "Roboto", "Oxygen", 
    "Ubuntu", "Cantarell", "Fira Sans", 
    "Droid Sans", "Helvetica Neue", sans-serif;
```
(adapted from https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/ )

**Comment by ai** [comment]
Technically it is not a prefix :-/. But I agree that it is useful and people may expect it from Autoprefixer.

Is `system-ui` is standard value? Will browsers support it in future?

**Comment by jltrv** [comment]
It's been approved by the whatwg ( https://drafts.csswg.org/css-fonts-4/#valdef-font-family-system-ui ) and it's supported in chrome 56 (currently in beta).

**Comment by ai** [comment]
I asked a community for feedback https://twitter.com/autoprefixer/status/814506174468984832

**Comment by ai** [comment]
Maybe we should add it to `postcss-cssnext`. I think it is a better place for standard polyfills. But let’s wait a feedback from Twitter users.

**Comment by ausi** [comment]
I think extending `system-ui` to the complete font list from above can be problematic. There is not “the one” list that is correct IMO, it’s just a best practice for now and may be different depending on the user base. The linked Smashing Magazine article itself notes that *“this is not future-proof”* and *“The list targets the most popular browsers and operating systems, but it doesn’t target all of them”*.

I think it would be nice if autoprefixer extends `system-ui` to only `system-ui, -apple-system, BlinkMacSystemFont` which are all equivalent AFAIK and that would be some kind of “prefixing”. The list of fallback fonts should be up to the CSS author (or to cssnext).

**Comment by yisibl** [comment]
I think autoprefixer should only deal with the prefix.

Input:

```css
font-family: system-ui, sans-serif;
```

Output:

```css
font-family: system-ui, -apple-system, sans-serif;
```

**Comment by ai** [comment]
@yisibl good idea!

@jltrv could you start with PR to caniuse with data for prefixes?

**Comment by jltrv** [comment]
@ai working on it

**Comment by ai** [comment]
I decide, that it is not a Autoprefixer deal. You could make a custom PostCSS plugin and we will add it to cssnext and add links from Autoprefixer docs.

Do you need help with it?

**Comment by ausi** [comment]
@ai Is there a specific reason why you decided that way?

I think expanding `system-ui` to `system-ui, -apple-system, BlinkMacSystemFont` would be a good fit for autoprefixer.

**Comment by ai** [comment]
@ausi I think polyfill is much better solution for this problem. Linux and Android users are important too, but  `system-ui, -apple-system, BlinkMacSystemFont` doesn’t cover them.

**Comment by ausi** [comment]
AFAIK `system-ui` will be supported on Linux and Android too according to [Chrome Platform Status](https://www.chromestatus.com/feature/5640395337760768).

**Comment by JLHwung** [comment]
For your information, I just composed a postcss plugin [postcss-font-family-system-ui](https://github.com/JLHwung/postcss-font-family-system-ui) to transform

```css
body {
  font-family: system-ui;
}
```
into
```css
body {
  font-family: system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue;
}
```

**Comment by ai** [comment]
@JLHwung great! Please send it to FAQ section in Autoprefixer README!

**Comment by ai** [comment]
I will try to promote it tomorrow in PostCSS twitter (if I will not forget :D)

**Comment by JLHwung** [comment]
@ai Sure. PR is raised.

спасибо.
