### ISSUE TITLE
`font-smooth: never` with webkit

### ISSUE THREAD

**Issue by lextoc** [postcss/autoprefixer#763]
Isn't `-webkit-font-smoothing: none` the equivalent of `font-smooth: never`? It doesn't get added by my autoprefixer.

Excuse me if I'm wrong, just giving heads up.

**Comment by ai** [comment]
[`font-smooth` property](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth) is not part of standard:

> Though present in early (2002) drafts of CSS3 Fonts, font-smooth has been removed from this specification and is currently not on the standard track.

It is very bad thing. Autoprefixer could not add prefixes for non-standard properties, because CSS will not be useful in future.

**Comment by lextoc** [comment]
Ah yes, I just looked it up on caniuse.com, you're right. I suppose you can close this ;)
