### ISSUE TITLE
notepad++ support for autoprefixer

### ISSUE THREAD

**Issue by jonathanblancor** [postcss/autoprefixer#764]
I don't think notepad++ supports autoprefixer right? Just another environment that could use this tool.

**Comment by ai** [comment]
1. Autoprefixer as text editor plugin is a very bad practice. Prefixes reduce readability. Prefixes will not be updated automatically. Please use Gulp, webpack or other build tool.
2. You should open this isse in Notepad++ issue tracker. I can’t write Notepad++ plugins. so I could not help here.
