### ISSUE TITLE
Problem with vendor prefix inserted *after* standard syntax

### ISSUE THREAD

**Issue by kReEsTaL** [postcss/autoprefixer#765]
Good morning,

I'm using autoprefixer 6.6.1 and I noticed a problem with the order of a CSS selector it produces.

In my Sass file, if I write:

    .some-selector {
      transition: color .15s, transform .5s;
    }

Autoprefixer generates the following code:

    .some-selector {
      -webkit-transition: color .15s, -webkit-transform .5s;
      transition: color .15s, -webkit-transform .5s;
      transition: color .15s, transform .5s;
      transition: color .15s, transform .5s, -webkit-transform .5s;
    }

The last line (`transition: color .15s, transform .5s, -webkit-transform .5s;`) contains a vendor prefix but since it comes _last_, it has priority over the previous line (`transition: color .15s, transform .5s;`) which contains no vendor prefix.

As a result, the transition does not work on Chrome 55.0.2883.95 (64-bit) nor on Firefox 50.1.0.

How would it be possible to invert both lines please? I'm stuck. Thanks for your help!

**Comment by ai** [comment]
Could you show Chrome DevTools screenshot of this block? I need to know does it ignore some properties.

Browsers ignore properties with unknown values, so if browser doesn’t know `-webkit-transform`, it will ignore last line and use `transition: color .15s, transform .5s`. So the order is correct by logic. But maybe we have some other issue here.

**Comment by kReEsTaL** [comment]
Sure, here you are:

![capture d ecran 2017-01-09 a 10 08 01](https://cloud.githubusercontent.com/assets/1950742/21761478/8e9a8918-d653-11e6-97f3-638bb3483d47.png)

**Comment by ai** [comment]
Everything is correct. Could you create some small HTML+CSS demo to check why your animations don’t work?

**Comment by kReEsTaL** [comment]
Sure! You can check a demo on [CodePen](http://codepen.io/kReEsTaL/pen/MJamYe).

The selector on which the bug occurs is `nav a`, where you will find the same lines as the ones I stated in my initial message:

    nav a {
      margin: .5em 0;
      padding: .2em 2em;
      font-size: 1.5em;
      color: white;
      text-decoration: none;
      font-weight: 500;
      -webkit-transform: translateX(-100%);
      transform: translateX(-100%);
      -webkit-transition: color .15s, -webkit-transform .5s;
      transition: color .15s, -webkit-transform .5s;
      transition: color .15s, transform .5s;
      transition: color .15s, transform .5s, -webkit-transform .5s;
      -webkit-transition-timing-function: cubic-bezier(0.19, 1, 0.22, 1);
      transition-timing-function: cubic-bezier(0.19, 1, 0.22, 1);
}

NB: this pen is a fork of [this one](http://codepen.io/Twikito/pen/zGdqVO), where Autoprefixer is not used, and where the animation on `nav a` does work.

I'm trying to obtain the same animation, but the only differences I can see with the original pen and mine is the vendor elements Autoprefixer has added.

**Comment by ai** [comment]
I found problem. `transition-delay` is hard coded to 2 values only, so it stop working on 3 values in `transition: color .15s, transform .5s, -webkit-transform .5s`.

```css
transition-delay: 0s, #{50 + (50 * $i)}ms;
```

You can fix it by:

```css
transition-delay: 0s, #{50 + (50 * $i)}ms, #{50 + (50 * $i)}ms;
```

Unfortunately, there is no way to prefix it in other way. Browsers that you support requires `-webkit-transform`. And the only way to fix it is this big preset and different values length (we thought a lot about some other solution).

Technically, Autoprefixer even warn you about this risk. But you should use gulp/webpack Aurtoprefixer to see warnings. Maybe we need ask @chriscoyier to add some UI and show warnings from PostCSS plugins.

**Comment by ai** [comment]
By the way, menu animation is really gorgeous :+1: 

I few BEM could also decrease Sass nested length and make code more readable.

**Comment by kReEsTaL** [comment]
Great, thank you so much for your help @ai!

I still cannot figure why I cannot compile the line you suggested:

    transition-delay: 0s, #{50 + (50 * $i)}ms, #{50 + (50 * $i)}ms;

Anyway, if I ditch the Sass `for` loop and write it by hand, it works. Another mystery yet to solve!

> By the way, menu animation is really gorgeous 👍

All credits go to @Twikito! :) As for the BEM syntax, yes you're absolutely right. However the original CodePen is a quick demo he wrote, so it's not as compact as it could be.

Thank you again so much for your help! \m/
