### ISSUE TITLE
user-drag

### ISSUE THREAD

**Issue by pinn3** [postcss/autoprefixer#767]
Is `user-drag` scheduled for implementation, or is it considered too experimental?

**Comment by ai** [comment]
We need a W3C draft for it. Do it have it?

**Comment by pinn3** [comment]
After a bit of research, I found [this](http://lists.w3.org/Archives/Public/www-validator-css/2007Nov/0003)
Sorry to bring up this apple webkit fossil, closing this issue now 🙈

**Comment by darsain** [comment]
Still, it's a useful property which is pretty much required in all electron apps. Is there no chance of adding it? 

I just hate that I have autoprefixer in my build pipeline and I still have to deal with prefixes.

**Comment by ai** [comment]
@darsain Autoprefixer idea, that in some prefix-free future you will be able to remove Autoprefixer and everything will work. Without standard non-prefixed property name, will `user-drag` will future proof.

I suggest you to use mixin here.

Or write custom `postcss-user-drag` plugin. Autoprefixer is PostCSS plugin too.

**Comment by darsain** [comment]
Fair enough :)
