### ISSUE TITLE
overflow-scrolling: touch;

### ISSUE THREAD

**Issue by michealengland** [postcss/autoprefixer#769]
I was not sure if this should be added here or not however, I figured it couldn't hurt to share.

When using the overflow: scroll; rule the webkit prefix: -webkit-overflow-scrolling:touch; is not added. The overflow scroll does not work on divs specifically on apple touch devices without the vendor prefix.

If there is a workaround for this please let me know.

Thank you for all of the your hard work on Autoprefixer!

**Comment by ai** [comment]
There is no W3C draft for `overflow-scrolling`, so we could not be sure what property name will be in unprefixed version.

**Comment by michealengland** [comment]
Thank you for taking the time to respond. This does make sense now because I looked that up on Can I Use and didn't have much luck finding the overflow-scrolling rule.
