### ISSUE TITLE
flex-flow does not generate -webkit-box-orient for Android >= 4.1

### ISSUE THREAD

**Issue by rch850** [postcss/autoprefixer#770]
`flex-direction: column;` generates `-webkit-box-orient: vertical;` but `flex-flow: column;` does not for "Android >= 4.1". I expect both results in same.

Before autoprefixer:

```
.example1 {
  flex-direction: column;
}

.example2 {
  flex-flow: column;
}
```

After autoprefixer:

```
.example1 {
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
          flex-direction: column;
}

.example2 {
  flex-flow: column;
}
```

I have tested these on https://autoprefixer.github.io/

**Comment by ai** [comment]
Main problem, that flexbox 2009 spec doesn’t support `flex-wrap`. So `flex-flow` will not work there in full way.

Should we apply part of features or should we ignore whole instruction?

**Comment by ai** [comment]
I think we should support part of features. `flex-flow` is just a shortcut. But if rule contains separated `flex-direction` and `flex-wrap` we anyway will prefix on;y first one.

But I will ask other users in Twitter.

**Comment by rch850** [comment]
I choose to apply part of features but understand there is another choice. I will wait for other's feedback.

**Comment by bfred-it** [comment]
I think it should prefix as much as possible. If the lack of `flex-wrap` _breaks_ my intended layout, imagine how much it breaks lacking both `flex-wrap` and `flex-direction`

**Comment by ai** [comment]
Done 26f5976

But I disabled hack detect for `flex-flow`. I don’t think it is a big problem. I will add more smarter code if somebody really will have problems with it.
