### ISSUE TITLE
Confusion about the right order in task runners etc

### ISSUE THREAD

**Issue by hendrikeng** [postcss/autoprefixer#772]
Hey there, thanks fort the awesome work. 
So, since i just wanted to use gulp and the advantages of stylelint, 
i decided to integrate postcss into my tasks, since we are still using sass and regarding this [article](http://julian.io/some-things-you-may-think-about-postcss-and-you-might-be-wrong/) : 

i decided to keep sass in the flow as well... 
now i am just a bit confused as i usually would put autoprefixer as a plugin into postcss, 
but since postcss needs to apply before sass ( need the linting before the concatenation of the files,
i am afraid that sass will eliminate some autoprefixes, because of the use of mixins and functions
so i thought it has to be after sass then, what eliminates the postcss plugin logic...kinda confusing, i know..i hope its the right place to ask it :-) thats my style task from gulp:

```
// Compile sass into CSS & auto-inject into browsers
gulp.task('scss', () => {
  const processors = [
    stylelint(pkg.stylelint),
    // Pretty reporting config
    reporter({
      clearMessages: true,
      throwError: true,
    }),
      //autoprefixer({ browsers: ['last 2 version'] }), --disabled because of sass
      // cssnano(),  -- same here
  ];
  gulp.src(pkg.paths.src.scss + pkg.vars.scssPattern)
    .pipe($.plumber({ errorHandler: onError }))
    .pipe($.sourcemaps.init())
    .pipe($.postcss(processors, { syntax: scss }))
    .pipe($.sass())
    .pipe($.sourcemaps.write())
    .pipe($.autoprefixer({ 
      browsers: ['last 2 versions'],
      cascade: false,
    }))
    .pipe(cleanCSS({debug: true}))
    .pipe($.rename({ suffix: '.min' }))
    .pipe(gulp.dest(pkg.paths.src.assets))
    .pipe($.notify({
      title: 'Gulp',
      subtitle: 'Success!',
      message: 'Scss task completed!',
      sound: 'Pop',
    }))
    .pipe($.browserSync.stream());
});

```

**Comment by ai** [comment]
I recommend to run PostCSS twice — before and after Sass. So it is a good reason to use PostCSS also for preprocessing to avoid this PostCSS→Sass, Sass→PostCSS transformations :D.

**Comment by ai** [comment]
Technically, Autoprefixer could work on Sass sources, but it is not right way to use it. Result could be wrong in some cases.

**Comment by hendrikeng** [comment]
so i would just include it like that e.g:

```
gulp.task('scss', () => {
  const preProcessors = [
    stylelint(pkg.stylelint),
    reporter({
      clearMessages: true,
      throwError: true,
    }),
  ];
  const postProcessors = [
    autoprefixer({ browsers: ['last 2 version'] }),
  ];
  gulp.src(pkg.paths.src.scss + pkg.vars.scssPattern)
    .pipe($.plumber({ errorHandler: onError }))
    .pipe($.sourcemaps.init())
    .pipe($.postcss(preProcessors, { syntax: scss }))
    .pipe($.sass())
    .pipe($.postcss(postProcessors))
    .pipe($.sourcemaps.write())
    .pipe(cleanCSS({ debug: true }))
    .pipe($.rename({ suffix: '.min' }))

    .pipe(gulp.dest(pkg.paths.src.assets))
    .pipe($.notify({
      title: 'Gulp',
      subtitle: 'Success!',
      message: 'Scss task completed!',
      sound: 'Pop',
    }))
    .pipe($.browserSync.stream());
});
```

thanks a lot for ur help
