### ISSUE TITLE
dppx to dpi conversion for IE 9-11.

### ISSUE THREAD

**Issue by bardiharborow** [postcss/autoprefixer#775]
Autoprefixer should convert:

```
@media (min-resolution: 2dppx) {}
```
to
```
@media (min-resolution: 192dpi), (min-resolution: 2dppx) {}
```

in order to support IE 9-11. 

http://caniuse.com/#feat=css-media-resolution

**Comment by ai** [comment]
It is not prefixes ;) It could be done with 5 lines of code with PostCSS

https://github.com/postcss/autoprefixer#does-it-add-polyfills
