### ISSUE TITLE
Regression: -webkit-box-orient rules removed

### ISSUE THREAD

**Issue by AgentME** [postcss/autoprefixer#776]
While upgrading my dependencies on a project with some pretty old css (and which includes [some webkit-specific hacks](https://css-tricks.com/line-clampin/)), I noticed an issue. Autoprefixer version 6.7.0 now entirely removes "-webkit-box-orient" rules. Version 6.6.1 did not have this issue.

```css
.foo {
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-box-align: stretch;
}
```
->
```css
.foo {
  display: -webkit-box;
  -webkit-box-align: stretch;
}
```

Here's the code I've tested with:

```js
require('postcss')([require('postcss-cssnext')({browsers: 'chrome >= 42, safari >= 8'})]).process('.foo { display: -webkit-box; -webkit-box-orient: vertical; -webkit-box-align: stretch; }').css
```

**Comment by ai** [comment]
Is it a really issue if you ask Autoprefixer to remove old prefix? ;)

**Comment by IharKrasnik** [comment]
@ai How to preserve -webkit-box-orient?

**Comment by ai** [comment]
Add any flexbox 2009 browser to `browserslist` in your `package.json`.

**Comment by IharKrasnik** [comment]
Thank you

**Comment by AgentME** [comment]
@ai This still happens even if I add `remove: false` to the options.

**Comment by ai** [comment]
Are you sure that it does from Autoprefixer? Maybe some other tool (like minification in webpack’s `css-loader`) change file too?

**Comment by yidea** [comment]
tested out with css-loader remain the same version, Autoprefixer is the only factor remains that causing this

**Comment by AgentME** [comment]
Oh, I was passing remove:false to postcss-cssnext. Passing it on to autoprefixer results in -webkit-box-orient not being removed.

```js
var postcss = require('postcss');

var css = postcss([
  require('postcss-cssnext')({
    browsers: 'chrome >= 42, safari >= 8',
    features: {
      autoprefixer: {remove: true}
    }
  })
]).process(`
.foo {
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-box-align: stretch;
}`).css;

console.log(css);
```

I thought the behavior of the (default) remove:true option was to only remove outdated rules if the modern rule was specified too. So that `display:-webkit-flex;display:flex;` -> `display:flex;`, but `display:-webkit-flex;` alone would remain as `display:-webkit-flex;`. This case still seems to be the same. The `-webkit-box-orient` rules uniquely being stripped unconditionally is surprising to me.

**Comment by jrowlingson** [comment]
Disabling the remove option or adding a flexbox 2009 browser to browsers list are both pretty coarse work arounds for this type of scenario. Any interest in adding an option to opt-out of removal at the property level?

**Comment by ai** [comment]
Extra option is not a solution, because most of developers will not read docs.

If you want to fix it, send a PR removing this hack
https://github.com/postcss/autoprefixer/blob/master/lib/processor.coffee#L133

**Comment by jrowlingson** [comment]
@ai thanks - will do

**Comment by Lars-Weber** [comment]
Possibly helpful for anyone reading up on this thread and problem, least intrusive option to prevent the removal of the line in question is to just disable the autoprefixer for this line/section

```
    /* autoprefixer: off */
    -webkit-box-orient: vertical;
    /* autoprefixer: on */
```

**Comment by ai** [comment]
@Lars-Weber best option is just add old Safari to `browserslist` config

**Comment by plamitgma** [comment]
@Lars-Weber: awesome, thank you so much!

**Comment by ai** [comment]
@Lars-Weber @plamitgma `/* autoprefixer: off|on */` doesn’t work like this. This comment disable/enable Autoprefxier for *whole block*, *not* for next lines.

**Comment by shizitou** [comment]
`-webkit-box-orient: vertical ` can not be completed, you say"add old Safari  to browserslist config".
I do not know how to write it. Can you give a specific example？
For beginners, please understand。 thank

**Comment by ai** [comment]
@shizitou create `.browserslistrc` file in your project root with this content:

```
defaults
Safari 6
```

**Comment by kmvan** [comment]
@Lars-Weber Works man.
@ai 

> defaults
> Safari 6

not works man.

**Comment by ai** [comment]
@kmvan do you created Browsersllist config?

**Comment by kmvan** [comment]
@ai Yes.
filename: `.browserslistrc`
content: 

> defaults
> Safari 6

**Comment by ai** [comment]
@kmvan what is your input CSS, output, and expected output?

**Comment by kmvan** [comment]
@ai The output result `-webkit-box-align: stretch;` is missing. Expected output that keeps  `-webkit-box-align: stretch;` .

**Comment by ai** [comment]
@kmvan what is CSS input? ;)

**Comment by kmvan** [comment]
@ai Sorry, not CSS. Just SCSS input: `-webkit-box-align: stretch;`

**Comment by ai** [comment]
@kmvan give me full rule of SCSS input, not a line

**Comment by wjtGitHub** [comment]
@Lars-Weber 
Thank you for your help.But the error occur when I use you method.
```
./node_modules/css-loader??ref--7-2!./node_modules/postcss-loader/lib??ref--7-3!./node_modules/stylus-loader??ref--7-4!./src/components/notecatalog/style.styl
(Emitted value instead of an instance of Error) autoprefixer: E:\code\webpack4\src\components\notecatalog\style.styl:21:28: Second Autoprefixer control comment was ignored. Autoprefixer applies control comment to whole block, not to next rules.
 @ ./src/components/notecatalog/style.styl 2:14-206 21:1-42:3 21:204-42:2 22:19-211
 @ ./src/components/notecatalog/index.tsx
 @ ./src/views/note/index.tsx
 @ ./src/route/entry.route.ts
 @ ./src/route/index.ts
 @ ./src/store/store.ts
 @ ./src/main.tsx
 @ multi webpack-hot-middleware/client?path=/__webpack_hmr&timeout=2000&reload=true ./src/main.tsx
```

**Comment by ai** [comment]
@wjtGitHub because it is a wrong code ;). `/* autoprefixer: off */` disable Autoprefixer for the whole rule, not for next properties.

**Comment by fan-haobai** [comment]
最后回退到6.5.1了。

**Comment by lukechinworth** [comment]
thanks @Lars-Weber 
for those working in scss, you need to add a `!` to the start of the comment so that it is preserved for postcss:
```css
.box-vertical {
    /*! autoprefixer: off */
    -webkit-box-orient: vertical;
}
```

**Comment by xuanGetit** [comment]
the best solution is the follow, if you use less
.test-orient{
        display: -webkit-box;
        /*! autoprefixer: off */
        -webkit-box-orient: vertical;
        /*! autoprefixer: on */
        -webkit-line-clamp: 2;
        overflow: hidden;
    }

**Comment by ai** [comment]
@xuanGetit it is wrong since `autoprefixer: off/on` disable/enable Autoprefixer for whole block, not next lines. Use `autoprefixer ignore next` (check docs for correct syntax).

**Comment by kmvan** [comment]
@ai Yes.
My `scss` file content:
```scss
.line {
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;

  /*! autoprefixer: off */
  -webkit-box-orient: vertical;
  /*! autoprefixer: on */
}
```

My `.browserslistrc` file content:
```
defaults
Safari 6
```

My `webpack config` :
```js
    new OptimizeCssAssetsPlugin({
      assetNameRegExp: /\.css$/g,
      cssProcessor: require('cssnano'),
      cssProcessorOptions: {
        discardComments: { removeAll: true },
      },
      canPrint: true,
    }),
```

output to `css` file (`-webkit-box-orient` is missing):
```css
.line {
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;
}
```

So can I keep `-webkit-box-orient` with `discardComments: { removeAll: true },` ?

**Comment by ai** [comment]
@kmvan 

> it is wrong since autoprefixer: off/on disable/enable Autoprefixer for whole block, not next lines. Use autoprefixer ignore next (check docs for correct syntax).

**Comment by kmvan** [comment]
@ai 
```scss
  /* autoprefixer: ignore next */
  -webkit-box-orient: vertical;
```
It works, thank you very much.

**Comment by minchangyong** [comment]
But it doesn't show up after packaging

**Comment by jinglf000** [comment]
@kmvan 
  **In vue-cli  project;** Some plugin may delete comment in css files for ugify css file; So like this
```
/* autoprefixer: off */
...
/* autoprefixer: on */
```
may be delete. In my vue project , Use this is efficient
```
 /*! autoprefixer: off */
...
 /*! autoprefixer: on */
```

**Comment by ai** [comment]
@jinglf000 I removed your comment since it is wrong to put off and on comments. Autoprefixer apply these comments to whole block, NOT next lines (Autoprefixer even show a warning about it).

In Sass use `/*! autoprefixer: ignore next */`

**Comment by mebibou** [comment]
I've been trying to use `/*! autoprefixer: ignore next */` in my sass file but it does not seem to be taken into account, probably something is removing the comment before `autoprefixer` tries to read it? my webpack config:
```
{
        test: /\.(sa|sc|c)ss$/,
        use: [
          devMode ? 'style-loader' : MiniCssExtractPlugin.loader,
          {
            loader: 'css-loader', // translates CSS into CommonJS modules
            options: {
              sourceMap: true
            }
          },
          {
            loader: 'resolve-url-loader',
            options: {
              attempts: 1,
              silent: true
            }
          },
          {
            loader: 'postcss-loader', // Run post css actions
            options: {
              sourceMap: true,
              plugins() { // post css plugins, can be exported to postcss.config.js
                return [
                  require('postcss-flexbugs-fixes'),
                  require('autoprefixer')
                ];
              }
            }
          },
          {
            loader: 'sass-loader', // compiles SASS to CSS
            options: {
              sourceMap: true
            }
          },
          {
            loader: 'sass-resources-loader',
            options: {
              resources: [
                `${conf.paths.src}/shared/mixins.scss`,
                `${conf.paths.library}/bootstrap-imports.scss`
              ]
            },
          }
        ]
      }
```

**Comment by jinglf000** [comment]
@ai In my Vue project( use vue-cli init), I had tried many ways, such as 
```
/*! autoprefixer: ignore next */
option - remove: false
/* autoprefixer: autoprefixer: off */
/* autoprefixer: autoprefixer: on */
```
That not useful,only by this way
```
/*! autoprefixer: off */
...
 /*! autoprefixer: on */
```

case:
![image](https://user-images.githubusercontent.com/14195057/42607654-9c24b752-85b6-11e8-90fa-0fd22172b15c.png)

**Comment by ai** [comment]
@meigesir you use very outdated Autoprefixer. The current version is 9.

**Comment by Benbzhou** [comment]
less 用/*! autoprefixer: off */
-webkit-box-orient: vertical;
/*! autoprefixer: on */
sass 用/* autoprefixer: off */
-webkit-box-orient: vertical;
/* autoprefixer: on */

**Comment by marialovesbeans** [comment]
Can anyone please make a PR to fix this by default? This css rule is used together with `-webkit-line-clamp` to achieve multiline ellipsis **even in the latest Chrome & Safari**, and **should NOT** be removed. 

```
line-height: 1em;
max-height: 2em;
display: -webkit-box;
-webkit-box-orient: vertical;
-webkit-line-clamp: 2;
```

**Comment by mozibrand** [comment]
> autoprefixer

Is it the same in less？ I used it in less, but it didn't work

**Comment by ai** [comment]
@zuobaiquan nope, `off` disable for the whole block. Use `/* autoprefixer: ignore next */`
