### ISSUE TITLE
The CSS Sizing module has renamed the fill keyword to stretch

### ISSUE THREAD

**Issue by Semigradsky** [postcss/autoprefixer#784]
Spec: https://www.w3.org/TR/2017/WD-css-sizing-3-20170207/#changes

**Comment by ai** [comment]
Fuck. I will try to fix in on this week.

Feel free to ping me, if I will forget.

**Comment by ai** [comment]
Done 922c512

Is everything good?

**Comment by ai** [comment]
I show a warning on every outdated `fill`

**Comment by Semigradsky** [comment]
Looks good to me

**Comment by ai** [comment]
Released in 6.7.3
