### ISSUE TITLE
-ms-flexbox and "not ie <= 11"

### ISSUE THREAD

**Issue by gauntface** [postcss/autoprefixer#789]
Hi,

I raised this issue on Lighthouse (a tool that checks certain rules against a website to see how it's performing as well as see it's taking advantage of latest API's while following web best practices).

One of the rules checks for old versions of flexbox of which the old `-ms-flexbox` rule gets flagged. I tried to explore how to disable this in autoprefixer and would have thought this would have been enough: 

    const browserSupport = [
      'last 2 versions',
      'not ie <= 11',
    ];

But it's still getting included. Any ideas what I'm doing wrong?

Cheers,
Matt

**Comment by ai** [comment]
Strange. Try this tool to select browsers: http://browserl.ist

Also be sure that you use `browserslist` config (or `browserslist` key in `package.json`) as we recommend.

**Comment by gauntface** [comment]
That is a super useful site!

I thought that ie_mob may be the culprit but removing ie and ie_mob, I'm still getting -ms-flexbox in the final CSS: 

```
const browserSupport = [
  'last 2 versions',
  'not ie <= 11',
  'not ie_mob <= 11',
];
```

**Comment by ai** [comment]
> Also be sure that you use `browserslist` config (or `browserslist` key in `package.json`) as we recommend.

**Comment by gauntface** [comment]
Got you. Looking at: https://autoprefixer.github.io/ it seems to work with 'last 2 versions, not ie <= 11, not ie_mob <= 11' so will figure out what is going on in my build browser.

**Comment by ai** [comment]
You may have Autoprefixer in some other tool. This is why using a browserslist config is a best idea, because it will share same browsers between all Autoprefixer instances. Also Babel, ESLint and Stylelint will use it.

**Comment by gauntface** [comment]
yeah it's cssnext. Using their `browsers` option doesn't seem to work and in the end using the config file seemed to work.

**Comment by ai** [comment]
If you have `cssnext` you should remove second Autoprefixer to speed up build process :).
