### ISSUE TITLE
-webkit-touch-overflow Issue

### ISSUE THREAD

**Issue by chaffeqa** [postcss/autoprefixer#802]
I don't know where to go with this issue, but `-webkit-touch-overflow: touch;` is a huge performance and optimization for iOS safari.

However since csslint `property-no-vendor-prefix` relies on autoprefixer and is flagging that property, I figure here or caniuse would be the place to ask if we could get that property white listed.

I understand its legacy, and has no spec or future, but its definitely a "hack" with huge wins for products and a decent market share, so I'd propose its worthy a workaround.

**Comment by ai** [comment]
Yeap, I agree. Autoprefixer doesn't remove it, so it is OK here.

Ask Stylelint to add some whitelist for this case.
