### ISSUE TITLE
Interested in porting to JavaScript?

### ISSUE THREAD

**Issue by alangpierce** [postcss/autoprefixer#810]
Hi there, I'm the main person working on the [decaffeinate](https://github.com/decaffeinate/decaffeinate) project recently, which converts CoffeeScript to readable modern JavaScript to help people who are looking to migrate away from CoffeeScript. I've been using the autoprefixer project as a test case and it seems to be stable.

You can see the progress on autoprefixer and other projects on the [status section of the README](https://github.com/decaffeinate/decaffeinate#status). I have a daily build that converts all autoprefixer files to JavaScript, then patches the build system to use babel and runs all of the tests, which all pass. The fork is on GitHub, in case you want to see what the output looks like:
https://github.com/decaffeinate-examples/autoprefixer

Obviously there are a lot of tradeoffs to think about and some inherent risks, and you may be happy with CoffeeScript, but if you're interested in migrating to JavaScript, I'd be happy to provide any advice on how to use decaffeinate. The fork is a good starting point, but for a real conversion it probably makes sense to spread the work out over time and clean up style issues in the code as you go.

Cheers, and thanks for the cool project!

**Comment by ai** [comment]
Hi. I am OK with rewritting Autoprefixer to ES6. Also we will have major release soon, so it will be safer.

But I will have time for this task only after I will finish PostCSS 6.0.

**Comment by ai** [comment]
I checked decoffeinated source. They are still a little dirty. We need human check and clean. I will try to find somebody for it.

**Comment by Semigradsky** [comment]
Hi, I can help with porting to JS.

**Comment by ai** [comment]
@Semigradsky OK, fork their branch, clean all sources and send PR (don’t forget to make it in own branch, not `master`, because we will may have many fixes after PR)

**Comment by azat-io** [comment]
Me too :+1:

**Comment by alangpierce** [comment]
> I checked decoffeinated source. They are still a little dirty. We need human check and clean.

Yeah, decaffeinate tries to make the JS code nice-looking, but in some cases it's hard to accomplish. Note that there are a bunch of `--loose` options in decaffeinate that produce nicer looking code but have some risk of introducing subtle bugs due to differences between CS and JS. Certainly feel to file bugs on the decaffeinate project if you think the resulting code could be improved without sacrificing correctness.

My fork of the project only changes the build system enough to get the tests running, but I imagine there would be more work to do as well. My repo also commits some of the results and changes the README for easy browsing in GitHub, so probably it would make sense to run decaffeinate from scratch rather than using my repo directly.

I wrote up a conversion guide a while back that may help:
https://github.com/decaffeinate/decaffeinate/blob/master/docs/conversion-guide.md#converting-a-whole-project

Certainly your call on how to go about the conversion, but here's what I'd recommend:

* Set up the build system to use babel with the config you want.
* Set up eslint with your preferred styles, and generally decide on any conventions.
* Run `bulk-decaffeinate convert` on one file. Figure out what you're happy with and what cleanups you want to make in each file. Figure out what decaffeinate config you want to use. For example, `--keep-commonjs` skips the conversion to `import`/`export`, which is safer but less modern.
* Work through the other files incrementally, maybe a few files at a time.
* When there's no more CoffeeScript, remove any CoffeeScript tooling and dependencies.

But this project is small enough that an all-at-once conversion may be fine and would save some of the headache of supporting both CS and JS in the same codebase. Another option is to do the automatic conversion and view the JS style issues as tech debt that will be cleaned up later, maybe when working with individual files. There are lots of options, just calling out a few different ways to think about it.

**Comment by ai** [comment]
Done by @Semigradsky in `v7` branch
