### ISSUE TITLE
[css-grid] aligning grid items

### ISSUE THREAD

**Issue by hovoodd** [postcss/autoprefixer#814]
input:

    .foo {
        align-self: center; 
    }
    
    .bar {
        justify-self: center;
    }

output:

    .foo {
        -ms-flex-item-align: center;
        -ms-grid-row-align: center;
        align-self: center;
    }

    .bar {
        justify-self: center;
    }

should be: 

    .foo {
        -ms-grid-row-align: center;
        align-self: center; 
    }

    .bar {
        -ms-grid-column-align: center;
        justify-self: center;
    }

**Comment by ai** [comment]
First example have two purity like property, because Autoprefixer doesn't know is it Flexbox or Grid case.

Second property should be fixed, agree.

**Comment by ai** [comment]
But I will be able to fix it only after a week. Right now we are in the middle of transition to ES6

**Comment by ai** [comment]
Done ba3821a

Will be released in 7.0
