### ISSUE TITLE
Replace initClass() to static propeties

### ISSUE THREAD

**Issue by ai** [postcss/autoprefixer#816]
Right now we use `initClass()` method to set static properties to class. But Babel support spec draft for static properties and we should use it as PostCSS.

@Semigradsky do you want to finish your CoffeeScript → ES7 migration?

**Comment by Semigradsky** [comment]
https://github.com/tc39/proposal-class-public-fields from Stage 2?
Yes, I will add.

I was not sure that it necessary: `initClass` readed not bad and adding features from Stage less that 3 is not good practice. But why not?

**Comment by ai** [comment]
Yeap, stage 2 is OK here. Anyway it is better than 100% custom CoffeeScript syntax :D.
