### ISSUE TITLE
@Mixin code not getting vendor prefixes

### ISSUE THREAD

**Issue by eliasylee** [postcss/autoprefixer#819]
The following is simplified, but roughly my code looks like this:

Current input:

```
#container {
  @include align-children;
}
```

```
@mixin align-children {
  & > * {
    position: relative;
    top: 50%;
    transform: translateY(-50%);
  }
}
```

Current output:

```
#container > * {
  position: relative;
  top: 50%;
  transform: translateY(-50%);
}
```

Am I doing something incorrectly here? I know that having the following:

```
#container {
  & > * {
    position: relative;
    top: 50%;
    transform: translateY(-50%);
  }
}
```

works fine with Autoprefixer as the vendor prefixes are all there.

**Comment by ai** [comment]
This question is about Sass mixins? Why you asked it here?

**Comment by ai** [comment]
You have this output because Sass expand nested blocks. You can’t disable it. It is how it works.

**Comment by eliasylee** [comment]
Do you mean if I don't nest it it should work fine?

```
@mixin align-children {
  position: relative;
  top: 50%;
  transform: translateY(-50%);
}
```

**Comment by ai** [comment]
@eliasylee why you ask this question here? Autoprefixer doesn’t work with `@mixin` and `@include` ;).

It only adds prefixes. And there is no prefixes problem here.

You should ask Sass team.

**Comment by eliasylee** [comment]
If Autoprefixer doesn't work with @mixin and @include, this sounds perfectly like an Autoprefixer issue.

But regardless, I was under the impression that Sass pre-processes CSS files and removes at-rules before Autoprefixer comes in sees:

```
#container > * {
  position: relative;
  top: 50%;
  transform: translateY(-50%);
}
```

Is this not the case?

**Comment by ai** [comment]
Just put PostCSS (Autoprefixer is PostCSS plugin) after Sass. In this case Autoprefixer will work with CSS.
