### ISSUE TITLE
text-fill-color not supported

### ISSUE THREAD

**Issue by DarkMatterMatt** [postcss/autoprefixer#822]
I don't know if I'm doing it wrong or if `text-fill-color` is not supported. [Can I Use](http://caniuse.com/#feat=text-stroke) says that it is compatible with most browsers with the `-webkit-` prefix.

I believe I should be able to type `text-fill-color: black;` into [AutoPrefixer](https://autoprefixer.github.io/), and it should turn into `-webkit-text-fill-color: black;`. Why is this not happening?

**Comment by ai** [comment]
There is no standard for it, so there will not be `text-fill-color` property.

https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-fill-color
