### ISSUE TITLE
Adding custom attributes

### ISSUE THREAD

**Issue by KurtPreston** [postcss/autoprefixer#826]
CanIUse is a great resource, but it doesn't include all prefixable attributes.

For example, is there any way to configure autoprefixer to prefix the `hyphenate-character` attribute?  CanIUse has an issue to list this attribute (https://github.com/Fyrd/caniuse/issues/2155), but it's been open for two years.  I'd love to be able to autoprefix this attribute without needing to rely on CanIUse.

**Comment by ai** [comment]
Do we have prefixes for this properties? I can create PR to Can I Use if b you get me any Information.

**Comment by KurtPreston** [comment]
Thanks for the prompt response!  Here's a table listing the new hyphen CSS classes and the supported prefixes:
http://webdesign.about.com/od/fonts/a/hyphenation-in-css3.htm

The CSS4 properties are:
```
hyphenate-character
hyphenate-limit-zone
hyphenate-limit-chars
hyphenate-limit-lines
hyphenate-limit-last
hyphenate-charset
hyphenate-limit-after
hyphenate-limit-before
```

Currently supported prefixed properties include:
```
-moz-hyphens
-webkit-hyphens
-ms-hyphens
-webkit-hyphenate-character
-ms-hyphenate-limit-zone
-ms-hyphenate-limit-chars
-webkit-hyphenate-limit-lines
-ms-hyphenate-limit-lines
-webkit-hyphenate-charset
-webkit-hyphenate-limit-after
-webkit-hyphenate-limit-before
```

**Comment by ai** [comment]
I will try to think of implementation after 7.0 release. If you want to help me, you can send PR to Can I Use.

**Comment by KurtPreston** [comment]
Cool, I opened a PR on CanIUse with what information I could find on browser support:
https://github.com/Fyrd/caniuse/pull/3407

**Comment by davidwebca** [comment]
Sorry to ping here, but has hyphenate-character been added? It doesn't get prefixed and it's still needed (sigh). At least, webkit prefix seems to be still needed for 102.0.5005.61.
