### ISSUE TITLE
Not creating any prefixes

### ISSUE THREAD

**Issue by chavab1** [postcss/autoprefixer#830]
I've used this plugin in several projects before and I've never had any problems. However, all of a sudden no prefixes are being added. In previous projects I never had to add the browserlist section in my package.json but since I'm having problems I added this time and I'm still not seeing prefixes.

I'm using PostCSS with this plugin. This is what I have in my gruntfile:
```
        postcss: {
            options: {
                map: true,
                processors: [
                    require('autoprefixer')({ browsers: ['last 2 versions'] }), // add vendor prefixes
                ]
            },

                src: 'stylesheets/css/styles.min.css'

        },
```

And this is the browserlist section in my package.json file:

```
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "ie 6-8",
    ">= 5%",
    "ie 6-8"
  ]
```

I've tried replacing `last 2 versions` with `>= 5%` but I got this error: `Fatal error: Unknown browser query `>= 5%``

Am I doing something wrong? As I said I've used this tool before with no problems whatsoever.

Any help would be appreciated.

Thanx

**Comment by ai** [comment]
`>=` will be released only in next Autoprefixer 7.

What CSS you use to test Autoprefixer? Maybe you don't need prefixes right now.

**Comment by ai** [comment]
Also you must remove `browsers` option if you use `browserslist` config

**Comment by chavab1** [comment]
Oh, OK. I got it. I thought I needed to included the browsers options as well. 
In previous projects I didn't even need to include the `browserlist`; I would only include the `browsers` option and it would work. That wasn't working this time. It finally worked when I added the `browserlist`.

Thank you very much for your help.
