### ISSUE TITLE
Autoprefixr is not working for rules like these @media (-webkit-min-device-pixel-ratio: 1) {}

### ISSUE THREAD

**Issue by jitendravyas** [postcss/autoprefixer#837]
I check here https://autoprefixer.github.io/ with `@media (min-device-pixel-ratio: 1) {}`

I'm not sure if I can go with this rule in stylelint

![image](https://cloud.githubusercontent.com/assets/77309/25897731/a36bff86-35a6-11e7-914c-348d36aae6b5.png)

**Comment by ai** [comment]
There is no `min-device-pixel-ratio`. You mist use `min-resolution`. I will write to stylelint config generator author.

**Comment by ai** [comment]
https://github.com/postcss/autoprefixer/blob/master/test/cases/resolution.out.css

**Comment by jitendravyas** [comment]
stylelint has same example https://stylelint.io/user-guide/rules/media-feature-name-no-vendor-prefix/

**Comment by ai** [comment]
Where? I didn’t found `min-device-pixel-ratio` there
