### ISSUE TITLE
-webkit-flex

### ISSUE THREAD

**Issue by webfansplz** [postcss/autoprefixer#845]
why -webkit-flex can't appear

**Comment by ai** [comment]
Show your input CSS, output CSS and build tool config

**Comment by xiaomaisu** [comment]
'postcss': [
                        require('autoprefixer')(['last 2 versions', '>1%', 'Android >= 3.2', 'Firefox >= 20', 'iOS 7'])
]  Is the config not ok?I used webpack


input:
.desc {
   display:flex;
}
output:

.desc {
  display: -ms-flexbox;
  display: flex;
}

**Comment by xiaomaisu** [comment]
I use gulp-autoprefixer and the config is the same,and the result is -webkit-flex can appear,
whether  it is  a error in  webpack config that lead that result?

**Comment by ai** [comment]
@xiaomaisu first you need to use Autoprefixer how we recommend it to you ;).

1. We don’t recommend to use `gulp-autoprefixer`. You must use `gulp-postcss` with `autoprefixer` plugin https://github.com/postcss/autoprefixer#gulp
2. Then you should define browsers in `browserslist`config, not in option https://github.com/postcss/autoprefixer#browsers
