### ISSUE TITLE
Browser list as object [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [postcss/autoprefixer#849]
In my package.json I'm already defining targets like this for babel and in `browserlist`
```
                    "targets": {
                        "chrome": "58"
                    },
```
How do I give an object to autoprefixer browser config? Because of this `Module build failed: TypeError: queries.forEach is not a function` I suspect is only taking arrays...

**Comment by Semigradsky** [comment]
> I'm already defining targets like this for babel

It's only babel feature. Use [`browserslist`](https://github.com/ai/browserslist) instead:
```
"targets": {
    "browsers": ["chrome 58"]
}
```

**Comment by ai** [comment]
Future version of Babel will support Browserslist format. But right now you show write browsers 2 times.
