### ISSUE TITLE
less files no autoprefixer  imported from main.js

### ISSUE THREAD

**Issue by freeliu** [postcss/autoprefixer#852]
import less or scss file from main.js ,the generated style has no autoprefixer  ,
But when I import the same file from the style tag of .vue file, it has autoprefixer   .
I want the autoprefixer  ,but I don't want  to import style Sheet from  style tag because webstorm has's no css code autocompletion  when there is a style tag  inside the page

**Comment by ai** [comment]
How do you import less/scss to `main.js`. Do you use webpack for it?

**Comment by freeliu** [comment]
sorry! my bad. I come across this problem in vue-cli. If you still Interested，here is the demo file.
[autoprefix.zip](https://github.com/postcss/autoprefixer/files/1126918/autoprefix.zip)


![0159fd9a-1d01-4916-bbd9-9b53fed6b02c](https://user-images.githubusercontent.com/16299375/27899387-9aec01ac-625c-11e7-9fc1-5c3d65cf48aa.png)
