### ISSUE TITLE
wrong linear-gradient for webkit prefixer

### ISSUE THREAD

**Issue by newdefence** [postcss/autoprefixer#853]
input: 
`background: #a5550e linear-gradient(#a7570e, #562901);`

browsers:`[" Chrome >= 1", "Firefox >=1"]`
output:
`background: #a5550e -webkit-linear-gradient(#a7570e, #562901);
background: #a5550e -moz-linear-gradient(#a7570e, #562901);
background: #a5550e linear-gradient(#a7570e, #562901);`

this is wrong, because -webkit- and -moz- color syntax is different from standard syntax,
the correct out is:
`background: #a5550e -webkit-linear-gradient(#562901, #a7570e);
background: #a5550e -moz-linear-gradient(#562901, #a7570e);
background: #a5550e linear-gradient(#a7570e, #562901);`

thanks for solve this bug;

**Comment by ai** [comment]
Can you show some proofs, that Chrome and Firefox need reverse color stops?

Strange that we found it only today after 5 years of using Autoprefixer by million users.

**Comment by newdefence** [comment]
You can try it in chrome and firefox browsers. Facts speak louder than words.

If you can undetstand Chinese language, look at this article: 
http://www.zhangxinxu.com/wordpress/2013/09/%e6%b7%b1%e5%85%a5%e7%90%86%e8%a7%a3css3-gradient%e6%96%9c%e5%90%91%e7%ba%bf%e6%80%a7%e6%b8%90%e5%8f%98/
