### ISSUE TITLE
Webpack, Autoprefixer and Source Maps

### ISSUE THREAD

**Issue by ronaldgj** [postcss/autoprefixer#859]
Hi there,

I have an issue and I don't know exactly where I should mention it. But I think this is the best place. I hope you can help me further.

I have a Webpack config file, to compile all Javascript and SCSS. For the SCSS I use the sass-loader, then resolve-url-loader, then postcss-loader and the css-loader is the last one.

In the options I pass the sourceMap: true, so I'll have source maps for developing. But when I use autoprefixer, the linenumbers of the sourcemap aren't correct.

I made a simple example with display: flex. Autoprefixer will add two lines for that. But when I check my Chrome Developers Console, the linenumbers are incorrect. The sourcemaps have included the two new lines, but in de .scss file I can only see display: flex;.

It is a little bit hard to explain, but I hope you understand.

```js
let path = require('path');
let webpack = require('webpack');
let ExtractTextPlugin = require('extract-text-webpack-plugin');

let webpackConfig = {

	entry: {
		'/js/main': [
			path.resolve( __dirname, 'src/js/main.js' ),
			path.resolve( __dirname, 'src/scss/main.scss' )
		]
	},

	output: {
		path: path.resolve( __dirname, 'public' ),
		filename: '[name].js',
		chunkFilename: 'js/[name].js'
	},

	devtool: false,

	stats: {
		hash: false,
		version: false,
		timings: false,
		children: false,
		errors: true
	},

	module: {
		rules: [{
			test: /\.s[ac]ss$/,
			use: ExtractTextPlugin.extract({

				fallback: 'style-loader',

				use: [{
					loader: 'css-loader',
					options: {
						importLoaders: 3,
						sourceMap: true
					}
				}, {
					loader: 'postcss-loader',
					options: {
						sourceMap: true
					}
				}, {
					loader: 'resolve-url-loader'
				}, {
					loader: 'sass-loader',
					options: {
						precision: 8,
						outputStyle: 'expanded',
						sourceMap: true
					}
				}],
			})
		}]
	},

	plugins: [

		new ExtractTextPlugin({
			filename: '/css/main.css',
			allChunks: true
		}),

		new webpack.LoaderOptionsPlugin({
			minimize: process.env.NODE_ENV === 'production',
		}),

		new webpack.DefinePlugin({
			'process.env': {
				NODE_ENV: JSON.stringify( process.env.NODE_ENV )
			}
		})
	]
}

module.exports = webpackConfig;
```

**Comment by ai** [comment]
1. I need example how line numbers are incorrect. What is actual and what is expected line numbers.
2. Can you try it without Sass? PreCSS or postcss-cssnext could give you preprocessor features.

**Comment by ronaldgj** [comment]
![autoprefixer-sourcemaps](https://user-images.githubusercontent.com/2691892/28088480-1751437e-6686-11e7-848b-10102290327e.png)

I hope this image will make sense! Please ask me if you need more info.

And I looked into postcss-cssnext, but I can't quickly figure it out yet how I get ik working. I need more time for that.

Thank you for your help and support.

**Comment by ai** [comment]
Seems like source maps are not passed to PostCSS. Can you debug `postcss/lib/postcss.js` to check what arguments are passed from Webpack.

Don't afraid, it is simple JS. Just put `console.log`. Webpack should pass `opts.map.prev`.

**Comment by ronaldgj** [comment]
I'm in the file, but where should I put the `console.log`. I can't find an argument of `opts`

**Comment by ronaldgj** [comment]
I also found `postcss/lib/map-generator.js`. When I debug there in this function:
```
MapGenerator.prototype.previous = function previous() {
        var _this = this;

        console.log( '\n\n' );
        console.log( this.previousMaps );
        console.log( '\n\n' );

        if (!this.previousMaps) {
            this.previousMaps = [];
            this.root.walk(function (node) {
                if (node.source && node.source.input.map) {
                    var map = node.source.input.map;
                    if (_this.previousMaps.indexOf(map) === -1) {
                        _this.previousMaps.push(map);
                    }
                }
            });
        }

        return this.previousMaps;
    };
```

It will log 4 times. The first time is 'undefined' and after that I'll get 3 times the same `PreviousMap` object.

**Comment by ai** [comment]
Strange. Could you create a issue in postcss-loader. I am not sure that all options are passed correctly.

But, honesty, source maps between different tools (like Sass > PostCSS) doesn't always work perfectly.

This is why using one tool for most of tasks is better. Also it will be much faster.

**Comment by ronaldgj** [comment]
I agree definitely with you about the last sentence! ;)

In my webpack configuration I didn't set the sourcemap flag on the `resolve-url-loader`. When I do, there aren't any sourcemaps more at all! Very strange.

I will make an issue so we take a look. I also don't know if it is a problem of webpack, sass-loader or maybe postcss. I hope we can find out!

Thank you again for support.

**Comment by michael-ciniawsky** [comment]
Could you try without `resolve-url-loader`, it uses `rework` (deprecated) internally, just to have a third CSS tool in there 😉  and uses `sourcemaps` to resolve `urls` somehow.

Another source might be between `postcss-loader` => `css-loader` updating the `sourcemap` incorrectly, if you use just the simple `main.scss` file without any `url()` or `@import`, you can remove `css-loader` temporarily and just use `postcss-loader` as the loader will export a module instead of a `{String}` then. Also the `{ sourceMap: 'inline' }` (`postcss-loader`) option might be helpful, which inlines the sourcemap generated by PostCSS directly as an annotation comment into the source (Firefox || Chrome >= 58 should supports it), so we can ensure at least if it's an issue with `postcss-loader` or not. If you could provide small test repo I can also take a look into it aswell :)

**Comment by ronaldgj** [comment]
Hi @michael-ciniawsky,

Thank you for your reply. I've a little busy time right now, so I'll try to make a simple example repo so we can dive in to it as soon as possible. I am using `url()` and `@import` so I can't leave out the `css-loader`.

I will share the repo here when I got it!

**Comment by ronaldgj** [comment]
Good evening @michael-ciniawsky,

It took some time but I uploaded an example to a repo:
https://github.com/ronaldgj/webpack

If you simple do `npm install` and after that run `npm run dev`, you will see that the line numbers of the sourcemap are different.

I hope you can help me with it.

Thank you in advance.
