### ISSUE TITLE
BrowserslistError: Unknown browser query `xxxxxx`

### ISSUE THREAD

**Issue by afzalah** [postcss/autoprefixer#860]
**npm ls autoprefixer**
```bash
├── autoprefixer@7.1.2 
└─┬ css-loader@0.28.4
  └─┬ cssnano@3.10.0
    └── autoprefixer@6.7.7 
```
**webpack.config.js**
 ```
module: {
        loaders: [
           {
                test: /\.(less|css)$/,
                loader: buildDep(["style-loader", "css-loader", "less-loader", "postcss-loader"], ExtractTextPlugin.extract({
                    fallback: "style-loader",
                    use: ["css-loader", "less-loader", "postcss-loader"]
                }))
            }
       ]
}
```
**postcss.config.js**
```
module.exports = {
    plugins: [
        require('autoprefixer')({
            browsers: [
                "last 1 Chrome versions",
                "last 1 Edge versions",
                "last 1 Firefox versions",
                "last 1 IE version",
                "last 1 iOS versions",
                "last 1 Opera versions",
                "last 1 Safari versions",
                "not ie <= 10",
                "not op_mini all", //opera mini
                "not op_mob all", //opera mobile
                "not ie_mob all",
                "not and_uc all", //ucandroid
                "not and_qq all" //qqandroid
            ]
        })
    ]
};
```

## Output
Module build failed: BrowserslistError: Unknown browser query `op_mob all`
Module build failed: BrowserslistError: Unknown browser query `ie_mob all`
Module build failed: BrowserslistError: Unknown browser query `and_uc all`
Module build failed: BrowserslistError: Unknown browser query `and_qq all`

**Comment by ai** [comment]
1. Plese, not use `browsers` option. Use `browserslist` config, as we recommend. 
2. You have this issue because of an inconsistency of Can I Use database. Sometimes Can I Use uses `all`, sometimes `0`, sometimes actual version. To fix it use `now last 1 op_mob version`.
3. you don’t need all `not ` queries here.
4. You can always debug your queries on http://browserl.ist/?q=last+1+op_mob+version

/cc @Fyrd
