### ISSUE TITLE
Windows10 System Webstorm Error

### ISSUE THREAD

**Issue by Hadeshjx** [postcss/autoprefixer#862]
![qq 20170713182033](https://user-images.githubusercontent.com/23182119/28162281-1c168f4e-67f9-11e7-9554-ec02933f2c24.png)

**Comment by Hadeshjx** [comment]
![qq 20170713182106](https://user-images.githubusercontent.com/23182119/28162379-63a2f424-67f9-11e7-8508-237bdfd1f40b.png)

**Comment by ai** [comment]
Sorry, you must open issue in [`postcss-cli`](https://github.com/postcss/postcss-cli).
