### ISSUE TITLE
A propos du fichier //build/style.css

### ISSUE THREAD

**Issue by aliouMarto** [postcss/autoprefixer#863]
Bonjour,
Alors je vous écrit à propos de votre article très bien expliqué et détaillé concernant grunt et  autoprefixer :
-Voici ma situation : 
1 - j'ai très bien réussi à installer grunt avec tous ces paramètre (aucun problème)
2 - j'ai respecté toutes les lignes de commandes comme dans votre article
Mais cependant une chose me stop et je ne comprend pas  le fichier Buid/style.css (fichier dans lequel je suis censé retrouvé la compilation de mon code css) j'arrive pas à le trouvé doit je le créé ? ou doit il venir automatiquement dans mon dossier principale ? sachant que j'ai déjà créé le fichier grunfile.js comme vous
Cette étape me fatigue(c'est la première fois que j'utilise grunt mais c'est surtout à cause de l'autoprefixer que je l'utilise pour mes problèmes de compatibilités de navigateurs) J'espère vraiment avoir une explication de votre part pour me permettre d’avancer sur mon projet.

Merci d'avance 
Bien à vous.

**Comment by ai** [comment]
Désolé, je ne connais pas la langue française. Vous pouvez poser votre question ici:

https://french.stackexchange.com/

**Comment by aliouMarto** [comment]
thank you  It's good i solved the problem
