### ISSUE TITLE
What to do in case where only vendor prefix is being used in source?

### ISSUE THREAD

**Issue by jitendravyas** [postcss/autoprefixer#864]
Related 
https://stylelint.io/user-guide/rules/property-no-vendor-prefix/
https://css-tricks.com/almanac/properties/a/appearance/
https://github.com/postcss/autoprefixer/issues/43

I have this in code 

> //Hide type=number arrow buttons
> input::-webkit-outer-spin-button,
> input::-webkit-inner-spin-button {
> 	-webkit-appearance: none;
> 	margin: 0; 
> }
> 
> input[type=number] {
> 	-moz-appearance: textfield;
> }
> 

And stylelint gives this error

` 74:2  ✖  Unexpected vendor-prefix "-webkit-appearance"   property-no-vendor-prefix`

Output on is this https://autoprefixer.github.io/

![monosnap 2017-07-20 13-14-13](https://user-images.githubusercontent.com/77309/28406259-6c9aa7a8-6d4d-11e7-98c8-2d09e229da67.jpg)

My aim was to not to have any vendor prefix in the source files because autoprefixer can do that.

**Comment by ai** [comment]
Use `appearance: none` in both options.

Right now your code works only in webkit and Firefox and it is not future proof code.

As I know, Autoprefixer will insert only `-webit-` in first example.

**Comment by ai** [comment]
Also you can just disable Stylelint in that rule.

**Comment by jitendravyas** [comment]
> Use appearance: none in both options.

Even for -moz-appearance: textfield;?

> As I know, Autoprefixer will insert only -webkit- in the first example.

It adds `-webkit` in 2nd example too as you see in screenshot


Are you suggesting this?

```
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
appearance: none;
margin: 0;
}
```

```
input[type=number] {
appearance: textfield;
}
```

yes I can just disable Stylelint in that rule though I would prefer to not to do this if I can fix this without breaking anything.

**Comment by ai** [comment]
Oops. Nope, only `none` is in standard.

**Comment by jitendravyas** [comment]
Do you mean that I should not rely on Autoprefixer for `appearance: textfield;` ?

**Comment by ai** [comment]
Nope. Autoprefixer supports only `appearance: none`

**Comment by jitendravyas** [comment]
But I get this output in Autoprefixer, just wonder how this is happening?

Input
```
input[type=number] {
appearance: textfield;
}
```
Output
```
input[type=number] {
-webkit-appearance: textfield;
   -moz-appearance: textfield;
        appearance: textfield;
}
```

**Comment by ai** [comment]
Oops, seems like I forgot about it :D.
