### ISSUE TITLE
Path must be a string,  Any idea why am I getting this error?

### ISSUE THREAD

**Issue by jitendravyas** [postcss/autoprefixer#868]
![monosnap 2017-07-23 15-32-39](https://user-images.githubusercontent.com/77309/28522338-3921f1e2-7095-11e7-9e4b-9876d311f3b1.jpg)

**Comment by retrixe** [comment]
This was a resolved issue with `browerslist` used by `autoprefixer`. `autoprefixer` has updated `browserslist` but has not released a new release. Try `npm i browserslist@2.2.0`

**Comment by jitendravyas** [comment]
But I don't have `browserslist` in my package.json

**Comment by retrixe** [comment]
`autoprefixer` depends on `browserslist` which is throwing this error.

**Comment by jitendravyas** [comment]
But should this be fixed if I update Autoprefixer?

**Comment by retrixe** [comment]
the latest version of autoprefixer doesn't use the patched version (yet).

**Comment by ai** [comment]
@jitendravyas 

1. Always put full stacktrace in issue report.
2. Update your Browserslist.

**Comment by jitendravyas** [comment]
@ai How to get full stacktrace ?

**Comment by retrixe** [comment]
@jitendravyas install it via the command I said. It'll override `autoprefixer`'s dependency.
