### ISSUE TITLE
Visual Studio 2017 doesn't appear to support SCSS autoprefixer

### ISSUE THREAD

**Issue by gordonhbarlow** [postcss/autoprefixer#869]
Visual Studio 2017 doesn't appear to support SCSS autoprefixer

**Comment by ai** [comment]
We officially don’t recommend to run Autoprefixer from IDE/text editors: https://github.com/postcss/autoprefixer#text-editors-and-ide

Use webpack, gulp or postcss-cli.

**Comment by ai** [comment]
Visual Studio 2017 is *not* an open source project. I can’t send PR to them. So you must open issue in Visual Studio issue tracker and ask them to fix the code.
