### ISSUE TITLE
Enable Grid prefixes by default?

### ISSUE THREAD

**Issue by raphaelgoetter** [postcss/autoprefixer#870]
Hello,

Now that grid layout is usable in production, can we reconsider this question? (issue : https://github.com/postcss/autoprefixer/issues/817 )

Would be very useful for those who don't want to use mixins fot that job.

**Comment by ai** [comment]
Twitter has been voted. Found more than 10 people, who want to enable it and I will start voting again.

**Comment by raphaelgoetter** [comment]
14 for now :)

**Comment by ai** [comment]
https://twitter.com/autoprefixer/status/896092076697190400

**Comment by raphaelgoetter** [comment]
OK, Vox Populi :)

**Comment by ShaggyDude** [comment]
+11

**Comment by ShaggyDude** [comment]
@Dan503  What restrictions exactly? autoprefixer can deal with gaps and the 'ascii' syntax now? I am using it for IE11 and there are no real restrictions anymore afaik.

**Comment by ai** [comment]
@ShaggyDude 

> autoprefixer can deal with gaps and the 'ascii' syntax now?

It can

> there are no real restrictions anymore afaik.

But 'ascii' syntax will work only for the most popular cases. There are edge cases, when it will not work as expected.

Here is some examples: https://css-tricks.com/css-grid-in-ie-css-grid-and-the-new-autoprefixer/

**Comment by ShaggyDude** [comment]
Ok cool. I was going down the route of writing out everything by hand and not using gaps so those restrictions are cool w me but, yeah I now kinda see the point of not promising magic for those who don't know the limits.  Thanks,

**Comment by Dan503** [comment]
> There are edge cases, when it will not work as expected.

I wouldn't call them "edge cases". Not being able to use autoplacement is a major fundamental flaw in the IE implementation that requires a significant shift in how people think about how they write CSS Grid code. It also locks you out from using some of CSS Grid's coolest features like `grid-auto-flow: dense` and `grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));`.

**Comment by ShaggyDude** [comment]
True but I think you can cut IE11 some slack seeing it implemented the spec as it was at the time. I prefer to use what works now rather than wait another 10 years but yes, I do now see why turning it on by default would give many a false hope of everything working. I've been doing front end work for decades and I am surprised that any of the new stuff is working. lol
