### ISSUE TITLE
Please add npx example❓

### ISSUE THREAD

**Issue by retyui** [postcss/autoprefixer#871]
I think it's a good idea to show that you can not install dependencies to run autoprefixer!?
https://github.com/postcss/autoprefixer#cli

**Comment by ai** [comment]
Agree. I have global install. Do you want to send PR to save your name in history?

**Comment by retyui** [comment]
Sure)

**Comment by retyui** [comment]
@ai Why are you remove "npx onse install" exmaple in CLI?

**Comment by ai** [comment]
Because install need to be done only once and you don't need to do this check again and again

Or what was your reason to add it?

**Comment by retyui** [comment]
Пример с одноразовой командой тоже не плох!

Когда , мы можем по быстрому выполнить префсирование\линтинг\форматирование нашего css
И при выполнении команды у нас всегда свежие `autoprefixer|stylefrm|stylelint`

Когда сервер клиента , навали ему нужна папка с этими dev пакетами!

**Comment by ai** [comment]
Это не главные сценарии. Мы форсим добавлять Автопрефиксер в систему сборки, а не запускать руками иногда.

**Comment by retyui** [comment]
@ai А как альтернативный не форсит?

**Comment by ai** [comment]
А зачем? Кому надо сами добавят опции
