### ISSUE TITLE
Please Update flexbox prefixes

### ISSUE THREAD

**Issue by agilBAKA** [postcss/autoprefixer#874]
[https://css-tricks.com/forums/topic/flexbox-prefixes/](https://css-tricks.com/forums/topic/flexbox-prefixes/)

**Comment by ai** [comment]
@agilBAKA Autopfrexer generates prefixes according to you default browsers. If you see some unnecessary for you prefixes, just check your `.browserslistrc` config and set there browsers that you really need.

Here is a doc about config for browsers: https://github.com/ai/browserslist
Here is debug tool for Browserslist queries: http://browserl.ist/
