### ISSUE TITLE
Question: radial-gradient

### ISSUE THREAD

**Issue by lsbyerley** [postcss/autoprefixer#877]
This has been posted before, but I'm still unsure why this doesn't prefixed. Without browser prefixes it doesn't work in the latest chrome, firefox, or safari

`radial-gradient(center top, ellipse cover, #cc0010 0%, #092462 100%);`

Is there a syntax error I'm missing?

**Comment by ai** [comment]
Because you use wrong direction syntax Only old prefixed versions used this direction syntax. Youuse old manuals for gradaients.

Autoprefixer writes a warning about this case. Make sure that see this warning. How did you run Autoprefixer on your CSS?

**Comment by lsbyerley** [comment]
I don't see a warning.. the autoprefixing happens at this line in my gulpfile

`.pipe(autoprefixer({ browsers: ['ie >= 8', 'last 2 versions', '> 1%'], map: false }))`

**Comment by ai** [comment]
Do you use non-official `gulp-autoprefixer` and not official `gulp-postcss` with `autoprefixer` as we recommend in our docs? ;)

**Comment by ai** [comment]
Oops, seems like we forget to add warnings for radial gradint

**Comment by lsbyerley** [comment]
I am using `gulp-autoprefixer` but i will look into changing that over to the recommended plugin

**Comment by ai** [comment]
Done https://github.com/postcss/autoprefixer/commit/d270841acb16c7897a60a9b929500dddb4bace8c

Next version will have warning

**Comment by ai** [comment]
Released in 6.1.3.
