### ISSUE TITLE
Custom code as a value and CssSyntaxError

### ISSUE THREAD

**Issue by AdamWojda** [postcss/autoprefixer#879]
I'm creating scss code for IPS Forums System, it looks like this:

```
$header_color: unquote("{{theme='adblock_header_color'}}");


.cAdBlock {
    $root: &;

    /*! autoprefixer: off */
    &__header {
        /*! autoprefixer: off */ 
        color: $header_color;
    }

}
```

I want to use custom variables from their Theme API, is there any way I can skip lines like this so autoprefixer won't throw error like this? 

```
CssSyntaxError in plugin 'gulp-autoprefixer'
Message:
    C:\***\style.css:1:352: Unknown word
```

I thought the autoprefixer off comment will do the job, but the error still occurs.

**Comment by ai** [comment]
1. Don't use gulp-autoprefixer, use gulp-postcss.
2. Add gulp-postcss after Sass compiling step.
3. If you really need add prefixes to Sass sources (for example, to distribute theme) use postcss-scss in `syntax` option to change PostCSS parser and stringifier.
