### ISSUE TITLE
Autoprefixer working for one file but not the other...

### ISSUE THREAD

**Issue by kinkwilde** [postcss/autoprefixer#880]
So I am a bit confused about this.

I am using gulp-autoprefixer which is just a shell that pulls in autoprefixer directly (I have tested this with just autoprefixer as well).

I have 2 tasks in my gulpfile. One comiles the site css and one compiles the admin css. The admin css compiles and gets prefixed just fine, however the site css compiles but doesn't get prefixed. It has nothing to do with the way the gulp process is setup (as far as I'm aware, because why would one work and the other not?), so I am assuming it is to do with autoprefixer some how.

My gulp development can be found at this repository - https://github.com/kinkwilde/personal-gulp-dev

Can anyone help me try to figure out what is wrong?

**Comment by kinkwilde** [comment]
Ah just spotted why...

So at the top of my variables file it has:
/* autoprefixer: off */
/* autoprefixer: on */

I was using this for reference purpose only - I thought adding the on after the off would mean it would still prefix on compile.

The interesting thing here is that my admin css imports the same variable file, so both work off of the one file. When compiling the admin css, it autoprefixes as mentioned but the site css doesn't get prefixed. Removing both the off and on comments and compiling the site css, it gets prefixed as expected.

So I now wonder if there is another bug? With the off and on comments in place why would one file get prefixed and the other file not get prefixed?

**Comment by ai** [comment]
Few notices about tools:

1. Do not use `gulp-autoprefixer`. Use `gulp-postcss` with `autoprefixer. Anyway `gulp-autoprefixer` uses PostCSS inside.
2. If you use PostCSS-based Autoprefixer you should also try PostCSS based Stylelint instead of CSSComb. Stylelint is used by Facebook, GitHub and Wikipedia. And CSSComb doesn’t have any development right now.

**Comment by ai** [comment]
How did you check, that CSS is prefixed? Maybe you look on properties, that doesn’t need prefixes anymore?

I got your repo and `assets/css/panel.css` has prefixed:

```css
.input:focus {
  -webkit-transform: scale(0.1);
      -ms-transform: scale(0.1);
          transform: scale(0.1);
```

**Comment by kinkwilde** [comment]
Yes so panel.css is my admin css, and that gets prefixed. Take a look inside styles.css - you will see that for some reason this is the file that doesn't get prefixed.

I use .csscomb for my atom setup only. It will beautify and sort properties on save in my custom alphabetical order. I don't use .csscomb for any other reason than that. I will take a look at trying to implement gulp-postcss inside my gulp file instead, I am just working from a few examples at the moment.

**Comment by ai** [comment]
@kinkwilde Stylelint could sort and check your errors.

**Comment by ai** [comment]
Yeap. Seems like you have a bug. But I doesn’t know where — seems like it is not Autoprefixer bug, bug Gulp config issue. Try to ask on StackOverflow.

**Comment by kinkwilde** [comment]
So as I say - if I remove the 2 comments mentioned from the top of my variables file ( /* autoprefixer: off / & / autoprefixer: on */ ), then styles.css will get prefixed as expected. But why would panel.css get prefixed and styles.css not get prefixed with those 2 comments being in place? Does that not point to autoprefixer?

I've already posted a question on stackoverflow with regards to whether I had an issue but I only talked about the 2 tasks and not the whole config of it.

**Comment by ai** [comment]
Why do you have this comments `/* autoprefixer: off */`? The best way is to not use them at all (especially because Sass compile variables before they will go to Autoprefixer).

**Comment by kinkwilde** [comment]
I was just using them for refernece so I didn't forget about them in case I needed to use them. But I thought putting on after off would turn it on again. I just find it strange that panel.css gets prefixed, but styles.css doesn't. They run off of the same variables file, panel.css (assets/admin) pulls it in from styles.css (admin/scss).

After this I don't think I will forget about those comments anymore, but I do find it strange that one file gets prefixed and the other one doesn't. So whether you count it as a bug in autoprefixer or not, something isn't right.

**Comment by ai** [comment]
I forgot many things about Sass to help you with understanding :D You can put `console.log()` to Autoprefixer source and find what exactly CSS it gets.
