### ISSUE TITLE
document exactly which CSS Grid properties are supported

### ISSUE THREAD

**Issue by hellochar** [postcss/autoprefixer#882]
Hey autoprefixer,

The README gives indication that autoprefixer handled certain CSS Grid properties, but it's not clear what properties are transformed in what way - could we get more documentation on what the transformation actually is? Google linked me to the table in https://rachelandrew.co.uk/archives/2016/11/26/should-i-try-to-use-the-ie-implementation-of-css-grid-layout/ , is that up to date?

Thanks!

**Comment by ai** [comment]
Sure. Do you want to make PR? I will not have on this week.

**Comment by ai** [comment]
Rachel Andrew article is up to date. But if we will fix #883 it will be outdated.
