### ISSUE TITLE
Intégrer Autoprefixer dans un projet aec Sass

### ISSUE THREAD

**Issue by Dybeweb** [postcss/autoprefixer#884]
Bonjour,
je tente désespérément d'intégrer Autoprefixer sur mon projet ayant déjà Compass et Sass...impossible de trouver la solution.
Il semblerait que c'est possible, mais si c'est le cas, je n'ai pas trouvé la solution...
Pourriez-vous me donner les billes nécessaires ?
Merci
Cordialement,
Rudy

**Comment by ai** [comment]
https://github.com/ai/autoprefixer-rails#compass
