### ISSUE TITLE
 Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by gaoxiaosong1113** [postcss/autoprefixer#885]
I used File Watchers in webstorm to add autoprefixer to suggest an error
![image](https://user-images.githubusercontent.com/16183057/29904392-3288755e-8e3b-11e7-8ff6-23f60ee28565.png)

postcss-cli、autoprefixer version
![image](https://user-images.githubusercontent.com/16183057/29904466-83890aa4-8e3b-11e7-984f-0c509eb6ce61.png)

What is the reason for that?

**Comment by ai** [comment]
You need to send issue to `postcss-cli`. Error went from there.
