### ISSUE TITLE
Not using package.json browserlist

### ISSUE THREAD

**Issue by mcshaman** [postcss/autoprefixer#897]
I am having trouble getting autoprefixer to use my browserlist property in my package.json file.

I have an entry in my package.json file:
```
...
"browserlist": [
    "last 2 Chrome versions"
]
```
and I am running the following from my gulpfile.js
```
...
.pipe(postcss([autoprefixer]))
...
```

When I run my gulp task I get all sorts of prefixes including `-ms-`.

If I modify my gulpfile.js to:
```
...
.pipe(postcss([autoprefixer({browsers: ['last 2 Chrome versions']})]))
...
```
autoprefixer compiles as expected.

Am I doing something wrong here?

**Comment by ai** [comment]
Show Autoprefixer version and full Gulpfile.

**Comment by mcshaman** [comment]
Sorry can kill this one... While organising I realised the property is meant to be `"browserslist"` not `"browserlist"`. I reckon this would trip a few people up... Well thats what I will tell myself.

**Comment by ai** [comment]
Don't worry. Your issue showed that we need warning for this typo in Browserslist 😉

I will add warning on this week.

**Comment by ai** [comment]
Done https://github.com/ai/browserslist/commit/7c5f3e1ca05ceb65c31a25a2da8b6b873a1c36e8
