### ISSUE TITLE
autoprefixer: off not working for ::placeholder rule

### ISSUE THREAD

**Issue by mcshaman** [postcss/autoprefixer#898]
The `/* autoprefixer: off */` option does not appear to be working for my `::placeholder` rules

in my stylesheet I have the following:

```
/* autoprefixer: off */
input::placeholder {
	background: white
}
/* autoprefixer: on */
```

and autoprefixer outputs the following:

```
input::-webkit-input-placeholder {
  background: #ffffff;
}
input:-ms-input-placeholder {
  background: #ffffff;
}
input::placeholder {
  background: #ffffff;
}
``` 

How do I disable autoprefixer for my `::placeholder` rules. I need write a very different set of rules for `-ms-` because of they way IE implements them.

**Comment by ai** [comment]
I will look on this weekend.

Fast fix is just write `input:-ms-input-placeholder` after placeholder.

**Comment by mcshaman** [comment]
Thanks I will give that one a go for now

**Comment by ai** [comment]
*Short answer:* you need to write:

```css
:-ms-input-placeholder {
	background: red
}
::placeholder {
	background: white
}
```

**Comment by ai** [comment]
**Long answer:** Autoprefuxer doesn’t read CSS step by step. it looks in entire AST. When Autoprefixer sees `::placeholder`, Autoprefixer goes to the parent and see `/* autoprefixer: off *//* autoprefixer: on */` (disabling and that enabling.

But there is a better way to write `-ms-` rules. Autoprefixer always check did you write some custom CSS for prefix.

**Comment by mcshaman** [comment]
Thanks @ai
