### ISSUE TITLE
flexbox and align-self

### ISSUE THREAD

**Issue by amerllica** [postcss/autoprefixer#900]
I got to a weird issue.

 Because of using `align-self`, PostCSS went error.

 I found similar issue by [this link](https://github.com/postcss/autoprefixer/issues/730) but the issue was settled in version 6.5.1, I use version 7.1.2  but I have this problem now.

My solution is downgrade to version 6.5.x and the problem solved, But why an issue was settled in earlier version and it's seeing in latest version?

I write : 

    .test {
        align-self: center;
    }

and I got this error:

    RangeError: Invalid array length
        at AlignSelf.calcBefore 
    (C:\Users\a.lotfi\WebstormProjects\digikalamag\node_modules\autoprefixer\lib\declaration.js:146:19)
         at AlignSelf.insert 
    (C:\Users\a.lotfi\WebstormProjects\digikalamag\node_modules\autoprefixer\lib\declaration.js:189:39)
        at AlignSelf.add 
    (C:\Users\a.lotfi\WebstormProjects\digikalamag\node_modules\autoprefixer\lib\declaration.js:221:21)
        at AlignSelf.process         
    (C:\Users\a.lotfi\WebstormProjects\digikalamag\node_modules\autoprefixer\lib\prefixer.js:170:22)
        at AlignSelf.process     
    (C:\Users\a.lotfi\WebstormProjects\digikalamag\node_modules\autoprefixer\lib\declaration.js:231:56)
        at C:\Users\a.lotfi\WebstormProjects\digikalamag\node_modules\autoprefixer\lib\processor.js:117:34
        at C:\Users\a.lotfi\WebstormProjects\digikalamag\node_modules\postcss\lib\container.es6:151:28
        at C:\Users\a.lotfi\WebstormProjects\digikalamag\node_modules\postcss\lib\container.es6:109:26
        at Rule.each (C:\Users\a.lotfi\WebstormProjects\digikalamag\node_modules\postcss\lib\container.es6:77:22)
        at Rule.walk (C:\Users\a.lotfi\WebstormProjects\digikalamag\node_modules\postcss\lib\container.es6:108:21)

**Comment by ai** [comment]
Can you create simple project to reproduce problem?

I can’t reproduce problem with this CSS input. Maybe you use other PostCSS plugins and they generate broken AST?

**Comment by ai** [comment]
Also, do you update PostCSS and `gulp-postcss` version?

**Comment by amerllica** [comment]
gulp config:

    gulp.task('postcss', ['postcss:lint'], () => {
      gulp.src('./src/*.pcss')
        .pipe(sourcemaps.init())
        .pipe(postcss([
          postcssPartialImport({
            prefix: "_",
            extension: ".pcss",
            glob: false,
            path: ['./src']
          }),
          postcssNestedAncestors(),
          postcssApply(),
          customProperties(),
          postcssNext({
            features: {
              nesting: false
            },
            warnForDuplicates: false
          }),
          postcssNested(),
          postcssExtend(),
          cssMqpacker({
            sort: true
          }),
          autoprefixer({browsers: ['last 5 versions']}),
          cssnano()
        ]))
        .pipe(rename({
          extname: ".css"
        }))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('./dist/assets/css'))
        .pipe(browserSync.stream());
    
    });

package.json: 

    "devDependencies": {
        "autoprefixer": "^6.5.x",
        "babel-cli": "^6.26.0",
        "babel-preset-env": "^1.6.0",
        "browser-sync": "^2.18.13",
        "css-mqpacker": "^6.0.1",
        "cssnano": "^3.10.0",
        "gulp": "^3.9.1",
        "gulp-postcss": "^7.0.0",
        "gulp-rename": "^1.2.2",
        "gulp-sourcemaps": "^2.6.1",
        "gulp-util": "^3.0.8",
        "postcss-apply": "^0.8.0",
        "postcss-cssnext": "^3.0.2",
        "postcss-custom-media": "^6.0.0",
        "postcss-custom-properties": "^6.1.0",
        "postcss-extend": "^1.0.5",
        "postcss-functions": "^3.0.0",
        "postcss-import": "^10.0.0",
        "postcss-mixins": "^6.1.0",
        "postcss-nested": "^2.1.2",
        "postcss-nested-ancestors": "^1.0.0",
        "postcss-partial-import": "^4.1.0",
        "postcss-reporter": "^5.0.0",
        "precss": "^2.0.0",
        "stylelint": "^8.0.0",
        "stylelint-config-standard": "^17.0.0",
        "stylelint-selector-bem-pattern": "^1.1.1"
      }

**Comment by ai** [comment]
Can you disable other PostCSS plugins?

**Comment by amerllica** [comment]
Wow, What a hard test, If I'll do this I fall in many errors and I lost all of my time, Thanks, I use earlier version.

**Comment by amerllica** [comment]
@ai , Hi dear
If you wanna see your autoprefixer issue, I can grand you an access to my GitLab project to see and settle issue.

**Comment by ai** [comment]
Full project is too big. It is better to create smaller project and try to remove all unrelated to issue code.

**Comment by amerllica** [comment]
Dear @ai , My project is in first step, so it is not very big, you just install `npm` modules and see `/src/home/partial/_user-pane.pcss` line `134`. I use `align-self: center`. But aware my `autoprefixer` is version `6.5.4`. Update it and `gulp postcss`. then see the error.

If you OK with this tell me I grant the access.

**Comment by ai** [comment]
Why you use old Autoprefixer? It could be the source of this error.

**Comment by amerllica** [comment]
Dear @ai , at first time I used version `7.x.x` but using this version cause to error, I downgrade it to version `6.5.4` and settled issue, if you wanna why newer version cause to error or which plugins conflict with the latest version of `autoprefixer` I can grant you an access to see my project on GitLab. If you are OK with this tell me and send for me your GitLab account.

**Comment by ai** [comment]
Can you disable plugin by plugin to detect what plugin before Autoprefixer brakes AST?

I don't have time in this week to debug code.

**Comment by amerllica** [comment]
Dear @ai , I don't have too much time too, I downgrade to version `6.5.4` and build without issue. next week work on it, I said the offer just for your plugin not my task issue. thanks bro.

**Comment by visormatt** [comment]
@amerllica and @ai Curious why this issue was closed out? I am running into the same issue ATM and it does not occur on `6.5.4`

**Comment by ai** [comment]
@visormatt report full stacktrace, `npm ls` nd CSS input

**Comment by visormatt** [comment]
I looks like this might be from not including the browser configuration in the `css-next` -> `postcss` build chain. The solution below works for use on `7.1.4` @amerllica might be useful in your debugging.

**Shared:**
```
const browsers = [
  'last 3 Android versions'
  // ...more config
];
```

**Before:**
```
const cssPlugins = [
   cssImport(),
   cssNext({ warnForDuplicates: false }),
   cssVariables(),
   customProps(),
   autoprefixer({ browsers })
];
```

**After:**
```
const cssPlugins = [
   cssImport(),
   cssNext({ warnForDuplicates: false, browsers }),
   cssVariables(),
   customProps()
 ];
```
