### ISSUE TITLE
Support for `:matches()`

### ISSUE THREAD

**Issue by grayghostvisuals** [postcss/autoprefixer#902]
Current support only shows in Safari and Firefox and Chrome maintain an older syntax. I think it's safe to assume `:matches()` will eventually be adopted widely by browser vendors.

```scss
// Firefox Stable
:-moz-any(a) {
  color: blue;
}

// Chrome Stable
:-webkit-any(a) {
  color: blue;
}

// Safari Stable
:matches(a) {
  color: blue;
}
```

**Comment by ai** [comment]
Thanks for issue.

We need to add data to Can I Use. Can you help me a find what versions exactly need it?

Does latest versions need prefixes?

**Comment by grayghostvisuals** [comment]
What I listed is the current state for "stable" browser releases at the present time

**Comment by yisibl** [comment]
These two aren't exactly equal, so there's a lot of risk for Autoprefixer.

**Comment by ai** [comment]
> These two aren't exactly equal, so there's a lot of risk for Autoprefixer.

Thanks! Any link with differences?

**Comment by grayghostvisuals** [comment]
@ai As far as stable browsers are concerned the only differences is the syntax I posted above.

**Comment by ai** [comment]
Yeap, there is some (still unknown) difference between `:matches()` and `-webkit-any()`

> Make sure to carefully test your pages when replacing :-webkit-any() by :matches() as they are not strictly equivalent. In particular, :-webkit-any() does not handle the specificity correctly.

— https://webkit.org/blog/3615/css-selectors-inside-selectors-discover-matches-not-and-nth-child/

**Comment by ai** [comment]
Same with `-moz-any()`, it changes specificity of the selector:

> Shortly I'm going to land bug 544834, which implements the :-moz-any() selector.  This patch, however, doesn't handle specificity properly; it just treats :-moz-any() as having the specificity of a pseudo-class.

— https://bugzilla.mozilla.org/show_bug.cgi?id=561154

**Comment by ai** [comment]
Since `:matches()` !== `-webkit-any()`/`-moz-any()` and we could not fix changes in Autoprefixer, we can’t add this feature.

@grayghostvisuals but with the power of PostCSS you can do it in PostCSS plugins. It will be something like:

```js
module.exports = postcss.plugin('postcss-matches', () => {
  return root => {
    root.walkRules(rule => {
      if (rule.selector.indexOf(':matches(') !== -1) {
        rule.selectors = rule.selectors.reduce((all, i) => {
          if (i.indexOf(':matches(') !== -1) {
            return all.concat([
              i,
              i.replace(/:matches\(/gi, '-webkit-any('),
              i.replace(/:matches\(/gi, '-moz-any(')
            ])
          } else {
            return all.concat([i])
          }
        }, [])
      }
    })
  }
})
```

Ping me when you implement it, I will add link to Autoprefixer `README.md`.

**Comment by yisibl** [comment]
@ai Sorry to reply you so late.

For example, ':any' does not support nesting.

* `:matches(:matches(h1, h2), h3)` 👍 
* `:-webkit-any(:-webkit-any(h1, h2), h3)` 👎

**Comment by ai** [comment]
@yisibl ouh, so there are even 2 differences: wrong selector specificity and nesting :(

**Comment by simevidas** [comment]
Just for completeness sake, there is another difference: `:-webkit-any` doesn’t support complex selectors.

* `:-webkit-any(p span)` ❌
* `:is(p span)` ✅

**Comment by tedw** [comment]
So I suppose using a Sass/Less mixin is the best way to go until all browsers support `:is()`, since there’s no way for Autoprefixer to safely convert it?

- https://caniuse.com/css-matches-pseudo
- https://developer.mozilla.org/en-US/docs/Web/CSS/:is

**Comment by simevidas** [comment]
@tedw If a CSS preprocessor is already used, then nesting may be preferable. It seems to me that `:is()`  is mainly useful in standard, unprocessed CSS code.

**Comment by tedw** [comment]
@simevidas Thanks for the quick reply! Here’s my use case for reference:

```css
:is(h1, h2, h3, h4, h5, h6) + :is(h1, h2, h3, h4, h5, h6) {
  margin-top: 0;
}
```

I was hoping to avoid generating every heading combination (especially because in my case there’s a parent class), but you‘re probably right that nesting is the best solution for now:

```scss
h1, h2, h3, h4, h5, h6 {
  & + h1,
  & + h2,
  & + h3,
  & + h4,
  & + h5,
  & + h6 {
    margin-top: 0;
  }
}
```

Although it make me feel good to do this in a single line of CSS, I realize the extra bytes of CSS are negligible after gzipping 😄.

P.S. Thanks for all the work you do for the web dev community! Been following you on Twitter and reading your blog posts for a long time.

**Comment by simevidas** [comment]
Btw, I just noticed that this selector generates some invalid combinations, such as `h3 + h1` and `h2 + h2`, where the first heading isn’t a higher level than the second heading. In fact, only 15 out of 36 combinations are valid in that sense. But I guess CSS performance is no longer a big issue, so it’s probably fine.

**Comment by tedw** [comment]
@simevidas Oh, good call! In my case, H1s are automatically stepped down to H2, so I think this would be the shortest selector for all accessible heading combinations:

```css
h2 + h2,
h2 + h3,
h3 + h3,
h3 + h4,
h4 + h4,
h4 + h5,
h5 + h5,
h5 + h6,
h6 + h6 {
  margin-top: 0;
}
```

Consecutive headings are already a bit of an edge case, and I’m fine with invalid combinations not getting the correct styling, so this is perfect.

Sorry for getting off topic here, but thanks for the reply!
