### ISSUE TITLE
`background-clip` doesn't work. 

### ISSUE THREAD

**Issue by wzup** [postcss/autoprefixer#903]
`background-clip` doesn't work. 

![background-clip - google chrome 2017-09-09 20 24 59](https://user-images.githubusercontent.com/3880497/30240117-272ed608-959d-11e7-9545-c11e64f593eb.png)

Don't know whose issue this is, `autoprefixer`'s or `postcss`. I write it here because I found same issue from 2013 https://github.com/postcss/autoprefixer/issues/156

**Comment by ai** [comment]
We never supported it. So PostCSS or Autoprefixer didn't change but anything here.
