### ISSUE TITLE
[FEATURE REQUEST] warn about unsupported css

### ISSUE THREAD

**Issue by kaynz** [postcss/autoprefixer#904]
Hi,
it would be cool if the autoprefixer warns when unsupported css tags are used, e.g.

browsers: safari
css: animation: 400ms blend reverse forwards;

reverse is [not supported by safari](https://developer.mozilla.org/de/docs/Web/CSS/animation-direction).

Is this possible? :)

**Comment by ai** [comment]
Autoprefixer is tools only for prefixes. But there is a great tools for this feature: [doiuse](https://github.com/anandthakker/doiuse). It even based on same CSS parser as Autoprefixer (PostCSS).

**Comment by kaynz** [comment]
doiuse doesnt work for me =/ And it looks like being no more maintained.

**Comment by ai** [comment]
Nope, we found new maintainer and he is good. Just create issue.
