### ISSUE TITLE
calc with sub calculations is destroying entire stylesheet.

### ISSUE THREAD

**Issue by jonascarlbaum** [postcss/autoprefixer#907]
`foo: calc(xxx - (yyy + zzz));` is rewritten to `foo: calc(xxx - (yyy + zzz);`.

### More specific:
`    flex: calc(50% - (8.33333% + 15px));`

is rewritten to:
```
flex-grow: 0;
flex-shrink: 0;
flex-basis: calc(50% - (8.33333% + 15px);
```
**At least in Chrome this results in wrapping in the remainder of the stylesheet into the flex-basis expression.** This is kind of problematic...

Guess you have to ensure that the old bug #403 is still fixed after fixing this one!? ;)

**Comment by ai** [comment]
I tested it in http://autoprefixer.github.io/ and Autoprefixer didn’t change `calc` brackets. Are you sure that it is Autoprefixer?

**Comment by jonascarlbaum** [comment]
I'll try again on monday. But I did comment out both autoprefixer and postcss-flexbugs-fixes, and also tried one at a time. I experienced that both did the same thing. At least when using it on "flex". I did use 3-4 postcss plugins

**Comment by jonascarlbaum** [comment]
...but commenting out both mentioned made the brackets not being tampered, however I want the prefixes... 😉

**Comment by ai** [comment]
I know the better test. Comment all other plugins and left only Autoprefixer uncommented.

**Comment by jonascarlbaum** [comment]
I'll do that, and maybe post my gulp-file, for further reference...
