### ISSUE TITLE
unsupport linear-gradient with degree for prefixer

### ISSUE THREAD

**Issue by AtrisMio** [postcss/autoprefixer#910]
input
```
background-image: linear-gradient( 77deg, #3F66E0 0%, #4985D7 100%);
```

output
```
background-image: linear-gradient( 77deg, #3F66E0 0%, #4985D7 100%);
```

browserslist
```
  "browserslist": [
    ">1%",
    "last 10 versions",
    "Firefox ESR",
    "Firefox >= 20",
    "iOS >= 6",
    "Android >= 4",
    "not ie <= 8"
  ],
```
Is here something wrong? I cannot get linear-gradient with prefix like -webkit-, -moz-, -o-

**Comment by ai** [comment]
Everything is correct on [autoprefixer.github.io](http://autoprefixer.github.io/). Seems like you have some other tool in build process, which removes prefixes after Autoprefixer.
