### ISSUE TITLE
Config from package.json doesn't get picked up

### ISSUE THREAD

**Issue by realityking** [postcss/autoprefixer#911]
It's very possible I'm just dense but I suspect there's a bug either in autoprefixer or browserslist. I'm using autoprefixer 7.1.4, postcss 6.0.11 and browserslist 2.4.0

I'm using the following bit of code
```javascript
const autoprefixer = require('autoprefixer');
const postcss = require('postcss');

return postcss([autoprefixer]).process(css)
  .then(result => {
    process.exit();
    result.warnings().forEach(function (warn) {
      ctx.log(warn.toString());
    });

    console.log(result.css);
  });
```

My package.json contains this configuration
```json
{
  "browserslist": [
    "last 2 chrome versions",
    "last 2 firefox versions",
    "last 2 edge versions",
    "last 2 opera versions",
    "last 2 safari versions",
    "ie 11"
  ]
}
```

But the resulting CSS is obviously processed with the default configuration.

Digging into the code, I noticed that `opts.path` is undefined in [line 193 of browser lists' index.js](https://github.com/ai/browserslist/blob/cb9abd4ae061a256157ff93c1bd7dc64a6997a2e/index.js#L193). Note that the property exists on the object, it just has no value. That's why the check on [line 179](https://github.com/ai/browserslist/blob/cb9abd4ae061a256157ff93c1bd7dc64a6997a2e/index.js#L179-L181) fails.

That seems to happen because of this piece of code in autoprefixer.

https://github.com/postcss/autoprefixer/blob/c6eb543248bf6ef6d9b4160689c39c62130f3d45/lib/browsers.js#L51-L55

My instinct would be to change the check in browserslist from hasOwnProperty to simply check for undefined. Happy to make a PR but I'm not sure if I'm overlooking something it should be fixed on the autoprefixer side of thing.

WDYT?

**Comment by ai** [comment]
You must pass `from` option to `PostCSS#process` method. Browserslist will use this option to detect file position.

```js
return postcss([autoprefixer]).process(css, { from: path.join(__dirname, 'app.css') })
```

**Comment by realityking** [comment]
Thanks for the quick response. I'm not sure I understand how the position of the file relates to the `package.json`.  Could you elaborate? In this case I don't even have a source file as such as we're reading multiple files and generating some rules in code.

**Comment by ai** [comment]
Browserslist need to know current path to look for configs. Using `process.cwd` by default force people to forget to set correct position.

Browserslist configs could be nested. For example `app/legacy` may contain different config. This is why setting correct path is very important.

Also missed `from` could broke source maps.

If you don't have CSS file, use JS file path `from: __filename`.

**Comment by realityking** [comment]
Thanks for the explanation 🙇

**Comment by jon-wong-sutd** [comment]
I set both `from` and `to`. Still no effect. I have key `browserslist`:

    "browerslist": [
      "last 20 versions"
    ]

Yeah, 20, just to be sure.

The JS code to invoke:

    postcss([ autoprefixer ]).process(
      orig.css, { from: options.src, to: options.dest }
    )

I am resisting opening a new issue for this. Can u help me find any errors on my part?
