### ISSUE TITLE
Placeholder pseudo element on Edge

### ISSUE THREAD

**Issue by plesiecki** [postcss/autoprefixer#913]
Hello,

Today autoprefixer adds `:-ms-input-placeholder` for Edge browser. Unfortunately Edge doesn't support this rule :disappointed: 

But on the other hand Edge supports `::-ms-input-placeholder` (double colon) or `::-webkit-input-placeholder`

Reference:
http://caniuse.com/#feat=css-placeholder

Peace

**Comment by ai** [comment]
Thanks. I will try to fix Autoprefixer on this weekend (will add `::-ms-input-placeholder`)

**Comment by ai** [comment]
Done fe790bd (sorry for the delay).

**Comment by ai** [comment]
Released in 7.1.5.

**Comment by plesiecki** [comment]
You're doing magnificent work. Don't let up
