### ISSUE TITLE
.sass?

### ISSUE THREAD

**Issue by Zerefdev** [postcss/autoprefixer#914]
Hello,

I'm having an issue using autoprefixer on .sass files

`gulp.task('autoprefixer', function (){
    return gulp.src('assets/sass/style.sass')
    .pipe(autoprefixer({
        browsers: ['last 2 versions'],
        cascade: false
    }))
    .pipe(gulp.dest('./'))
});`

It says Missing semicolon

`events.js:160
      throw er; // Unhandled 'error' event
      ^
CssSyntaxError: D:\Dev\zerefdev\test\assets\sass\style.sass:1:9: Missed semicolon
You tried to parse Sass with the standard CSS parser; try again with the postcss-sass parser> 1 | $color: #2980b9
    |         ^
  2 | $bxsize: 200px
  3 | $wcolor: #fff`

I don't wanna install the postcss-sass but keep using the gulp-autoprefixer
is there any solution to this?

**Comment by ai** [comment]
No. `gulp-autoprefixer` is a non-official way to use Autoprefixer. Check docs, we recommend only `gulp-postcss`. Also, not that `gulp-autoprefixer` contains same PostCSS (Autoprefixer can’t be executed without PostCSS).

Also `postcss-sass` is not really stable. There is no 100% sure way to compile Sass sources. Please, run Sass compiler before using Autoprefixer.

**Comment by Zerefdev** [comment]
Thanks for the explanation
