### ISSUE TITLE
-webkit-flex-wrap: wrap is missing

### ISSUE THREAD

**Issue by weilinzung** [postcss/autoprefixer#917]
on latest version or 3.1.1 of `gulp-autoprefixer` & `bootstrap 4 beta` is missing `-webkit-flex-wrap: wrap` after compiled.

Also `display: -webkit-box;` is not correct, should be `display: -webkit-flex;`.

I tested on all IOS devices.
thanks!

**Comment by ai** [comment]
Thanks. Can you show input, output and expected CSD

**Comment by weilinzung** [comment]
`.row {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    margin-right: -15px;
    margin-left: -15px;
}`

**Comment by ai** [comment]
Thanks. But to understand the issue I need 3 code examples. Input CSS. Current output CSS. And expected output CSS.

Ouh, and I need your Browserslist config (what is your target browsers for Autoprefixer).

**Comment by weilinzung** [comment]
**Input CSS:** bootstrap 4 beta - `_grid.scss`, `.row` is default from it.

Output CSS: 
```
.row {
 display: -webkit-box;
 display: -ms-flexbox;
 display: flex;
 -ms-flex-wrap: wrap;
 flex-wrap: wrap;
 margin-right: -15px;
 margin-left: -15px;
}
```

**Expected output CSS should be:**
```
.row {
 display: -webkit-flex;
 display: -ms-flexbox;
 display: flex;
 -webkit-flex-wrap: wrap;
 -ms-flex-wrap: wrap;
 flex-wrap: wrap;
 margin-right: -15px;
 margin-left: -15px
}
```

**Browserlist:**
```
      browsers: [
        'last 4 versions',
        'iOS 7',
        'ie 10',
        'android 4',
        'opera 12'
      ]

```

**Comment by ai** [comment]
I tested same input and browsers in [online demo](http://autoprefixer.github.io/) and I got correct result:

```css
.row {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-flex-wrap: wrap;
      -ms-flex-wrap: wrap;
          flex-wrap: wrap;
```

Seems like you have problem in environment, somebody cut prefixes after Autoprefixer.

Try to move browser list to [`browserslist`](https://github.com/ai/browserslist) config

**Comment by weilinzung** [comment]
I did the same thing like this: https://github.com/ai/browserslist#environments

also tested with the online demo:

```
.example {
  display: flex;
  flex-wrap: wrap;
  transition: all .5s;
  user-select: none;
  background: linear-gradient(to bottom, white, black);
}
```
which is:
```
.example {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -ms-flex-wrap: wrap;
  flex-wrap: wrap;
}
```

It is still missing ` -webkit-flex-wrap: wrap;` and `display: -webkit-flex;`

thanks!

**Comment by ai** [comment]
@weilinzung did you set browsers in online demo? Your output didn’t have `-webkit-flex-wrap`, since `-webkit-box`-browsers doesn’t support it and we have no `-webkit-flex`-browsers in default browsers list.

**Comment by ai** [comment]
Also, can you move from `gulp-autoprefixer` to `gulp-postcss`. We doesn’t support `gulp-autoprefixer`.

**Comment by weilinzung** [comment]
ok. cool, will do that.
