### ISSUE TITLE
There is mistake in docs about setting supported browsers

### ISSUE THREAD

**Issue by partyzant** [postcss/autoprefixer#922]
I was trying setting support of "last X versions" and nothing worked the same as on https://autoprefixer.github.io/. After some time of debugging I've discovered that name of option should be "browsers" not "browserslist".

**Comment by ai** [comment]
We do not recommend to use `browsers` option. You should use `browserslist` in `package.json`.

I will add warning for this case.

**Comment by ai** [comment]
Fixed 0019958

**Comment by ai** [comment]
Released in 7.1.6.
