### ISSUE TITLE
Autoprefixer still need to add prefix for backface-visibility property for safari 11 and less

### ISSUE THREAD

**Issue by Ricozor** [postcss/autoprefixer#923]
Hi,
For Safari 11 and less `backface-visibility` property still need the prefix :( . 
=> http://caniuse.com/#search=backface-visibility
The comment hasn't been update but it still true for Safari 11.
If you can fix this, it should be great ^^

Regards,
Eric Fressange

PS : And thx for this very good plugin 👍

**Comment by ai** [comment]
Ouh. Sorry, I will be able to find it only after ReactiveConf in the end of October.

As quick solution you can write PostCSS plugin for this case.

**Comment by ai** [comment]
Strange, we have fix for it already https://github.com/postcss/autoprefixer/blob/master/data/prefixes.js#L128

**Comment by ai** [comment]
I checked Autoprefixer on [online demo](http://autoprefixer.github.io) and everything is work.

Maybe you didn’t use Browswerslist config for target browsers?
