### ISSUE TITLE
-ms- prefixes not added for CSS Grid and IE11

### ISSUE THREAD

**Issue by soluml** [postcss/autoprefixer#925]
browserlist in package.json:

```
"browserslist": [
    "> 1%",
    "last 2 versions",
    "ie >= 11"
  ]
```

I'm not getting any of the -ms- prefix properties for any of the grid properties.  I do get them from flexbox so I know Autoprefixer is working.

**Comment by soluml** [comment]
Found #882 and Rachel's article.

**Comment by ai** [comment]
You can enable `-ms-` Grid prefixes by `grid: true` option

**Comment by AyzPat** [comment]
But how can we use it directly in the interactive demo ?? I already have a css and trying to paste in the online interactive demo but the grid option unable to find.. http://autoprefixer.github.io/

**Comment by ai** [comment]
@AyzPat ask interactive demo author to add this option. Sorry, I don’t have access to this demo

**Comment by AyzPat** [comment]
K, but the demo link is in this repo's readme file....

**Comment by evgeny-petukhov** [comment]
@AyzPat Grid support is added https://github.com/autoprefixer/autoprefixer.github.io/issues/27

**Comment by AyzPat** [comment]
@evgeny-petukhov Thanks man will check that out...
