### ISSUE TITLE
Installing autoprefixer without package manager

### ISSUE THREAD

**Issue by mr-bjerre** [postcss/autoprefixer#929]
I work at a company where there are very strict rules about which software to install. Hence I don't have package manager tools like `npm`. 

Is it possible to install `autoprefixer` without?

**Comment by ai** [comment]
Install `npm` on your machine and then put `node_modules` to git, so your `node_modules` will be available on this machine (you don’t need npm to use `node_modules`).

**Comment by mr-bjerre** [comment]
But if the machine can't install `npm`? That is my issue. I guess I'll have to accept...

**Comment by ai** [comment]
You don't need to install npm on every machine. Run `npm install` on one machine and then copy `node_modules`. For example, install at home at bring to work on USB stick.

**Comment by mr-bjerre** [comment]
For some reason that doesn't work. I use it through a flask app using [`webassets`](http://webassets.readthedocs.io/en/latest/builtin_filters.html#webassets.filter.autoprefixer.AutoprefixerFilter).

`'postcss' is not recognized as an internal or external command`

`npm install autoprefixer` works just fine and installs `node_modules`. I use win10.

**Comment by ai** [comment]
I am not sure that this error is related to non-npm environment. You get this error when you have wrong path for PostCSS binary.

Try to find correct option and set it to `node_modules/.bin/postcss` (don't forget to install `npm` first).

But I am not sure that my recommendation is correct for webassets you should all them. Or on StackOverflow.

**Comment by mr-bjerre** [comment]
Ahhh didn't realize the executable were in .bin. Although I now get `Input Error: Did not receive any STDIN` but that may be how `webassets` interacts with `autoprefixer` I suppose.

**Comment by mr-bjerre** [comment]
Wuhuu it works. Thank you for your kind help !

**Comment by mr-bjerre** [comment]
I might have been too fast. I don't get any error. But the following

```
:fullscreen a {
  display: flex; 
}
```

yields

```
:fullscreen a {
  display: flex; }


/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInN0ZGluIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBOztFQUVFO0FBQ0Y7RUFDRSxjQUFjLEVBQUUiLCJmaWxlIjoic3RkaW4iLCJzb3VyY2VzQ29udGVudCI6WyIvKiohXHJcbiogQ3VzdG9tIHNhc3NcclxuKi9cbjpmdWxsc2NyZWVuIGEge1xuICBkaXNwbGF5OiBmbGV4OyB9XG4iXX0= */
```

**Comment by ai** [comment]
Ask in `webassets`. Maybe Autoprefixer was not executed? Maybe webassets config is wrong.

**Comment by mr-bjerre** [comment]
I will. I've just noticed something with my original issue though. `node_modules/.bin/postcss.cmd` have the following content
```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\postcss-cli\bin\postcss" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\postcss-cli\bin\postcss" %*
)
```
Hence the machine has to have `node.exe`, which are only available by installing `Node.js`. So copying `node_modules` isn't sufficient as I see it?

**Comment by ai** [comment]
Yeap. You must have Node.js for it.

How you plan to run JS files without Node.js?

**Comment by mr-bjerre** [comment]
Ah yeh of course. I'm new in this game but now I get it. Sorry for the inconvenience.

**Comment by hmsaini** [comment]
{
  "name": "2-trillo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "node-sass": "^4.9.4"
  },
  "devDependencies": {
    "autoprefixer": "^9.2.0",
    "concat": "^1.0.3",
    "npm-run-all": "^4.1.3",
    "postcss": "^7.0.5"
  },
  "scripts": {
    "watch:sass": "node-sass sass/main.scss css/style.css -w",
 
    "start":"npm-run-all --parallel devserver watch:sass",
    "devserver":"live-server",
    "compile:sass": "node-sass sass/main.scss css/style.comp.css",
    "prefix:css":"postcss --use autoprefixer -b 'last 10 versions' css/style.comp.css -o css/style.prefix.css",
    "compress:css":"node-sass css/style.prefix.css css/style.css --output-style compressed ",
    "build css":"npm-run-all compile:sass prefix:css compress:css"
   
  },
  "author": "Harpreet Saini",
  "license": "ISC"
}

**Comment by hmsaini** [comment]
please help me...i am a window user & each time i got an error...


E:\MyWork\vscode\css\Practice css\css_course2\2-TRILLO>npm run start

> 2-trillo@1.0.0 start E:\MyWork\vscode\css\Practice css\css_course2\2-TRILLO
> npm-run-all --parallel devserver watch:sass


> 2-trillo@1.0.0 watch:sass E:\MyWork\vscode\css\Practice css\css_course2\2-TRILLO
> node-sass sass/main.scss css/style.css -w


> 2-trillo@1.0.0 devserver E:\MyWork\vscode\css\Practice css\css_course2\2-TRILLO
> live-server
'live-server' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2-trillo@1.0.0 devserver: `live-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2-trillo@1.0.0 devserver script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hspre\AppData\Roaming\npm-cache\_logs\2018-10-15T13_52_58_618Z-debug.log
ERROR: "devserver" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2-trillo@1.0.0 start: `npm-run-all --parallel devserver watch:sass`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2-trillo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hspre\AppData\Roaming\npm-cache\_logs\2018-10-15T13_52_58_971Z-debug.log

E:\MyWork\vscode\css\Practice css\css_course2\2-TRILLO>

**Comment by ai** [comment]
Sorry, have no idea
