### ISSUE TITLE
info() not seeing browserlist configuration

### ISSUE THREAD

**Issue by pdokas** [postcss/autoprefixer#931]
This is similar to #838.

When using 7.1.6, the `info()` method on the plugin returns the default list of browsers no matter what your configuration is.

Example usage:

**.browserslistrc** (or `browserslist`, or `package.json`)
```
safari >= 6
```

**gulpfile.js**
```js
var autoprefixer = require('autoprefixer');

var ap = autoprefixer({
	cascade: false,
	add: true,
	remove: false,
	supports: true,
	flexbox: true,
	grid: false
});

console.log(ap.info());
```

Results in this output:

```
Browsers:
  Chrome for Android: 61
  Firefox for Android: 56
  And_qq: 1.2
  UC for Android: 11.4
  Android: 56, 4.4.3-4.4.4
  Baidu: 7.12
  Bb: 10, 7
  Chrome: 62, 61, 60, 49
  Edge: 16, 15
  Firefox: 56, 55, 52
  IE: 11, 10
  IE Mobile: 11, 10
  iOS: 11, 10.3, 10.0-10.2
  Opera Mini: all
  Opera Mobile: 37, 12.1
  Opera: 48, 47
  Safari: 11, 10.1
  Samsung: 5, 4
```

Where the correct output would look like:

```
Browsers:
  Safari: 11, 10.1, 10, 9.1, 9, 8, 7.1, 7, 6.1, 6
```

Looking into the code, I believe the issue is that the [`plugin.info`](https://github.com/postcss/autoprefixer/blob/7.1.6/lib/autoprefixer.js#L95-L97) method’s `opts` var is `undefined` since nothing is passed in ([as per the docs](https://github.com/postcss/autoprefixer#debug)).

I believe the fix is to change [line 96](https://github.com/postcss/autoprefixer/blob/7.1.6/lib/autoprefixer.js#L96) to be:

```js
return require('./info')(loadPrefixes({ from: path.resolve('.') }));
```

I’d be happy to make a PR to this effect, but I wanted to open a discussion first!

**Comment by ai** [comment]
You must provide `from` option

```js
console.log(ap.info({ from: process.cwd() }));
```

But I understand that it is not clear. There are 2 options:

1. Add default value (`process.cwd`) to `from`. But if users will have different configs (like `src/legacy/.browserslistrc`), they will not know how to load it properly.
2. Show warning on missed `from` option.

What do you think?

**Comment by pdokas** [comment]
IMO keeping debug info simple for newcomers would be ideal. So perhaps we could leave the ability to pass a hash into `plugin.info` _but_ if it wasn’t passed then we could supply a default hash of `{ from: process.cwd() }`. How does that sound?

**Comment by ai** [comment]
Sounds good. But it will be a major update, so we will wait for more changes for it. OK?

**Comment by pdokas** [comment]
I won’t press the point beyond this, but IMHO this seems like a “patch” level change since it fixes a bug resulting in incorrect behavior and doesn't introduce any new functionality. If we were _removing_ the `opts` param from `plugin.info` that would seem like a “minor” level change, but since it’s not then existing functionality will remain as-is and only one incorrect behavior will be removed.

But again, I’ll only float that suggestion this one time and if you feel it’s a minor revision, then a minor revision it is!

I’ll get a PR ready!

**Comment by ai** [comment]
@pdokas hm. maybe. I need few days and then I will have free time to think about it.

**Comment by ai** [comment]
Sorry. Grid fix was delayed. Hope to release it on next week.
