### ISSUE TITLE
with postcss-loader, some browser prefixes can not be add

### ISSUE THREAD

**Issue by wwervin72** [postcss/autoprefixer#933]
i use postcss-loader in webpack,  when it's dev env, transform success. this is my webpack config.
`
       {test: /\.scss$/,
            use: [
                {
                    loader: 'style-loader'
                },
                {
                    loader: 'css-loader'
                },
                {
                    loader: 'postcss-loader',
                    options: {
                        plugins: [
                            require('autoprefixer')({browsers: ['last 5 versions']})
                        ]
                    }
                },
                {
                    loader: 'sass-loader'
                }
            ]
        }
`
this is transform result.
![image](https://user-images.githubusercontent.com/17847729/32256015-68645d28-bee7-11e7-8c2a-03557ca822ed.png)

but, in prod env, it doesn't work. this is my prod webpack config.
`
{
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({
            use: [{
                    loader: 'css-loader'
                },
                {
                    loader: 'postcss-loader',
                    options: {
                        plugins: [
                            require('autoprefixer')({
                                browsers: ['last 5 versions']
                            })
                        ]
                    }
                },
                {
                    loader: 'sass-loader'
                }
            ]
        })
    }
`
and the transform result.
![image](https://user-images.githubusercontent.com/17847729/32255975-2630a42a-bee7-11e7-97ee-5a9ddc040e48.png)

how can i do? thanks.

**Comment by ai** [comment]
https://github.com/postcss/autoprefixer#no-prefixes-in-production
