### ISSUE TITLE
Prefix animation-direction only for basic values

### ISSUE THREAD

**Issue by toptalo** [postcss/autoprefixer#934]
Available values for `-o-animation-direction`, `-moz-animation-direction` and `-webkit-animation-direction` is `[ normal | alternate ]#` [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-direction).

But if there are `animation-direction: reverse;` in stylesheet, autoprefixer generates vendor prefixed properties that are obviously do not need

Or I misunderstand MDN compatibility tables

**Comment by ai** [comment]
So `reverse` value was not supported in browsers, which need prefixes.

Good catch. I will fix it on next week.

**Comment by ai** [comment]
Done 9a523b5

**Comment by toptalo** [comment]
Thanks!

**Comment by ai** [comment]
Released in 7.2
