### ISSUE TITLE
break-*/page-break-* props.

### ISSUE THREAD

**Issue by AleshaOleg** [postcss/autoprefixer#935]
I found, that an `autoprefixer` - makes a default `page-` prefix to old Mozilla browsers for `break-*` properties. As example lets take an `break-before` property with `region` value. After adding prefix, it should be something like: `page-break-before: region`. Now take a look to MSD. [break-before](https://developer.mozilla.org/en-US/docs/Web/CSS/break-before) and [page-break-before](https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-before) it's a different properties. And `page-break-before` even no have `region` value. I will test both of this properties deeper (actually i don't know how they works), and will write about the results there later. Would be great, if somebody from Mozilla team will join this issue, and explain how this should be resolved. Thanks!

**Comment by AleshaOleg** [comment]
In W3C (draft)[https://drafts.csswg.org/css-page-3/#conform-testing] marked that `page` properties should be implemented without any prefixes. Main question for me, for example two years before `page-break-before` and `break-before` was same properties or not? Why we need `page` prefix for `break-*`?

**Comment by ai** [comment]
As I understood `page-` worked pretty similar to non-page one. So we use `page-` to emulate non-page one. Maybe you can find the original issue?

**Comment by AleshaOleg** [comment]
Take a look to `Note` section - https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-after. It seems, they really pretty similar. But what about different values?

I tried to find original issue, it ended unsuccessfully.

**Comment by ai** [comment]
I removed `break-*` to `page-break-*` for Firefox since it is not a prefix e1853af
