### ISSUE TITLE
Support for css-variables

### ISSUE THREAD

**Issue by tobiastom** [postcss/autoprefixer#936]
It would be very nice if autoprefixer could handle the minor edge case with [css-variables](https://github.com/w3c/csswg-drafts/pull/1817) where `constant` is supported, but `env` is not.

**Comment by ai** [comment]
Autoprefixer takes care only about prefixes, not polyfills.

You can [write custom PostCSS plugin](https://github.com/postcss/postcss/blob/master/docs/writing-a-plugin.md) to take care of this case (Autoprefixer is PostCSS plugin as well). Then you can submit this plugin to [cssnext plugin pack](https://github.com/MoOx/postcss-cssnext) (pack of CSS polyfills).

**Comment by tobiastom** [comment]
Thank you for the clarification.
