### ISSUE TITLE
autoprefixer removing '-webkit-background-clip'

### ISSUE THREAD

**Issue by mbacon40** [postcss/autoprefixer#940]
I am aware after reading through some support threads that `background-clip` is not supported by autoprefixer, which is fine, however when I run autoprefixer using grunt `-webkit-background-clip` is removed from my code. Removing this breaks the display of my site in the newest version of Chrome. In this case `-webkit` is very much required. I am fine manually adding it, but it should not be removed by autoprefixer.

Before:

h1.entry-title {
    background: linear-gradient(#fff, #76777a);
    -webkit-background-clip: text;
    background-clip: text;
    -webkit-text-fill-color: transparent;
    padding-bottom: 2px;
}

After:

h1.entry-title {
    background: linear-gradient(#fff, #76777a);
    background-clip: text;
    -webkit-text-fill-color: transparent;
    padding-bottom: 2px;
}

**Comment by ai** [comment]
Are you sure that it was Autoprefixer. I tried your input on online demo and prefix was not removed.

1. What browsers do you selected?
2. Do you use latest versions of all build components?
3. What tool you use to build CSS?

**Comment by mbacon40** [comment]
I just realized that I was running an extremely old version of autoprefixer. It was the issue, but updating solved it. Thanks!
