### ISSUE TITLE
Error - option in documentation have wrong name

### ISSUE THREAD

**Issue by Triloworld** [postcss/autoprefixer#941]
I have error and I fix it but documentation state something else. Can you provide answear why is that? 
More over, it is configuration of autoprefixer rather than cssnano, it only send it to process.
I use file with configuration but in this case special file is crafted only for IE and old ones.

Configuration A (working):

    .pipe(plugin.postcss([
        plugin.cssnano({
            autoprefixer: {
                browserslist: [
                    "ie < 11",
                    "< 5%"
                ],
                add: true,
                remove: false,
                flexbox: true,
                grid: true
            },
            safe: true
        })
    ]))

Configuration B (not working - is correct by documentation):

    .pipe(plugin.postcss([
        plugin.cssnano({
            autoprefixer: {
                browsers: [
                    "ie < 11",
                    "< 5%"
                ],
                add: true,
                remove: false,
                flexbox: true,
                grid: true
            },
            safe: true
        })
    ]))

Plumber message:

        [11:28:15] gulp-notify: [] BrowserslistError in plugin 'gulp-postcss'
        Message:
            Unknown browser query `< 5%`
        Details:
            browserslist: true
            fileName: /web/css/print.css
        Stack:
        BrowserslistError: Unknown browser query `< 5%`
            at error (node_modules/browserslist/index.js:37:11)
            at node_modules/browserslist/index.js:222:9
            at Array.forEach (<anonymous>)
            at browserslist (node_modules/browserslist/index.js:196:13)
            at Browsers.parse (node_modules/autoprefixer/lib/browsers.js:44:14)
            at new Browsers (node_modules/autoprefixer/lib/browsers.js:39:28)
            at loadPrefixes (node_modules/autoprefixer/lib/autoprefixer.js:56:18)
            at plugin (node_modules/autoprefixer/lib/autoprefixer.js:62:18)
            at LazyResult.run (node_modules/postcss/lib/lazy-result.js:274:20)
            at LazyResult.asyncTick (node_modules/postcss/lib/lazy-result.js:189:32)
        [11:28:15]

ENV usage of example:
npm --version
5.5.1

node --version
v8.9.0

gulp
gulp@4.0.0-alpha.2 
autoprefixer@6.7.7
cssnano@3.10.0

If is error in documentation, I will be glad to do pull request :)

**Comment by ai** [comment]
You use wrong symbol in query. You need `>` instead of `<`. Where you find it in docs?

Also you should use Browserslist config, not option. I tried to remove any example work option from docs, where I forget to remove option?

`browserslist` option if wrong, Autoprefixer have special warning about it.

**Comment by Triloworld** [comment]
Thanks for info about symbol in query, why not?.
In they example:

> Firefox < 20: versions of Firefox less than 20.

So this is clearly working way. If wrong I will replace it. It isn't problem for browserslist to run it.

There is, clearly section about options:
[https://github.com/postcss/autoprefixer#options](https://github.com/postcss/autoprefixer#options)

They even show ii in first point: https://github.com/ai/browserslist#queries

**Comment by ai** [comment]
So you need to select browsers with market share **less** than some percentage? Why?

Sure, send PR to this options docs.

In https://github.com/ai/browserslist#queries we show key for package.json, not for Autoprefixer option. Do you have idea how to make it more clear?
