### ISSUE TITLE
Safari 11 position: sticky bug

### ISSUE THREAD

**Issue by leshek-pawlak** [postcss/autoprefixer#950]
## Description
Attribute `position: sticky;` without prefix doesn't work for Safari 11. (https://caniuse.com/#feat=css-sticky)
After generate css file from autoprefixer for "last 2 versions" I haven't got any `position: -webkit-sticky;`.

## Desire outcome
Autoprefixer should add `position: -webkit-sticky;` for every safari version.

**Comment by ai** [comment]
`position: sticky` is supported by Autoprefixer and works in [online demo](http://autoprefixer.github.io/). Seems like yo have environmental problems.

**Comment by leshek-pawlak** [comment]
Oh. That's really strange. Thank you. 
Sorry for unnecessary ticket.
