### ISSUE TITLE
Autoprefixer breaks the build after 7.2.x release

### ISSUE THREAD

**Issue by bomsy** [postcss/autoprefixer#952]
For some reason 
Autoprefixer causes the webpack build to break because of this line

https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-launchpad/src/components/LandingPage.css#L103.
Not sure what its issue is with `text-align: center`.

Here is a screenshot of the error

![image](https://user-images.githubusercontent.com/792924/33745892-5f91bb96-dbb1-11e7-8fd1-685e51570ee9.png)

**Comment by ai** [comment]
OK. I am on it (goodbye sleep).

**Comment by bomsy** [comment]
Thanks a lot!

**Comment by ai** [comment]
@bomsy everything works on my machine and in [online demo](http://autoprefixer.github.io).

I need target browsers, exact version of PostCSS, exact version of Autoprefixer and JS code of how do you run Autoprefixer.

**Comment by ai** [comment]
OK. I can’t reproduce it, but I should fix it :sweat_smile: Fix 0072163

My guess is that PostCSS AST was broken in devtools-html.

**Comment by bomsy** [comment]
Yeah! thanks!

**Comment by ai** [comment]
Released in 7.2.2.

If you think this issue was fixed very quickly, you can subscribe to one of my Twitter accounts: [lostinwiki](https://twitter.com/lostinwiki), [linguopunk](https://twitter.com/linguopunk) =^_^=

**Comment by bomsy** [comment]
Thanks! its fixed!
