### ISSUE TITLE
-ms-scroll-chaining similar to overscroll-behavior?

### ISSUE THREAD

**Issue by Malvoz** [postcss/autoprefixer#956]
Consider adding [`-ms-scroll-chaining`](https://msdn.microsoft.com/library/Hh772034) as prefix for [`overscroll-behavior`](https://wicg.github.io/overscroll-behavior/).

Note that the `overscroll-behavior` property allows for authors to specify on which axis `overscroll-behavior` applies to (by setting `overscroll-behavior-{x/y}`, while `-ms-scroll-chaining` does not allow for that type of control.

**Comment by ai** [comment]
Do you want to add overscroll data to [Can I Use](https://github.com/Fyrd/caniuse)?

**Comment by ai** [comment]
Also do we have prefixed version for other browsers?

**Comment by Malvoz** [comment]
There is an [overscroll-behavior suggestion on CanIUse](https://github.com/Fyrd/caniuse/issues/3725). I have not found any other vendor prefixes. Also the new `overscroll-behavior` will probably have wide UA support. In which case the -ms-prefix is only of benefit in old IE browsers, I think.

**Comment by ai** [comment]
Does IE 11 and Edge support `-ms-scroll-chaining`?

**Comment by Malvoz** [comment]
I haven't found any documentation on IE 11 and Edge, but according to [this WCIG discourse comment](https://discourse.wicg.io/t/generic-scroll-chaining-prevention-mechanism-or-expand-standardize-ms-scroll-chaining/1811/4) it seems to work in Edge.

**Comment by Malvoz** [comment]
@ai 
> Do you want to add overscroll data to Can I Use?

[The recently added data](https://caniuse.com/#feat=css-overscroll-behavior) reveals `-ms-scroll-chaining` is supported in IE 10 + 11 and also in all Edge versions. And because neither IE or Edge supports the new `overscroll-behavior` I think it might be a good idea to add the `ms-scroll-chaining` as fallback prefix.

**Comment by ai** [comment]
@Malvoz awesome! Can I Use data is really helpful here.

**Comment by ai** [comment]
Done 49eecef.

Thanks for great instructions. They really helped. I will release it when #989 will be fixed.

**Comment by ai** [comment]
Released in 8.1
