### ISSUE TITLE
flexbox: "no-2009" dosen't work

### ISSUE THREAD

**Issue by HawkonDK** [postcss/autoprefixer#957]
the documentation say `flexbox: "no-2009"` so i suppose to belive that they mean `/*! flexbox: "no-2009" */` but that dosn't work.

beside that, how to prevent it from keep the` /*! option */` from being in the finely css file

**Comment by ai** [comment]
There is no such control comment as I know 😉. You should pass this option to Autoprefixer plugin:

```js
postcss([
  autoprefixer ({ flexbox: "no-2009" })
])
```

If you want this control comment you need send pull request to Autoprefixer since it is very rare feature.

**Comment by HawkonDK** [comment]
> In Sass/SCSS you can use all the disable options above, add an exclamation mark in the start of comment: /*! autoprefixer: off */.

**Comment by ai** [comment]
Yeap. This comment works only for `on`/`off`. I will change docs to make it more clear.

**Comment by HawkonDK** [comment]
but why the hell then write that you can use them all?

**Comment by ai** [comment]
Disabling section tell about all disabling methods. Some of this methods works by plugin options. Some by control comments.

Why you can set option to the plugin as I showed you?

**Comment by HawkonDK** [comment]
No, I was talked about the documentation... 

ehmm not sure if this it a bug with autoprefixer or with caniuseit.com but Safari dosn't need `-webkit-box-flex`

**Comment by ai** [comment]
Yeap, I will make docs more clear as I said.

Yeap, modern Safari doesn't need old webkit for flexbox. You can run `npx autoprefixer-info` and find what browser requires old prefix (I think it is some of Chinese browsers, but I don't recommend to disable them, they are very popular).

**Comment by HawkonDK** [comment]
oh yes of course the UC Browser.

Btw how do you change so `/*! autoprefixer: off */` dosn't stand ind the final css file?

**Comment by ai** [comment]
`/*! autoprefixer: off */` should work. What problem with it do you have?

**Comment by HawkonDK** [comment]
Example if the Sass/Scss file look like this:
```
.someClass {
    /*! autoprefixer: off */
    flex: 0 0 33.33%
}
```

the output will be:
```
.someClass {
    /*! autoprefixer: off */
    flex: 0 0 33.33%
}
```

but i will like it to be:

```
.someClass {
    flex: 0 0 33.33%
}
```

**Comment by ai** [comment]
You get it after SCSS only? Or only after Autoprefixer?

What told do you use in your build process?

**Comment by HawkonDK** [comment]
codekit

**Comment by ai** [comment]
Ask this question for CodeKit author. Maybe it has special tool lying trim comments after Autoprefixer.

**Comment by ai** [comment]
Done 9c52095
