### ISSUE TITLE
Prefix text-decoration-skip only for `none` and the non-standard `skip` values

### ISSUE THREAD

**Issue by toptalo** [postcss/autoprefixer#959]
Available values for `-webkit-text-decoration-skip` is `none` and the non-standard value `skip` [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip).

But if there are `text-decoration-skip: ink;` in stylesheet, autoprefixer generates vendor prefixed properties that are obviously do not need

**Comment by ai** [comment]
Yeap. I will try to fix it on the weekend.

**Comment by ai** [comment]
If you want to save your name in Autoprefixer history, you can send the pull request. You just need to define `check()` method in “hack” for `text-decoration-skip`. Just check `hacks/`.

**Comment by toptalo** [comment]
I'll try, thanks!

**Comment by toptalo** [comment]
I've read MDN more attentively and now not sure that we do not need to add prefixes for this declaration.
> Safari implements a `-webkit` prefixed version of this property since version 8, though only supports the value `none` and the non-standard value `skip`.

But

> **All other values behave like those two values.**

So I think we can leave it as it is or force replace not `none` values to non-standard `skip` value

**Comment by ai** [comment]
I think we should force users to use standard syntax for the future when they will remove Autoprefixer.

I will add warning for `skip` if it could be replaced to `none`.

**Comment by toptalo** [comment]
I think no one in whole world did not use this value [https://github.com/search?q=-webkit-text-decoration-skip](https://github.com/search?q=-webkit-text-decoration-skip%3A+skip%3B&type=Code&utf8=%E2%9C%93)
This is my misunderstanding of MDN

We can close this issue
