### ISSUE TITLE
transform hex color with alpha

### ISSUE THREAD

**Issue by yukulele** [postcss/autoprefixer#960]
hex color with alpha (like `#fffc`, `#002244aa`) should be converted to rgba style

spec: https://drafts.csswg.org/css-color/#hex-notation
support: https://caniuse.com/#feat=css-rrggbbaa
doc: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#Syntax

**Comment by ai** [comment]
1. https://github.com/postcss/autoprefixer#does-it-add-polyfills
2. https://github.com/postcss/postcss-color-hex-alpha
