### ISSUE TITLE
.browserlistsrc file not being used

### ISSUE THREAD

**Issue by planetflash** [postcss/autoprefixer#964]
I'd like to use the .browserslistrc file rather than the webpack inline browsers option or the package.json "browserslist" option if at all possible, but for some reason this doesn't seem to be working for me. Is this an error in my understanding / config, or a bug?

Webpack config:
```
{
  loader: 'postcss-loader',
  options: {
    plugins: () => {
      return [
        require('autoprefixer')
      ];
    },
    sourceMap: true
  }
},
```

.browserslistrc file contents:
```
last 3 versions
ie 11
````

Output incorrectly adds unnecessary  prefixes:
```
display: -webkit-box;
display: -ms-flexbox;
display: flex;
```

If I put the same list either in package.json "browserslist" option, or inline webpack config the output is as expected:
```
display: -ms-flexbox;
display: flex;
```

**Comment by ai** [comment]
Why you think it is unnecessary prefixes. There are a lot of Chinese browsers with old flexbox. Check your browsers query with http://browserl.ist

**Comment by planetflash** [comment]
@ai perhaps my use of the word 'unnecessary' was poor. My point was that it appears the config is not being used. I get different results using the same list in package.json and webpack inline settings vs using the .browserslistrc file. If I use the .browserslistrc file, the output is the same as if I had no config settings at all, which is what leads me to think the config is either not being used, or I have missed a setting somewhere. Running `npx browserslist` gives me the list of browsers as expected when using the .browserslistrc file, but this does not match the output of my css.

**Comment by ai** [comment]
@planetflash can you try to write `IE 11` in `.browserslist`, clean everything and compile CSS again? You current output feets your `.browserslistrc` config.

**Comment by planetflash** [comment]
@ai my output is as before:
```
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
```
which is not the same as if I put the same option in package.json or inline webpack

**Comment by ai** [comment]
What Autoprefixer and postcss-loader are in `npm ls`?

**Comment by planetflash** [comment]
postcss-loader@2.0.10
autoprefixer@6.7.7

**Comment by ai** [comment]
Update them :D. Always try to update dependencies before creating an issue.

**Comment by planetflash** [comment]
@ai Thanks! :) Turns out I was using autoprefixer from another dependency and hadn't installed it myself. I hadn't picked up on it as it was "working". Sorted now.
