### ISSUE TITLE
Order of prefixed appearance result in different behaviour

### ISSUE THREAD

**Issue by valorize** [postcss/autoprefixer#966]
Findings:
Case 1:
```
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
```
results in: `appearance: none`

Case 2:
`appearance: none`
results in: `appearance: none`

Case 3:
```
  appearance: none;
  -webkit-appearance: none;
  -moz-appearance: none;
```
results in 
```
  appearance: none;
  -webkit-appearance: none;
  -moz-appearance: none;
```
Is this intended?

**Comment by ai** [comment]
Yeap. It is useful for vendor hack. What if you want a different value for Firefox? With this behavior you can write:

```css
box-shadow: 1px solid black;
-moz-box-shadow: 1px solid red;
```

`-moz-box-shadow` will override `box-shadow` and in Firefox you will have red shadow.

**Comment by ai** [comment]
If you want to clean *all* prefixes, you could use [postcss-unprefix](https://github.com/gucong3000/postcss-unprefix) or some different PostCSS plugin.

**Comment by valorize** [comment]
Ok, thanks for the explanation.

**Comment by valorize** [comment]
Shouldn't Case 1 and Case 2 expand to prefixed versions of appearance? 
Is it theoretically possible to check if the contents of the prefixed and unprefixed properties is equal?

**Comment by ai** [comment]
Yeap, Case 1 and Case 2 Autoprefixer’s output is the same

**Comment by valorize** [comment]
Lol, it's to early ^^,
I tried to say, that the output of case 1 and 2 is wrong ;)
I would assume that Case 1 and Case 2 output the same as the output given in Case 3.

**Comment by ai** [comment]
Why they are wrong?

**Comment by valorize** [comment]
According to https://caniuse.com/#search=appearance all chrome and firefox versions need a prefixed version. So this plugin should take `appearance: ...` and prefix it with moz and webkit, right?

**Comment by ai** [comment]
Run `npx autoprefixer-info` in your project directory. You will get what browsers do you use and what prefixes is applied.

Chrome is not the only `webkit` browser.

**Comment by ai** [comment]
Yeap, Autoprefixer adds prefixes. What is your CSS input and output?

**Comment by valorize** [comment]
See the first comment of this issue. The cases give the input and the results are the output. I'll try to run `npx autoprefixer-info` but it gives me `npm ERR! 404 Not Found: autoprefixer-info@latest` (will investigate)

**Comment by ai** [comment]
What is your Browserslist config?

**Comment by valorize** [comment]
None, so > 1%, Firefox ESR, last 2 versions

**Comment by ai** [comment]
I tested at [online demo](http://autoprefixer.github.io) and everything works correctly.

Maybe you have old Autoprefixer?

**Comment by valorize** [comment]
Sry should have checked that first. 7.1.6 to 7.2.4 fixed it

**Comment by valorize** [comment]
Thank you very much for your support. Sometimes you overlook the obvious. :-)
