### ISSUE TITLE
Usage in browser?

### ISSUE THREAD

**Issue by ZeeCoder** [postcss/autoprefixer#967]
Not really a big issue, more of a question:

I tried to use autoprefixer using codesandbox, but I it didn't work unfortunately.
(I think it complained about a missing `fs.existsSync` or something)

How hard would it be to make it work in browsers? Are there any big blockers? 🤔
Also: I'm opening this issue because I wasn't 100% sure based on the readme whether this was meant to work in browsers or not. Probably worth leaving a note somewhere, unless there's one already I missed. 👍

Cheers 🙌

**Comment by ai** [comment]
Hi. It should work in browser. What error do you have and bundler do you use?

**Comment by ZeeCoder** [comment]
I tried to set it up in [codesandbox](https://codesandbox.io).
I'll create a demo link for you to reproduce the error in the next two hours or so, thanks for the quick response!

**Comment by ZeeCoder** [comment]
Here's a test link @ai 
https://codesandbox.io/s/vokvqnxwl

Screenshot:
![screenshot from 2018-01-10 13-21-56](https://user-images.githubusercontent.com/3679506/34774956-489fa46c-f609-11e7-90db-13936fa3c28a.png)

**Comment by ai** [comment]
Fixed https://github.com/ai/browserslist/commit/0bfb5d5da885f2e2a6524a1e36e849f5fe006968

**Comment by ai** [comment]
Released in Browserslist 2.11.1.

**Comment by ZeeCoder** [comment]
Great thank you! 🎉
That change makes sense. :)
