### ISSUE TITLE
How do I remove the warning : You should write display: flex by final spec instead of display: box

### ISSUE THREAD

**Issue by fengxinming** [postcss/autoprefixer#970]
Due to support IOS 8 I have to use `display: box`, how do I remove the warning?

**Comment by ai** [comment]
Replace `display: box` in your CSS. It is very big problem. You must solve it, not hide useful warning.

**Comment by ai** [comment]
You don’t need `display: box` for iOS 8. iOS 8 uses only `display: -webkit-box`, not `display: box`.

Write `display: flex` and Autoprefier will fix it to `display: -webkit-box` (for iOS 8) automatically.

**Comment by g-rodigy** [comment]
I got this warning too.
My **.browserslistrc**
`
last 2 years
`
