### ISSUE TITLE
CSS gradient conversion to color names does not work with transparent for iOS

### ISSUE THREAD

**Issue by AirBorne04** [postcss/autoprefixer#974]
Hi,

i do have a gradient from transparent to white (any color will do) i want to use this on iOS web app (safari is the same behavior). When i put the generic gradient
`linear-gradient(to bottom, rgba(0,0,0,0) 0%,rgba(255,255,255,1) 10%,rgba(255,255,255,1) 100%)`
auto prefixer converts it to
`linear-gradient(to bottom, transparent 0%, white 20%, white 100%)`
This rgba to color naming conversion seems to cause a problem as on the iPhone this causes the transparent part to be black instead.

For now i disabled auto prefixer on this property but is this a bug or am i doing something wrong?

**Comment by ai** [comment]
Autoprefixer doesn’t change colors in gradients. You can try it in [online demo](http://autoprefixer.github.io/) to be sure.

I think some other tool convert colors (cssnext or csnano).

**Comment by AirBorne04** [comment]
hi ai, ok just realized that too, sorry, maybe postcss, i gotta dig more :)

**Comment by ai** [comment]
PostCSS is just a parser. Without plugins, it doesn’t change anything :). But yeap, maybe some specific PostCSS plugin could change it.

**Comment by AirBorne04** [comment]
yes ok was just going through the list of stuff i am using :)
webpack with sass-loader and postcss with autoprefixer but in the meantime i found postcss-gradient-transparency-fix npm package that is fixing my issues. For anybody with the same issue as reference.
