### ISSUE TITLE
"background-clip: text" needs "-webkit" prefix

### ISSUE THREAD

**Issue by asinning** [postcss/autoprefixer#975]
We distribute ePub titles to school libraries in our own e-reader. The files which we get from publishers often include declarations for specific browsers, but are missing the more general prefix-less declaration. So, we run the css through unprefix and then autoprefixer.

The problem has to do with the declaration "-webkit-background-clip: text". unprefix removes the "-webkit" prefix, but autoprefixer does not recognize that "background-clip: text" needs to be prefixed.

Should autoprefixer be doing "background-clip: text" -> "-webkit-background-clip: text", or should unprefix leave the prefix in place, or does this use case fall out of the scope of both projects?

Thanks!

**Comment by asinning** [comment]
I am closing this as it is a duplicate of 831.

**Comment by ai** [comment]
Done 73c7b6a
