### ISSUE TITLE
Gradient for IE9 as embedded svg

### ISSUE THREAD

**Issue by thany** [postcss/autoprefixer#977]
Would be nice if autoprefixer would generate embedded SVG as a fallback for linear gradients for IE9. This will give nearly full capabilities, as far as linear gradients go.

So this:
```css
background: linear-gradient(to bottom, #fff, #000);
```
Would generate this:
```css
background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI2ZmZmZmZiIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiMwMDAwMDAiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
```

See also: http://www.colorzilla.com/gradient-editor/ (with the IE9 checkbox ticked)

I know this is technically not a prefix, but I can't find any other plugin (for gulp) that can do this, so Autoprefixer seems to me like the most suitable place to have this.

**Comment by ai** [comment]
Yeap, it will be useful. But Autoprefixer is only for prefixes, not for polyfills. Polyfills require different API.

In your case you should use https://github.com/yuezk/postcss-filter-gradient (maybe extend it for SVG gradients).

**Comment by ai** [comment]
The reasons why we don't do polyfills in Autoprefixer:

1. How we will clean them? Autoprefixer cleans prefixes if they are not needed anymore.
2. How we will prevent duplication. Current algorithm is not ready for it.

**Comment by thany** [comment]
1. You don't. These SVG gradients are not the kind of gradients that people will (or should) type in manually. And autoprefixer doesn't (or shouldn't) be set up to change one's css in-place.
2. That is up to the css author, because the same issue goes for any prefix and any gradient.

postcss-filter-gradient is not useful, as it only creates a DX filter (which are absolutely stinking horrible), but not an SVG fallback.

**Comment by thany** [comment]
Btw, the Microsoft flexbox implementation for IE10, being as different from the standard as it is, is as much as a polyfill as SVG gradients is.

**Comment by ai** [comment]
@thany flexbox properties have prefix ;).

**Comment by thany** [comment]
Not just prefixes. The properties themselves *for MSIE* are very different. Same goes for CSS grid btw.

The point is that it makes sense to construct SVG gradients when clearly autoprefixer isn't so strict on their "prefixes only!!" premise.

**Comment by ai** [comment]
Yeap, Autoprefixer = prefix + change syntax for prefixed version. But not only "change syntax", prefix is still required.

It is very easy to wow new custom PostCSS plugin. I will make a link to it from Autoprefixer docs.
