### ISSUE TITLE
Add prefixing support for justify-items and align-items on grid level

### ISSUE THREAD

**Issue by derzwen** [postcss/autoprefixer#987]
Would it be possible to implement also prefixing the justify-items and align-items CSS grid property?

As I understood it, `justify-items` applies to all grid cells and basically does the same as `justify-self` for a single cell (same for `align-items` and `align-self`) The prefixing per cell for `justify-items` and `align-items` already works (`-ms-grid-column-align` and `-ms-grid-row-align`) fine.

So what about adding support for `justify-items` and `align-items` based on this according to the following method:

- if `justify-items` or `align-items` is present at grid level, add the according prefixed -ms properties to all grid cells
- but do this only, if the prefixed -ms property is not yet present (this covers the case that i.e. `justify-self` overrides the `justify-items` property in the unprefixed spec world)

**Comment by ai** [comment]
Autoprefixer doesn’t know real HTML structure. So we can’t be sure about parents and children.

**Comment by derzwen** [comment]
Jep, you're right. Totally forgot about this. So this will never be done and can be closed i guess.
