### ISSUE TITLE
Adding outdated property for flexbox

### ISSUE THREAD

**Issue by techsin** [postcss/autoprefixer#995]
https://developer.mozilla.org/en-US/docs/Web/CSS/box-direction

all i wrote is this: `flex-flow: row-reverse;`, prefixer added depreciated props...

` -webkit-box-direction: reverse;` is being added and causing weird stretching to happen 1/3 times.

Is there a way to not add any deprecated css properties

**Comment by ai** [comment]
1. Run `npx autoprefixer --info` in your project, found that browser uses that prefix for `flex-flow`, remove it from target browsers in Browserslist config.
2. Set `flexbox: "no-2009"` option to Autoprefixer to disable old flexbox prefixes.
