### ISSUE TITLE
Not able to update Autoprefixer more than 4.1.0

### ISSUE THREAD

**Issue by webmasterpf** [postcss/autoprefixer#996]
Hi,

I would to update my npm gulp-autoprefixer but npm say I can't do that:
```
Package            Current  Wanted  Latest  Location
gulp-autoprefixer    4.1.0   4.1.0   5.0.0  starter-d6-susy3
```

I would to add Edge support to my Autoprefixer list in gulpfile:
```
var AUTOPREFIXER_BROWSERS = [

'> 1%',
'ie >= 8',
'ie_mob >= 10',
'ff >= 45',
'chrome >= 45',
'safari >= 7',
'opera >= 23',
'ios >= 7',
'android >= 4',
'bb >= 10'
];
```

So do I need to update the module, or just add it in my list by hand ?

thanks

EDIT: adding it by hand like 
`'edge >= 15',`
doesn't work, 

`    display: grid;` is still not prefixed.

**Comment by ai** [comment]
`gulp-autoprefixer` is unofficial ;). The only official way is to use `gulp-postcss` with `autoprefixer`. Move to official way, it could fix the problem.

**Comment by webmasterpf** [comment]
ok, will do that.

**Comment by webmasterpf** [comment]
It works :) with adding PostCSS
