### ISSUE TITLE
`-webkit-box-orient` has been removed?

### ISSUE THREAD

**Issue by aleen42** [postcss/autoprefixer#998]
I rencently found that `-webkit-box-orient` has been removed by autoprefixer when browsers list was set as `defaults`, and why?

**Comment by ai** [comment]
Autoprefixer adds prefixes only for actual browsers. There are no actual browsers which require prefix `-webkit-box-orient`.

https://caniuse.com/#feat=flexbox
https://github.com/postcss/autoprefixer#why-doesnt-autoprefixer-add-prefixes-to-border-radius

**Comment by aleen42** [comment]
It does required for Chrome, especially when using `-webkit-box`, as it affect the behavior of `text-align`. You can check the example by visiting my snippet: https://codepen.io/aleen42/pen/GxZzKe

**Comment by ai** [comment]
@aleen42 Chome doesn’t need a prefixes for Flexbox since Chrome 29 https://caniuse.com/#search=flexbox

Maybe you found a Chrome’s bug and `-webkit-box-orient` somehow fixes it.

**Comment by aleen42** [comment]
@ai Okay, I report it to the Chromium Discuss Group.

**Comment by ai** [comment]
Fixed by 69ed8a0 and released in 9.6.1.
