### ISSUE TITLE
autoprefixer does nothing when used with postcss-cli

### ISSUE THREAD

**Issue by kkweon** [postcss/autoprefixer#999]
- [Issue](#sec-1)
- [Reproduce Step](#sec-2)
- [Version Information](#sec-3)

# Issue<a id="sec-1"></a>

-   It's not adding prefixes when using postcss-cli
-   It was working fine before upgrading. I am not sure which version I was using before though.

# Reproduce Step<a id="sec-2"></a>

1.  Content of CSS File
    
    ```bash
    cat temp.css
    ```
    
        .d-flex {
          display: flex;
        }
        
        a {
          display: flex;
        }
        
        a {
          transition: 1s; /* it will be prefixed */
        }

2.  Run postcss &#x2013;use autoprefixer
    
    ```bash
    npx postcss temp.css --use autoprefixer -d build/
    ```

3.  Check content
    
    ```bash
    cat build/temp.css
    ```
    
        .d-flex {
          display: flex;
        }
        
        a {
          display: flex;
        }
        
        a {
          transition: 1s; /* it will be prefixed */
        }
        
        /*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uL3RlbXAuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBO0VBQ0UsY0FBYztDQUNmOztBQUVEO0VBQ0UsY0FBYztDQUNmOztBQUVEO0VBQ0UsZUFBZSxDQUFDLHlCQUF5QjtDQUMxQyIsImZpbGUiOiJ0ZW1wLmNzcyIsInNvdXJjZXNDb250ZW50IjpbIi5kLWZsZXgge1xuICBkaXNwbGF5OiBmbGV4O1xufVxuXG5hIHtcbiAgZGlzcGxheTogZmxleDtcbn1cblxuYSB7XG4gIHRyYW5zaXRpb246IDFzOyAvKiBpdCB3aWxsIGJlIHByZWZpeGVkICovXG59XG4iXX0= */

# Version Information<a id="sec-3"></a>

-   OSX 10.13.3

-   npx version
    
    ```bash
    npx --version
    ```
    
        9.7.1

-   autoprefixer version
    
    ```bash
    autoprefixer --version
    ```
    
        autoprefixer 8.1.0

-   postcss &#x2013;version
    
    ```bash
    postcss --version
    ```
    
        
                        /|\
                      //   //
                    //       //
                  //___*___*___//
                //--*---------*--//
              /|| *             * ||/
            // ||*    v5.0.0     *|| //
          //   || *             * ||   //
        //_____||___*_________*___||_____//

**Comment by ai** [comment]
Default target browsers don’t need prefixes for `transition` and `flex`.

https://github.com/postcss/autoprefixer#why-doesnt-autoprefixer-add-prefixes-to-border-radius

**Comment by ai** [comment]
Sure 6579eb5
